<div class = "alert alert-block alert-info">
    <b>CCDR Inventory:</b> 306 variables
</div>

In [79]:
import os
import pandas as pd
import wbgapi as wb # https://github.com/tgherzog/wbgapi
import plotly.express as px
import plotly.graph_objects as go
import datetime
import numpy as np
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
# CCDR is number 87
wb.source.info()

id    name                                                                  lastupdated
----  --------------------------------------------------------------------  -------------
1     Doing Business                                                        2021-08-18
2     World Development Indicators                                          2021-09-15
3     Worldwide Governance Indicators                                       2021-09-27
5     Subnational Malnutrition Database                                     2016-03-21
6     International Debt Statistics                                         2021-01-21
11    Africa Development Indicators                                         2013-02-22
12    Education Statistics                                                  2020-12-20
13    Enterprise Surveys                                                    2021-04-02
14    Gender Statistics                                                     2021-09-27
15    Global Economic Monitor                                               2020-07-27
16    Health Nutrition and Population Statistics                            2021-09-15
18    IDA Results Measurement System                                        2021-07-23
19    Millennium Development Goals                                          2018-09-19
20    Quarterly Public Sector Debt                                          2021-07-26
22    Quarterly External Debt Statistics SDDS                               2021-07-30
23    Quarterly External Debt Statistics GDDS                               2021-07-30
24    Poverty and Equity                                                    2021-10-05
25    Jobs                                                                  2021-02-17
27    Global Economic Prospects                                             2021-06-08
28    Global Financial Inclusion                                            2018-10-15
29    The Atlas of Social Protection: Indicators of Resilience and Equity   2021-09-23
30    Exporter Dynamics Database – Indicators at Country-Year Level         2016-03-31
31    Country Policy and Institutional Assessment                           2021-09-16
32    Global Financial Development                                          2019-10-30
33    G20 Financial Inclusion Indicators                                    2019-02-27
34    Global Partnership for Education                                      2013-04-12
35    Sustainable Energy for All                                            2018-06-30
36    Statistical Capacity Indicators                                       2021-02-03
37    LAC Equity Lab                                                        2016-04-06
38    Subnational Poverty                                                   2015-04-27
39    Health Nutrition and Population Statistics by Wealth Quintile         2021-06-08
40    Population estimates and projections                                  2021-09-15
41    Country Partnership Strategy for India (FY2013 - 17)                  2015-05-22
43    Adjusted Net Savings                                                  2021-04-27
45    Indonesia Database for Policy and Economic Research                   2019-05-07
46    Sustainable Development Goals                                         2021-07-02
50    Subnational Population                                                2017-09-21
54    Joint External Debt Hub                                               2021-05-17
57    WDI Database Archives                                                 2021-09-24
58    Universal Health Coverage                                             2019-04-25
59    Wealth Accounts                                                       2018-01-30
60    Economic Fitness                                                      2018-04-19
61    PPPs Regulatory Quality                                               2019-04-25
62    International Comparison Program (ICP) 2011                           2020-08-24
63    Human Capital Index                                                   2020-09-21
64    Worldwide Bureaucracy Indicators                                      2021-05-26
65    Health Equity and Financial Protection Indicators                     2019-11-06
66    Logistics Performance Index                                           2019-10-29
67    PEFA 2011                                                             2021-09-20
68    PEFA 2016                                                             2021-09-20
69    Global Financial Inclusion and Consumer Protection Survey             2019-06-27
70    Economic Fitness 2                                                    2019-04-26
71    International Comparison Program (ICP) 2005                           2021-09-10
73    Global Financial Inclusion and Consumer Protection Survey (Internal)  2019-06-27
75    Environment, Social and Governance (ESG) Data                         2021-09-16
76    Remittance Prices Worldwide (Sending Countries)                       2020-12-07
77    Remittance Prices Worldwide (Receiving Countries)                     2020-12-07
78    ICP 2017                                                              2020-10-21
79    PEFA_GRPFM                                                            2021-07-28
80    Gender Disaggregated Labor Database (GDLD)                            2020-07-25
81    International Debt Statistics: DSSI                                   2021-01-21
82    Global Public Procurement                                             2021-03-24
83    Statistical Performance Indicators (SPI)                              2021-04-01
84    Education Policy                                                      2021-05-11
85    PEFA_2021_SNG                                                         2021-08-17
86    Global Jobs Indicators Database (JOIN)                                2021-09-24
87    Country Climate and Development Report (CCDR)                         2021-10-03
      67 elements

In [4]:
# 306 variables
desc = pd.DataFrame(list(wb.series.list(db=87)))
desc = desc.rename({'id': 'variable', 'value': 'description'}, axis=1)
desc = desc.sort_values(by='variable', ascending=True)
desc[["code1", "code2", "code3", "code4", "code5"]] = desc['variable'].str.split(expand=True, pat='.')
desc.to_csv('desc.csv')
desc

,variable,description,code1,code2,code3,code4,code5
0,AG.LND.AGRI.ZS,Agricultural land (% of land area),AG,LND,AGRI,ZS,None
1,AG.LND.ARBL.ZS,Arable land (% of land area),AG,LND,ARBL,ZS,None
2,AG.LND.FRST.ZS,Share of surface occupied by forest (% of total),AG,LND,FRST,ZS,None
3,CC.ACLD.PRTS.NO,Total protests and riots by event type since 2018,CC,ACLD,PRTS,NO,None
4,CC.ADPO.MAEX.AA,Additional population exposed to annual coasta...,CC,ADPO,MAEX,AA,None
...,...,...,...,...,...,...,...
301,SI.POV.UMIC,Poverty headcount ratio at $5.50 a day (2011 P...,SI,POV,UMIC,None,None
302,SL.TLF.TOTL.FE.ZS,"Labor force, female (% of total labor force)",SL,TLF,TOTL,FE,ZS
303,SL.UEM.TOTL.ZS,"Unemployment, total (% of total labor force) (...",SL,UEM,TOTL,ZS,None
304,SP.POP.TOTL,"Population, total",SP,POP,TOTL,None,None
305,SP.URB.TOTL.IN.ZS,Urban population (% of total population),SP,URB,TOTL,IN,ZS

In [5]:
ccdr_306 = list(desc['variable'])
len(ccdr_306)

306

In [7]:
appended_data = []
for count, variable in enumerate(ccdr_306, start=1):
    print(count, variable)
    df = wb.data.DataFrame(series = variable, 
                           db = 87, 
                           labels = True).reset_index()
    df["variable"] = variable
    print("Done")
    appended_data.append(df)
    
appended_data = pd.concat(appended_data)

1 AG.LND.AGRI.ZS
Done
2 AG.LND.ARBL.ZS
Done
3 AG.LND.FRST.ZS
Done
4 CC.ACLD.PRTS.NO
Done
5 CC.ADPO.MAEX.AA
Done
6 CC.ADPO.MAEX.BB
Done
7 CC.ADPO.MIEX.AA
Done
8 CC.ADPO.MIEX.BB
Done
9 CC.AG.NTR.TOHA
Done
10 CC.ASP.COVG.QT
Done
11 CC.ASP.COVG.ZS
Done
12 CC.ASP.TRAF.PC
Done
13 CC.AVPB.PTPI.AI
Done
14 CC.AVPB.PTPI.AR
Done
15 CC.AVPB.PTPI.DI
Done
16 CC.AVPB.PTPI.FP
Done
17 CC.AVPB.PTPI.HE
Done
18 CC.AVPB.PTPI.LP
Done
19 CC.AVPB.TPOP.AG
Done
20 CC.AVPB.TPOP.AI
Done
21 CC.AVPB.TPOP.DI
Done
22 CC.AVPB.TPOP.HE
Done
23 CC.AVPB.TPOP.TE
Done
24 CC.CHIC.BTFP.AG
Done
25 CC.CHIC.BTFP.AI
Done
26 CC.CHIC.BTFP.DI
Done
27 CC.CHIC.BTFP.HE
Done
28 CC.CHIC.BTFP.TE
Done
29 CC.CHIC.CFPI.AG
Done
30 CC.CHIC.CFPI.AI
Done
31 CC.CHIC.CFPI.DI
Done
32 CC.CHIC.CFPI.FP
Done
33 CC.CHIC.CFPI.HE
Done
34 CC.CHIC.CFPI.LP
Done
35 CC.CO2.EMSE.BF
Done
36 CC.CO2.EMSE.BL
Done
37 CC.CO2.EMSE.EH
Done
38 CC.CO2.EMSE.EL
Done
39 CC.CO2.EMSE.EN
Done
40 CC.CO2.EMSE.FE
Done
41 CC.CO2.EMSE.IL
Done
42 CC.CO2.EMSE.IP
Done
43 CC.CO2.EMSE.LU
Done
44 CC.CO2.EMSE.MC
Done
45 CC.CO2.EMSE.OF
Done
46 CC.CO2.EMSE.TR
Done
47 CC.COAL.EMIS.CH
Done
48 CC.COAL.EMIS.CO
Done
49 CC.COAL.EMPR.CH
Done
50 CC.COAL.EMPR.CO
Done
51 CC.CUF.STUN
Done
52 CC.EG.CAP.GAEX
Done
53 CC.EG.CAP.GAIM
Done
54 CC.EG.COAL.EMIS
Done
55 CC.EG.COAL.MW
Done
56 CC.EG.COAL.PROD
Done
57 CC.EG.CONS.COAL.PC
Done
58 CC.EG.CONS.GAS.PC
Done
59 CC.EG.CONS.OIL.PC
Done
60 CC.EG.EMIS.MAN
Done
61 CC.EG.INTS.KW
Done
62 CC.EG.SOLR.KW
Done
63 CC.EG.STL.PROD
Done
64 CC.EG.SUBF.PC
Done
65 CC.EG.WIND.PC
Done
66 CC.EG.WIND.TOTL
Done
67 CC.EMP.MULT.NO
Done
68 CC.EN.ATM.COAL.CE
Done
69 CC.ENTX.ENE.ZS
Done
70 CC.ENTX.ENV.ZS
Done
71 CC.ENV.GDS.CADV
Done
72 CC.ENV.TRAD.EX
Done
73 CC.ENV.TRAD.IM
Done
74 CC.ESG.AGFE
Done
75 CC.ESG.AGMA
Done
76 CC.ESG.CMFE
Done
77 CC.ESG.CMMA
Done
78 CC.ESG.CNFE
Done
79 CC.ESG.CNMA
Done
80 CC.ESG.EUFE
Done
81 CC.ESG.EUMA
Done
82 CC.ESG.FBFE
Done
83 CC.ESG.FBMA
Done
84 CC.ESG.INFE
Done
85 CC.ESG.INMA
Done
86 CC.ESG.MAFE
Done
87 CC.ESG.MAMA
Done
88 CC.ESG.MIFE
Done
89 CC.ESG.MIMA
Done
90 CC.ESG.OSFE
Done
91 CC.ESG.OSMA
Done
92 CC.ESG.PAFE
Done
93 CC.ESG.PAMA
Done
94 CC.ESG.PSFE
Done
95 CC.ESG.PSMA
Done
96 CC.ESG.SEFE
Done
97 CC.ESG.SEMA
Done
98 CC.ESG.TCFE
Done
99 CC.ESG.TCMA
Done
100 CC.FDX.FTN.ZS
Done
101 CC.FDX.FTY.ZS
Done
102 CC.FDX.PMT.ZS
Done
103 CC.FDX.SAV.ZS
Done
104 CC.FGHG.SYS.CS
Done
105 CC.FGHG.SYS.EO
Done
106 CC.FGHG.SYS.LU
Done
107 CC.FGHG.SYS.PC
Done
108 CC.FGHG.SYS.PD
Done
109 CC.FGHG.SYS.PR
Done
110 CC.FGHG.SYS.RE
Done
111 CC.FGHG.SYS.TR
Done
112 CC.FLD.BELW.ZS
Done
113 CC.FLD.CITY.ZS
Done
114 CC.FLD.TOTL.ZS
Done
115 CC.FOOD.ANIM.ZS
Done
116 CC.FOOD.VEGT.ZS
Done
117 CC.FRVOL.MOD.AI
Done
118 CC.FRVOL.MOD.IW
Done
119 CC.FRVOL.MOD.RA
Done
120 CC.FRVOL.MOD.RO
Done
121 CC.FSU.PECA
Done
122 CC.GAS.PPBC.CN
Done
123 CC.GAS.PPBC.CO
Done
124 CC.GAS.PPBC.ID
Done
125 CC.GAS.PPBC.MB
Done
126 CC.GAS.PPBC.OP
Done
127 CC.GAS.PPBC.PR
Done
128 CC.GAS.PPBC.RT
Done
129 CC.GAS.PPBC.SH
Done
130 CC.GHG.EMSE.AG
Done
131 CC.GHG.EMSE.BF
Done
132 CC.GHG.EMSE.BL
Done
133 CC.GHG.EMSE.EH
Done
134 CC.GHG.EMSE.EL
Done
135 CC.GHG.EMSE.EN
Done
136 CC.GHG.EMSE.FE
Done
137 CC.GHG.EMSE.IL
Done
138 CC.GHG.EMSE.IP
Done
139 CC.GHG.EMSE.LU
Done
140 CC.GHG.EMSE.MC
Done
141 CC.GHG.EMSE.OF
Done
142 CC.GHG.EMSE.TR
Done
143 CC.GHG.EMSE.WA
Done
144 CC.GHG.FSYS.CH
Done
145 CC.GHG.FSYS.CO
Done
146 CC.GHG.FSYS.FG
Done
147 CC.GHG.FSYS.NO
Done
148 CC.GHG.GRPE
Done
149 CC.GHG.PECA
Done
150 CC.GHG.SDEG.AG
Done
151 CC.GHG.SDEG.BU
Done
152 CC.GHG.SDEG.EH
Done
153 CC.GHG.SDEG.FE
Done
154 CC.GHG.SDEG.IP
Done
155 CC.GHG.SDEG.LU
Done
156 CC.GHG.SDEG.MC
Done
157 CC.GHG.SDEG.OF
Done
158 CC.GHG.SDEG.TR
Done
159 CC.GHG.SDEG.WA
Done
160 CC.GNBD.ISS.BD
Done
161 CC.INCP.ALRS
Done
162 CC.INCP.KRGC
Done
163 CC.INCP.SPMC
Done
164 CC.ISG.FFFE
Done
165 CC.ISG.FFMA
Done
166 CC.ISG.NAFE
Done
167 CC.ISG.NAMA
Done
168 CC.ISG.NBFE
Done
169 CC.ISG.NBMA
Done
170 CC.KBA.MRN.ZS
Done
171 CC.KBA.TERR.ZS
Done
172 CC.MT.GE.EST
Done
173 CC.MT.PS.EST
Done
174 CC.MT.RL.EST
Done
175 CC.MT.RQ.EST
Done
176 CC.MT.VA.EST
Done
177 CC.NCO.GHG.AG
Done
178 CC.NCO.GHG.EL
Done
179 CC.NCO.GHG.EN
Done
180 CC.NCO.GHG.FE
Done
181 CC.NCO.GHG.IL
Done
182 CC.NCO.GHG.IP
Done
183 CC.NCO.GHG.LU
Done
184 CC.NCO.GHG.OF
Done
185 CC.NCO.GHG.WA
Done
186 CC.NEFO.IMCR.BA
Done
187 CC.NEFO.IMCR.BP
Done
188 CC.NEFO.IMCR.MA
Done
189 CC.NEFO.IMCR.RB
Done
190 CC.NEFO.IMCR.RE
Done
191 CC.NEFO.IMCR.RH
Done
192 CC.NEFO.IMCR.RI
Done
193 CC.NEFO.IMCR.RM
Done
194 CC.NEFO.IMCR.SB
Done
195 CC.NEFO.IMCR.WH
Done
196 CC.OIL.PSBC.CN
Done
197 CC.OIL.PSBC.CO
Done
198 CC.OIL.PSBC.ID
Done
199 CC.OIL.PSBC.OP
Done
200 CC.OIL.PSBC.PR
Done
201 CC.OIL.PSBC.RT
Done
202 CC.OIL.PSBC.SH
Done
203 CC.OPCO.AG.CA1
Done
204 CC.OPCO.AG.CA2
Done
205 CC.OPCO.AG.CA3
Done
206 CC.OPCO.AG.CA4
Done
207 CC.OPCO.AG.CA5
Done
208 CC.OPCO.AG.CA6
Done
209 CC.OPCO.PLTY.CC
Done
210 CC.OPCO.PLTY.CF
Done
211 CC.OPCO.PLTY.IG
Done
212 CC.OPCO.PLTY.SC
Done
213 CC.OPCO.PLTY.SU
Done
214 CC.OPCO.PLTY.UK
Done
215 CC.OPCO.PLTY.US
Done
216 CC.POP.INF.TL
Done
217 CC.PRNX.CAT1.ZS
Done
218 CC.PRNX.CAT2.ZS
Done
219 CC.PRNX.CAT3.ZS
Done
220 CC.PRNX.CAT4.ZS
Done
221 CC.PRNX.CAT5.ZS
Done
222 CC.PRO.ANI
Done
223 CC.PSVOL.MOD.AI
Done
224 CC.PSVOL.MOD.RA
Done
225 CC.PSVOL.MOD.RO
Done
226 CC.PUN.TOTL
Done
227 CC.RIC.PECA
Done
228 CC.RISK.AST.ZS
Done
229 CC.RISK.WELL.ZS
Done
230 CC.SE.ADT.LITR.ZS
Done
231 CC.SE.CAT1.ZS
Done
232 CC.SE.CAT2.ZS
Done
233 CC.SE.CAT3.ZS
Done
234 CC.SE.CAT4.ZS
Done
235 CC.SE.COMP.ZS
Done
236 CC.SE.NYRS.AVG
Done
237 CC.SH.AIRP.AIR
Done
238 CC.SH.AIRP.AMB
Done
239 CC.SP.COV.ZS
Done
240 CC.SP.EXP.ZS
Done
241 CC.TCFD.COMP.CB
Done
242 CC.TCFD.COMP.CD
Done
243 CC.TCFD.COMP.CM
Done
244 CC.TCFD.COMP.CS
Done
245 CC.TCFD.COMP.EN
Done
246 CC.TCFD.COMP.FI
Done
247 CC.TCFD.COMP.GO
Done
248 CC.TCFD.COMP.HC
Done
249 CC.TCFD.COMP.IN
Done
250 CC.TCFD.COMP.IT
Done
251 CC.TCFD.COMP.MT
Done
252 CC.TCFD.COMP.NO
Done
253 CC.TCFD.COMP.OT
Done
254 CC.TCFD.COMP.RE
Done
255 CC.TCFD.COMP.TR
Done
256 CC.TCFD.COMP.UT
Done
257 CC.THHZ.RANK.CF
Done
258 CC.THHZ.RANK.CY
Done
259 CC.THHZ.RANK.EH
Done
260 CC.THHZ.RANK.EQ
Done
261 CC.THHZ.RANK.LS
Done
262 CC.THHZ.RANK.RF
Done
263 CC.THHZ.RANK.TS
Done
264 CC.THHZ.RANK.UF
Done
265 CC.THHZ.RANK.WF
Done
266 CC.TNET.CYC.ZS
Done
267 CC.TNET.EAR.ZS
Done
268 CC.TNET.FLD.ZS
Done
269 CC.TNET.INV.ZS
Done
270 CC.TNET.NAT.ZS
Done
271 CC.TNET.REP.FAC
Done
272 CC.TOTL.COCA.AN
Done
273 CC.TOTL.COCA.CA
Done
274 CC.TOTL.COCA.CO
Done
275 CC.TOTL.COCA.MB
Done
276 CC.TOTL.COCA.OP
Done
277 CC.TOTL.COCA.PE
Done
278 CC.TOTL.COCA.PP
Done
279 CC.TOTL.COCA.RE
Done
280 CC.TOTL.COCA.SH
Done
281 EG.ELC.ACCS.ZS
Done
282 ER.H2O.INTR.PC
Done
283 GC.DOD.TOTL.GD.ZS
Done
284 GC.TAX.TOTL.GD.ZS
Done
285 IC.ELC.OUTG
Done
286 IC.ELC.OUTG.ZS
Done
287 IC.FRM.FEMO.ZS
Done
288 IC.FRM.OUTG.ZS
Done
289 NY.GDP.COAL.RT.ZS
Done
290 NY.GDP.MINR.RT.ZS
Done
291 NY.GDP.MKTP.CD
Done
292 NY.GDP.MKTP.KD.ZG
Done
293 NY.GDP.NGAS.RT.ZS
Done
294 NY.GDP.PCAP.CD
Done
295 NY.GDP.PETR.RT.ZS
Done
296 NY.GDP.TOTL.RT.ZS
Done
297 SG.GEN.PARL.ZS
Done
298 SH.H2O.BASW.ZS
Done
299 SH.STA.BASS.ZS
Done
300 SH.STA.HYGN.ZS
Done
301 SI.POV.GINI
Done
302 SI.POV.UMIC
Done
303 SL.TLF.TOTL.FE.ZS
Done
304 SL.UEM.TOTL.ZS
Done
305 SP.POP.TOTL
Done
306 SP.URB.TOTL.IN.ZS
Done

In [9]:
appended_data.to_csv('appended_data.csv')

In [114]:
# 220 countries
tableau = appended_data.groupby('variable').count().reset_index()
#tableau[["code1", "code2", "code3", "code4", "code5"]] = tableau['variable'].str.split(expand=True, pat='.')
tableau = tableau.merge(desc, left_on = 'variable', right_on = 'variable')
tableau["row"] = tableau["variable"] + ": " + tableau["description"]
tableau.set_index('variable', inplace = True)

In [115]:
counts = tableau[["code1", "code2", "code3", "code4", "code5"]].value_counts().to_frame('counts')
counts.sort_values(by=["code1", "code2", "code3", "code4", "code5"], ascending=True)

                               counts
code1 code2 code3 code4 code5
CC    EG    CONS  COAL  PC          1
                  GAS   PC          1
                  OIL   PC          1
      EN    ATM   COAL  CE          1
      SE    ADT   LITR  ZS          1
GC    DOD   TOTL  GD    ZS          1
      TAX   TOTL  GD    ZS          1
NY    GDP   COAL  RT    ZS          1
            MINR  RT    ZS          1
            MKTP  KD    ZG          1
            NGAS  RT    ZS          1
            PETR  RT    ZS          1
            TOTL  RT    ZS          1
SL    TLF   TOTL  FE    ZS          1
SP    URB   TOTL  IN    ZS          1

In [116]:
#list(tableau.columns)
columns = [ 'YR1960',
 'YR1961',
 'YR1962',
 'YR1963',
 'YR1964',
 'YR1965',
 'YR1966',
 'YR1967',
 'YR1968',
 'YR1969',
 'YR1970',
 'YR1971',
 'YR1972',
 'YR1973',
 'YR1974',
 'YR1975',
 'YR1976',
 'YR1977',
 'YR1978',
 'YR1979',
 'YR1980',
 'YR1981',
 'YR1982',
 'YR1983',
 'YR1984',
 'YR1985',
 'YR1986',
 'YR1987',
 'YR1988',
 'YR1989',
 'YR1990',
 'YR1991',
 'YR1992',
 'YR1993',
 'YR1994',
 'YR1995',
 'YR1996',
 'YR1997',
 'YR1998',
 'YR1999',
 'YR2000',
 'YR2001',
 'YR2002',
 'YR2003',
 'YR2004',
 'YR2005',
 'YR2006',
 'YR2007',
 'YR2008',
 'YR2009',
 'YR2010',
 'YR2011',
 'YR2012',
 'YR2013',
 'YR2014',
 'YR2015',
 'YR2016',
 'YR2017',
 'YR2018',
 'YR2019',
 'YR2020',
 'YR2021',
 'YR2022',
 'YR2023',
 'YR2024',
 'YR2025',
 'YR2026',
 'YR2027',
 'YR2028',
 'YR2029',
 'YR2030',
 'YR2031',
 'YR2032',
 'YR2033',
 'YR2034',
 'YR2035',
 'YR2036',
 'YR2037',
 'YR2038',
 'YR2039',
 'YR2040',
 'YR2041',
 'YR2042',
 'YR2043',
 'YR2044',
 'YR2045',
 'YR2046',
 'YR2047',
 'YR2048',
 'YR2049',
 'YR2050',
 'YR2100',]

In [117]:
countZ = pd.DataFrame(tableau[columns].astype(bool).sum(axis=1), columns=['number_years'])
tableau = tableau.merge(countZ, left_on = 'variable', right_on = 'variable').sort_values(by='number_years', ascending=False)
tableau

                    economy  Country  YR1960  YR1961  YR1962  YR1963  YR1964  \
variable
SP.URB.TOTL.IN.ZS       220      220     215     215     215     215     215
SP.POP.TOTL             220      220     216     216     216     216     216
NY.GDP.PCAP.CD          220      220      99     100     103     103     103
NY.GDP.MKTP.CD          220      220      99     100     103     103     103
NY.GDP.MKTP.KD.ZG       220      220       0      93      96      96      96
AG.LND.ARBL.ZS          220      220       0     176     176     176     176
AG.LND.AGRI.ZS          220      220       0     179     179     179     179
NY.GDP.TOTL.RT.ZS       220      220       0       0       0       0       0
NY.GDP.COAL.RT.ZS       220      220       0       0       0       0       0
NY.GDP.MINR.RT.ZS       220      220       0       0       0       0       0
NY.GDP.NGAS.RT.ZS       220      220       0       0       0       0       0
NY.GDP.PETR.RT.ZS       220      220       0       0       0       0       0
GC.TAX.TOTL.GD.ZS       220      220       0       0       0       0       0
SI.POV.UMIC             220      220       0       0       0       0       0
SI.POV.GINI             220      220       0       0       0       0       0
CC.EG.CONS.COAL.PC      220      220       0       0       0       0       0
CC.EG.CONS.GAS.PC       220      220       0       0       0       0       0
CC.EG.CONS.OIL.PC       220      220       0       0       0       0       0
GC.DOD.TOTL.GD.ZS       220      220       0       0       0       0       0
SL.UEM.TOTL.ZS          220      220       0       0       0       0       0
EG.ELC.ACCS.ZS          220      220       0       0       0       0       0
CC.GHG.EMSE.WA          220      220       0       0       0       0       0
CC.CO2.EMSE.TR          220      220       0       0       0       0       0
CC.CO2.EMSE.OF          220      220       0       0       0       0       0
CC.CO2.EMSE.MC          220      220       0       0       0       0       0
CC.CO2.EMSE.LU          220      220       0       0       0       0       0
CC.GHG.EMSE.OF          220      220       0       0       0       0       0
CC.GHG.EMSE.TR          220      220       0       0       0       0       0
CC.CO2.EMSE.EH          220      220       0       0       0       0       0
CC.GHG.EMSE.MC          220      220       0       0       0       0       0
CC.GHG.EMSE.LU          220      220       0       0       0       0       0
CC.GHG.EMSE.IP          220      220       0       0       0       0       0
CC.CO2.EMSE.IL          220      220       0       0       0       0       0
CC.GHG.EMSE.IL          220      220       0       0       0       0       0
CC.GHG.EMSE.FE          220      220       0       0       0       0       0
CC.GHG.EMSE.EN          220      220       0       0       0       0       0
CC.GHG.EMSE.EL          220      220       0       0       0       0       0
CC.GHG.EMSE.EH          220      220       0       0       0       0       0
CC.GHG.EMSE.BL          220      220       0       0       0       0       0
CC.CO2.EMSE.IP          220      220       0       0       0       0       0
CC.GHG.EMSE.BF          220      220       0       0       0       0       0
CC.CO2.EMSE.FE          220      220       0       0       0       0       0
CC.GHG.PECA             220      220       0       0       0       0       0
CC.NCO.GHG.AG           220      220       0       0       0       0       0
CC.NCO.GHG.EL           220      220       0       0       0       0       0
CC.NCO.GHG.EN           220      220       0       0       0       0       0
CC.NCO.GHG.FE           220      220       0       0       0       0       0
CC.NCO.GHG.IL           220      220       0       0       0       0       0
CC.NCO.GHG.IP           220      220       0       0       0       0       0
CC.NCO.GHG.LU           220      220       0       0       0       0       0
CC.NCO.GHG.OF           220      220       0       0       0       0       0
CC.CO2.EMSE.EN          220      220       0       0       0       0       0
CC.NCO.GHG.WA           220      220       0       0       0       0       0
CC.CO2.EMSE.BF          220      220       0       0       0       0       0
CC.CO2.EMSE.BL          220      220       0       0       0       0       0
CC.GHG.EMSE.AG          220      220       0       0       0       0       0
CC.CO2.EMSE.EL          220      220       0       0       0       0       0
CC.GHG.GRPE             220      220       0       0       0       0       0
CC.FGHG.SYS.RE          220      220       0       0       0       0       0
CC.FGHG.SYS.PR          220      220       0       0       0       0       0
CC.FGHG.SYS.PD          220      220       0       0       0       0       0
CC.FGHG.SYS.PC          220      220       0       0       0       0       0
CC.FGHG.SYS.LU          220      220       0       0       0       0       0
CC.FGHG.SYS.EO          220      220       0       0       0       0       0
CC.FGHG.SYS.CS          220      220       0       0       0       0       0
CC.FGHG.SYS.TR          220      220       0       0       0       0       0
CC.GHG.FSYS.FG          220      220       0       0       0       0       0
CC.GHG.FSYS.CH          220      220       0       0       0       0       0
CC.GHG.FSYS.CO          220      220       0       0       0       0       0
CC.GHG.FSYS.NO          220      220       0       0       0       0       0
CC.GNBD.ISS.BD          220      220       0       0       0       0       0
CC.ENV.GDS.CADV         220      220       0       0       0       0       0
CC.ENV.TRAD.EX          220      220       0       0       0       0       0
CC.ENV.TRAD.IM          220      220       0       0       0       0       0
CC.SE.CAT2.ZS           220      220       0       0       0       0       0
CC.ESG.SEMA             220      220       0       0       0       0       0
CC.ESG.OSFE             220      220       0       0       0       0       0
CC.ESG.OSMA             220      220       0       0       0       0       0
CC.ESG.PAMA             220      220       0       0       0       0       0
CC.ESG.SEFE             220      220       0       0       0       0       0
CC.SE.CAT4.ZS           220      220       0       0       0       0       0
CC.ESG.TCFE             220      220       0       0       0       0       0
CC.ESG.TCMA             220      220       0       0       0       0       0
CC.SE.CAT3.ZS           220      220       0       0       0       0       0
CC.SE.CAT1.ZS           220      220       0       0       0       0       0
CC.ESG.MIFE             220      220       0       0       0       0       0
CC.ESG.MIMA             220      220       0       0       0       0       0
CC.ESG.PAFE             220      220       0       0       0       0       0
CC.ESG.MAMA             220      220       0       0       0       0       0
CC.ESG.CMMA             220      220       0       0       0       0       0
CC.ESG.CNMA             220      220       0       0       0       0       0
CC.ESG.CMFE             220      220       0       0       0       0       0
CC.ESG.AGMA             220      220       0       0       0       0       0
CC.ESG.AGFE             220      220       0       0       0       0       0
CC.ESG.EUFE             220      220       0       0       0       0       0
CC.ESG.EUMA             220      220       0       0       0       0       0
CC.ESG.FBFE             220      220       0       0       0       0       0
CC.ESG.FBMA             220      220       0       0       0       0       0
CC.ESG.MAFE             220      220       0       0       0       0       0
CC.ESG.INFE             220      220       0       0       0       0       0
CC.ESG.INMA             220      220       0       0       0       0       0
CC.ESG.CNFE             220      220       0       0       0       0       0
CC.ISG.NBMA             220      220       0       0       0       0       0
CC.ISG.FFMA             220      220       0       0       0       0       0
CC.ISG.NAFE             220      220       0       0       0       0       0
CC.ISG.FFFE             220      220       0       0       0       0       0
CC.ISG.NBFE             220      220       0       0       0       0       0
CC.SE.NYRS.AVG          220      220       0       0       0       0       0
CC.ISG.NAMA             220      220       0       0       0       0       0
CC.ASP.COVG.QT          220      220       0       0       0       0       0
CC.ASP.COVG.ZS          220      220       0       0       0       0       0
CC.EG.EMIS.MAN          220      220       0       0       0       0       0
CC.ASP.TRAF.PC          220      220       0       0       0       0       0
CC.CUF.STUN             220      220       0       0       0       0       0
SH.STA.HYGN.ZS          220      220       0       0       0       0       0
SH.STA.BASS.ZS          220      220       0       0       0       0       0
SH.H2O.BASW.ZS          220      220       0       0       0       0       0
CC.ESG.PSFE             220      220       0       0       0       0       0
CC.ESG.PSMA             220      220       0       0       0       0       0
CC.SE.ADT.LITR.ZS       220      220       0       0       0       0       0
IC.FRM.OUTG.ZS          220      220       0       0       0       0       0
IC.ELC.OUTG.ZS          220      220       0       0       0       0       0
IC.ELC.OUTG             220      220       0       0       0       0       0
ER.H2O.INTR.PC          220      220       0       0     155       0       0
CC.PUN.TOTL             220      220       0       0       0       0       0
CC.ENTX.ENE.ZS          220      220       0       0       0       0       0
CC.SP.EXP.ZS            220      220       0       0       0       0       0
CC.ENTX.ENV.ZS          220      220       0       0       0       0       0
CC.TOTL.COCA.CO         220      220       0       0       0       0       0
CC.TOTL.COCA.MB         220      220       0       0       0       0       0
CC.TOTL.COCA.OP         220      220       0       0       0       0       0
CC.TOTL.COCA.RE         220      220       0       0       0       0       0
CC.TOTL.COCA.PE         220      220       0       0       0       0       0
CC.TOTL.COCA.PP         220      220       0       0       0       0       0
CC.TOTL.COCA.CA         220      220       0       0       0       0       0
CC.TOTL.COCA.SH         220      220       0       0       0       0       0
CC.TOTL.COCA.AN         220      220       0       0       0       0       0
CC.NEFO.IMCR.BA         220      220       0       0       0       0       0
CC.SP.COV.ZS            220      220       0       0       0       0       0
CC.NEFO.IMCR.RM         220      220       0       0       0       0       0
CC.NEFO.IMCR.RB         220      220       0       0       0       0       0
CC.NEFO.IMCR.RI         220      220       0       0       0       0       0
CC.NEFO.IMCR.WH         220      220       0       0       0       0       0
CC.FSU.PECA             220      220       0       0       0       0       0
CC.FOOD.ANIM.ZS         220      220       0       0       0       0       0
CC.FOOD.VEGT.ZS         220      220       0       0       0       0       0
CC.NEFO.IMCR.BP         220      220       0       0       0       0       0
CC.NEFO.IMCR.MA         220      220       0       0       0       0       0
CC.NEFO.IMCR.SB         220      220       0       0       0       0       0
CC.NEFO.IMCR.RE         220      220       0       0       0       0       0
CC.NEFO.IMCR.RH         220      220       0       0       0       0       0
CC.FDX.FTY.ZS           220      220       0       0       0       0       0
CC.EG.SUBF.PC           220      220       0       0       0       0       0
CC.FDX.FTN.ZS           220      220       0       0       0       0       0
CC.MT.PS.EST            220      220       0       0       0       0       0
CC.MT.RL.EST            220      220       0       0       0       0       0
CC.MT.GE.EST            220      220       0       0       0       0       0
CC.PSVOL.MOD.AI         220      220       0       0       0       0       0
CC.MT.RQ.EST            220      220       0       0       0       0       0
CC.FRVOL.MOD.AI         220      220       0       0       0       0       0
CC.MT.VA.EST            220      220       0       0       0       0       0
CC.FDX.PMT.ZS           220      220       0       0       0       0       0
CC.FDX.SAV.ZS           220      220       0       0       0       0       0
CC.PRO.ANI              220      220       0       0       0       0       0
CC.RIC.PECA             220      220       0       0       0       0       0
CC.RISK.AST.ZS          220      220       0       0       0       0       0
CC.RISK.WELL.ZS         220      220       0       0       0       0       0
CC.POP.INF.TL           220      220       0       0       0       0       0
CC.PRNX.CAT1.ZS         220      220       0       0       0       0       0
CC.PSVOL.MOD.RA         220      220       0       0       0       0       0
CC.PRNX.CAT5.ZS         220      220       0       0       0       0       0
CC.PRNX.CAT4.ZS         220      220       0       0       0       0       0
CC.PRNX.CAT3.ZS         220      220       0       0       0       0       0
CC.PRNX.CAT2.ZS         220      220       0       0       0       0       0
CC.PSVOL.MOD.RO         220      220       0       0       0       0       0
CC.ADPO.MIEX.BB         220      220       0       0       0       0       0
CC.SH.AIRP.AIR          220      220       0       0       0       0       0
CC.THHZ.RANK.EH         220      220       0       0       0       0       0
CC.THHZ.RANK.LS         220      220       0       0       0       0       0
CC.THHZ.RANK.RF         220      220       0       0       0       0       0
CC.THHZ.RANK.TS         220      220       0       0       0       0       0
CC.OPCO.PLTY.UK         220      220       0       0       0       0       0
CC.THHZ.RANK.UF         220      220       0       0       0       0       0
CC.THHZ.RANK.WF         220      220       0       0       0       0       0
CC.TNET.CYC.ZS          220      220       0       0       0       0       0
CC.TNET.EAR.ZS          220      220       0       0       0       0       0
CC.TNET.FLD.ZS          220      220       0       0       0       0       0
CC.TNET.INV.ZS          220      220       0       0       0       0       0
CC.TNET.NAT.ZS          220      220       0       0       0       0       0
CC.TNET.REP.FAC         220      220       0       0       0       0       0
CC.ADPO.MAEX.BB         220      220       0       0       0       0       0
CC.ADPO.MAEX.AA         220      220       0       0       0       0       0
CC.ACLD.PRTS.NO         220      220       0       0       0       0       0
CC.THHZ.RANK.EQ         220      220       0       0       0       0       0
CC.THHZ.RANK.CY         220      220       0       0       0       0       0
CC.SH.AIRP.AMB          220      220       0       0       0       0       0
CC.THHZ.RANK.CF         220      220       0       0       0       0       0
CC.TCFD.COMP.CB         220      220       0       0       0       0       0
CC.TCFD.COMP.CD         220      220       0       0       0       0       0
CC.TCFD.COMP.CM         220      220       0       0       0       0       0
CC.TCFD.COMP.CS         220      220       0       0       0       0       0
CC.TCFD.COMP.EN         220      220       0       0       0       0       0
CC.TCFD.COMP.FI         220      220       0       0       0       0       0
CC.TCFD.COMP.GO         220      220       0       0       0       0       0
CC.TCFD.COMP.HC         220      220       0       0       0       0       0
CC.TCFD.COMP.IN         220      220       0       0       0       0       0
CC.TCFD.COMP.IT         220      220       0       0       0       0       0
CC.TCFD.COMP.MT         220      220       0       0       0       0       0
CC.TCFD.COMP.OT         220      220       0       0       0       0       0
CC.TCFD.COMP.RE         220      220       0       0       0       0       0
CC.TCFD.COMP.TR         220      220       0       0       0       0       0
CC.TCFD.COMP.UT         220      220       0       0       0       0       0
CC.OPCO.PLTY.US         220      220       0       0       0       0       0
CC.GHG.SDEG.OF          220      220       0       0       0       0       0
CC.OPCO.PLTY.SU         220      220       0       0       0       0       0
CC.EG.COAL.PROD         220      220       0       0       0       0       0
CC.CHIC.CFPI.LP         220      220       0       0       0       0       0
CC.COAL.EMIS.CH         220      220       0       0       0       0       0
CC.COAL.EMIS.CO         220      220       0       0       0       0       0
CC.COAL.EMPR.CH         220      220       0       0       0       0       0
CC.COAL.EMPR.CO         220      220       0       0       0       0       0
CC.EG.CAP.GAEX          220      220       0       0       0       0       0
CC.EG.CAP.GAIM          220      220       0       0       0       0       0
CC.EG.COAL.MW           220      220       0       0       0       0       0
CC.EG.INTS.KW           220      220       0       0       0       0       0
CC.FRVOL.MOD.RO         220      220       0       0       0       0       0
CC.EG.SOLR.KW           220      220       0       0       0       0       0
CC.EG.STL.PROD          220      220       0       0       0       0       0
CC.EG.WIND.PC           220      220       0       0       0       0       0
CC.EG.WIND.TOTL         220      220       0       0       0       0       0
CC.EN.ATM.COAL.CE       220      220       0       0       0       0       0
CC.FLD.BELW.ZS          220      220       0       0       0       0       0
CC.OPCO.PLTY.SC         220      220       0       0       0       0       0
CC.FRVOL.MOD.IW         220      220       0       0       0       0       0
CC.CHIC.CFPI.HE         220      220       0       0       0       0       0
CC.CHIC.CFPI.FP         220      220       0       0       0       0       0
CC.CHIC.CFPI.DI         220      220       0       0       0       0       0
CC.CHIC.CFPI.AI         220      220       0       0       0       0       0
CC.AVPB.PTPI.AI         220      220       0       0       0       0       0
CC.AVPB.PTPI.AR         220      220       0       0       0       0       0
CC.AVPB.PTPI.DI         220      220       0       0       0       0       0
CC.AVPB.PTPI.FP         220      220       0       0       0       0       0
CC.AVPB.PTPI.HE         220      220       0       0       0       0       0
CC.AVPB.PTPI.LP         220      220       0       0       0       0       0
CC.AVPB.TPOP.AG         220      220       0       0       0       0       0
CC.AVPB.TPOP.AI         220      220       0       0       0       0       0
CC.AVPB.TPOP.DI         220      220       0       0       0       0       0
CC.AVPB.TPOP.HE         220      220       0       0       0       0       0
CC.AVPB.TPOP.TE         220      220       0       0       0       0       0
CC.CHIC.BTFP.AG         220      220       0       0       0       0       0
CC.CHIC.BTFP.AI         220      220       0       0       0       0       0
CC.CHIC.BTFP.DI         220      220       0       0       0       0       0
CC.CHIC.BTFP.HE         220      220       0       0       0       0       0
CC.CHIC.BTFP.TE         220      220       0       0       0       0       0
CC.CHIC.CFPI.AG         220      220       0       0       0       0       0
CC.FRVOL.MOD.RA         220      220       0       0       0       0       0
CC.FLD.TOTL.ZS          220      220       0       0       0       0       0
CC.GAS.PPBC.CN          220      220       0       0       0       0       0

In [118]:
countZ["number_years"].value_counts()

1     133
29     36
21     28
5      14
26     12
2      10
0       9
7       9
18      8
20      7
50      5
40      3
22      3
8       3
15      3
3       3
30      2
61      2
58      2
19      2
91      2
11      1
31      1
16      1
47      1
48      1
49      1
28      1
13      1
60      1
23      1
Name: number_years, dtype: int64

In [126]:
# Empty = 9
empty = countZ[countZ["number_years"]==0].reset_index()["variable"].to_list()

#["variable"].to_list()
len(empty)
empty

['AG.LND.FRST.ZS',
 'CC.EG.COAL.EMIS',
 'CC.EMP.MULT.NO',
 'CC.FLD.CITY.ZS',
 'CC.SE.COMP.ZS',
 'CC.TCFD.COMP.NO',
 'IC.FRM.FEMO.ZS',
 'SG.GEN.PARL.ZS',
 'SL.TLF.TOTL.FE.ZS']

In [124]:
# Cross-section = 133
crossSection = countZ[countZ["number_years"]==1].reset_index()["variable"].to_list()

In [103]:
# Time series = 164
timeSeries = countZ[countZ["number_years"]>1]["variable"].to_list()
len(timeSeries)

164

In [121]:
pd.options.display.float_format = '{:,.1f}'.format
percentages = tableau[columns]/220*100
data = percentages.values.round(1)
data

array([[97.7, 97.7, 97.7, ..., 97.7, 97.7,  0. ],
       [98.2, 98.2, 98.2, ..., 96.8, 96.8,  0. ],
       [45. , 45.5, 46.8, ...,  0. ,  0. ,  0. ],
       ...,
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ]])

In [122]:
fig = px.imshow(data,
                labels=dict(x = "Year", y = "Indicator", color = "Available"),
                x = columns,
                y = tableau["row"].str.slice(0,100).tolist(), 
                #width=1500, 
                height=5000,
                #color_continuous_scale = "portland_r"
               )
fig.update_layout(
    title="CCDR Variables: Availability and Number of Observations",
    coloraxis_colorbar=dict(
    thicknessmode="pixels", thickness=70,
    lenmode="pixels", len=400,
    yanchor="top", y=.95,
    ticks="outside", ticksuffix=" %",
    dtick=5)
)
fig.update_xaxes(side="top")
fig.write_html("../CCDRinventory.html")
#fig.write_json("../WDIinventory.json", pretty=True)