# AreaSqKm_01_Notebook
Javier Parada

October 18, 2021

## Purpose
This notebook documents the procedure followed in the measurement of areas. 

How do we loop over a FeatureCollection?

print(shapes.distinct("ADM0_NAME").aggregate_array("ADM0_CODE"))

## References

https://geemap.org/notebooks/select_features/#Select-multiple-states

https://geemap.org/common/#geemap.common.zonal_statistics_by_group

https://www.youtube.com/watch?v=4dN5iTT7mhY

https://spatialthoughts.com/2020/06/19/calculating-area-gee/

In [1]:
# Data manipulation
import pandas as pd
import numpy as np
pd.options.display.float_format = "{:,.2f}".format

# Options for pandas
pd.options.display.max_columns = 50
pd.options.display.max_rows = 50

# Visualizations
import plotly
import plotly.graph_objs as go
import plotly.offline as ply
plotly.offline.init_notebook_mode(connected=True)

import plotly.express as px

import cufflinks as cf
cf.go_offline(connected=True)
cf.set_config_file(theme='white')

import matplotlib as plt

# Autoreload extension
if 'autoreload' not in get_ipython().extension_manager.loaded:
    %load_ext autoreload
    
%autoreload 2

In [12]:
# Additional libraries
import os
from os.path import exists
import glob
import random
import folium
import wbgapi as wb
import geopandas as gpd
import matplotlib.pyplot as plt
#import plotly.graph_objects as go

import ee
ee.Initialize()
import leafmap
#leafmap.update_package()
import geemap
#geemap.update_package()

In [3]:
out_dir = os.path.join(os.path.expanduser('~'), 'Documents/Websites/JavierParada.github.io/EL5M/')
print(out_dir)

/Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/

In [4]:
# Shapefiles
gaul0 = ee.FeatureCollection("FAO/GAUL/2015/level0")
gaul1 = ee.FeatureCollection("FAO/GAUL/2015/level1")
gaul2 = ee.FeatureCollection("FAO/GAUL_SIMPLIFIED_500m/2015/level2")

# Tutorial

In [5]:
Map = geemap.Map()
Map

Map(center=[40, -100], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=HBox(children=(T…

In [6]:
gaul2 = ee.FeatureCollection('FAO/GAUL/2015/level2')
Map.addLayer(gaul2, {}, "FAO/GAUL/2015/level2")

# Elevation Data

In [7]:
merit = ee.Image("MERIT/DEM/v1_0_3").select('dem')
lowAreas = merit.lte(5)

# Generate list of 276 countries

In [8]:
listOfCodes0 = gaul2.sort('ADM0_CODE', True).distinct("ADM0_CODE").aggregate_array("ADM0_CODE").getInfo()
print(listOfCodes0)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 2647, 2648, 33364, 40760, 40762, 40765, 40781, 61013, 74578, 147295, 147296]

# Loop

In [9]:
stattype = 'SUM'

In [10]:
skip = [259]

In [ ]:
for code in reversed(listOfCodes0):
    print(code)
    
    roi = gaul2.filter(ee.Filter.eq('ADM0_CODE', code))
    nlcd_stats = os.path.join(out_dir, 'district_results/district_results_{}.csv'.format(code)) 
    
    if code not in [259]:
        if exists(nlcd_stats):
            print("Already done")
        else:
            geemap.zonal_statistics_by_group(lowAreas, 
                                 roi, 
                                 nlcd_stats, 
                                 statistics_type = stattype, 
                                 denominator=1000000, 
                                 decimal_places=2,
                                 scale = 100)
    else:
        print("Skipped")

147296
Already done
147295
Already done
74578
Already done
61013
Already done
40781
Already done
40765
Already done
40762
Already done
40760
Already done
33364
Already done
2648
Already done
2647
Already done
271
Already done
270
Already done
269
Already done
268
Already done
267
Already done
266
Already done
265
Already done
264
Already done
263
Already done
262
Already done
261
Already done
260
Already done
259
Skipped
258
Already done
257
Already done
256
Already done
255
Already done
254
Already done
253
Already done
252
Already done
251
Already done
250
Already done
249
Already done
248
Already done
247
Already done
246
Already done
245
Already done
244
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/87c1ac1982d8eb105e89317f987c8182-28a14ddc8e3a946cdf6ca93cb00eae18:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_244.csv
243
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/27ff090d2de4f95c751f5157ce59e112-63394ba3129443b5756ebc5556f1543a:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_243.csv
242
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/74f95a82dcac83bacaab59a3a8e3f9d7-c907f5e9a3fb0a67399e6381ba33bade:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_242.csv
241
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/5efb86ae509faec0ad626a5010a7cc5f-02a8d92aacbce5d69aa52d6481bba4c6:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_241.csv
240
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/9771b62b4583c1715edc4043243fa741-27826fdf1c1bf2304a40faec6b5c2a87:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_240.csv
239
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/6b5525de346113cfb74f0562e903419a-de1ea460c4a1b232bc8c7ac753a170b5:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_239.csv
238
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/0a452b439bb04e5c42a646deebec8fbe-a084966fc639445759273b6a05290e8f:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_238.csv
237
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/834c335a8e583e0bc46b02894569e83d-c1d89023cb2c8b94a2eaf322a52be4ce:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_237.csv
236
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/ec1aabf707643f50d3a8e3d677967b72-16be722d048cec5a4e89c76342babf11:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_236.csv
235
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/2f237cd0d59db2848396cb65fa524b58-9de41632299acdf1457f17fac4a671d7:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_235.csv
234
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/1cff7d6552bd4b9cedc48e4c0464cfe4-581ee229dd93aca2eaa9ed739be86a28:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_234.csv
233
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/6df13622760031a02cb241ff2a62487c-1bb72f8a506c56ba7376c783a0c51acd:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_233.csv
231
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/4c33ad0777fd69a12829b54f7cac920c-9b25557e2e629c4e012be06efd9b198f:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_231.csv
230
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/591a810134c5847c99096159b4d0d71d-b35d3e4f2ebc1d932216d0c0ecbeb97a:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_230.csv
229
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/1f033ec8c3b06110a06cf54f52bd56ab-a2350b31269b55bd2e063cc21f753af8:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_229.csv
228
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/b4e9a59be8697e45bc6e606bbb4f4cc0-6c100a83ab53fcd3dde57b3d228035bc:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_228.csv
227
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/d83b7688c72545870adc2fa1fbd3d19c-0c5dae6c6fefa37fde7aedf59018ffaf:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_227.csv
226
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/507eefbfbc60f8fb73ad7d0e6885b819-653e123de4344e23a23ef5f3f10d215d:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_226.csv
225
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/a6b5e53329eea735791b4e6a51a99d9c-3e63150da5f1c77576dceb6462af3a25:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_225.csv
224
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/cfac0d627e8d49d829a15c0aebf1531b-eca2dfbe4af8777aef91cacc75626179:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_224.csv
223
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/2d696be77d24d031e291275801a3512b-1e557b517f195d522e71f852057ff984:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_223.csv
222

Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/d55aacfe7ed166b9788f3ce3e77b9642-c3c523571f44361dffe4a56cb193f8ef:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_222.csv
221
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/6397b2c3ac8aa0bcc8e8615a61a11cd8-f149d5b633e39625cf958b1144ff5798:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_221.csv
220
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/05fa71eb93a7470131f3b5fe7c5731d5-cb7b724f3b2c59b032935e4cac7a43bc:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_220.csv
218
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/23a76bb39a7016b65eb6230750fe320f-673e4714126d78730ea74dd362423328:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_218.csv
217
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/6a966fcc47a5832d8e1bc93134b97dd7-81afecd892537f14b5fb25e9d5b188ba:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_217.csv
216
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/5e399ca85e5fd9303ec3a87bcd818d65-f4496a23dae63755c3e91c7697209caf:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_216.csv
215
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/d6876977edb856d93a7c47606599ab9e-5eecb61485fbf553478c9801e9741bea:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_215.csv
214
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/30d73ac27b98e896d43c61e84bb947d0-5dbcb689956da503f2a382a0d69009ff:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_214.csv
213
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/43f4a098c6aa496af4a3b1887609858a-ba6a2dc41d9e81feaa6a3421c12cb1d1:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_213.csv
212
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/d2ecd163a252b17ac2bb5e50f3fb2ac6-df7bedec9b7cf39873e89690febd9b1d:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_212.csv
211
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/a826b1444346d79b15b4f6117c1af847-501f44980b2e549df926f780d6ff716b:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_211.csv
210
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/163a9e94f201b10f63676ba79164f870-0c311969334ac1bcfb51a263443118ea:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_210.csv
209
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/34b46bae0fecbd53aca021cf903543e0-4392d5fc90599af204d713089dc8b491:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_209.csv
208
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/0ba4aea9213abbf9fe69a38427553772-350eda68c8d1bf33d1d44529e5bcb6d9:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_208.csv
207
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/528eeb6e6efba7a7b1175b2ccdc6d2ac-69260b6f23c5bdeec352bb98c9809624:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_207.csv
206
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/9d01e9bed247906f917a5177631ad37f-32f17b7bd60a4ddc86ab28b93583fdd3:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_206.csv
205
Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/bb17cca2c7222768c000e8a96087b718-80d7066a8297e0967b3fc85c32ff80b6:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/district_results_205.csv
204
Computing ...

# United States 
3228
3239

In [ ]:
UsaStates = gaul2.filter(ee.Filter.eq('ADM0_CODE', 259)).sort('ADM1_NAME', True).distinct("ADM1_NAME").aggregate_array("ADM1_NAME").getInfo()
print(UsaStates)

In [ ]:
skip = ["Alaska"]
for state in UsaStates:
    print(state)
    roi = gaul2.filter(ee.Filter.eq('ADM0_CODE', 259)).filter(ee.Filter.eq('ADM1_NAME', state))
    nlcd_stats = os.path.join(out_dir, 'district_results/district_results_259_{}.csv'.format(state)) 
    if state not in skip:
        if exists(nlcd_stats):
            print("Already done")
        else:
            geemap.zonal_statistics_by_group(lowAreas, 
                                 roi, 
                                 nlcd_stats, 
                                 statistics_type = stattype, 
                                 denominator=1000000, 
                                 decimal_places=2,
                                 scale = 100)
    else:
        print("Skipped")

# Alaska

In [ ]:
AlaksaSHP = gaul2.filter(ee.Filter.eq('ADM0_CODE', 259)).filter(ee.Filter.eq('ADM1_NAME', 'Alaska')).sort('ADM2_CODE', True).distinct("ADM2_CODE").aggregate_array("ADM2_CODE").getInfo()
print(AlaksaSHP)

In [ ]:
skip = []
for county in AlaksaSHP:
    print(county)
    roi = gaul2.filter(ee.Filter.eq('ADM0_CODE', 259)).filter(ee.Filter.eq('ADM1_NAME', "Alaska")).filter(ee.Filter.eq('ADM2_CODE', county))
    nlcd_stats = os.path.join(out_dir, 'district_results/district_results_259_Alaska_{}.csv'.format(county)) 
    
    if county not in skip:
        if exists(nlcd_stats):
            print("Already done")
        else:
            geem1ap.zonal_statistics_by_group(lowAreas, 
                                 roi, 
                                 nlcd_stats, 
                                 statistics_type = stattype, 
                                 denominator=1000000, 
                                 decimal_places=2,
                                 scale = 100)
    else:
        print("Skipped")

# Append all results

In [ ]:
# 216 countries, 354 files
os.chdir("/Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/district_results/")
extension = 'csv'
all_filenames = sorted([i for i in glob.glob('*.{}'.format(extension))])
len(all_filenames)

In [ ]:
# allDistricts
allDistricts = pd.concat([pd.read_csv(f) for f in all_filenames])
allDistricts["Percent_0"] = allDistricts["Class_0"]/allDistricts["Class_sum"]
allDistricts["Percent_1"] = 1 - allDistricts["Percent_0"]

In [ ]:
allDistricts.to_csv("../allDistricts.csv", index=False)

## 38,229

In [7]:
GAUL_2_38229 = 'shapes/GAUL Districts/districts.shp'
GAUL_borders_2 = gpd.read_file(os.path.join(out_dir, GAUL_2_38229))

In [8]:
borders_0 = pd.DataFrame(pd.unique(GAUL_borders_2["ADM0_CODE"]))
borders_1 = pd.DataFrame(pd.unique(GAUL_borders_2["ADM1_CODE"]))
borders_2 = pd.DataFrame(pd.unique(GAUL_borders_2["ADM2_CODE"]))
print('{} countries, {} states, {} provinces in WDI'.format(len(borders_0), len(borders_1), len(GAUL_borders_2)))

255 countries, 3409 states, 38229 provinces in WDI

In [9]:
GAUL_borders_2 = GAUL_borders_2.sort_values(by=['ADM0_NAME', 'ADM1_NAME', 'ADM2_NAME'])

In [ ]:
shapeNew = geemap.shp_to_ee("/Users/javierparada/Documents/Websites/JavierParada.github.io/EL5M/shapes/GAUL Districts/districts.shp", encoding='latin-1')

In [42]:
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')

dictOfShapes = {}
for i, (iso, name) in enumerate(zip(GAUL_borders_2["ADM2_CODE"], GAUL_borders_2["ADM2_NAME"])):
    
    print(i+1, iso, name)
    
    roi = GAUL_borders_2[GAUL_borders_2["ADM2_CODE"] == iso]
    nlcd_stats = os.path.join(out_dir, 'kerala.csv')  
    geemap.zonal_statistics_by_group(lowAreas.clip(roi), 
                                 a, 
                                 nlcd_stats, 
                                 statistics_type='SUM', 
                                 denominator=1000000, 
                                 decimal_places=2,
                                 scale = 500)

    if i == 1:
        break

1 100006 Arghanjkhwa

EEException: Can't encode object:        OBJECTID  ADM2_CODE    ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
31273 31,274.00     100006  Arghanjkhwa       2004       3000        272

        ADM1_NAME        STATUS DISP_AREA  ADM0_CODE    ADM0_NAME  Shape_Leng  \
31273  Badakhshan  Member State        NO          1  Afghanistan        1.62

       Shape_Le_1  Shape_Area  \
31273        1.62        0.07

                                                geometry
31273  POLYGON ((70.92578 37.30446, 70.92749 37.30363...

In [25]:
dictOfShapes = {}
for i, (iso, name) in enumerate(zip(df["economy"], df["Country"])):
    
    print(i+1, iso, name)
    
    GAUL_borders_2[GAUL_borders_2["ADM0_NAME"] == name]

1 AFG Afghanistan
       OBJECTID  ADM2_CODE             ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
30896 30,897.00       3505            Qala-e-Kah       1000       3000
30897 30,898.00       3504              Pushtrod       1000       3000
30898 30,899.00       3506               Shibkoh       1000       3000
30899 30,900.00       3499                 Farah       1000       3000
30900 30,901.00       3676                  Kang       1000       3000
...         ...        ...                   ...        ...        ...
31290 31,291.00     100023  Dara-e- Suf-e- Payin       2004       3000
31291 31,292.00     100024            Qala-e-Naw       2004       3000
31292 31,293.00     100025                Kajran       2004       3000
31293 31,294.00     100026                  kiti       2004       3000
31294 31,295.00     100027                Khadir       2004       3000

       ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE    ADM0_NAME  \
30896        277     Farah  Member State        NO          1  Afghanistan
30897        277     Farah  Member State        NO          1  Afghanistan
30898        277     Farah  Member State        NO          1  Afghanistan
30899        277     Farah  Member State        NO          1  Afghanistan
30900        293    Nimroz  Member State        NO          1  Afghanistan
...          ...       ...           ...       ...        ...          ...
31290        298  Samangan  Member State        NO          1  Afghanistan
31291        273   Badghis  Member State        NO          1  Afghanistan
31292      99878  Daykundi  Member State        NO          1  Afghanistan
31293      99878  Daykundi  Member State        NO          1  Afghanistan
31294      99878  Daykundi  Member State        NO          1  Afghanistan

       Shape_Leng  Shape_Le_1  Shape_Area  \
30896        3.08        3.08        0.34
30897        1.07        1.07        0.04
30898        2.82        2.82        0.26
30899        3.87        3.87        0.33
30900        2.29        2.29        0.11
...           ...         ...         ...
31290        2.13        2.13        0.13
31291        1.23        1.23        0.06
31292        2.72        2.72        0.13
31293        1.75        1.75        0.09
31294        2.11        2.11        0.16

                                                geometry
30896  POLYGON ((61.85315 32.52808, 61.85434 32.52513...
30897  POLYGON ((62.21101 32.57128, 62.21068 32.56854...
30898  POLYGON ((61.88133 32.30833, 61.88385 32.30768...
30899  POLYGON ((62.74635 32.45141, 62.74656 32.44049...
30900  POLYGON ((62.05778 31.10795, 62.05615 31.10823...
...                                                  ...
31290  POLYGON ((67.64953 36.16876, 67.66484 36.13880...
31291  POLYGON ((63.19357 34.87578, 63.19473 34.87263...
31292  POLYGON ((65.83411 33.32314, 65.82948 33.32014...
31293  POLYGON ((65.87828 33.69697, 65.88494 33.69333...
31294  POLYGON ((66.00515 34.06405, 66.00613 34.06304...

[399 rows x 15 columns]
2 ALB Albania
       OBJECTID  ADM2_CODE ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
36810 36,811.00       3775     Berat       1000       3000        305
36811 36,812.00       3776   Cukalat       1000       3000        305
36812 36,813.00       3777   Kutalli       1000       3000        305
36813 36,814.00       3778     Lumas       1000       3000        305
36814 36,815.00       3779    Otllak       1000       3000        305
...         ...        ...       ...        ...        ...        ...
37179 37,180.00       4144  Selenice       1000       3000        340
37180 37,181.00       4145  Sevaster       1000       3000        340
37181 37,182.00       4146  Shushice       1000       3000        340
37182 37,183.00       4147  Vllahine       1000       3000        340
37183 37,184.00       4148     Vlore       1000       3000        340

      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
36810     Berat  Member State        NO          3   Albania        0.18
36811     Berat  Member State        NO          3   Albania        0.31
36812     Berat  Member State        NO          3   Albania        0.30
36813     Berat  Member State        NO          3   Albania        0.54
36814     Berat  Member State        NO          3   Albania        0.57
...         ...           ...       ...        ...       ...         ...
37179     Vlore  Member State        NO          3   Albania        0.15
37180     Vlore  Member State        NO          3   Albania        0.49
37181     Vlore  Member State        NO          3   Albania        0.36
37182     Vlore  Member State        NO          3   Albania        0.70
37183     Vlore  Member State        NO          3   Albania        0.18

       Shape_Le_1  Shape_Area  \
36810        0.18        0.00
36811        0.31        0.00
36812        0.30        0.00
36813        0.54        0.01
36814        0.57        0.01
...           ...         ...
37179        0.15        0.00
37180        0.49        0.01
37181        0.36        0.00
37182        0.70        0.01
37183        0.18        0.00

                                                geometry
36810  POLYGON ((19.95629 40.72403, 19.95794 40.71567...
36811  POLYGON ((19.80061 40.76481, 19.80865 40.75840...
36812  POLYGON ((19.81445 40.77568, 19.81342 40.77480...
36813  POLYGON ((20.01721 40.87812, 20.01376 40.87384...
36814  POLYGON ((19.93215 40.78887, 19.93572 40.78564...
...                                                  ...
37179  POLYGON ((19.63207 40.55541, 19.63282 40.55355...
37180  POLYGON ((19.77702 40.42688, 19.78138 40.42264...
37181  POLYGON ((19.57715 40.56077, 19.57116 40.55782...
37182  POLYGON ((19.71646 40.49979, 19.71688 40.49708...
37183  POLYGON ((19.49618 40.45879, 19.48997 40.45174...

[374 rows x 15 columns]
3 DZA Algeria
      OBJECTID  ADM2_CODE            ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
2964  2,965.00      37631                Adrar       1000       3000
2965  2,966.00      37632              Akabili       1000       3000
2966  2,967.00      37633             Aougrout       1000       3000
2967  2,968.00      37634               Aoulef       1000       3000
2968  2,969.00      37635  Bordj Badji Mokhtar       1000       3000
...        ...        ...                  ...        ...        ...
4500  4,501.00      39167          Souk Thlata       1000       3000
4501  4,502.00      39168    Terni Beni Hediel       1000       3000
4502  4,503.00      39169               Tienet       1000       3000
4503  4,504.00      39170              Tlemcen       1000       3000
4504  4,505.00      39171               Zenata       1000       3000

      ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
2964        341     Adrar  Member State        NO          4   Algeria
2965        341     Adrar  Member State        NO          4   Algeria
2966        341     Adrar  Member State        NO          4   Algeria
2967        341     Adrar  Member State        NO          4   Algeria
2968        341     Adrar  Member State        NO          4   Algeria
...         ...       ...           ...       ...        ...       ...
4500        388   Tlemcen  Member State        NO          4   Algeria
4501        388   Tlemcen  Member State        NO          4   Algeria
4502        388   Tlemcen  Member State        NO          4   Algeria
4503        388   Tlemcen  Member State        NO          4   Algeria
4504        388   Tlemcen  Member State        NO          4   Algeria

      Shape_Leng  Shape_Le_1  Shape_Area  \
2964        1.10        1.10        0.06
2965        2.28        2.28        0.15
2966        5.40        5.40        1.31
2967        2.43        2.43        0.28
2968       17.39       17.39       10.62
...          ...         ...         ...
4500        0.40        0.40        0.01
4501        0.77        0.77        0.02
4502        0.25        0.25        0.00
4503        0.34        0.34        0.00
4504        0.41        0.41        0.01

                                               geometry
2964  POLYGON ((-0.17099 27.76973, -0.17086 27.77254...
2965  POLYGON ((0.91251 26.22968, 0.91186 26.22906, ...
2966  POLYGON ((2.02293 28.90011, 1.99661 28.73091, ...
2967  POLYGON ((1.25656 26.79097, 1.10847 26.74766, ...
2968  POLYGON ((1.39688 23.99846, 1.39827 23.95920, ...
...                                                 ...
4500  POLYGON ((-1.96917 35.07223, -1.97007 35.07025...
4501  POLYGON ((-1.26807 34.86606, -1.25683 34.86606...
4502  POLYGON ((-1.81098 35.06152, -1.80723 35.05367...
4503  POLYGON ((-1.34840 34.93666, -1.31484 34.92308...
4504  POLYGON ((-1.43598 35.01500, -1.43779 35.01203...

[1541 rows x 15 columns]
4 ASM American Samoa
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
5 AND Andorra
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
36056 36,057.00       4199  Administrative unit not available       1000
36057 36,058.00       4200  Administrative unit not available       1000
36058 36,059.00       4201  Administrative unit not available       1000
36059 36,060.00       4202  Administrative unit not available       1000
36060 36,061.00       4203  Administrative unit not available       1000
36061 36,062.00       4204  Administrative unit not available       1000
36062 36,063.00       4205  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE            ADM1_NAME        STATUS DISP_AREA  \
36056       3000        391     Andorra La Vella  Member State        NO
36057       3000        392              Canillo  Member State        NO
36058       3000        393               Encamp  Member State        NO
36059       3000        394   Escaldes-engordany  Member State        NO
36060       3000        395           La Massana  Member State        NO
36061       3000        396               Ordino  Member State        NO
36062       3000        397  Sant Julia De Loria  Member State        NO

       ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
36056          7   Andorra        0.26        0.26        0.00
36057          7   Andorra        0.58        0.58        0.01
36058          7   Andorra        0.49        0.49        0.01
36059          7   Andorra        0.38        0.38        0.01
36060          7   Andorra        0.41        0.41        0.01
36061          7   Andorra        0.43        0.43        0.01
36062          7   Andorra        0.34        0.34        0.01

                                                geometry
36056  POLYGON ((1.56639 42.47614, 1.55510 42.47741, ...
36057  POLYGON ((1.78038 42.57164, 1.77521 42.57164, ...
36058  POLYGON ((1.74447 42.56623, 1.74261 42.56584, ...
36059  POLYGON ((1.66936 42.50198, 1.66842 42.50114, ...
36060  POLYGON ((1.56503 42.55329, 1.55613 42.54290, ...
36061  POLYGON ((1.59659 42.63917, 1.59974 42.63701, ...
36062  POLYGON ((1.56639 42.47614, 1.57172 42.45456, ...
6 AGO Angola
      OBJECTID  ADM2_CODE      ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
2035  2,036.00       4206         Ambriz       1000       3000        398
2036  2,037.00       4207    Bula Atumba       1000       3000        398
2037  2,038.00       4208          Dande       1000       3000        398
2038  2,039.00       4209         Dembos       1000       3000        398
2039  2,040.00       4210  Icolo E Bengo       1000       3000        398
...        ...        ...            ...        ...        ...        ...
2189  2,190.00       4361         N'zeto       1000       3000        415
2190  2,191.00       4363           Soyo       1000       3000        415
2191  2,192.00       4364        Tomboco       1000       3000        415
2192  2,193.00       4214     Baia Farta       1000       3000        399
2193  2,194.00       4362          Noqui       1000       3000        415

     ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
2035     Bengo  Member State        NO          8    Angola        2.64
2036     Bengo  Member State        NO          8    Angola        1.49
2037     Bengo  Member State        NO          8    Angola        3.44
2038     Bengo  Member State        NO          8    Angola        1.57
2039     Bengo  Member State        NO          8    Angola        2.57
...        ...           ...       ...        ...       ...         ...
2189     Zaire  Member State        NO          8    Angola        3.72
2190     Zaire  Member State        NO          8    Angola        9.38
2191     Zaire  Member State        NO          8    Angola        4.15
2192  Benguela  Member State        NO          8    Angola        4.25
2193     Zaire  Member State        NO          8    Angola        2.85

      Shape_Le_1  Shape_Area  \
2035        2.64        0.32
2036        1.49        0.11
2037        3.44        0.57
2038        1.57        0.11
2039        2.57        0.29
...          ...         ...
2189        3.72        0.71
2190        9.38        0.36
2191        4.15        0.67
2192        4.25        0.56
2193        2.85        0.45

                                               geometry
2035  POLYGON ((13.08171 -7.79454, 13.09522 -7.79282...
2036  POLYGON ((14.90244 -8.75927, 14.90244 -8.75927...
2037  POLYGON ((13.83726 -8.05365, 13.91213 -8.07104...
2038  POLYGON ((14.79526 -8.40146, 14.82180 -8.48789...
2039  POLYGON ((14.08372 -8.92102, 14.07713 -8.93132...
...                                                 ...
2189  POLYGON ((13.49935 -6.89549, 13.50518 -6.90271...
2190  MULTIPOLYGON (((12.44968 -6.14298, 12.44955 -6...
2191  POLYGON ((12.62131 -6.72836, 12.62490 -6.72687...
2192  MULTIPOLYGON (((12.52282 -13.45160, 12.52295 -...
2193  MULTIPOLYGON (((13.09221 -5.88900, 13.09188 -5...

[159 rows x 15 columns]
7 ATG Antigua and Barbuda
      OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
7237  7,238.00      40214  Administrative unit not available       1000
7238  7,239.00      40215  Administrative unit not available       1000
7239  7,240.00      40216  Administrative unit not available       1000
7240  7,241.00      40217  Administrative unit not available       1000
7241  7,242.00      40218  Administrative unit not available       1000
7242  7,243.00      40219  Administrative unit not available       1000
7243  7,244.00      40220  Administrative unit not available       1000
7244  7,245.00      40221  Administrative unit not available       1000

      EXP2_YEAR  ADM1_CODE     ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
7237       3000      40206       Barbuda  Member State        NO         11
7238       3000      40207  Name Unknown  Member State        NO         11
7239       3000      40208    St. George  Member State        NO         11
7240       3000      40209      St. John  Member State        NO         11
7241       3000      40210      St. Mary  Member State        NO         11
7242       3000      40211      St. Paul  Member State        NO         11
7243       3000      40212     St. Peter  Member State        NO         11
7244       3000      40213    St. Philip  Member State        NO         11

                ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
7237  Antigua and Barbuda        0.64        0.64        0.01
7238  Antigua and Barbuda        0.03        0.03        0.00
7239  Antigua and Barbuda        0.40        0.40        0.00
7240  Antigua and Barbuda        0.62        0.62        0.01
7241  Antigua and Barbuda        0.54        0.54        0.00
7242  Antigua and Barbuda        0.45        0.45        0.00
7243  Antigua and Barbuda        0.48        0.48        0.00
7244  Antigua and Barbuda        0.76        0.76        0.00

                                               geometry
7237  MULTIPOLYGON (((-61.81925 17.70291, -61.81941 ...
7238  POLYGON ((-62.34540 16.93397, -62.34611 16.933...
7239  MULTIPOLYGON (((-61.76264 17.14606, -61.76222 ...
7240  MULTIPOLYGON (((-61.90856 17.09971, -61.90869 ...
7241  MULTIPOLYGON (((-61.89090 17.02510, -61.89106 ...
7242  MULTIPOLYGON (((-61.78258 17.01461, -61.78251 ...
7243  MULTIPOLYGON (((-61.72755 17.11241, -61.72783 ...
7244  MULTIPOLYGON (((-61.67933 17.04061, -61.67949 ...
8 ARG Argentina
       OBJECTID  ADM2_CODE               ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
21649 21,650.00       4379              25 de Mayo       1000       3000
21650 21,651.00       4380              9 de Julio       1000       3000
21651 21,652.00       4381           Adolfo Alsina       1000       3000
21652 21,653.00       4382  Adolfo Gonzales Chaves       1000       3000
21653 21,654.00       4383                 Alberti       1000       3000
...         ...        ...                     ...        ...        ...
22169 22,170.00      82750               Comuna 11       2010       3000
22170 22,171.00      82751               Comuna 12       2010       3000
22171 22,172.00      82752               Comuna 13       2010       3000
22172 22,173.00      82753               Comuna 14       2010       3000
22173 22,174.00      82754               Comuna 15       2010       3000

       ADM1_CODE          ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
21649        429       Buenos Aires  Member State        NO         12
21650        429       Buenos Aires  Member State        NO         12
21651        429       Buenos Aires  Member State        NO         12
21652        429       Buenos Aires  Member State        NO         12
21653        429       Buenos Aires  Member State        NO         12
...          ...                ...           ...       ...        ...
22169        430  Buenos Aires D.f.  Member State        NO         12
22170        430  Buenos Aires D.f.  Member State        NO         12
22171        430  Buenos Aires D.f.  Member State        NO         12
22172        430  Buenos Aires D.f.  Member State        NO         12
22173        430  Buenos Aires D.f.  Member State        NO         12

       ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
21649  Argentina        4.26        4.26        0.48
21650  Argentina        3.03        3.03        0.43
21651  Argentina        3.90        3.90        0.60
21652  Argentina        3.51        3.51        0.39
21653  Argentina        1.75        1.75        0.11
...          ...         ...         ...         ...
22169  Argentina        0.20        0.20        0.00
22170  Argentina        0.17        0.17        0.00
22171  Argentina        0.17        0.17        0.00
22172  Argentina        0.17        0.17        0.00
22173  Argentina        0.19        0.19        0.00

                                                geometry
21649  POLYGON ((-59.82312 -35.17691, -59.82307 -35.1...
21650  POLYGON ((-60.52811 -35.40966, -60.52795 -35.4...
21651  POLYGON ((-63.28579 -36.60993, -63.28268 -36.6...
21652  POLYGON ((-59.67467 -37.99938, -59.67414 -37.9...
21653  POLYGON ((-60.23967 -34.82682, -60.25114 -34.8...
...                                                  ...
22169  POLYGON ((-58.50347 -34.59395, -58.50308 -34.5...
22170  POLYGON ((-58.46808 -34.57291, -58.46829 -34.5...
22171  POLYGON ((-58.43791 -34.55623, -58.43799 -34.5...
22172  MULTIPOLYGON (((-58.44121 -34.56347, -58.44057...
22173  POLYGON ((-58.44445 -34.58317, -58.44440 -34.5...

[525 rows x 15 columns]
9 ARM Armenia
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
33080 33,081.00       4891                           Achtarak       1000
33081 33,082.00       4892                             Aparan       1000
33082 33,083.00       4893                            Aragats       1000
33083 33,084.00       4894                             Ararat       1000
33084 33,085.00       4895                           Artashat       1000
33085 33,086.00       4896                              Masis       1000

       OBJECTID  ADM2_CODE            ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
37375 37,376.00       5573  Bruck an der Leitha       1000       3000
37376 37,377.00       5574           Eisenstadt       1000       3000
37377 37,378.00       5575  Eisenstadt Umgebung       1000       3000
37378 37,379.00       5576              Gussing       1000       3000
37379 37,380.00       5577          Jennersdorf       1000       3000
...         ...        ...                  ...        ...        ...
37470 37,471.00       5668              Bludenz       1000       3000
37471 37,472.00       5669              Bregenz       1000       3000
37472 37,473.00       5670             Dornbirn       1000       3000
37473 37,474.00       5671            Feldkirch       1000       3000
37474 37,475.00       5672                 Wien       1000       3000

       ADM1_CODE   ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
37375        478  Burgenland  Member State        NO         18   Austria
37376        478  Burgenland  Member State        NO         18   Austria
37377        478  Burgenland  Member State        NO         18   Austria
37378        478  Burgenland  Member State        NO         18   Austria
37379        478  Burgenland  Member State        NO         18   Austria
...          ...         ...           ...       ...        ...       ...
37470        485  Vorarlberg  Member State        NO         18   Austria
37471        485  Vorarlberg  Member State        NO         18   Austria
37472        485  Vorarlberg  Member State        NO         18   Austria
37473        485  Vorarlberg  Member State        NO         18   Austria
37474        486        Wien  Member State        NO         18   Austria

       Shape_Leng  Shape_Le_1  Shape_Area  \
37375        1.96        1.96        0.06
37376        0.34        0.34        0.00
37377        1.90        1.90        0.05
37378        1.60        1.60        0.06
37379        1.25        1.25        0.03
...           ...         ...         ...
37470        2.26        2.26        0.15
37471        2.25        2.25        0.11
37472        0.81        0.81        0.02
37473        1.08        1.08        0.03
37474        1.37        1.37        0.05

                                                geometry
37375  POLYGON ((17.07040 48.12213, 17.06640 48.11590...
37376  POLYGON ((16.57210 47.87800, 16.57250 47.87440...
37377  POLYGON ((16.73190 47.80910, 16.72950 47.80930...
37378  POLYGON ((16.45856 47.14726, 16.49218 47.14816...
37379  MULTIPOLYGON (((16.29317 47.01375, 16.29441 47...
...                                                  ...
37470  POLYGON ((10.19920 47.23760, 10.19710 47.23390...
37471  POLYGON ((10.17483 47.27905, 10.17484 47.27904...
37472  POLYGON ((9.83510 47.27870, 9.83210 47.28070, ...
37473  POLYGON ((9.83510 47.27870, 9.83690 47.27740, ...
37474  POLYGON ((16.42560 48.32010, 16.43080 48.31790...

[100 rows x 15 columns]
13 AZE Azerbaijan
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
32765 32,766.00     147308                              Babek       2004
32766 32,767.00     147309                              Julfa       1000
32767 32,768.00     147310                            Ordubad       1000
32768 32,769.00     147311                             Sharur       2004
32769 32,770.00     147312                          Kangharli       2004
...         ...        ...                                ...        ...
32835 32,836.00        529                              Khizi       1000
32836 32,837.00        552                           Sumgayit       1000
32837 32,838.00        495                               Baku       1000
32838 32,839.00        534  Administrative unit not available       1000
32839 32,840.00        559                           Zangilan       1000

       EXP2_YEAR  ADM1_CODE                          ADM1_NAME        STATUS  \
32765       3000     147304                         Nakhchivan  Member State
32766       3000     147304                         Nakhchivan  Member State
32767       3000     147304                         Nakhchivan  Member State
32768       3000     147304                         Nakhchivan  Member State
32769       3000     147304                         Nakhchivan  Member State
...          ...        ...                                ...           ...
32835       3000     147297                           Absheron  Member State
32836       3000     147297                           Absheron  Member State
32837       3000     147297                           Absheron  Member State
32838       3000     147307  Administrative unit not available  Member State
32839       3000     147302                    Kalbajar-Lachin  Member State

      DISP_AREA  ADM0_CODE   ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
32765        NO         19  Azerbaijan        2.22        2.22        0.08
32766        NO         19  Azerbaijan        1.88        1.88        0.10
32767        NO         19  Azerbaijan        1.54        1.54        0.10
32768        NO         19  Azerbaijan        1.75        1.75        0.09
32769        NO         19  Azerbaijan        1.37        1.37        0.07
...         ...        ...         ...         ...         ...         ...
32835        NO         19  Azerbaijan        2.08        2.08        0.20
32836        NO         19  Azerbaijan        0.66        0.66        0.02
32837        NO         19  Azerbaijan        5.74        5.74        0.20
32838        NO         19  Azerbaijan       17.66       17.66        8.46
32839        NO         19  Azerbaijan        1.67        1.67        0.07

                                                geometry
32765  POLYGON ((45.48595 39.50224, 45.47801 39.47044...
32766  POLYGON ((46.00000 39.29694, 45.96728 39.31145...
32767  POLYGON ((46.00000 39.29694, 46.00000 39.25737...
32768  POLYGON ((45.33143 39.55999, 45.29877 39.53932...
32769  POLYGON ((45.41128 39.53342, 45.41128 39.53342...
...                                                  ...
32835  POLYGON ((49.34269 40.93825, 49.35797 40.93220...
32836  POLYGON ((49.63972 40.66774, 49.65331 40.62792...
32837  MULTIPOLYGON (((49.39652 39.81634, 49.39191 39...
32838  POLYGON ((50.82111 41.61784, 50.97412 41.49656...
32839  POLYGON ((46.87046 39.14708, 46.87359 39.13901...

[75 rows x 15 columns]
14 BHS Bahamas, The
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
15 BHR Bahrain
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
31362 31,363.00       5748  Administrative unit not available       1000
31363 31,364.00       5749  Administrative unit not available       1000
31364 31,365.00       5750  Administrative unit not available       1000
31365 31,366.00       5751  Administrative unit not available       1000
31366 31,367.00       5752  Administrative unit not available       1000
31367 31,368.00       5753  Administrative unit not available       1000
31368 31,369.00       5754  Administrative unit not available       1000
31369 31,370.00       5755  Administrative unit not available       1000
31370 31,371.00       5756  Administrative unit not available       1000
31371 31,372.00       5757  Administrative unit not available       1000
31372 31,373.00       5758  Administrative unit not available       1000
31373 31,374.00       5759  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE        ADM1_NAME        STATUS DISP_AREA  \
31362       3000        562   Central Region  Member State        NO
31363       3000        563       Hamad Town  Member State        NO
31364       3000        564     Hawar Island  Member State        NO
31365       3000        565             Hidd  Member State        NO
31366       3000        566         Isa Town  Member State        NO
31367       3000        567          Jidhafs  Member State        NO
31368       3000        568           Manama  Member State        NO
31369       3000        569         Muharraq  Member State        NO
31370       3000        570  Northern Region  Member State        NO
31371       3000        571            Riffa  Member State        NO
31372       3000        572            Sitra  Member State        NO
31373       3000        573   Western Region  Member State        NO

       ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
31362         21   Bahrain        0.38        0.38        0.00
31363         21   Bahrain        0.18        0.18        0.00
31364         21   Bahrain        0.89        0.89        0.00
31365         21   Bahrain        0.05        0.05        0.00
31366         21   Bahrain        0.16        0.16        0.00
31367         21   Bahrain        0.22        0.22        0.00
31368         21   Bahrain        0.25        0.25        0.00
31369         21   Bahrain        0.21        0.21        0.00
31370         21   Bahrain        0.22        0.22        0.00
31371         21   Bahrain        0.81        0.81        0.02
31372         21   Bahrain        0.27        0.27        0.00
31373         21   Bahrain        1.10        1.10        0.02

                                                geometry
31362  POLYGON ((50.55933 26.18785, 50.56764 26.18684...
31363  POLYGON ((50.53288 26.06285, 50.52959 26.05881...
31364  MULTIPOLYGON (((50.79704 25.64768, 50.80180 25...
31365  POLYGON ((50.66336 26.24665, 50.66187 26.23834...
31366  POLYGON ((50.55331 26.14048, 50.55323 26.14150...
31367  POLYGON ((50.55848 26.22012, 50.55891 26.21549...
31368  MULTIPOLYGON (((50.59706 26.17670, 50.58932 26...
31369  POLYGON ((50.66336 26.24665, 50.66217 26.24665...
31370  POLYGON ((50.50608 26.18085, 50.50066 26.17881...
31371  POLYGON ((50.59374 26.14002, 50.59537 26.13885...
31372  MULTIPOLYGON (((50.62864 26.12150, 50.63333 26...
31373  MULTIPOLYGON (((50.51911 26.13409, 50.51989 26...
16 BGD Bangladesh
       OBJECTID  ADM2_CODE    ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
29531 29,532.00       5761      Barguna       1000       3000        575
29532 29,533.00       5762      Barisal       1000       3000        575
29533 29,534.00       5763        Bhola       1000       3000        575
29534 29,535.00       5764    Jhalokati       1000       3000        575
29535 29,536.00       5765   Patuakhali       1000       3000        575
...         ...        ...          ...        ...        ...        ...
29590 29,591.00       5810  Lalmonirhat       1000       3000      61363
29591 29,592.00       5814   Nilphamari       1000       3000      61363
29592 29,593.00       5816   Panchagarh       1000       3000      61363
29593 29,594.00       5818      Rangpur       1000       3000      61363
29594 29,595.00       5820   Thakurgaon       1000       3000      61363

      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE   ADM0_NAME  Shape_Leng  \
29531   Barisal  Member State        NO         23  Bangladesh        3.45
29532   Barisal  Member State        NO         23  Bangladesh        3.79
29533   Barisal  Member State        NO         23  Bangladesh        6.07
29534   Barisal  Member State        NO         23  Bangladesh        2.07
29535   Barisal  Member State        NO         23  Bangladesh        9.87
...         ...           ...       ...        ...         ...         ...
29590   Rangpur  Member State        NO         23  Bangladesh        3.16
29591   Rangpur  Member State        NO         23  Bangladesh        2.65
29592   Rangpur  Member State        NO         23  Bangladesh        3.15
29593   Rangpur  Member State        NO         23  Bangladesh        3.60
29594   Rangpur  Member State        NO         23  Bangladesh        2.82

       Shape_Le_1  Shape_Area  \
29531        3.45        0.12
29532        3.79        0.22
29533        6.07        0.20
29534        2.07        0.07
29535        9.87        0.22
...           ...         ...
29590        3.16        0.11
29591        2.65        0.15
29592        3.15        0.12
29593        3.60        0.21
29594        2.82        0.16

                                                geometry
29531  MULTIPOLYGON (((90.06894 21.86092, 90.06923 21...
29532  POLYGON ((90.34884 23.05595, 90.34896 23.05571...
29533  MULTIPOLYGON (((90.81645 21.86236, 90.81425 21...
29534  MULTIPOLYGON (((90.19624 22.48536, 90.19612 22...
29535  MULTIPOLYGON (((90.46411 21.77047, 90.46383 21...
...                                                  ...
29590  POLYGON ((89.47646 26.00188, 89.47965 25.99630...
29591  POLYGON ((89.02011 26.23622, 89.02027 26.23609...
29592  POLYGON ((88.76156 26.30297, 88.76012 26.30005...
29593  POLYGON ((89.45874 25.79133, 89.45887 25.79112...
29594  POLYGON ((88.62615 26.05647, 88.62602 26.05651...

[64 rows x 15 columns]
17 BRB Barbados
      OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
7225  7,226.00       5825  Administrative unit not available       1000
7226  7,227.00       5826  Administrative unit not available       1000
7227  7,228.00       5827  Administrative unit not available       1000
7228  7,229.00       5828  Administrative unit not available       1000
7229  7,230.00       5829  Administrative unit not available       1000
7230  7,231.00       5830  Administrative unit not available       1000
7231  7,232.00       5831  Administrative unit not available       1000
7232  7,233.00       5832  Administrative unit not available       1000
7233  7,234.00       5834  Administrative unit not available       1000
7234  7,235.00       5835  Administrative unit not available       1000
7235  7,236.00       5833  Administrative unit not available       1000

      EXP2_YEAR  ADM1_CODE      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
7225       3000        581  Christ Church  Member State        NO         24
7226       3000        582     St. Andrew  Member State        NO         24
7227       3000        583     St. George  Member State        NO         24
7228       3000        584      St. James  Member State        NO         24
7229       3000        585       St. John  Member State        NO         24
7230       3000        586     St. Joseph  Member State        NO         24
7231       3000        587       St. Lucy  Member State        NO         24
7232       3000        588    St. Michael  Member State        NO         24
7233       3000        590    St. Phillip  Member State        NO         24
7234       3000        591      St. Tomas  Member State        NO         24
7235       3000        589      St. Peter  Member State        NO         24

     ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
7225  Barbados        0.31        0.31        0.00
7226  Barbados        0.23        0.23        0.00
7227  Barbados        0.24        0.24        0.00
7228  Barbados        0.27        0.27        0.00
7229  Barbados        0.24        0.24        0.00
7230  Barbados        0.20        0.20        0.00
7231  Barbados        0.28        0.28        0.00
7232  Barbados        0.28        0.28        0.00
7233  Barbados        0.31        0.31        0.00
7234  Barbados        0.21        0.21        0.00
7235  Barbados        0.26        0.26        0.00

                                               geometry
7225  POLYGON ((-59.47525 13.07621, -59.47605 13.075...
7226  POLYGON ((-59.53605 13.22633, -59.53637 13.226...
7227  POLYGON ((-59.50308 13.12844, -59.50780 13.116...
7228  POLYGON ((-59.59273 13.20783, -59.59598 13.199...
7229  POLYGON ((-59.45251 13.17635, -59.45291 13.175...
7230  POLYGON ((-59.50329 13.20409, -59.50520 13.202...
7231  MULTIPOLYGON (((-59.64463 13.26284, -59.64472 ...
7232  POLYGON ((-59.56421 13.09008, -59.59754 13.073...
7233  MULTIPOLYGON (((-59.44335 13.16555, -59.44348 ...
7234  POLYGON ((-59.57035 13.19558, -59.56716 13.194...
7235  MULTIPOLYGON (((-59.64470 13.25533, -59.64474 ...
18 BLR Belarus
       OBJECTID  ADM2_CODE     ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
33887 33,888.00      39898   Baranovichi       1000       3000        593
33888 33,889.00      39899        Bereza       1000       3000        593
33889 33,890.00      39900         Brest       1000       3000        593
33890 33,891.00      39901     Drogichin       1000       3000        593
33891 33,892.00      39902    Gancevichi       1000       3000        593
...         ...        ...           ...        ...        ...        ...
34001 34,002.00      40011     Shumilino       1000       3000        599
34002 34,003.00      40012      Tolochin       1000       3000        599
34003 34,004.00      40013       Ushachi       1000       3000        599
34004 34,005.00      40014  Verhnedvinsk       1000       3000        599
34005 34,006.00      40015       Vitebsk       1000       3000        599

      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
33887     Brest  Member State        NO         26   Belarus        2.62
33888     Brest  Member State        NO         26   Belarus        2.55
33889     Brest  Member State        NO         26   Belarus        3.91
33890     Brest  Member State        NO         26   Belarus        2.98
33891     Brest  Member State        NO         26   Belarus        2.47
...         ...           ...       ...        ...       ...         ...
34001   Vitebsk  Member State        NO         26   Belarus        2.36
34002   Vitebsk  Member State        NO         26   Belarus        2.12
34003   Vitebsk  Member State        NO         26   Belarus        2.42
34004   Vitebsk  Member State        NO         26   Belarus        3.24
34005   Vitebsk  Member State        NO         26   Belarus        4.33

       Shape_Le_1  Shape_Area  \
33887        2.62        0.31
33888        2.55        0.21
33889        3.91        0.22
33890        2.98        0.27
33891        2.47        0.19
...           ...         ...
34001        2.36        0.23
34002        2.12        0.17
34003        2.42        0.17
34004        3.24        0.29
34005        4.33        0.46

                                                geometry
33887  POLYGON ((25.80758 53.39502, 25.86000 53.39083...
33888  POLYGON ((25.04052 52.66757, 25.05215 52.66333...
33889  POLYGON ((23.82018 52.30708, 23.82352 52.30079...
33890  POLYGON ((25.43422 52.41997, 25.42782 52.37423...
33891  POLYGON ((27.05427 52.70372, 27.02206 52.68571...
...                                                  ...
34001  POLYGON ((29.60259 55.31516, 29.60585 55.29317...
34002  POLYGON ((30.07972 54.35944, 30.02861 54.33443...
34003  POLYGON ((28.93315 55.21743, 28.87495 55.19755...
34004  POLYGON ((28.23991 56.12951, 28.25197 56.09533...
34005  POLYGON ((30.94067 55.61615, 30.95219 55.60864...

[119 rows x 15 columns]
19 BEL Belgium
       OBJECTID  ADM2_CODE                                 ADM2_NAME  \
37223 37,224.00       5844  Area without administration at 2nd level
37224 37,225.00       5846                           Oost-Vlaanderen
37225 37,226.00       5847                            Vlaams-Brabant
37226 37,227.00       5848                                   Limburg
37227 37,228.00       5849                           West-Vlaanderen
37228 37,229.00      40442                                 Antwerpen
37229 37,230.00       5850                                   Hainaut
37230 37,231.00       5851                                     Liege
37231 37,232.00       5852                                Luxembourg
37232 37,233.00       5853                                     Namur
37233 37,234.00       5854                            Brabant wallon

       STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
37223       1995       3000        600
37224       1000       3000        601
37225       1995       3000        601
37226       1000       3000        601
37227       1000       3000        601

      OBJECTID  ADM2_CODE   ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
6540  6,541.00       5861   Banikoara       1000       3000        609
6541  6,542.00       5862    Gogounou       1000       3000        609
6542  6,543.00       5863       Kandi       1000       3000        609
6543  6,544.00       5864    Karimama       1000       3000        609
6544  6,545.00       5865  Malanville       1000       3000        609
...        ...        ...         ...        ...        ...        ...
6612  6,613.00       5934      Ouinhi       1000       3000        620
6613  6,614.00       5935    Za-kpota       1000       3000        620
6614  6,615.00       5936  Zangnanado       1000       3000        620
6615  6,616.00       5937   Zogbodome       1000       3000        620
6616  6,617.00       5917     Aguegue       1000       3000        618

     ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
6540   Alibori  Member State        NO         29     Benin        2.82
6541   Alibori  Member State        NO         29     Benin        3.27
6542   Alibori  Member State        NO         29     Benin        2.75
6543   Alibori  Member State        NO         29     Benin        4.13
6544   Alibori  Member State        NO         29     Benin        2.34
...        ...           ...       ...        ...       ...         ...
6612       Zou  Member State        NO         29     Benin        0.76
6613       Zou  Member State        NO         29     Benin        0.78
6614       Zou  Member State        NO         29     Benin        1.44
6615       Zou  Member State        NO         29     Benin        1.15
6616     Oueme  Member State        NO         29     Benin        0.54

      Shape_Le_1  Shape_Area  \
6540        2.82        0.36
6541        3.27        0.41
6542        2.75        0.29
6543        4.13        0.50
6544        2.34        0.27
...          ...         ...
6612        0.76        0.03
6613        0.78        0.03
6614        1.44        0.05
6615        1.15        0.07
6616        0.54        0.01

                                               geometry
6540  POLYGON ((2.84185 11.43059, 2.84163 11.42114, ...
6541  POLYGON ((3.19362 10.90465, 3.19200 10.89730, ...
6542  POLYGON ((3.25846 11.29882, 3.25769 11.29174, ...
6543  POLYGON ((3.30365 11.91596, 3.30360 11.91595, ...
6544  POLYGON ((3.30365 11.91596, 3.30417 11.90338, ...
...                                                 ...
6612  POLYGON ((2.51821 7.17067, 2.52362 7.15327, 2....
6613  POLYGON ((2.23828 7.33873, 2.24198 7.32623, 2....
6614  POLYGON ((2.40551 7.44277, 2.41678 7.42736, 2....
6615  POLYGON ((2.20044 7.12367, 2.23443 7.12330, 2....
6616  MULTIPOLYGON (((2.51714 6.47123, 2.51740 6.470...

[77 rows x 15 columns]
22 BMU Bermuda
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
23 BTN Bhutan
       OBJECTID  ADM2_CODE        ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
29595 29,596.00      41315         Pemaling       2005       3000      41312
29596 29,597.00      41316  Trashichhoeling       2005       3000      41312
29597 29,598.00      41317  NamgayChhoeling       2005       3000      41312
29598 29,599.00      41318         Doomtoed       2005       3000      41312
29599 29,600.00      41319      Duenchhukha       2005       3000      41312
...         ...        ...              ...        ...        ...        ...
29795 29,796.00       6089          Khaling       1000       3000        637
29796 29,797.00       6090           Lumang       1000       3000        637
29797 29,798.00       6098       Thrimshing       1000       3000        637
29798 29,799.00       6088          Kangpar       1000       3000        637
29799 29,800.00       6091            Merag       1000       3000        637

        ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
29595      Samtse  Member State        NO         31    Bhutan        0.36
29596      Samtse  Member State        NO         31    Bhutan        0.28
29597      Samtse  Member State        NO         31    Bhutan        0.55
29598      Samtse  Member State        NO         31    Bhutan        0.33
29599      Samtse  Member State        NO         31    Bhutan        0.40
...           ...           ...       ...        ...       ...         ...
29795  Trashigang  Member State        NO         31    Bhutan        0.68
29796  Trashigang  Member State        NO         31    Bhutan        0.45
29797  Trashigang  Member State        NO         31    Bhutan        0.53
29798  Trashigang  Member State        NO         31    Bhutan        0.85
29799  Trashigang  Member State        NO         31    Bhutan        1.39

       Shape_Le_1  Shape_Area  \
29595        0.36        0.00
29596        0.28        0.00
29597        0.55        0.01
29598        0.33        0.00
29599        0.40        0.01
...           ...         ...
29795        0.68        0.01
29796        0.45        0.01
29797        0.53        0.00
29798        0.85        0.03
29799        1.39        0.04

                                                geometry
29595  POLYGON ((88.89431 27.00243, 88.89371 27.00232...
29596  MULTIPOLYGON (((88.89316 27.00251, 88.89371 27...
29597  POLYGON ((89.06900 27.07229, 89.06865 27.07214...
29598  POLYGON ((89.21423 27.02705, 89.21482 27.02620...
29599  POLYGON ((89.31877 27.08227, 89.31918 27.08069...
...                                                  ...
29795  POLYGON ((91.62943 27.24245, 91.62986 27.24195...
29796  POLYGON ((91.58738 27.10498, 91.58702 27.10455...
29797  POLYGON ((91.60354 27.06161, 91.60324 27.06107...
29798  POLYGON ((91.82028 27.13601, 91.81907 27.13417...
29799  POLYGON ((91.80545 27.35823, 91.80578 27.35777...

[205 rows x 15 columns]
24 BOL Bolivia
       OBJECTID  ADM2_CODE             ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
13803 13,804.00       6141               Cercado       1000       3000
13804 13,805.00       6142  General Jose Ballivi       1000       3000
13805 13,806.00       6143                Itenez       1000       3000
13806 13,807.00       6144                Mamore       1000       3000
13807 13,808.00      40451                Marban       1000       3000
...         ...        ...                   ...        ...        ...
13911 13,912.00      40537                Avilez       1000       3000
13912 13,913.00      40541       Burnet O'Connor       1000       3000
13913 13,914.00      40538               Cercado       1000       3000
13914 13,915.00      40539            Gran Chaco       1000       3000
13915 13,916.00      40540                Mendez       1000       3000

       ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
13803      40443      Beni  Member State        NO         33   Bolivia
13804      40443      Beni  Member State        NO         33   Bolivia
13805      40443      Beni  Member State        NO         33   Bolivia
13806      40443      Beni  Member State        NO         33   Bolivia
13807      40443      Beni  Member State        NO         33   Bolivia
...          ...       ...           ...       ...        ...       ...
13911      40450    Tarija  Member State        NO         33   Bolivia
13912      40450    Tarija  Member State        NO         33   Bolivia
13913      40450    Tarija  Member State        NO         33   Bolivia
13914      40450    Tarija  Member State        NO         33   Bolivia
13915      40450    Tarija  Member State        NO         33   Bolivia

       Shape_Leng  Shape_Le_1  Shape_Area  \
13803        5.10        5.10        0.90
13804       15.94       15.94        3.40
13805        9.34        9.34        2.95
13806        8.69        8.69        1.75
13807        7.11        7.11        1.24
...           ...         ...         ...
13911        3.85        3.85        0.23
13912        4.46        4.46        0.44
13913        3.29        3.29        0.19
13914        8.38        8.38        1.62
13915        4.02        4.02        0.35

                                                geometry
13803  POLYGON ((-65.11862 -13.97650, -64.20201 -14.2...
13804  POLYGON ((-66.41761 -11.38463, -66.41793 -11.3...
13805  POLYGON ((-63.77364 -12.45447, -63.74489 -12.4...
13806  POLYGON ((-64.99744 -11.93509, -65.00000 -11.9...
13807  POLYGON ((-63.92328 -14.99930, -63.92394 -14.9...
...                                                  ...
13911  POLYGON ((-65.09297 -21.47731, -65.09100 -21.4...
13912  POLYGON ((-64.15925 -20.88500, -64.15829 -20.8...
13913  POLYGON ((-64.43639 -21.30767, -64.43530 -21.3...
13914  POLYGON ((-63.71368 -21.00041, -63.61363 -21.0...
13915  POLYGON ((-64.69314 -20.93241, -64.69294 -20.9...

[113 rows x 15 columns]
25 BIH Bosnia and Herzegovina
       OBJECTID  ADM2_CODE        ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
36543 36,544.00       6241    Gornjedrinski       1000       3000        652
36544 36,545.00       6242    Neretvljanski       1000       3000        652
36545 36,546.00       6243         Posavski       1000       3000        652
36546 36,547.00       6244         Sarajevo       1000       3000        652
36547 36,548.00       6245  Srednjebosanski       1000       3000        652
...         ...        ...              ...        ...        ...        ...
36619 36,620.00       6317            Tuzla       1000       3000        653
36620 36,621.00       6318         Ugljevik       1000       3000        653
36621 36,622.00       6319         Visegrad       1000       3000        653
36622 36,623.00       6320        Vlasenica       1000       3000        653
36623 36,624.00       6321          Zvornik       1000       3000        653

                            ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
36543  Federacija Bosne I Hercegovine  Member State        NO         34
36544  Federacija Bosne I Hercegovine  Member State        NO         34
36545  Federacija Bosne I Hercegovine  Member State        NO         34
36546  Federacija Bosne I Hercegovine  Member State        NO         34
36547  Federacija Bosne I Hercegovine  Member State        NO         34
...                               ...           ...       ...        ...
36619                Republika Srpska  Member State        NO         34
36620                Republika Srpska  Member State        NO         34
36621                Republika Srpska  Member State        NO         34
36622                Republika Srpska  Member State        NO         34
36623                Republika Srpska  Member State        NO         34

                    ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
36543  Bosnia and Herzegovina        1.00        1.00        0.05
36544  Bosnia and Herzegovina        6.04        6.04        0.47
36545  Bosnia and Herzegovina        1.57        1.57        0.03
36546  Bosnia and Herzegovina        3.56        3.56        0.15
36547  Bosnia and Herzegovina        4.16        4.16        0.39
...                       ...         ...         ...         ...
36619  Bosnia and Herzegovina        0.30        0.30        0.00
36620  Bosnia and Herzegovina        0.90        0.90        0.02
36621  Bosnia and Herzegovina        1.34        1.34        0.05
36622  Bosnia and Herzegovina        1.42        1.42        0.06
36623  Bosnia and Herzegovina        1.51        1.51        0.04

                                                geometry
36543  POLYGON ((18.87381 43.77189, 18.87389 43.77184...
36544  POLYGON ((18.00989 43.80129, 18.01018 43.80042...
36545  MULTIPOLYGON (((18.60968 45.07899, 18.61183 45...
36546  MULTIPOLYGON (((18.25838 43.48817, 18.25948 43...
36547  POLYGON ((17.28769 44.63563, 17.28747 44.63415...
...                                                  ...
36619  MULTIPOLYGON (((18.83126 44.57263, 18.83340 44...
36620  POLYGON ((19.08842 44.60250, 19.08797 44.60088...
36621  POLYGON ((19.50630 43.71819, 19.50630 43.71819...
36622  POLYGON ((19.10921 44.26238, 19.10953 44.26055...
36623  POLYGON ((19.18802 44.57748, 19.18791 44.57738...

[81 rows x 15 columns]
26 BWA Botswana
      OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
4964  4,965.00       6322  Administrative unit not available       1000
4965  4,966.00       6323  Administrative unit not available       1000
4966  4,967.00       6324  Administrative unit not available       1000
4967  4,968.00       6325  Administrative unit not available       1000
4968  4,969.00       6326  Administrative unit not available       1000
4969  4,970.00       6327  Administrative unit not available       1000
4970  4,971.00       6328  Administrative unit not available       1000
4971  4,972.00       6329  Administrative unit not available       1000
4972  4,973.00       6330  Administrative unit not available       1000
4973  4,974.00       6331  Administrative unit not available       1000

      EXP2_YEAR  ADM1_CODE   ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
4964       3000        654     Central  Member State        NO         35
4965       3000        655       Chobe  Member State        NO         35
4966       3000        656      Ghanzi  Member State        NO         35
4967       3000        657   Kgalagadi  Member State        NO         35
4968       3000        658    Kgatleng  Member State        NO         35
4969       3000        659     Kweneng  Member State        NO         35
4970       3000        660   Ngamiland  Member State        NO         35
4971       3000        661  North East  Member State        NO         35
4972       3000        662  South-East  Member State        NO         35
4973       3000        663    Southern  Member State        NO         35

     ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
4964  Botswana       19.05       19.05       12.79
4965  Botswana        6.55        6.55        1.79
4966  Botswana       14.36       14.36       10.03
4967  Botswana       17.65       17.65        9.40
4968  Botswana        4.01        4.01        0.69
4969  Botswana        8.51        8.51        3.27
4970  Botswana       14.59       14.59        9.60
4971  Botswana        3.52        3.52        0.46
4972  Botswana        2.71        2.71        0.18
4973  Botswana        8.13        8.13        2.45

                                               geometry
4964  POLYGON ((26.69159 -19.89356, 26.69192 -19.893...
4965  POLYGON ((25.26280 -17.79139, 25.26839 -17.790...
4966  POLYGON ((23.88125 -20.99294, 23.89500 -21.007...
4967  POLYGON ((23.05667 -23.31139, 23.05805 -23.318...
4968  POLYGON ((26.96656 -23.74986, 26.96656 -23.749...
4969  POLYGON ((26.01723 -23.55865, 26.01944 -23.581...
4970  POLYGON ((23.30320 -18.00369, 23.30492 -18.003...
4971  POLYGON ((27.71875 -20.51689, 27.72207 -20.519...
4972  POLYGON ((26.18221 -24.68372, 26.13096 -24.695...
4973  POLYGON ((25.68574 -24.77061, 25.68583 -24.788...
27 BRA Brazil
       OBJECTID  ADM2_CODE     ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
13916 13,917.00       6333    Acrelandia       1000       3000        665
13917 13,918.00       6334  Assis Brasil       1000       3000        665
13918 13,919.00       6335     Brasileia       1000       3000        665
13919 13,920.00       6336        Bujari       1000       3000        665
13920 13,921.00       6337      Capixaba       1000       3000        665
...         ...        ...           ...        ...        ...        ...
19421 19,422.00      11838       Xambioa       1000       3000        691
19422 19,423.00      11839  Name Unknown       1000       3000        692
19423 19,424.00      11840  Name Unknown       1000       3000        693
19424 19,425.00      11841  Name Unknown       1000       3000        694
19425 19,426.00      11842  Name Unknown       1000       3000        695

          ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
13916          Acre  Member State        NO         37    Brazil        1.69
13917          Acre  Member State        NO         37    Brazil        3.72
13918          Acre  Member State        NO         37    Brazil        4.71
13919          Acre  Member State        NO         37    Brazil        3.15
13920          Acre  Member State        NO         37    Brazil        1.98
...             ...           ...       ...        ...       ...         ...
19421     Tocantins  Member State        NO         37    Brazil        1.91
19422  Name Unknown  Member State        NO         37    Brazil        0.01
19423  Name Unknown  Member State        NO         37    Brazil        0.04
19424  Name Unknown  Member State        NO         37    Brazil        0.22
19425  Name Unknown  Member State        NO         37    Brazil        0.04

       Shape_Le_1  Shape_Area  \
13916        1.69        0.13
13917        3.72        0.24
13918        4.71        0.36
13919        3.15        0.28
13920        1.98        0.14
...           ...         ...
19421        1.91        0.11
19422        0.01        0.00
19423        0.04        0.00
19424        0.22        0.00
19425        0.04        0.00

                                                geometry
13916  POLYGON ((-66.80572 -9.81410, -66.61747 -9.894...
13917  POLYGON ((-69.71895 -10.73417, -69.71839 -10.7...
13918  POLYGON ((-68.64486 -10.92353, -68.65308 -10.9...
13919  POLYGON ((-68.18325 -9.23446, -67.93950 -9.336...
13920  POLYGON ((-67.63734 -10.36338, -67.63736 -10.3...
...                                                  ...
19421  POLYGON ((-48.33508 -6.37622, -48.33825 -6.380...
19422  POLYGON ((-33.81476 -3.86744, -33.81501 -3.867...
19423  MULTIPOLYGON (((-28.84936 -20.49572, -28.84896...
19424  MULTIPOLYGON (((-29.32455 -20.52939, -29.32465...
19425  MULTIPOLYGON (((-45.70770 -24.11119, -45.70714...

[5510 rows x 15 columns]
28 VGB British Virgin Islands
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
29 BRN Brunei Darussalam
       OBJECTID  ADM2_CODE           ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
27789 27,790.00      61095         Bukit Sawat       1000       3000
27790 27,791.00      61096         Kuala Balai       1000       3000
27791 27,792.00      61097        Kuala Belait       1000       3000
27792 27,793.00      61098                Labi       1000       3000
27793 27,794.00      61099               Liang       1000       3000
27794 27,795.00      61100             Melilas       1000       3000
27795 27,796.00      61101               Seria       1000       3000
27796 27,797.00      61102              Sukang       1000       3000
27797 27,798.00      61105  Burong Pingai Ayer       1000       3000
27798 27,799.00      61106              Gadong       1000       3000
27799 27,800.00      61107            Kianggeh       1000       3000
27800 27,801.00      61108             Kilanas       1000       3000
27801 27,802.00      61109           Kota Batu       1000       3000
27802 27,803.00      61110             Lumapas       1000       3000
27803 27,804.00      61111             Mentiri       1000       3000
27804 27,805.00      61112      Pangkalan Batu       1000       3000
27805 27,806.00      61113              Peramu       1000       3000
27806 27,807.00      61114                Saba       1000       3000
27807 27,808.00      61115          Sengkurong       1000       3000
27808 27,809.00      61116              Serasa       1000       3000
27809 27,810.00      61117        Sungai Kebun       1000       3000
27810 27,811.00      61118      Sungai Kedayan       1000       3000
27811 27,812.00      61119               Tamoi       1000       3000
27812 27,813.00      61120                 Amo       1000       3000
27813 27,814.00      61121              Bangar       1000       3000

      OBJECTID  ADM2_CODE    ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
6495  6,496.00     154442        Banwa       2001       3000      40276
6496  6,497.00     154443        Kossi       2001       3000      40276
6497  6,498.00     154444         Bale       2001       3000      40276
6498  6,499.00     154445      Mouhoun       2001       3000      40276
6499  6,500.00     154446       Nayala       2001       3000      40276
6500  6,501.00     154447       Sourou       2001       3000      40276
6501  6,502.00     154448        Comoe       2001       3000      40277
6502  6,503.00     154449       Leraba       2001       3000      40277
6503  6,504.00     154450      Kadiogo       2001       3000      40278
6504  6,505.00     154451      Boulgou       2001       3000      40279
6505  6,506.00     154452   Koulpelogo       2001       3000      40279
6506  6,507.00     154453   Kouritenga       2001       3000      40279
6507  6,508.00     154454          Bam       2001       3000      40280
6508  6,509.00     154455   Namentenga       2001       3000      40280
6509  6,510.00     154456   Sanmatenga       2001       3000      40280
6510  6,511.00     154457   Boulkiemde       2001       3000      40281
6511  6,512.00     154458      Sanguie       2001       3000      40281
6512  6,513.00     154459      Sissili       2001       3000      40281
6513  6,514.00     154460         Ziro       2001       3000      40281
6514  6,515.00     154461       Bazega       2001       3000      40282
6515  6,516.00     154462      Nahouri       2001       3000      40282
6516  6,517.00     154463   Zoundweogo       2001       3000      40282
6517  6,518.00     154464       Gnagna       2001       3000      40283
6518  6,519.00     154465       Gourma       2001       3000      40283
6519  6,520.00     154466  Komonjdjari       2001       3000      40283
6520  6,521.00     154467    Kompienga       2001       3000      40283
6521  6,522.00     154468        Tapoa       2001       3000      40283
6522  6,523.00     154469        Houet       2001       3000      40284
6523  6,524.00     154470   Kenedougou       2001       3000      40284
6524  6,525.00     154471          Tuy       2001       3000      40284
6525  6,526.00     154472       Loroum       2001       3000      40285
6526  6,527.00     154473      Passore       2001       3000      40285
6527  6,528.00     154474      Yatenga       2001       3000      40285
6528  6,529.00     154475      Zondoma       2001       3000      40285
6529  6,530.00     154476   Ganzourgou       2001       3000      40286
6530  6,531.00     154477    Kourweogo       2001       3000      40286
6531  6,532.00     154478   Oubritenga       2001       3000      40286
6532  6,533.00     154479      Oudalan       2001       3000      40287
6533  6,534.00     154480         Seno       2001       3000      40287
6534  6,535.00     154481         Soum       2001       3000      40287
6535  6,536.00     154482        Yagha       2001       3000      40287
6536  6,537.00     154483   Bougouriba       2001       3000      40288
6537  6,538.00     154484         Ioba       2001       3000      40288
6538  6,539.00     154485     Noumbiel       2001       3000      40288
6539  6,540.00     154486         Poni       2001       3000      40288

              ADM1_NAME        STATUS DISP_AREA  ADM0_CODE     ADM0_NAME  \
6495  Boucle Du Mouhoun  Member State        NO         42  Burkina Faso
6496  Boucle Du Mouhoun  Member State        NO         42  Burkina Faso
6497  Boucle Du Mouhoun  Member State        NO         42  Burkina Faso
6498  Boucle Du Mouhoun  Member State        NO         42  Burkina Faso
6499  Boucle Du Mouhoun  Member State        NO         42  Burkina Faso
6500  Boucle Du Mouhoun  Member State        NO         42  Burkina Faso
6501           Cascades  Member State        NO         42  Burkina Faso
6502           Cascades  Member State        NO         42  Burkina Faso
6503             Centre  Member State        NO         42  Burkina Faso
6504         Centre-est  Member State        NO         42  Burkina Faso
6505         Centre-est  Member State        NO         42  Burkina Faso
6506         Centre-est  Member State        NO         42  Burkina Faso
6507        Centre-nord  Member State        NO         42  Burkina Faso
6508        Centre-nord  Member State        NO         42  Burkina Faso
6509        Centre-nord  Member State        NO         42  Burkina Faso
6510       Centre-ouest  Member State        NO         42  Burkina Faso
6511       Centre-ouest  Member State        NO         42  Burkina Faso
6512       Centre-ouest  Member State        NO         42  Burkina Faso
6513       Centre-ouest  Member State        NO         42  Burkina Faso
6514         Centre-sud  Member State        NO         42  Burkina Faso
6515         Centre-sud  Member State        NO         42  Burkina Faso
6516         Centre-sud  Member State        NO         42  Burkina Faso
6517                Est  Member State        NO         42  Burkina Faso
6518                Est  Member State        NO         42  Burkina Faso
6519                Est  Member State        NO         42  Burkina Faso
6520                Est  Member State        NO         42  Burkina Faso
6521                Est  Member State        NO         42  Burkina Faso
6522      Hauts-bassins  Member State        NO         42  Burkina Faso
6523      Hauts-bassins  Member State        NO         42  Burkina Faso
6524      Hauts-bassins  Member State        NO         42  Burkina Faso
6525               Nord  Member State        NO         42  Burkina Faso
6526               Nord  Member State        NO         42  Burkina Faso
6527               Nord  Member State        NO         42  Burkina Faso
6528               Nord  Member State        NO         42  Burkina Faso
6529    Plateau Central  Member State        NO         42  Burkina Faso
6530    Plateau Central  Member State        NO         42  Burkina Faso
6531    Plateau Central  Member State        NO         42  Burkina Faso
6532              Sahel  Member State        NO         42  Burkina Faso
6533              Sahel  Member State        NO         42  Burkina Faso
6534              Sahel  Member State        NO         42  Burkina Faso
6535              Sahel  Member State        NO         42  Burkina Faso
6536          Sud-ouest  Member State        NO         42  Burkina Faso
6537          Sud-ouest  Member State        NO         42  Burkina Faso
6538          Sud-ouest  Member State        NO         42  Burkina Faso
6539          Sud-ouest  Member State        NO         42  Burkina Faso

      Shape_Leng  Shape_Le_1  Shape_Area  \
6495        5.02        5.02        0.49
6496        4.10        4.10        0.62
6497        4.84        4.84        0.38
6498        5.53        5.53        0.57
6499        2.76        2.76        0.31
6500        3.85        3.85        0.50
6501        7.45        7.45        1.27
6502        2.98        2.98        0.25
6503        2.99        2.99        0.24
6504        5.18        5.18        0.54
6505        3.23        3.23        0.45
6506        2.94        2.94        0.23
6507        3.02        3.02        0.34
6508        4.71        4.71        0.53
6509        5.21        5.21        0.78
6510        3.91        3.91        0.36
6511        4.73        4.73        0.43
6512        5.61        5.61        0.58
6513        3.43        3.43        0.44
6514        3.63        3.63        0.33
6515        3.39        3.39        0.32
6516        3.22        3.22        0.30
6517        4.73        4.73        0.71
6518        5.98        5.98        0.93
6519        3.68        3.68        0.43
6520        4.53        4.53        0.57
6521        5.61        5.61        1.23
6522        6.65        6.65        0.96
6523        4.79        4.79        0.69
6524        4.59        4.59        0.47
6525        2.85        2.85        0.31
6526        3.82        3.82        0.33
6527        4.76        4.76        0.56
6528        2.30        2.30        0.17
6529        3.15        3.15        0.35
6530        2.29        2.29        0.13
6531        3.53        3.53        0.24
6532        4.09        4.09        0.84
6533        3.93        3.93        0.59
6534        4.66        4.66        1.06
6535        3.99        3.99        0.54
6536        3.22        3.22        0.23
6537        3.39        3.39        0.27
6538        2.93        2.93        0.24
6539        4.92        4.92        0.62

                                               geometry
6495  POLYGON ((-4.23000 12.71653, -4.22651 12.71594...
6496  POLYGON ((-3.96257 13.49940, -3.96229 13.49935...
6497  POLYGON ((-2.92401 12.04835, -2.92165 12.04655...
6498  POLYGON ((-3.41552 12.74612, -3.41415 12.74577...
6499  POLYGON ((-2.73649 12.93744, -2.73581 12.93366...
6500  POLYGON ((-3.20984 13.69655, -3.20571 13.69464...
6501  POLYGON ((-4.95813 10.88730, -4.95608 10.88717...
6502  POLYGON ((-5.39668 11.00061, -5.39578 10.99896...
6503  POLYGON ((-1.09793 12.26615, -1.09847 12.26433...
6504  POLYGON ((-0.50808 12.00237, -0.50252 12.00041...
6505  POLYGON ((0.11931 11.78512, 0.12181 11.78510, ...
6506  POLYGON ((-0.24067 12.55975, -0.24291 12.55690...
6507  POLYGON ((-1.35121 13.76111, -1.35278 13.75634...
6508  POLYGON ((-0.61966 13.99928, -0.62209 13.99394...
6509  POLYGON ((-0.69064 12.70324, -0.69277 12.70358...
6510  POLYGON ((-1.94676 12.69281, -1.94390 12.69131...
6511  POLYGON ((-2.32936 12.65812, -2.32480 12.64968...
6512  MULTIPOLYGON (((-1.42725 11.02047, -1.42495 11...
6513  POLYGON ((-1.34704 11.59137, -1.34607 11.59006...
6514  POLYGON ((-1.07206 12.17824, -1.07149 12.17755...
6515  POLYGON ((-1.29232 11.52863, -1.28997 11.52839...
6516  POLYGON ((-0.89365 11.89651, -0.89336 11.89522...
6517  POLYGON ((0.06191 13.57748, 0.06428 13.57539, ...
6518  POLYGON ((1.21235 12.78013, 1.21310 12.77856, ...
6519  POLYGON ((0.98892 13.08464, 0.98974 13.08438, ...
6520  POLYGON ((0.88250 11.93736, 0.88428 11.93704, ...
6521  POLYGON ((1.31644 12.83792, 1.31903 12.83725, ...
6522  POLYGON ((-4.49027 12.09498, -4.48717 12.09001...
6523  POLYGON ((-4.65272 12.00003, -4.65238 11.99319...
6524  POLYGON ((-3.57217 11.77222, -3.57133 11.77071...
6525  POLYGON ((-2.13562 14.16660, -2.10582 14.15028...
6526  POLYGON ((-1.74593 13.14143, -1.74362 13.13958...
6527  POLYGON ((-2.65594 14.13994, -2.65546 14.13815...
6528  POLYGON ((-2.14288 13.08522, -2.14497 13.08771...
6529  POLYGON ((-0.69064 12.70324, -0.68957 12.70314...
6530  POLYGON ((-1.60583 12.68509, -1.60748 12.68209...
6531  POLYGON ((-1.53855 12.92626, -1.52974 12.92254...
6532  POLYGON ((-0.45567 15.08082, -0.45411 15.07937...
6533  POLYGON ((0.22461 14.42997, 0.26658 14.39049, ...
6534  POLYGON ((-1.03404 14.80428, -1.03094 14.80384...
6535  POLYGON ((0.58942 13.78756, 0.60217 13.78098, ...
6536  POLYGON ((-3.04123 10.74530, -3.04460 10.74500...
6537  POLYGON ((-3.13650 11.35645, -3.13507 11.35472...
6538  POLYGON ((-2.87833 10.19563, -2.87015 10.19523...
6539  POLYGON ((-2.99395 10.74535, -2.99223 10.74462...
32 BDI Burundi
     OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
0        1.00      40621                           Ryansoro       1000
1        2.00      40667                              Ndava       1000
2        3.00      40593                          Buyengero       1000
3        4.00      40580                           Bugarama       2004
4        5.00      40590  Administrative unit not available       1000
..        ...        ...                                ...        ...
129    130.00      40579  Administrative unit not available       1000
130    131.00      40564  Administrative unit not available       1000
131    132.00      40596                            Rumonge       1000
132    133.00      40645  Administrative unit not available       1000
133    134.00      40604                            Mishiha       1000

     EXP2_YEAR  ADM1_CODE         ADM1_NAME        STATUS DISP_AREA  \
0         3000      40548            Gitega  Member State        NO
1         3000      40555             Mwaro  Member State        NO
2         3000      40545            Bururi  Member State        NO
3         3000      40544   Bujumbura Rural  Member State        NO
4         3000      40545            Bururi  Member State        NO
..         ...        ...               ...           ...       ...
129       3000      40544   Bujumbura Rural  Member State        NO
130       3000      40543  Bujumbura Mairie  Member State        NO
131       3000      40545            Bururi  Member State        NO
132       3000      40552           Makamba  Member State        NO
133       3000      40546           Cankuzo  Member State        NO

     ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
0           43   Burundi        0.75        0.75        0.01
1           43   Burundi        0.72        0.72        0.01
2           43   Burundi        0.74        0.74        0.02
3           43   Burundi        0.62        0.62        0.01
4           43   Burundi        1.38        1.38        0.06
..         ...       ...         ...         ...         ...
129         43   Burundi        0.35        0.35        0.00
130         43   Burundi        0.50        0.50        0.01
131         43   Burundi        1.60        1.60        0.03
132         43   Burundi        0.96        0.96        0.05
133         43   Burundi        0.84        0.84        0.03

                                              geometry
0    POLYGON ((29.79610 -3.62673, 29.79516 -3.63288...
1    POLYGON ((29.82561 -3.36665, 29.82505 -3.36981...
2    POLYGON ((29.60733 -3.78270, 29.60393 -3.78899...
3    POLYGON ((29.49645 -3.66299, 29.49792 -3.66422...
4    POLYGON ((29.53687 -4.19135, 29.53699 -4.19171...
..                                                 ...
129  POLYGON ((29.29005 -3.34999, 29.28933 -3.35479...
130  POLYGON ((29.34006 -3.36141, 29.34048 -3.36174...
131  POLYGON ((29.53687 -4.19135, 29.53612 -4.19047...
132  POLYGON ((29.66152 -4.44872, 29.65629 -4.44869...
133  POLYGON ((30.71965 -2.98556, 30.72643 -2.99089...

[134 rows x 15 columns]
33 CPV Cabo Verde
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
34 KHM Cambodia
       OBJECTID  ADM2_CODE                             ADM2_NAME  STR2_YEAR  \
26945 26,946.00      65291  Area under National Administration 1       1000
26946 26,947.00      65293  Area under National Administration 2       1000
26947 26,948.00      12275                  Krong Serei Saophoan       1000
26948 26,949.00      12270                                 Malai       1000
26949 26,950.00      12271                         Mongkol Borei       1000
...         ...        ...                                   ...        ...
27127 27,128.00      12460                              Samraong       1000
27128 27,129.00      12461                              Tram Kak       1000
27129 27,130.00      12458                                Treang       1000
27130 27,131.00      12450                      Krong Svay Rieng       1000
27131 27,132.00      12446                           Kampong Rou       1000

       EXP2_YEAR  ADM1_CODE                             ADM1_NAME  \
26945       3000      65290  Area under National Administration 1
26946       3000      65289  Area under National Administration 2
26947       3000        791                      Banteay Meanchey
26948       3000        791                      Banteay Meanchey
26949       3000        791                      Banteay Meanchey
...          ...        ...                                   ...
27127       3000        814                                 Takeo
27128       3000        814                                 Takeo
27129       3000        814                                 Takeo
27130       3000        813                            Svay Rieng
27131       3000        813                            Svay Rieng

             STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  \
26945  Member State        NO         44  Cambodia        5.27        5.27
26946  Member State        NO         44  Cambodia        0.38        0.38
26947  Member State        NO         44  Cambodia        0.83        0.83
26948  Member State        NO         44  Cambodia        1.26        1.26
26949  Member State        NO         44  Cambodia        2.00        2.00
...             ...       ...        ...       ...         ...         ...
27127  Member State        NO         44  Cambodia        0.77        0.77
27128  Member State        NO         44  Cambodia        1.19        1.19
27129  Member State        NO         44  Cambodia        1.06        1.06
27130  Member State        NO         44  Cambodia        0.21        0.21
27131  Member State        NO         44  Cambodia        1.25        1.25

       Shape_Area                                           geometry
26945        0.21  POLYGON ((103.73797 13.25685, 103.73862 13.256...
26946        0.00  MULTIPOLYGON (((102.88538 9.93100, 102.88578 9...
26947        0.02  POLYGON ((102.91810 13.71530, 103.00014 13.696...
26948        0.04  POLYGON ((102.63018 13.60591, 102.63022 13.604...
26949        0.07  POLYGON ((103.08834 13.56700, 103.08876 13.566...
...           ...                                                ...
27127        0.02  POLYGON ((104.79194 11.21607, 104.79187 11.215...
27128        0.05  POLYGON ((104.41655 11.13221, 104.41658 11.131...
27129        0.03  POLYGON ((104.87095 10.99125, 104.87234 10.990...
27130        0.00  POLYGON ((105.83616 11.05595, 105.83581 11.055...
27131        0.03  POLYGON ((105.88608 11.05348, 105.88865 11.051...

[187 rows x 15 columns]
35 CMR Cameroon
      OBJECTID  ADM2_CODE        ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
1906  1,907.00      12462           Djerem       1000       3000        815
1907  1,908.00      12463  Faro - Et - Déo       1000       3000        815
1908  1,909.00      12464       Mayo-Banyo       1000       3000        815
1909  1,910.00      12465            Mbéré       1000       3000        815
1910  1,911.00      12466             Vina       1000       3000        815
...        ...        ...              ...        ...        ...        ...
1959  1,960.00      12511   Kupé Manenguba       1998       3000        824
1960  1,961.00      12512         Lebialem       1998       3000        824
1961  1,962.00      12513            Manyu       1998       3000        824
1962  1,963.00      12514             Meme       1998       3000        824
1963  1,964.00      12515            Ndian       1000       3000        824

        ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
1906     Adamaoua  Member State        NO         45  Cameroon        5.93
1907     Adamaoua  Member State        NO         45  Cameroon        5.92
1908     Adamaoua  Member State        NO         45  Cameroon        5.42
1909     Adamaoua  Member State        NO         45  Cameroon        7.43
1910     Adamaoua  Member State        NO         45  Cameroon        7.88
...           ...           ...       ...        ...       ...         ...
1959  Sud - Ouest  Member State        NO         45  Cameroon        3.50
1960  Sud - Ouest  Member State        NO         45  Cameroon        1.32
1961  Sud - Ouest  Member State        NO         45  Cameroon        5.13
1962  Sud - Ouest  Member State        NO         45  Cameroon        3.33
1963  Sud - Ouest  Member State        NO         45  Cameroon        8.63

      Shape_Le_1  Shape_Area  \
1906        5.93        1.09
1907        5.92        0.87
1908        5.42        0.69
1909        7.43        1.19
1910        7.88        1.40

       OBJECTID  ADM2_CODE                ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
19426 19,427.00      12940                    Aisen       1991       3000
19427 19,428.00      12941             Capitan Prat       1991       3000
19428 19,429.00      12942                Coyhaique       1000       3000
19429 19,430.00      12943          General Carrera       1991       3000
19430 19,431.00      12932              Antofagasta       1991       3000
...         ...        ...                      ...        ...        ...
19474 19,475.00      12981  San Felipe de Aconcagua       1991       3000
19475 19,476.00     149634               Valparaiso       1991       3000
19476 19,477.00      12961         Tierra del Fuego       1991       3000
19477 19,478.00     149632                    Ranco       2007       3000
19478 19,479.00     149633                 Valdivia       2007       3000

       ADM1_CODE                                ADM1_NAME        STATUS  \
19426        886  Aisen del Gral. Carlos Ibañez del Campo  Member State
19427        886  Aisen del Gral. Carlos Ibañez del Campo  Member State
19428        886  Aisen del Gral. Carlos Ibañez del Campo  Member State
19429        886  Aisen del Gral. Carlos Ibañez del Campo  Member State
19430        883                              Antofagasta  Member State
...          ...                                      ...           ...
19474     149630                               Valparaiso  Member State
19475     149630                               Valparaiso  Member State
19476        891           Magallanes y Antartica chilena  Member State
19477      91504                                 Los Rios  Member State
19478      91504                                 Los Rios  Member State

      DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
19426        NO         51     Chile      192.68      192.68        5.27
19427        NO         51     Chile      110.88      110.88        4.39
19428        NO         51     Chile       11.87       11.87        1.47
19429        NO         51     Chile        6.53        6.53        1.38
19430        NO         51     Chile       16.08       16.08        6.01
...         ...        ...       ...         ...         ...         ...
19474        NO         51     Chile        3.46        3.46        0.25
19475        NO         51     Chile        6.00        6.00        0.26
19476        NO         51     Chile       28.53       28.53        3.03
19477        NO         51     Chile        7.08        7.08        0.87
19478        NO         51     Chile        7.98        7.98        1.07

                                                geometry
19426  MULTIPOLYGON (((-75.46859 -46.96446, -75.46879...
19427  MULTIPOLYGON (((-75.57988 -48.75920, -75.57988...
19428  POLYGON ((-71.95223 -43.92710, -71.92994 -43.9...
19429  POLYGON ((-72.92701 -45.92013, -72.91407 -45.9...
19430  MULTIPOLYGON (((-70.70268 -25.89142, -70.70219...
...                                                  ...
19474  POLYGON ((-70.33602 -32.27299, -70.32763 -32.2...
19475  MULTIPOLYGON (((-80.78686 -33.72190, -80.78616...
19476  MULTIPOLYGON (((-69.35098 -54.71448, -69.35098...
19477  POLYGON ((-71.89003 -39.89914, -71.88285 -39.9...
19478  MULTIPOLYGON (((-73.43243 -39.86066, -73.43241...

[53 rows x 15 columns]
41 CHN China
       OBJECTID  ADM2_CODE     ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
26538 26,539.00      12984         Hefei       1000       3000        898
26539 26,540.00      12985          Wuhu       1000       3000        898
26540 26,541.00      12986        Bengbu       1000       3000        898
26541 26,542.00      12987       Huainan       1000       3000        898
26542 26,543.00      12988     Ma'anshan       1000       3000        898
...         ...        ...           ...        ...        ...        ...
26876 26,877.00      13243  Name Unknown       1000       3000        922
26877 26,878.00      13263  Name Unknown       1000       3000        924
26878 26,879.00      13278  Name Unknown       1000       3000        926
26879 26,880.00      13279  Name Unknown       1000       3000        926
26880 26,881.00      13291  Name Unknown       1000       3000        927

                    ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
26538             Anhui Sheng  Member State        NO     147295     China
26539             Anhui Sheng  Member State        NO     147295     China
26540             Anhui Sheng  Member State        NO     147295     China
26541             Anhui Sheng  Member State        NO     147295     China
26542             Anhui Sheng  Member State        NO     147295     China
...                       ...           ...       ...        ...       ...
26876            Shanghai Shi  Member State        NO     147295     China
26877           Sichuan Sheng  Member State        NO     147295     China
26878             Tianjin Shi  Member State        NO     147295     China
26879             Tianjin Shi  Member State        NO     147295     China
26880  Xinjiang Uygur Zizhiqu  Member State        NO     147295     China

       Shape_Leng  Shape_Le_1  Shape_Area  \
26538        4.66        4.66        0.71
26539        3.10        3.10        0.32
26540        3.86        3.86        0.57
26541        2.22        2.22        0.20
26542        1.72        1.72        0.16
...           ...         ...         ...
26876        6.47        6.47        0.29
26877        4.10        4.10        0.50
26878        3.80        3.80        0.40
26879        6.81        6.81        0.86
26880        1.83        1.83        0.14

                                                geometry
26538  POLYGON ((117.85668 32.02414, 117.76963 31.992...
26539  POLYGON ((118.67449 31.31315, 118.67437 31.266...
26540  POLYGON ((117.94735 33.33840, 117.95826 33.295...
26541  POLYGON ((116.75575 32.94517, 116.80776 32.915...
26542  POLYGON ((118.73105 31.32287, 118.67449 31.313...
...                                                  ...
26876  MULTIPOLYGON (((121.66303 31.17230, 121.66432 ...
26877  POLYGON ((105.42543 29.68823, 105.39383 29.645...
26878  POLYGON ((117.48463 39.18695, 117.53926 39.172...
26879  MULTIPOLYGON (((117.16492 38.69271, 117.14689 ...
26880  POLYGON ((85.05717 44.74458, 85.04603 44.70180...

[343 rows x 15 columns]
42 COL Colombia
       OBJECTID  ADM2_CODE          ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
19479 19,480.00      13333         El Encanto       1000       3000
19480 19,481.00      13334        La Chorrera       1000       3000
19481 19,482.00      13335         La Pedrera       1000       3000
19482 19,483.00      13336            Leticia       1000       3000
19483 19,484.00      13337      Miriti Parana       1000       3000
...         ...        ...                ...        ...        ...
20560 20,561.00      14416     Puerto Carreno       1000       3000
20561 20,562.00      14417  San Jose De Ocune       1000       3000
20562 20,563.00      14418         Santa Rita       1000       3000
20563 20,564.00      14419      Santa Rosalia       1000       3000
20564 20,565.00      13659               Isla       1000       3000

       ADM1_CODE     ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
19479        934      Amazonas  Member State        NO         57  Colombia
19480        934      Amazonas  Member State        NO         57  Colombia
19481        934      Amazonas  Member State        NO         57  Colombia
19482        934      Amazonas  Member State        NO         57  Colombia
19483        934      Amazonas  Member State        NO         57  Colombia
...          ...           ...           ...       ...        ...       ...
20560        966       Vichada  Member State        NO         57  Colombia
20561        966       Vichada  Member State        NO         57  Colombia
20562        966       Vichada  Member State        NO         57  Colombia
20563        966       Vichada  Member State        NO         57  Colombia
20564        940  Buenaventura  Member State        NO         57  Colombia

       Shape_Leng  Shape_Le_1  Shape_Area  \
19479        7.97        7.97        0.88
19480        7.25        7.25        1.81
19481        9.74        9.74        1.96
19482        2.56        2.56        0.33
19483        7.15        7.15        1.35
...           ...         ...         ...
20560        3.80        3.80        0.80
20561        9.93        9.93        2.05
20562        6.26        6.26        1.57
20563        2.90        2.90        0.35
20564        0.04        0.04        0.00

                                                geometry
19479  POLYGON ((-73.72420 -0.43310, -73.72360 -0.448...
19480  POLYGON ((-72.71010 -0.64240, -72.71760 -0.646...
19481  MULTIPOLYGON (((-69.41947 -1.07005, -69.42337 ...
19482  POLYGON ((-69.76051 -3.26198, -69.83733 -3.686...
19483  POLYGON ((-70.21880 -0.48360, -70.20900 -0.489...
...                                                  ...
20560  POLYGON ((-67.82461 5.33953, -67.82461 5.33953...
20561  POLYGON ((-68.87930 3.92910, -68.90510 3.65020...
20562  POLYGON ((-67.82461 5.33953, -67.82800 5.33284...
20563  POLYGON ((-70.38830 4.67341, -70.39980 4.66840...
20564  POLYGON ((-77.10439 3.80797, -77.10587 3.79542...

[1086 rows x 15 columns]
43 COM Comoros
     OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
136    137.00      14420  Administrative unit not available       1000
137    138.00      14421  Administrative unit not available       1000
138    139.00      14422  Administrative unit not available       1000

     EXP2_YEAR  ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
136       3000        967   Anjouan  Member State        NO         58
137       3000        968    Moheli  Member State        NO         58
138       3000        969  Ngazidja  Member State        NO         58

    ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
136   Comoros        1.36        1.36        0.04
137   Comoros        1.25        1.25        0.02
138   Comoros        1.80        1.80        0.08

                                              geometry
136  MULTIPOLYGON (((44.20592 -12.16117, 44.20617 -...
137  MULTIPOLYGON (((43.71993 -12.40682, 43.72064 -...
138  MULTIPOLYGON (((43.25007 -11.70165, 43.25017 -...
44 COD Congo, Dem. Rep.
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
45 COG Congo, Rep.
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
46 CRI Costa Rica
       OBJECTID  ADM2_CODE            ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
10271 10,272.00      14470             Alajuela       1000       3000
10272 10,273.00      14471          Alfaro Ruiz       1000       3000
10273 10,274.00      14472               Atenas       1000       3000
10274 10,275.00      14473               Grecia       1000       3000
10275 10,276.00      14474              Guatuso       1000       3000
...         ...        ...                  ...        ...        ...
10347 10,348.00      14546            Santa Ana       1000       3000
10348 10,349.00      14547              Tarrazu       1000       3000
10349 10,350.00      14548                Tibas       1000       3000
10350 10,351.00      14549           Turrubares       1000       3000
10351 10,352.00      14550  Vasquez De Coronado       1000       3000

       ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE   ADM0_NAME  \
10271        981  Alajuela  Member State        NO         61  Costa Rica
10272        981  Alajuela  Member State        NO         61  Costa Rica
10273        981  Alajuela  Member State        NO         61  Costa Rica
10274        981  Alajuela  Member State        NO         61  Costa Rica
10275        981  Alajuela  Member State        NO         61  Costa Rica
...          ...       ...           ...       ...        ...         ...
10347        987  San Jose  Member State        NO         61  Costa Rica
10348        987  San Jose  Member State        NO         61  Costa Rica
10349        987  San Jose  Member State        NO         61  Costa Rica
10350        987  San Jose  Member State        NO         61  Costa Rica
10351        987  San Jose  Member State        NO         61  Costa Rica

       Shape_Leng  Shape_Le_1  Shape_Area  \
10271        1.28        1.28        0.03
10272        0.51        0.51        0.01
10273        0.43        0.43        0.01
10274        1.30        1.30        0.03
10275        1.06        1.06        0.06
...           ...         ...         ...
10347        0.29        0.29        0.00
10348        0.80        0.80        0.02
10349        0.09        0.09        0.00
10350        1.02        1.02        0.03
10351        0.78        0.78        0.02

                                                geometry
10271  POLYGON ((-84.16298 10.28917, -84.16505 10.172...
10272  POLYGON ((-84.34480 10.25545, -84.33082 10.239...
10273  POLYGON ((-84.36324 10.03812, -84.36241 10.029...
10274  MULTIPOLYGON (((-84.23274 10.20150, -84.22997 ...
10275  POLYGON ((-84.66808 10.64918, -84.68993 10.642...
...                                                  ...
10347  POLYGON ((-84.18840 9.97058, -84.17687 9.96759...
10348  POLYGON ((-83.99301 9.47771, -83.99482 9.46596...
10349  POLYGON ((-84.06247 9.97429, -84.06168 9.96711...
10350  POLYGON ((-84.40481 9.92153, -84.40639 9.91279...
10351  POLYGON ((-83.94253 10.14967, -83.93382 10.128...

[81 rows x 15 columns]
47 CIV Cote d'Ivoire
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
48 HRV Croatia
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
35967 35,968.00      14551  Administrative unit not available       1000
35968 35,969.00      14552  Administrative unit not available       1000
35969 35,970.00      14553  Administrative unit not available       1000
35970 35,971.00      14554  Administrative unit not available       1000
35971 35,972.00      14555  Administrative unit not available       1000
35972 35,973.00      14556  Administrative unit not available       1000
35973 35,974.00      14557  Administrative unit not available       1000
35974 35,975.00      14558  Administrative unit not available       1000
35975 35,976.00      14559  Administrative unit not available       1000
35976 35,977.00      14560  Administrative unit not available       1000
35977 35,978.00      14561  Administrative unit not available       1000
35978 35,979.00      14562  Administrative unit not available       1000
35979 35,980.00      14563  Administrative unit not available       1000
35980 35,981.00      14564  Administrative unit not available       1000
35981 35,982.00      14565  Administrative unit not available       1000
35982 35,983.00      14566  Administrative unit not available       1000
35983 35,984.00      14567  Administrative unit not available       1000
35984 35,985.00      14568  Administrative unit not available       1000
35985 35,986.00      14569  Administrative unit not available       1000
35986 35,987.00      14570  Administrative unit not available       1000
35987 35,988.00      14571  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE             ADM1_NAME        STATUS DISP_AREA  \
35967       3000        988     Bjelovar-bilogora  Member State        NO
35968       3000        989     Dubrovnik-neretva  Member State        NO
35969       3000        990           Grad Zagreb  Member State        NO
35970       3000        991                 Istra  Member State        NO
35971       3000        992              Karlovac  Member State        NO
35972       3000        993   Koprivnica-krizevci  Member State        NO
35973       3000        994       Krapina-zagorje  Member State        NO
35974       3000        995             Lika-senj  Member State        NO
35975       3000        996             Medimurje  Member State        NO
35976       3000        997        Osijek-baranja  Member State        NO
35977       3000        998      Pozega-slavonija  Member State        NO
35978       3000        999  Primorje-gorski Kota  Member State        NO
35979       3000       1000               Sibenik  Member State        NO
35980       3000       1001       Sisak-moslavina  Member State        NO
35981       3000       1002  Slavonski Brod-posav  Member State        NO
35982       3000       1003       Split-dalmatija  Member State        NO
35983       3000       1004              Varazdin  Member State        NO
35984       3000       1005  Virovitica-podravina  Member State        NO
35985       3000       1006        Vukovar-srijem  Member State        NO
35986       3000       1007            Zadar-knin  Member State        NO
35987       3000       1008                Zagreb  Member State        NO

       ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
35967         62   Croatia        3.33        3.33        0.30
35968         62   Croatia        9.68        9.68        0.20
35969         62   Croatia        1.44        1.44        0.08
35970         62   Croatia        4.52        4.52        0.33
35971         62   Croatia        4.10        4.10        0.42
35972         62   Croatia        3.08        3.08        0.21
35973         62   Croatia        1.93        1.93        0.14
35974         62   Croatia        4.24        4.24        0.59
35975         62   Croatia        1.63        1.63        0.09
35976         62   Croatia        4.99        4.99        0.47
35977         62   Croatia        3.18        3.18        0.21
35978         62   Croatia       10.31       10.31        0.42
35979         62   Croatia        8.22        8.22        0.34
35980         62   Croatia        4.71        4.71        0.51
35981         62   Croatia        3.99        3.99        0.23
35982         62   Croatia       10.54       10.54        0.51
35983         62   Croatia        2.37        2.37        0.14
35984         62   Croatia        2.90        2.90        0.24
35985         62   Croatia        3.77        3.77        0.28
35986         62   Croatia       12.95       12.95        0.41
35987         62   Croatia        5.44        5.44        0.34

                                                geometry
35967  POLYGON ((17.12330 45.87750, 17.18400 45.85620...
35968  MULTIPOLYGON (((16.25840 42.39972, 16.26150 42...
35969  POLYGON ((15.94910 45.90510, 16.04590 45.93570...
35970  MULTIPOLYGON (((13.79694 44.90172, 13.78837 44...
35971  POLYGON ((15.91520 45.48130, 15.88840 45.50300...
35972  POLYGON ((16.88534 46.30888, 16.88822 46.30046...
35973  POLYGON ((16.25530 46.06790, 16.21980 46.05010...
35974  MULTIPOLYGON (((14.87165 44.46894, 14.86923 44...
35975  POLYGON ((16.37414 46.52870, 16.38234 46.52787...
35976  POLYGON ((19.02609 45.48945, 19.02534 45.48982...
35977  POLYGON ((17.89810 45.48220, 17.90860 45.46400...
35978  MULTIPOLYGON (((14.56194 44.45588, 14.57363 44...
35979  MULTIPOLYGON (((15.60551 43.68005, 15.61859 43...
35980  POLYGON ((16.93830 45.48260, 16.96440 45.45540...
35981  POLYGON ((18.07790 45.26800, 18.08860 45.25810...
35982  MULTIPOLYGON (((16.01048 42.99401, 16.01445 42...
35983  POLYGON ((16.28271 46.37373, 16.33540 46.34980...
35984  POLYGON ((17.65611 45.85407, 17.65852 45.84696...
35985  POLYGON ((19.00030 45.43648, 19.00242 45.43569...
35986  MULTIPOLYGON (((15.52541 43.83122, 15.52219 43...
35987  POLYGON ((16.33560 46.02680, 16.35610 46.01380...
49 CUB Cuba
      OBJECTID  ADM2_CODE               ADM2_NAME  STR2_YEAR  EXP2_YEAR  \

      OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
6989  6,990.00      15283  Administrative unit not available       1000
6990  6,991.00      15285  Administrative unit not available       1000
6991  6,992.00      15286  Administrative unit not available       1000
6992  6,993.00      15287  Administrative unit not available       1000
6993  6,994.00      15288  Administrative unit not available       1000
6994  6,995.00      15289  Administrative unit not available       1000
6995  6,996.00      15290  Administrative unit not available       1000
6996  6,997.00      15291  Administrative unit not available       1000
6997  6,998.00      15292  Administrative unit not available       1000
6998  6,999.00      15284  Administrative unit not available       1000

      EXP2_YEAR  ADM1_CODE    ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
6989       3000       1098   St. Andrew  Member State        NO         71
6990       3000       1100   St. George  Member State        NO         71
6991       3000       1101     St. John  Member State        NO         71
6992       3000       1102   St. Joseph  Member State        NO         71
6993       3000       1103     St. Luke  Member State        NO         71
6994       3000       1104     St. Mark  Member State        NO         71
6995       3000       1105  St. Patrick  Member State        NO         71
6996       3000       1106     St. Paul  Member State        NO         71
6997       3000       1107    St. Peter  Member State        NO         71
6998       3000       1099    St. David  Member State        NO         71

     ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
6989  Dominica        0.75        0.75        0.02
6990  Dominica        0.25        0.25        0.00
6991  Dominica        0.36        0.36        0.00
6992  Dominica        0.41        0.41        0.01
6993  Dominica        0.11        0.11        0.00
6994  Dominica        0.09        0.09        0.00
6995  Dominica        0.52        0.52        0.01
6996  Dominica        0.29        0.29        0.00
6997  Dominica        0.22        0.22        0.00
6998  Dominica        0.78        0.78        0.02

                                               geometry
6989  MULTIPOLYGON (((-61.30253 15.57229, -61.30241 ...
6990  POLYGON ((-61.32167 15.31981, -61.31723 15.309...
6991  POLYGON ((-61.45812 15.63802, -61.45798 15.637...
6992  POLYGON ((-61.34197 15.47552, -61.34184 15.474...
6993  POLYGON ((-61.37359 15.25894, -61.35796 15.256...
6994  POLYGON ((-61.34739 15.21860, -61.34407 15.209...
6995  MULTIPOLYGON (((-61.33469 15.21088, -61.33458 ...
6996  POLYGON ((-61.33343 15.33698, -61.38938 15.316...
6997  MULTIPOLYGON (((-61.47410 15.52499, -61.47419 ...
6998  MULTIPOLYGON (((-61.25069 15.36248, -61.25060 ...
56 DOM Dominican Republic
      OBJECTID  ADM2_CODE             ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
6681  6,682.00      36859                  Azua       1000       3000
6682  6,683.00      36860       Esteban¡a  (DM)       1000       3000
6683  6,684.00      36861        Guayabal  (DM)       1000       3000
6684  6,685.00      36862     Las Charcas  (DM)       1000       3000
6685  6,686.00      36863  Las Yayas de Viajama       1000       3000
...        ...        ...                   ...        ...        ...
6838  6,839.00      36982         Rancho Arriba       1000       3000
6839  6,840.00      36983          Sabana Larga       1000       3000
6840  6,841.00      36984      San Jos‚ de Ocoa       1000       3000
6841  6,842.00      36891     Distrito Nacional       1000       3000
6842  6,843.00      36973               S nchez       1000       3000

      ADM1_CODE          ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
6681       1108               Azua  Member State        NO         72
6682       1108               Azua  Member State        NO         72
6683       1108               Azua  Member State        NO         72
6684       1108               Azua  Member State        NO         72
6685       1108               Azua  Member State        NO         72
...         ...                ...           ...       ...        ...
6838      36857   San José de Ocoa  Member State        NO         72
6839      36857   San José de Ocoa  Member State        NO         72
6840      36857   San José de Ocoa  Member State        NO         72
6841      36858  Distrito Nacional  Member State        NO         72
6842       1127             Samana  Member State        NO         72

               ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
6681  Dominican Republic        1.65        1.65        0.04
6682  Dominican Republic        0.99        0.99        0.02
6683  Dominican Republic        0.78        0.78        0.02
6684  Dominican Republic        0.73        0.73        0.02
6685  Dominican Republic        1.42        1.42        0.03
...                  ...         ...         ...         ...
6838  Dominican Republic        0.75        0.75        0.02
6839  Dominican Republic        0.69        0.69        0.02
6840  Dominican Republic        1.65        1.65        0.04
6841  Dominican Republic        0.49        0.49        0.01
6842  Dominican Republic        1.57        1.57        0.03

                                               geometry
6681  MULTIPOLYGON (((-70.93837 18.45096, -70.93746 ...
6682  POLYGON ((-70.66435 18.65982, -70.66435 18.659...
6683  POLYGON ((-70.68432 18.68556, -70.68394 18.685...
6684  POLYGON ((-70.50222 18.46112, -70.50346 18.456...
6685  POLYGON ((-71.07301 18.67016, -71.07202 18.669...
...                                                 ...
6838  POLYGON ((-70.41163 18.76147, -70.41108 18.761...
6839  POLYGON ((-70.50624 18.68235, -70.50882 18.678...
6840  POLYGON ((-70.62589 18.68559, -70.62664 18.685...
6841  MULTIPOLYGON (((-69.88029 18.47533, -69.88036 ...
6842  MULTIPOLYGON (((-69.60768 19.08129, -69.60761 ...

[162 rows x 15 columns]
57 ECU Ecuador
       OBJECTID  ADM2_CODE                 ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
20565 20,566.00      15320                 Chordeleg       1992       3000
20566 20,567.00      15321                    Cuenca       1000       3000
20567 20,568.00      15322                    El Pan       1992       3000
20568 20,569.00      15323                     Giron       1000       3000
20569 20,570.00      15324                  Gualaceo       1992       3000
...         ...        ...                       ...        ...        ...
20784 20,785.00      22034  San Miguel de los Bancos       1992       3000
20785 20,786.00      15424               La Libertad       1992       3000
20786 20,787.00      15433                   Salinas       1992       3000
20787 20,788.00      15435               Santa Elena       1000       3000
20788 20,789.00      15514             Santo Domingo       1000       3000

       ADM1_CODE                       ADM1_NAME        STATUS DISP_AREA  \
20565       1135                           Azuay  Member State        NO
20566       1135                           Azuay  Member State        NO
20567       1135                           Azuay  Member State        NO
20568       1135                           Azuay  Member State        NO
20569       1135                           Azuay  Member State        NO
...          ...                             ...           ...       ...
20784      22006                       Pichincha  Member State        NO
20785      22007                     Santa Elena  Member State        NO
20786      22007                     Santa Elena  Member State        NO
20787      22007                     Santa Elena  Member State        NO
20788      22008  Santo Domingo de los Tsachilas  Member State        NO

       ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
20565         73   Ecuador        0.53        0.53        0.01
20566         73   Ecuador        3.22        3.22        0.26
20567         73   Ecuador        0.59        0.59        0.01
20568         73   Ecuador        1.15        1.15        0.03
20569         73   Ecuador        1.29        1.29        0.03
...          ...       ...         ...         ...         ...
20784         73   Ecuador        2.05        2.05        0.07
20785         73   Ecuador        0.24        0.24        0.00
20786         73   Ecuador        0.57        0.57        0.01
20787         73   Ecuador        3.40        3.40        0.29
20788         73   Ecuador        3.74        3.74        0.28

                                                geometry
20565  POLYGON ((-78.77811 -2.90561, -78.77799 -2.905...
20566  POLYGON ((-79.39734 -2.49713, -79.39698 -2.497...
20567  POLYGON ((-78.64574 -2.74128, -78.64570 -2.741...
20568  POLYGON ((-79.22802 -3.06530, -79.22774 -3.065...
20569  POLYGON ((-78.69723 -2.80718, -78.69630 -2.807...
...                                                  ...
20784  POLYGON ((-78.93264 0.09571, -78.93274 0.09534...
20785  POLYGON ((-80.88619 -2.21317, -80.88590 -2.213...
20786  POLYGON ((-80.99250 -2.18391, -80.99199 -2.184...
20787  POLYGON ((-80.74603 -1.66906, -80.74576 -1.669...
20788  POLYGON ((-79.28343 0.01623, -79.28229 0.01498...

[224 rows x 15 columns]
58 EGY Egypt, Arab Rep.
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
59 SLV El Salvador
       OBJECTID  ADM2_CODE         ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
10009 10,010.00      15604  Nueva Concepcion       1000       3000       1186
10010 10,011.00      15587     Agua Caliente       1000       3000       1186
10011 10,012.00      15599          La Palma       1000       3000       1186
10012 10,013.00      15613       San Ignacio       1000       3000       1186
10013 10,014.00      15592            Citala       1000       3000       1186
...         ...        ...               ...        ...        ...        ...
10266 10,267.00      15644       La Libertad       1000       3000       1188
10267 10,268.00      15586          Victoria       1000       3000       1185
10268 10,269.00      15598         La Laguna       1000       3000       1186
10269 10,270.00      15687          La Union       1000       3000       1190
10270 10,271.00      15693         San Alejo       1000       3000       1190

          ADM1_NAME        STATUS DISP_AREA  ADM0_CODE    ADM0_NAME  \
10009  Chalatenango  Member State        NO         75  El Salvador
10010  Chalatenango  Member State        NO         75  El Salvador
10011  Chalatenango  Member State        NO         75  El Salvador
10012  Chalatenango  Member State        NO         75  El Salvador
10013  Chalatenango  Member State        NO         75  El Salvador
...             ...           ...       ...        ...          ...
10266   La Libertad  Member State        NO         75  El Salvador
10267       Cabanas  Member State        NO         75  El Salvador
10268  Chalatenango  Member State        NO         75  El Salvador
10269      La Union  Member State        NO         75  El Salvador
10270      La Union  Member State        NO         75  El Salvador

       Shape_Leng  Shape_Le_1  Shape_Area  \
10009        1.02        1.02        0.03
10010        0.54        0.54        0.01
10011        0.69        0.69        0.01
10012        0.45        0.45        0.00
10013        0.51        0.51        0.01
...           ...         ...         ...
10266        0.90        0.90        0.01
10267        0.56        0.56        0.01
10268        0.32        0.32        0.00
10269        1.32        1.32        0.01
10270        0.86        0.86        0.02

                                                geometry
10009  POLYGON ((-89.28916 14.24249, -89.28889 14.241...
10010  POLYGON ((-89.19118 14.25554, -89.18779 14.248...
10011  POLYGON ((-89.08274 14.35528, -89.08324 14.352...
10012  POLYGON ((-89.08274 14.35528, -89.08275 14.355...
10013  POLYGON ((-89.16689 14.36431, -89.16848 14.363...
...                                                  ...
10266  POLYGON ((-89.34096 13.53891, -89.34097 13.538...
10267  POLYGON ((-88.56854 13.97982, -88.57110 13.979...
10268  POLYGON ((-88.93068 14.20409, -88.93316 14.203...
10269  MULTIPOLYGON (((-87.73935 13.28891, -87.73883 ...
10270  POLYGON ((-87.88618 13.51911, -87.88564 13.519...

[262 rows x 15 columns]
60 GNQ Equatorial Guinea
      OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
1363  1,364.00      15828  Administrative unit not available       1000
1364  1,365.00      15829  Administrative unit not available       1000
1365  1,366.00      15830  Administrative unit not available       1000
1366  1,367.00      15831  Administrative unit not available       1000
1367  1,368.00      15832  Administrative unit not available       1000
1368  1,369.00      15833  Administrative unit not available       1000
1369  1,370.00      15834  Administrative unit not available       1000

      EXP2_YEAR  ADM1_CODE    ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
1363       3000       1198      Annobon  Member State        NO         76
1364       3000       1199  Bioko Norte  Member State        NO         76
1365       3000       1200    Bioko Sur  Member State        NO         76
1366       3000       1201   Centro Sur  Member State        NO         76
1367       3000       1202      Kientem  Member State        NO         76
1368       3000       1203      Litoral  Member State        NO         76
1369       3000       1204     Welenzas  Member State        NO         76

              ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
1363  Equatorial Guinea        0.21        0.21        0.00
1364  Equatorial Guinea        1.13        1.13        0.05
1365  Equatorial Guinea        1.59        1.59        0.11
1366  Equatorial Guinea        4.92        4.92        0.68
1367  Equatorial Guinea        2.82        2.82        0.26
1368  Equatorial Guinea        5.37        5.37        0.59
1369  Equatorial Guinea        3.91        3.91        0.50

                                               geometry
1363  POLYGON ((5.63372 -1.40429, 5.63449 -1.40442, ...
1364  MULTIPOLYGON (((8.90891 3.76049, 8.90963 3.759...
1365  POLYGON ((8.85669 3.53459, 8.85632 3.53387, 8....
1366  POLYGON ((10.40434 2.17293, 10.40159 2.14312, ...
1367  POLYGON ((11.33400 1.75837, 11.32347 1.76107, ...
1368  MULTIPOLYGON (((9.30626 0.87706, 9.30524 0.876...
1369  POLYGON ((11.33400 1.75837, 11.33360 1.74805, ...
61 ERI Eritrea
     OBJECTID  ADM2_CODE       ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
150    151.00      15835  Adi Tekeliezan       1000       3000       1205
151    152.00      15836           Asmat       1000       3000       1205
152    153.00      15837        Elabered       1000       3000       1205
153    154.00      15838           Geleb       1000       3000       1205
154    155.00      15839          Habero       1000       3000       1205
..        ...        ...             ...        ...        ...        ...
203    204.00      15889         Massawa       1000       3000       1211
204    205.00      15890           Nakfa       1000       3000       1211
205    206.00      15891         Quarura       1000       3000       1211
206    207.00      15892            Sheb       1000       3000       1211
207    208.00      15861     Central Srs       1000       3000       1208

               ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
150               Anseba  Member State        NO         77   Eritrea
151               Anseba  Member State        NO         77   Eritrea
152               Anseba  Member State        NO         77   Eritrea
153               Anseba  Member State        NO         77   Eritrea
154               Anseba  Member State        NO         77   Eritrea
..                   ...           ...       ...        ...       ...
203  Semenawi Keih Bahri  Member State        NO         77   Eritrea
204  Semenawi Keih Bahri  Member State        NO         77   Eritrea
205  Semenawi Keih Bahri  Member State        NO         77   Eritrea
206  Semenawi Keih Bahri  Member State        NO         77   Eritrea
207  Debubawi Keih Bahri  Member State        NO         77   Eritrea

     Shape_Leng  Shape_Le_1  Shape_Area  \
150        0.85        0.85        0.03
151        2.43        2.43        0.24
152        1.26        1.26        0.05
153        1.05        1.05        0.04
154        2.37        2.37        0.13
..          ...         ...         ...
203        1.14        1.14        0.03
204        2.62        2.62        0.26
205        3.58        3.58        0.57
206        2.23        2.23        0.16
207        3.15        3.15        0.35

                                              geometry
150  POLYGON ((38.86334 15.69571, 38.86359 15.69523...
151  POLYGON ((38.04707 16.65514, 38.04746 16.65448...
152  POLYGON ((38.59676 15.80109, 38.59570 15.79952...
153  POLYGON ((38.86334 15.69571, 38.86248 15.69563...
154  POLYGON ((38.42772 16.38601, 38.42833 16.38617...
..                                                 ...
203  MULTIPOLYGON (((39.48033 15.59564, 39.48086 15...
204  POLYGON ((38.58455 16.76704, 38.58446 16.76628...
205  MULTIPOLYGON (((38.61778 17.92374, 38.61751 17...
206  POLYGON ((39.25909 16.03167, 39.26326 16.03163...
207  MULTIPOLYGON (((41.94548 13.88799, 41.94599 13...

[58 rows x 15 columns]
62 EST Estonia
       OBJECTID  ADM2_CODE         ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
35033 35,034.00      15893     Aegviidu vald       1000       3000       1212
35034 35,035.00      15895        Harku vald       1000       3000       1212
35035 35,036.00      15896    Jõelähtme vald       1000       3000       1212
35036 35,037.00      15899        Keila linn       1000       3000       1212
35037 35,038.00      15898        Keila vald       1000       3000       1212
...         ...        ...               ...        ...        ...        ...
35258 35,259.00     149738       Räpina vald       2002       3000       1220
35259 35,260.00     149739       Kohila vald       2002       3000       1221
35260 35,261.00     149740     Märjamaa vald       2002       3000       1221
35261 35,262.00     149741        Rapla vald       2002       3000       1221
35262 35,263.00     149742  Suure-Jaani vald       2005       3000       1225

              ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
35033     Harju maakond  Member State        NO         78   Estonia
35034     Harju maakond  Member State        NO         78   Estonia
35035     Harju maakond  Member State        NO         78   Estonia
35036     Harju maakond  Member State        NO         78   Estonia
35037     Harju maakond  Member State        NO         78   Estonia
...                 ...           ...       ...        ...       ...
35258     Põlva maakond  Member State        NO         78   Estonia
35259     Rapla maakond  Member State        NO         78   Estonia
35260     Rapla maakond  Member State        NO         78   Estonia
35261     Rapla maakond  Member State        NO         78   Estonia
35262  Viljandi maakond  Member State        NO         78   Estonia

       Shape_Leng  Shape_Le_1  Shape_Area  \
35033        0.22        0.22        0.00
35034        1.32        1.32        0.03
35035        2.19        2.19        0.03
35036        0.32        0.32        0.00
35037        1.48        1.48        0.03
...           ...         ...         ...
35258        1.40        1.40        0.04
35259        1.23        1.23        0.04
35260        2.74        2.74        0.14
35261        1.30        1.30        0.04
35262        2.45        2.45        0.11

                                                geometry
35033  POLYGON ((25.64940 59.27252, 25.65155 59.27143...
35034  MULTIPOLYGON (((24.61842 59.37422, 24.61760 59...

     OBJECTID  ADM2_CODE      ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
208    209.00     149277      Region 14       2007       3000       1227
209    210.00     149278       Awi/Agew       2007       3000       1229
210    211.00     149279        No Name       2007       3000       1229
211    212.00     149280   North Gonder       2007       3000       1229
212    213.00     149281    South Wollo       2007       3000       1229
..        ...        ...            ...        ...        ...        ...
278    279.00      40848           Siti       1000       3000      47679
279    280.00      40850        Central       1000       3000       1237
280    281.00      40851      Eastern\n       1000       3000       1237
281    282.00      47710  North Western       1000       3000       1237
282    283.00      47711        Western       1000       3000       1237

       ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
208  Addis Ababa  Member State        NO         79  Ethiopia        1.07
209       Amhara  Member State        NO         79  Ethiopia        7.68
210       Amhara  Member State        NO         79  Ethiopia        3.49
211       Amhara  Member State        NO         79  Ethiopia       14.81
212       Amhara  Member State        NO         79  Ethiopia        7.24
..           ...           ...       ...        ...       ...         ...
278       Somali  Member State        NO         79  Ethiopia        8.07
279       Tigray  Member State        NO         79  Ethiopia        6.12
280       Tigray  Member State        NO         79  Ethiopia        5.03
281       Tigray  Member State        NO         79  Ethiopia        7.01
282       Tigray  Member State        NO         79  Ethiopia        5.16

     Shape_Le_1  Shape_Area                                           geometry
208        1.07        0.04  MULTIPOLYGON (((38.70186 8.92537, 38.70185 8.9...
209        7.68        0.74  POLYGON ((36.34735 12.05205, 36.34768 12.05089...
210        3.49        0.26  POLYGON ((37.47740 12.29739, 37.47875 12.29722...
211       14.81        3.57  POLYGON ((36.47877 13.72192, 36.47821 13.72102...
212        7.24        1.42  POLYGON ((39.55328 11.70639, 39.55637 11.70545...
..          ...         ...                                                ...
278        8.07        2.50  POLYGON ((42.63944 11.09452, 42.64408 11.09060...
279        6.12        0.88  POLYGON ((39.16881 14.64889, 39.15800 14.63444...
280        5.03        0.51  MULTIPOLYGON (((39.83761 13.85406, 39.83716 13...
281        7.01        0.99  MULTIPOLYGON (((37.38187 14.34227, 37.38260 14...
282        5.16        1.11  POLYGON ((37.31604 14.43368, 37.31928 14.43116...

[75 rows x 15 columns]
65 FRO Faroe Islands
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
66 FJI Fiji
       OBJECTID  ADM2_CODE         ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
38183 38,184.00      40191         Naitasiri       1000       3000      40187
38184 38,185.00      40192            Namosi       1000       3000      40187
38185 38,186.00      40193              Rewa       1000       3000      40187
38186 38,187.00      40194             Serua       1000       3000      40187
38187 38,188.00      40195           Tailevu       1000       3000      40187
38188 38,189.00      40196            Kadavu       1000       3000      40188
38189 38,190.00      40197               Lau       1000       3000      40188
38190 38,191.00      40198         Lomaiviti       1000       3000      40188
38191 38,192.00      40199            Rotuma       1000       3000      40188
38192 38,193.00      40200               Bua       1000       3000      40189
38193 38,194.00      40201        Cakaudrove       1000       3000      40189
38194 38,195.00      40202           Macuata       1000       3000      40189
38195 38,196.00      40203                Ba       1000       3000      40190
38196 38,197.00      40204  Nadroga & Navosa       1000       3000      40190
38197 38,198.00      40205                Ra       1000       3000      40190

      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
38183   Central  Member State        NO         83      Fiji        2.93
38184   Central  Member State        NO         83      Fiji        1.70
38185   Central  Member State        NO         83      Fiji        1.99
38186   Central  Member State        NO         83      Fiji        1.86
38187   Central  Member State        NO         83      Fiji        3.00
38188   Eastern  Member State        NO         83      Fiji        2.78
38189   Eastern  Member State        NO         83      Fiji        5.38
38190   Eastern  Member State        NO         83      Fiji        2.37
38191   Eastern  Member State        NO         83      Fiji        0.31
38192  Northern  Member State        NO         83      Fiji        3.54
38193  Northern  Member State        NO         83      Fiji        9.04
38194  Northern  Member State        NO         83      Fiji        6.16
38195   Western  Member State        NO         83      Fiji        5.85
38196   Western  Member State        NO         83      Fiji        4.62
38197   Western  Member State        NO         83      Fiji        2.41

       Shape_Le_1  Shape_Area  \
38183        2.93        0.14
38184        1.70        0.05
38185        1.99        0.02
38186        1.86        0.07
38187        3.00        0.08
38188        2.78        0.04
38189        5.38        0.04
38190        2.37        0.03
38191        0.31        0.00
38192        3.54        0.12
38193        9.04        0.23
38194        6.16        0.18
38195        5.85        0.24
38196        4.62        0.20
38197        2.41        0.11

                                                geometry
38183  POLYGON ((178.27512 -17.67528, 178.27531 -17.6...
38184  POLYGON ((178.00986 -17.91828, 178.01070 -17.9...
38185  MULTIPOLYGON (((178.17114 -18.40683, 178.16705...
38186  MULTIPOLYGON (((178.00258 -18.38981, 177.99849...
38187  MULTIPOLYGON (((178.61926 -17.94105, 178.61447...
38188  MULTIPOLYGON (((178.11627 -19.17794, 178.11386...
38189  MULTIPOLYGON (((-178.68997 -20.65900, -178.694...
38190  MULTIPOLYGON (((179.28381 -17.94338, 179.29175...
38191  POLYGON ((177.09566 -12.52327, 177.07669 -12.5...
38192  MULTIPOLYGON (((179.11337 -17.10799, 179.10400...
38193  MULTIPOLYGON (((-179.46996 -17.25852, -179.470...
38194  MULTIPOLYGON (((179.07477 -16.43077, 179.07123...
38195  MULTIPOLYGON (((177.37059 -17.82236, 177.36784...
38196  MULTIPOLYGON (((177.66438 -18.60177, 177.65715...
38197  MULTIPOLYGON (((178.18950 -17.31616, 178.19333...
67 FIN Finland
       OBJECTID  ADM2_CODE              ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
35439 35,440.00      16218                 Aaland       1000       3000
35440 35,441.00      16219          North Karelia       1000       3000
35441 35,442.00      16220          Northern Savo       1000       3000
35442 35,443.00      16221          Southern Savo       1000       3000
35443 35,444.00      16222                Lapland       1000       3000
35444 35,445.00      16223                 Kainuu       1000       3000
35445 35,446.00      16224  Northern Ostrobothnia       1000       3000
35446 35,447.00      16225                   Hame       1000       3000
35447 35,448.00      16226            Ita-uusimaa       1000       3000
35448 35,449.00      16227            Kymenlaakso       1000       3000
35449 35,450.00      16228            Paijat-hame       1000       3000
35450 35,451.00      16229          South Karelia       1000       3000
35451 35,452.00      16230                Uusimaa       1000       3000
35452 35,453.00      16231        Central Finland       1000       3000
35453 35,454.00      16232   Central Ostrobothnia       1000       3000
35454 35,455.00      16233           Ostrobothnia       1000       3000
35455 35,456.00      16234              Satakunta       1000       3000
35456 35,457.00      16235     South Ostrobothnia       1000       3000
35457 35,458.00      16236     South-west Finland       1000       3000
35458 35,459.00      16237         Tampere Region       1000       3000

       ADM1_CODE         ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
35439       1242            Aaland  Member State        NO         84
35440       1243   Eastern Finland  Member State        NO         84
35441       1243   Eastern Finland  Member State        NO         84
35442       1243   Eastern Finland  Member State        NO         84
35443       1244           Lapland  Member State        NO         84
35444       1245              Oulu  Member State        NO         84
35445       1245              Oulu  Member State        NO         84
35446       1246  Southern Finland  Member State        NO         84
35447       1246  Southern Finland  Member State        NO         84
35448       1246  Southern Finland  Member State        NO         84
35449       1246  Southern Finland  Member State        NO         84
35450       1246  Southern Finland  Member State        NO         84
35451       1246  Southern Finland  Member State        NO         84
35452       1247   Western Finland  Member State        NO         84
35453       1247   Western Finland  Member State        NO         84
35454       1247   Western Finland  Member State        NO         84
35455       1247   Western Finland  Member State        NO         84
35456       1247   Western Finland  Member State        NO         84
35457       1247   Western Finland  Member State        NO         84
35458       1247   Western Finland  Member State        NO         84

      ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
35439   Finland       19.68       19.68        0.20
35440   Finland       10.75       10.75        3.79
35441   Finland       10.82       10.82        3.56
35442   Finland       12.09       12.09        3.29
35443   Finland       33.94       33.94       20.96
35444   Finland       12.44       12.44        4.56
35445   Finland       25.87       25.87        7.06
35446   Finland        6.79        6.79        0.94
35447   Finland       11.19       11.19        0.46
35448   Finland       10.74       10.74        0.92
35449   Finland        6.51        6.51        1.05
35450   Finland        8.38        8.38        1.20
35451   Finland       17.71       17.71        1.09
35452   Finland       12.63       12.63        3.39
35453   Finland        8.03        8.03        0.99
35454   Finland       29.51       29.51        1.34
35455   Finland       13.93       13.93        1.47
35456   Finland        9.72        9.72        2.46
35457   Finland       48.44       48.44        1.70
35458   Finland        9.88        9.88        2.50

                                                geometry
35439  MULTIPOLYGON (((20.97238 59.92908, 20.95865 59...
35440  POLYGON ((29.98095 63.75448, 29.98235 63.75231...
35441  POLYGON ((28.37458 63.75814, 28.37867 63.75389...
35442  POLYGON ((29.59120 61.73322, 29.58287 61.73322...
35443  MULTIPOLYGON (((24.97577 65.60342, 24.97900 65...
35444  POLYGON ((29.76539 65.49502, 29.76037 65.48343...
35445  MULTIPOLYGON (((23.68343 64.17709, 23.68172 64...
35446  POLYGON ((25.11638 60.81659, 25.12659 60.80517...
35447  MULTIPOLYGON (((25.44674 60.17076, 25.45749 60...
35448  MULTIPOLYGON (((27.32392 60.28280, 27.31278 60...
35449  POLYGON ((26.32467 61.60823, 26.32937 61.57729...
35450  POLYGON ((30.15392 61.85429, 30.14997 61.85168...
35451  MULTIPOLYGON (((22.96127 59.76882, 22.95158 59...
35452  POLYGON ((26.14967 63.45816, 26.17854 63.44902...
35453  MULTIPOLYGON (((22.84181 63.89720, 22.84932 63...
35454  MULTIPOLYGON (((21.29783 62.08204, 21.29626 62...
35455  MULTIPOLYGON (((21.40442 61.18086, 21.41006 61...
35456  POLYGON ((23.71644 63.38316, 23.72170 63.36568...
35457  MULTIPOLYGON (((22.39605 59.82368, 22.40307 59...
35458  POLYGON ((24.02476 62.36653, 24.02936 62.33571...
68 FRA France
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
663      664.00      19545  Administrative unit not available       1000
664      665.00      25273  Administrative unit not available       1000
665      666.00      25274  Administrative unit not available       1000
6617   6,618.00      61301  Administrative unit not available       1000
6618   6,619.00      61302  Administrative unit not available       1000
...         ...        ...                                ...        ...
37359 37,360.00      16330                              Isere       1000
37360 37,361.00      16331                              Loire       1000
37361 37,362.00      16332                              Rhone       1000
37362 37,363.00      16333                             Savoie       1000
38224 38,225.00      16736  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE                          ADM1_NAME        STATUS  \
663         3000       2027  Administrative unit not available  FR Territory
664         3000       2590             Arrondissement_du_vent  FR Territory
665         3000       2591       Arrondissement_souse_le_vent  FR Territory
6617        3000      61297                     Fort-de-France  FR Territory
6618        3000      61298                         La Trinite  FR Territory
...          ...        ...                                ...           ...
37359       3000       1270                        Rhone-Alpes  Member State
37360       3000       1270                        Rhone-Alpes  Member State
37361       3000       1270                        Rhone-Alpes  Member State
37362       3000       1270                        Rhone-Alpes  Member State
38224       3000       1358  Administrative unit not available  FR Territory

      DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
663          NO         85    France        2.40        2.40        0.03
664          NO         85    France        1.52        1.52        0.08
665          NO         85    France        2.24        2.24        0.14
6617         NO         85    France        0.83        0.83        0.01
6618         NO         85    France        1.87        1.87        0.03
...         ...        ...       ...         ...         ...         ...
37359        NO         85    France        6.66        6.66        0.90
37360        NO         85    France        5.62        5.62        0.56
37361        NO         85    France        4.41        4.41        0.38
37362        NO         85    France        5.51        5.51        0.72
38224        NO         85    France        7.01        5.65        0.14

                                                geometry
663    MULTIPOLYGON (((45.13795 -13.00506, 45.13774 -...
664    MULTIPOLYGON (((55.82732 -21.14869, 55.82730 -...
665    MULTIPOLYGON (((55.56850 -21.37737, 55.56841 -...
6617   MULTIPOLYGON (((-61.02070 14.60983, -61.02066 ...
6618   MULTIPOLYGON (((-60.88308 14.67114, -60.88288 ...
...                                                  ...
37359  POLYGON ((5.61653 45.61860, 5.61537 45.61532, ...
37360  POLYGON ((4.38092 46.22363, 4.39959 46.22348, ...
37361  POLYGON ((4.77305 46.18092, 4.77515 46.17588, ...
37362  POLYGON ((6.79332 45.78426, 6.79097 45.77126, ...
38224  MULTIPOLYGON (((-61.60685 15.83419, -61.60688 ...

[125 rows x 15 columns]
69 PYF French Polynesia
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
70 GAB Gabon
      OBJECTID  ADM2_CODE         ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
1509  1,510.00      16357              Komo       1000       3000       1275
1510  1,511.00      16358       Komo-Mondah       1000       3000       1275
1511  1,512.00      16359        Libreville       1000       3000       1275
1512  1,513.00      16360              Noya       1000       3000       1275
1513  1,514.00      16361      Bayi-Brikolo       1000       3000       1276
1514  1,515.00      16362             Djoue       1000       3000       1276
1515  1,516.00      16363    Djouori-Agnili       1000       3000       1276
1516  1,517.00      16364     Lebombi-Leyou       1000       3000       1276
1517  1,518.00      16365     Lekabi-Lewolo       1000       3000       1276
1518  1,519.00      16366            Lekoko       1000       3000       1276
1519  1,520.00      16367     Lekoni-Lekori       1000       3000       1276
1520  1,521.00      16368     Ogooue-Letili       1000       3000       1276
1521  1,522.00      16369             Passa       1000       3000       1276
1522  1,523.00      16370          Plateaux       1000       3000       1276
1523  1,524.00      16371      Sebe-Brikolo       1000       3000       1276
1524  1,525.00      16372      Abanga-Bigne       1000       3000       1277
1525  1,526.00      16373    Ogooue et Lacs       1000       3000       1277
1526  1,527.00      16374     Boumi-Louetsi       1000       3000       1278
1527  1,528.00      16375              Dola       1000       3000       1278
1528  1,529.00      16376       Douya-Onoye       1000       3000       1278
1529  1,530.00      16377    Louetsi-Bibaka       1000       3000       1278
1530  1,531.00      16378      Louetsi-Wano       1000       3000       1278
1531  1,532.00      16379         Mougalaba       1000       3000       1278
1532  1,533.00      16380            Ndolou       1000       3000       1278
1533  1,534.00      16381           Ogoulou       1000       3000       1278
1534  1,535.00      16382    Tsamba-Magotsi       1000       3000       1278
1535  1,536.00      16383       Basse-Banio       1000       3000       1279
1536  1,537.00      16384           Douigni       1000       3000       1279
1537  1,538.00      16385          Doutsila       1000       3000       1279
1538  1,539.00      16386       Haute-Banio       1000       3000       1279
1539  1,540.00      16387             Mongo       1000       3000       1279
1540  1,541.00      16388         Mougoutsi       1000       3000       1279
1541  1,542.00      16389            Ivindo       1000       3000       1280
1542  1,543.00      16390              Lope       1000       3000       1280
1543  1,544.00      16391            Mvoung       1000       3000       1280
1544  1,545.00      16392             Zadie       1000       3000       1280
1545  1,546.00      16393   Lolo-Bouenguidi       1000       3000       1281
1546  1,547.00      16394  Lombo-Bouenguidi       1000       3000       1281
1547  1,548.00      16395        Mouloundou       1000       3000       1281
1548  1,549.00      16396      Offoue-Onoye       1000       3000       1281
1549  1,550.00      16397            Bendje       1000       3000       1282
1550  1,551.00      16398          Etimboue       1000       3000       1282
1551  1,552.00      16399           Ndougou       1000       3000       1282
1552  1,553.00      16400         Haut-Komo       1000       3000       1283
1553  1,554.00      16401         Haut-Ntem       1000       3000       1283
1554  1,555.00      16402              Ntem       1000       3000       1283
1555  1,556.00      16403             Okano       1000       3000       1283
1556  1,557.00      16404             Woleu       1000       3000       1283

            ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
1509         Estuaire  Member State        NO         89     Gabon
1510         Estuaire  Member State        NO         89     Gabon
1511         Estuaire  Member State        NO         89     Gabon
1512         Estuaire  Member State        NO         89     Gabon
1513      Haut-Ogooue  Member State        NO         89     Gabon
1514      Haut-Ogooue  Member State        NO         89     Gabon

       OBJECTID  ADM2_CODE                                 ADM2_NAME  \
37234 37,235.00      16526                                  Freiburg
37235 37,236.00      16527                                 Karlsruhe
37236 37,237.00      16528                                 Stuttgart
37237 37,238.00      16529                                 Tuebingen
37238 37,239.00      16530                             Mittelfranken
37239 37,240.00      16531                              Niederbayern
37240 37,241.00      16532                                Oberbayern
37241 37,242.00      16533                               Oberfranken
37242 37,243.00      16534                                 Oberpfalz
37243 37,244.00      16535                                  Schwaben
37244 37,245.00      16536                              Unterfranken
37245 37,246.00      16537  Area without administration at 2nd level
37246 37,247.00      16538  Area without administration at 2nd level
37247 37,248.00      16539  Area without administration at 2nd level
37248 37,249.00      16540  Area without administration at 2nd level
37249 37,250.00      16541                                 Darmstadt
37250 37,251.00      16542                                   Giessen
37251 37,252.00      16543                                    Kassel
37252 37,253.00      16544  Area without administration at 2nd level
37253 37,254.00      16549                                  Arnsberg
37254 37,255.00      16550                                   Detmold
37255 37,256.00      16551                               Duesseldorf
37256 37,257.00      16552                                     Koeln
37257 37,258.00      16553                                  Muenster
37258 37,259.00      16554  Area without administration at 2nd level
37259 37,260.00      16555  Area without administration at 2nd level
37260 37,261.00      16559                                  Chemnitz
37261 37,262.00      16560                                   Dresden
37262 37,263.00      16561                                   Leipzig
37263 37,264.00      16562  Area without administration at 2nd level
37264 37,265.00      16563  Area without administration at 2nd level
37265 37,266.00      40699  Area without administration at 2nd level
37266 37,267.00      40698  Area without administration at 2nd level

       STR2_YEAR  EXP2_YEAR  ADM1_CODE               ADM1_NAME        STATUS  \
37234       1000       3000       1308      Baden-Wuerttemberg  Member State
37235       1000       3000       1308      Baden-Wuerttemberg  Member State
37236       1000       3000       1308      Baden-Wuerttemberg  Member State
37237       1000       3000       1308      Baden-Wuerttemberg  Member State
37238       1000       3000       1309                  Bayern  Member State
37239       1000       3000       1309                  Bayern  Member State
37240       1000       3000       1309                  Bayern  Member State
37241       1000       3000       1309                  Bayern  Member State
37242       1000       3000       1309                  Bayern  Member State
37243       1000       3000       1309                  Bayern  Member State
37244       1000       3000       1309                  Bayern  Member State
37245       1000       3000       1310                  Berlin  Member State
37246       1000       3000       1311             Brandenburg  Member State
37247       1000       3000       1312                  Bremen  Member State
37248       1000       3000       1313                 Hamburg  Member State
37249       1000       3000       1314                  Hessen  Member State
37250       1000       3000       1314                  Hessen  Member State
37251       1000       3000       1314                  Hessen  Member State
37252       1000       3000       1315  Mecklenburg-Vorpommern  Member State
37253       1000       3000       1317     Nordrhein-Westfalen  Member State
37254       1000       3000       1317     Nordrhein-Westfalen  Member State
37255       1000       3000       1317     Nordrhein-Westfalen  Member State
37256       1000       3000       1317     Nordrhein-Westfalen  Member State
37257       1000       3000       1317     Nordrhein-Westfalen  Member State
37258       1000       3000       1318         Rheinland-Pfalz  Member State
37259       1000       3000       1319                Saarland  Member State
37260       1000       3000       1320                 Sachsen  Member State
37261       1000       3000       1320                 Sachsen  Member State
37262       1000       3000       1320                 Sachsen  Member State
37263       1000       3000       1322      Schleswig-Holstein  Member State
37264       1000       3000       1323              Thueringen  Member State
37265       2004       3000       1321          Sachsen-Anhalt  Member State
37266       2005       3000       1316           Niedersachsen  Member State

      DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
37234        NO         93   Germany        7.47        7.47        1.12
37235        NO         93   Germany        6.96        6.96        0.85
37236        NO         93   Germany        7.59        7.59        1.28
37237        NO         93   Germany        6.24        6.24        1.11
37238        NO         93   Germany        5.70        5.70        0.89
37239        NO         93   Germany        6.75        6.75        1.27
37240        NO         93   Germany       10.18       10.18        2.13
37241        NO         93   Germany        6.25        6.25        0.91
37242        NO         93   Germany        6.65        6.65        1.20
37243        NO         93   Germany        8.52        8.52        1.21
37244        NO         93   Germany        6.74        6.74        1.08
37245        NO         93   Germany        2.07        2.07        0.12
37246        NO         93   Germany       14.66       14.66        3.93
37247        NO         93   Germany        1.65        1.65        0.05
37248        NO         93   Germany        2.01        2.01        0.10
37249        NO         93   Germany        7.07        7.07        0.93
37250        NO         93   Germany        4.95        4.95        0.68
37251        NO         93   Germany        8.04        8.04        1.07
37252        NO         93   Germany       24.89       24.89        3.23
37253        NO         93   Germany        6.56        6.56        1.03
37254        NO         93   Germany        5.87        5.87        0.84
37255        NO         93   Germany        4.83        4.83        0.68
37256        NO         93   Germany        6.33        6.33        0.93
37257        NO         93   Germany        6.45        6.45        0.90
37258        NO         93   Germany       10.29       10.29        2.47
37259        NO         93   Germany        3.26        3.26        0.32
37260        NO         93   Germany        5.50        5.50        0.79
37261        NO         93   Germany        6.19        6.19        1.03
37262        NO         93   Germany        3.48        3.48        0.56
37263        NO         93   Germany       17.84       17.84        2.16
37264        NO         93   Germany       10.38       10.38        2.04
37265        NO         93   Germany       10.70       10.70        2.63
37266        NO         93   Germany       25.52       25.52        6.34

                                                geometry
37234  MULTIPOLYGON (((8.72018 47.69629, 8.72092 47.6...
37235  POLYGON ((8.76050 48.52520, 8.76529 48.50642, ...
37236  POLYGON ((10.08664 49.55205, 10.10281 49.52212...
37237  POLYGON ((10.21972 48.52349, 10.23700 48.50584...
37238  POLYGON ((11.54110 49.69081, 11.57426 49.63863...
37239  POLYGON ((12.94524 48.20753, 12.94524 48.20753...
37240  POLYGON ((11.59288 48.95853, 11.60407 48.94609...
37241  POLYGON ((11.87231 50.41111, 11.89683 50.42400...
37242  POLYGON ((13.16521 49.17296, 13.16521 49.17295...
37243  POLYGON ((10.96591 48.86280, 10.99575 48.82951...
37244  POLYGON ((10.69573 50.22719, 10.74695 50.22176...
37245  POLYGON ((13.51312 52.63296, 13.49035 52.61650...
37246  POLYGON ((14.40731 53.33523, 14.41283 53.32692...
37247  MULTIPOLYGON (((8.66397 53.17149, 8.67099 53.1...
37248  POLYGON ((10.28582 53.42716, 10.23538 53.40665...
37249  POLYGON ((9.46937 50.44459, 9.46978 50.42570, ...
37250  POLYGON ((9.46937 50.44459, 9.43497 50.42759, ...
37251  POLYGON ((9.93101 51.37271, 9.93335 51.35220, ...
37252  MULTIPOLYGON (((11.48215 53.99916, 11.48295 53...
37253  POLYGON ((8.31165 51.72588, 8.39464 51.71847, ...
37254  POLYGON ((9.43130 51.64545, 9.35052 51.62524, ...
37255  POLYGON ((6.40997 51.82804, 6.40997 51.82804, ...
37256  POLYGON ((7.78362 50.93949, 7.74604 50.92305, ...
37257  POLYGON ((8.09614 52.05506, 8.07457 52.02528, ...
37258  POLYGON ((8.12246 50.68383, 8.10904 50.67157, ...
37259  POLYGON ((7.36895 49.16807, 7.36940 49.16613, ...
37260  POLYGON ((13.22080 51.07850, 13.22154 51.01379...
37261  POLYGON ((14.72275 51.57571, 14.71043 51.56180...
37262  POLYGON ((13.02581 51.62967, 13.04956 51.61011...
37263  MULTIPOLYGON (((9.53210 53.66995, 9.52858 53.6...
37264  POLYGON ((12.25790 51.10104, 12.30621 51.10112...
37265  POLYGON ((11.59731 53.03251, 11.58988 53.00745...
37266  MULTIPOLYGON (((9.69848 53.56465, 9.74062 53.5...
74 GHA Ghana
      OBJECTID  ADM2_CODE               ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
6224  6,225.00     190539                  Adenta       2012       3000
6225  6,226.00     190540      Ledzokuku / Krowor       2012       3000
6226  6,227.00     190541               Chereponi       2007       3000
6227  6,228.00     190542            Wa Municipal       2003       3000
6228  6,229.00     190543                  Jirapa       2007       3000
...        ...        ...                     ...        ...        ...
6435  6,436.00     190723                Ashaiman       2012       3000
6436  6,437.00     190724         Kpone Katamanso       2012       3000
6437  6,438.00     190725  Tamale North Sub Metro       2012       3000
6438  6,439.00     190726               Sagnerigu       2012       3000
6439  6,440.00     190727          Afadzato South       2012       3000

      ADM1_CODE      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
6224       1328  Greater Accra  Member State        NO         94     Ghana
6225       1328  Greater Accra  Member State        NO         94     Ghana
6226       1329       Northern  Member State        NO         94     Ghana
6227       1331     Upper West  Member State        NO         94     Ghana
6228       1331     Upper West  Member State        NO         94     Ghana
...         ...            ...           ...       ...        ...       ...
6435       1328  Greater Accra  Member State        NO         94     Ghana
6436       1328  Greater Accra  Member State        NO         94     Ghana
6437       1329       Northern  Member State        NO         94     Ghana
6438       1329       Northern  Member State        NO         94     Ghana
6439       1332          Volta  Member State        NO         94     Ghana

      Shape_Leng  Shape_Le_1  Shape_Area  \
6224        0.46        0.46        0.01
6225        0.30        0.30        0.00
6226        2.23        2.23        0.11
6227        1.32        1.32        0.05
6228        1.74        1.74        0.10
...          ...         ...         ...
6435        0.17        0.17        0.00
6436        0.97        0.97        0.02
6437        1.55        1.55        0.05
6438        0.73        0.73        0.02
6439        1.73        1.73        0.05

                                               geometry
6224  POLYGON ((-0.07813 5.67195, -0.07769 5.67172, ...
6225  POLYGON ((-0.05609 5.60679, -0.05683 5.60655, ...
6226  POLYGON ((0.36554 9.92909, 0.36541 9.92984, 0....
6227  POLYGON ((-2.40446 10.16043, -2.40436 10.16016...
6228  POLYGON ((-2.43411 10.73889, -2.43227 10.73939...
...                                                 ...
6435  POLYGON ((-0.01620 5.68274, -0.01780 5.68245, ...
6436  POLYGON ((-0.06091 5.84264, -0.06209 5.83994, ...
6437  POLYGON ((-0.57596 9.41279, -0.57635 9.40977, ...
6438  POLYGON ((-0.77943 9.47273, -0.77982 9.46170, ...
6439  POLYGON ((0.39793 7.08137, 0.39818 7.08094, 0....

[216 rows x 15 columns]
75 GIB Gibraltar
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
76 GRC Greece
       OBJECTID  ADM2_CODE     ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
36063 36,064.00      16675        Dramas       1000       3000       1336
36064 36,065.00      16676         Evrou       1000       3000       1336
36065 36,066.00      16677       Kavalas       1000       3000       1336
36066 36,067.00      16678       Rodopis       1000       3000       1336
36067 36,068.00      16679       Xanthis       1000       3000       1336
...         ...        ...           ...        ...        ...        ...
36114 36,115.00      16709      Kykladon       1000       3000      40766
36115 36,116.00      40767          Simi       1000       3000      40766
36116 36,117.00      40768  Name Unknown       1000       3000      40766
36117 36,118.00      40769  Name Unknown       1000       3000      40766
36118 36,119.00      40770  Name Unknown       1000       3000      40766

                            ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
36063  Anatoliki Makedonia Kai Thraki  Member State        NO         97
36064  Anatoliki Makedonia Kai Thraki  Member State        NO         97
36065  Anatoliki Makedonia Kai Thraki  Member State        NO         97
36066  Anatoliki Makedonia Kai Thraki  Member State        NO         97
36067  Anatoliki Makedonia Kai Thraki  Member State        NO         97
...                               ...           ...       ...        ...
36114                    Notio Aigaio  Member State        NO         97
36115                    Notio Aigaio  Member State        NO         97
36116                    Notio Aigaio  Member State        NO         97
36117                    Notio Aigaio  Member State        NO         97
36118                    Notio Aigaio  Member State        NO         97

      ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
36063    Greece        3.36        3.36        0.40
36064    Greece        4.81        4.81        0.45
36065    Greece        3.76        3.76        0.21
36066    Greece        2.61        2.61        0.28
36067    Greece        2.49        2.49        0.20
...         ...         ...         ...         ...
36114    Greece       15.00       15.00        0.27
36115    Greece        0.79        0.79        0.01
36116    Greece        0.05        0.05        0.00
36117    Greece        0.05        0.05        0.00
36118    Greece        0.16        0.16        0.00

                                                geometry
36063  POLYGON ((24.38175 41.53540, 24.38240 41.53573...
36064  MULTIPOLYGON (((25.57253 40.52281, 25.60447 40...
36065  MULTIPOLYGON (((24.79169 40.67250, 24.78510 40...
36066  MULTIPOLYGON (((25.14759 41.00576, 25.15151 41...
36067  POLYGON ((24.93195 41.41220, 24.93195 41.41220...
...                                                  ...
36114  MULTIPOLYGON (((25.21238 36.24675, 25.20813 36...
36115  MULTIPOLYGON (((27.85481 36.51912, 27.84909 36...
36116  POLYGON ((29.63478 36.10021, 29.62903 36.09860...
36117  POLYGON ((29.49955 36.15120, 29.49554 36.15044...
36118  POLYGON ((29.56861 36.10902, 29.56266 36.10880...

[56 rows x 15 columns]
77 GRL Greenland
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
78 GRD Grenada
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
6621   6,622.00      16731  Administrative unit not available       1000
6622   6,623.00      16732  Administrative unit not available       1000
6623   6,624.00      16733  Administrative unit not available       1000
6624   6,625.00      16734  Administrative unit not available       1000
6625   6,626.00      16735  Administrative unit not available       1000
38217 38,218.00      16730  Administrative unit not available       1000
38218 38,219.00      76500    Carriacou and Petite Martinique       1000

       EXP2_YEAR  ADM1_CODE                        ADM1_NAME        STATUS  \
6621        3000       1353                     St. Andrew's  Member State
6622        3000       1354                     St. George's  Member State
6623        3000       1355                       St. John's  Member State
6624        3000       1356                       St. Mark's  Member State
6625        3000       1357                    St. Patrick's  Member State
38217       3000       1352                     Name Unknown  Member State
38218       3000      75500  Carriacou and Petite Martinique  Member State

      DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
6621         NO         99   Grenada        0.53        0.53        0.01
6622         NO         99   Grenada        0.83        0.83        0.01
6623         NO         99   Grenada        0.27        0.27        0.00
6624         NO         99   Grenada        0.22        0.22        0.00
6625         NO         99   Grenada        0.38        0.38        0.00
38217        NO         99   Grenada        0.67        0.67        0.00
38218        NO         99   Grenada        0.67        0.63        0.00

                                                geometry
6621   MULTIPOLYGON (((-61.62276 12.06925, -61.62289 ...
6622   MULTIPOLYGON (((-61.78731 11.98554, -61.78777 ...
6623   POLYGON ((-61.67764 12.15738, -61.67742 12.157...
6624   POLYGON ((-61.67157 12.16419, -61.67170 12.164...
6625   MULTIPOLYGON (((-61.54998 12.20886, -61.54949 ...
38217  MULTIPOLYGON (((-61.69280 12.01412, -61.69277 ...
38218  MULTIPOLYGON (((-61.49764 12.39008, -61.49766 ...
79 GUM Guam
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
80 GTM Guatemala
      OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
7256  7,257.00     115000                     Unión Cantinil       2005
7257  7,258.00     114998                            Raxruja       2008
7258  7,259.00     114999                             Chisec       2008
7259  7,260.00      65122                  Melchor de Mencos       1000
7260  7,261.00      65112                             Flores       1000
...        ...        ...                                ...        ...
7587  7,588.00      65057                  Concepción Huista       1000
7588  7,589.00      65065             Santiago Chimaltenango       1000
7589  7,590.00      65041                    San Pedro Necta       1000
7590  7,591.00      65050            Todos Santos Cuchumatán       1000
7591  7,592.00      65298  Administrative unit not available       1000

      EXP2_YEAR  ADM1_CODE      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
7256       3000      64833  Huehuetenango  Member State        NO        103
7257       3000      64836   Alta Verapaz  Member State        NO        103
7258       3000      64836   Alta Verapaz  Member State        NO        103
7259       3000      64837          Petén  Member State        NO        103
7260       3000      64837          Petén  Member State        NO        103
...         ...        ...            ...           ...       ...        ...
7587       3000      64833  Huehuetenango  Member State        NO        103
7588       3000      64833  Huehuetenango  Member State        NO        103

      OBJECTID  ADM2_CODE                  ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
6110  6,111.00      17068                     Bafata       1000       3000
6111  6,112.00      17069                 Bambadinca       1000       3000
6112  6,113.00      17070                  Contuboel       1000       3000
6113  6,114.00      17071             Galomaro/cosse       1000       3000
6114  6,115.00      17072            Gamamudo/ganadu       1000       3000
6115  6,116.00      17073                     Xitole       1000       3000
6116  6,117.00      17074                     Prabis       1000       3000
6117  6,118.00      17075                  Quinhamel       1000       3000
6118  6,119.00      17076                      Safim       1000       3000
6119  6,120.00      17077                     Bolama       1000       3000
6120  6,121.00      17078                    Bubaque       2004       3000
6121  6,122.00      17079                   Caravela       2004       3000
6122  6,123.00      17080                        Uno       2004       3000
6123  6,124.00      17081                     Bigene       1000       3000
6124  6,125.00      17082                       Bula       1000       3000
6125  6,126.00      17083          Cacheu/calequisse       1000       3000
6126  6,127.00      17084                       Caio       1000       3000
6127  6,128.00      17085                  Canchungo       1000       3000
6128  6,129.00      17086               Sao Domingos       1000       3000
6129  6,130.00      17087                        Boe       1000       3000
6130  6,131.00      17088                       Gabu       1000       3000
6131  6,132.00      17089                     Pirada       1000       3000
6132  6,133.00      17090                     Pitche       1000       3000
6133  6,134.00      17091                     Sonaco       1000       3000
6134  6,135.00      17092                    Bissora       1000       3000
6135  6,136.00      17093                      Farim       1000       3000
6136  6,137.00      17094                    Mansaba       1000       3000
6137  6,138.00      17095                     Mansoa       1000       3000
6138  6,139.00      17096                     Nhacra       1000       3000
6139  6,140.00      17097                       Buba       1000       3000
6140  6,141.00      17098                     Empada       1000       3000
6141  6,142.00      17099                  Fulacunda       1000       3000
6142  6,143.00      17100                       Tite       1000       3000
6143  6,144.00      17101  Sector Autonomo De Bissau       1000       3000
6144  6,145.00      17102                    Bedanda       1000       3000
6145  6,146.00      17103                     Cacine       1000       3000
6146  6,147.00      17104                      Catio       2007       3000
6147  6,148.00      17105                       Komo       2007       3000
6148  6,149.00      17106                      Quebo       1000       3000

      ADM1_CODE                  ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
6110       1385                     Bafata  Member State        NO        105
6111       1385                     Bafata  Member State        NO        105
6112       1385                     Bafata  Member State        NO        105
6113       1385                     Bafata  Member State        NO        105
6114       1385                     Bafata  Member State        NO        105
6115       1385                     Bafata  Member State        NO        105
6116       1386                     Biombo  Member State        NO        105
6117       1386                     Biombo  Member State        NO        105
6118       1386                     Biombo  Member State        NO        105
6119       1387             Bolama/bijagos  Member State        NO        105
6120       1387             Bolama/bijagos  Member State        NO        105
6121       1387             Bolama/bijagos  Member State        NO        105
6122       1387             Bolama/bijagos  Member State        NO        105
6123       1388                     Cacheu  Member State        NO        105
6124       1388                     Cacheu  Member State        NO        105
6125       1388                     Cacheu  Member State        NO        105
6126       1388                     Cacheu  Member State        NO        105
6127       1388                     Cacheu  Member State        NO        105
6128       1388                     Cacheu  Member State        NO        105
6129       1389                       Gabu  Member State        NO        105
6130       1389                       Gabu  Member State        NO        105
6131       1389                       Gabu  Member State        NO        105
6132       1389                       Gabu  Member State        NO        105
6133       1389                       Gabu  Member State        NO        105
6134       1390                        Oio  Member State        NO        105
6135       1390                        Oio  Member State        NO        105
6136       1390                        Oio  Member State        NO        105
6137       1390                        Oio  Member State        NO        105
6138       1390                        Oio  Member State        NO        105
6139       1391                    Quinara  Member State        NO        105
6140       1391                    Quinara  Member State        NO        105
6141       1391                    Quinara  Member State        NO        105
6142       1391                    Quinara  Member State        NO        105
6143       1392  Sector Autonomo De Bissau  Member State        NO        105
6144       1393                    Tombali  Member State        NO        105
6145       1393                    Tombali  Member State        NO        105
6146       1393                    Tombali  Member State        NO        105
6147       1393                    Tombali  Member State        NO        105
6148       1393                    Tombali  Member State        NO        105

          ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
6110  Guinea-Bissau        1.53        1.53        0.06
6111  Guinea-Bissau        1.70        1.70        0.07
6112  Guinea-Bissau        2.26        2.26        0.13
6113  Guinea-Bissau        0.97        0.97        0.05
6114  Guinea-Bissau        1.33        1.33        0.08
6115  Guinea-Bissau        1.52        1.52        0.10
6116  Guinea-Bissau        1.70        1.70        0.01
6117  Guinea-Bissau        2.38        2.38        0.03
6118  Guinea-Bissau        1.10        1.10        0.01
6119  Guinea-Bissau        3.70        3.70        0.02
6120  Guinea-Bissau        7.33        7.33        0.02
6121  Guinea-Bissau        4.31        4.31        0.03
6122  Guinea-Bissau        6.39        6.39        0.03
6123  Guinea-Bissau        5.57        5.57        0.06
6124  Guinea-Bissau        4.77        4.77        0.05
6125  Guinea-Bissau        8.02        8.02        0.05
6126  Guinea-Bissau        3.50        3.50        0.04
6127  Guinea-Bissau        3.79        3.79        0.05
6128  Guinea-Bissau        6.77        6.77        0.05
6129  Guinea-Bissau        2.95        2.95        0.26
6130  Guinea-Bissau        2.25        2.25        0.18
6131  Guinea-Bissau        1.64        1.64        0.08
6132  Guinea-Bissau        2.06        2.06        0.16
6133  Guinea-Bissau        1.95        1.95        0.07
6134  Guinea-Bissau        4.48        4.48        0.09
6135  Guinea-Bissau        1.88        1.88        0.13
6136  Guinea-Bissau        1.59        1.59        0.10
6137  Guinea-Bissau        3.47        3.47        0.09
6138  Guinea-Bissau        2.69        2.69        0.02
6139  Guinea-Bissau        3.54        3.54        0.06
6140  Guinea-Bissau        8.55        8.55        0.04
6141  Guinea-Bissau        4.63        4.63        0.06
6142  Guinea-Bissau        2.93        2.93        0.04
6143  Guinea-Bissau        0.52        0.52        0.01
6144  Guinea-Bissau        7.52        7.52        0.07
6145  Guinea-Bissau        7.16        7.16        0.03
6146  Guinea-Bissau        8.50        8.50        0.03
6147  Guinea-Bissau        4.89        4.89        0.01
6148  Guinea-Bissau        1.63        1.63        0.09

                                               geometry
6110  POLYGON ((-14.55221 12.35069, -14.55094 12.350...
6111  MULTIPOLYGON (((-15.02932 11.93920, -15.02885 ...
6112  POLYGON ((-14.33965 12.67654, -14.35079 12.643...
6113  POLYGON ((-14.53606 12.11384, -14.53900 12.111...
6114  POLYGON ((-14.68257 12.28538, -14.67661 12.277...
6115  POLYGON ((-14.71818 11.92597, -14.70555 11.922...
6116  MULTIPOLYGON (((-15.77458 11.86472, -15.77514 ...
6117  MULTIPOLYGON (((-15.86307 11.75490, -15.86448 ...
6118  MULTIPOLYGON (((-15.71168 11.85792, -15.71405 ...
6119  MULTIPOLYGON (((-15.71335 11.43423, -15.71388 ...
6120  MULTIPOLYGON (((-15.72265 10.85933, -15.72317 ...
6121  MULTIPOLYGON (((-16.30728 11.40654, -16.30741 ...
6122  MULTIPOLYGON (((-16.08544 10.99898, -16.08531 ...
6123  MULTIPOLYGON (((-15.81127 12.21653, -15.81127 ...
6124  MULTIPOLYGON (((-15.83177 12.00728, -15.83350 ...
6125  MULTIPOLYGON (((-16.30628 12.00256, -16.30602 ...
6126  MULTIPOLYGON (((-16.04944 11.74878, -16.05023 ...
6127  MULTIPOLYGON (((-16.10631 11.97069, -16.10683 ...
6128  MULTIPOLYGON (((-16.44481 12.18507, -16.44271 ...
6129  POLYGON ((-14.40433 11.55642, -14.40585 11.558...
6130  POLYGON ((-14.07589 12.41490, -14.07747 12.410...
6131  POLYGON ((-13.84448 12.67597, -13.84448 12.675...
6132  POLYGON ((-13.94955 12.15978, -13.95730 12.159...
6133  POLYGON ((-14.34554 12.63260, -14.34100 12.634...
6134  MULTIPOLYGON (((-15.55095 12.01459, -15.55117 ...
6135  POLYGON ((-14.91290 12.67825, -14.91290 12.678...
6136  POLYGON ((-14.97162 12.42570, -14.97221 12.422...
6137  MULTIPOLYGON (((-15.19560 11.91469, -15.19586 ...
6138  MULTIPOLYGON (((-15.55985 11.90339, -15.55936 ...
6139  MULTIPOLYGON (((-15.07927 11.41126, -15.08116 ...
6140  MULTIPOLYGON (((-15.49945 11.32353, -15.49945 ...
6141  MULTIPOLYGON (((-15.22024 11.63721, -15.22050 ...
6142  MULTIPOLYGON (((-15.30442 11.62528, -15.30468 ...
6143  MULTIPOLYGON (((-15.59066 11.82054, -15.59078 ...
6144  MULTIPOLYGON (((-15.20071 11.00782, -15.20123 ...
6145  MULTIPOLYGON (((-15.08409 10.96121, -15.08487 ...
6146  MULTIPOLYGON (((-15.23975 11.22739, -15.23962 ...
6147  MULTIPOLYGON (((-15.22687 11.11927, -15.22739 ...
6148  POLYGON ((-14.51378 11.64829, -14.50654 11.649...
83 GUY Guyana
       OBJECTID  ADM2_CODE                                    ADM2_NAME  \
20810 20,811.00      17142                                       Cuyuni
20811 20,812.00      17145                   Moblissa/la Reconnaissance
20812 20,813.00      17146   Black Bush Polder Frontlands And Extension
20813 20,814.00      17147                      East Berbice/west Canje
20814 20,815.00      17148                East Canje/east Coast Berbice
20815 20,816.00      17149      Left Bank Upper Canje/ikuruwa/corentyne
20816 20,817.00      17150                  Lower Corentyne River/canje
20817 20,818.00      17151                        Upper Canje/corentyne
20818 20,819.00      17152                              Upper Corentyne
20819 20,820.00      17153                          Bonasika/boerasirie
20820 20,821.00      17154  Essequibo Islands/left Bank Essequibo River
20821 20,822.00      17155                    Lower West Demerara River
20822 20,823.00      17158                              Moruka/pomeroon
20823 20,824.00      17159            Somerset And Berks/supenaam River
20824 20,825.00      17160                           Ireng/upper Potaro
20825 20,826.00      17161          Lower Potaro/lower Lady Smith Creek
20826 20,827.00      17162          Right Bank Essequibo/upper Demerara
20827 20,828.00      17163                            Torani/bulletwood
20828 20,829.00      17164                                Rupununi West
20829 20,830.00      17165                        Rewai/upper Essequibo
20830 20,831.00      17140                               Barima/amakura
20831 20,832.00      17141                                        Waini
20832 20,833.00      17143           Mazaruni/left Bank Essequibo River
20833 20,834.00      17144                               Buxton/mahaica
20834 20,835.00      17156                            Mahaica/mahaicony
20835 20,836.00      17157                            Mahaicony/berbice

       STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
20810       1000       3000       1399
20811       1000       3000       1400
20812       1000       3000       1401
20813       1000       3000       1401
20814       1000       3000       1401
20815       1000       3000       1401
20816       1000       3000       1401
20817       1000       3000       1401
20818       1000       3000       1401
20819       1000       3000       1402
20820       1000       3000       1402
20821       1000       3000       1402
20822       1000       3000       1404
20823       1000       3000       1404
20824       1000       3000       1405
20825       1000       3000       1405
20826       1000       3000       1406
20827       1000       3000       1406
20828       1000       3000       1407
20829       1000       3000       1407
20830       1000       3000       1398
20831       1000       3000       1398
20832       1000       3000       1399
20833       1000       3000       1400
20834       1000       3000       1403
20835       1000       3000       1403

                                          ADM1_NAME        STATUS DISP_AREA  \
20810                  Cuyuni/mazaruni (region N°7)  Member State        NO
20811                 Demerara Mahaica (region N°4)  Member State        NO
20812           East Berbice/corentyne (region N°6)  Member State        NO
20813           East Berbice/corentyne (region N°6)  Member State        NO
20814           East Berbice/corentyne (region N°6)  Member State        NO
20815           East Berbice/corentyne (region N°6)  Member State        NO
20816           East Berbice/corentyne (region N°6)  Member State        NO
20817           East Berbice/corentyne (region N°6)  Member State        NO
20818           East Berbice/corentyne (region N°6)  Member State        NO
20819  Essequibo Islands/west Demerara (region N°3)  Member State        NO
20820  Essequibo Islands/west Demerara (region N°3)  Member State        NO
20821  Essequibo Islands/west Demerara (region N°3)  Member State        NO
20822                 Pomeroon/supenaam (region N°2  Member State        NO
20823                 Pomeroon/supenaam (region N°2  Member State        NO
20824                  Potaro/siparuni (region N°8)  Member State        NO
20825                  Potaro/siparuni (region N°8)  Member State        NO
20826          Upper Demerara/berbice (region N°10)  Member State        NO
20827          Upper Demerara/berbice (region N°10)  Member State        NO
20828     Upper Takutu/upper Essequibo (region N°9)  Member State        NO
20829     Upper Takutu/upper Essequibo (region N°9)  Member State        NO
20830                     Barima Waini (region N°1)  Member State        NO
20831                     Barima Waini (region N°1)  Member State        NO
20832                  Cuyuni/mazaruni (region N°7)  Member State        NO
20833                 Demerara Mahaica (region N°4)  Member State        NO
20834                  Mahaica Berbice (region N°5)  Member State        NO
20835                  Mahaica Berbice (region N°5)  Member State        NO

       ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
20810        107    Guyana        8.57        8.57        1.23
20811        107    Guyana        2.34        2.34        0.07
20812        107    Guyana        0.95        0.95        0.05
20813        107    Guyana        1.70        1.70        0.09
20814        107    Guyana        0.87        0.87        0.03
20815        107    Guyana        2.32        2.32        0.21
20816        107    Guyana        1.38        1.38        0.09
20817        107    Guyana        3.79        3.79        0.19
20818        107    Guyana       11.50       11.50        2.33
20819        107    Guyana        1.49        1.49        0.08
20820        107    Guyana        1.85        1.85        0.13
20821        107    Guyana        2.05        2.05        0.10
20822        107    Guyana        2.59        2.59        0.28
20823        107    Guyana        2.01        2.01        0.17
20824        107    Guyana        3.71        3.71        0.61
20825        107    Guyana        5.91        5.91        1.11
20826        107    Guyana        5.26        5.26        0.80
20827        107    Guyana        3.99        3.99        0.58
20828        107    Guyana        8.44        8.44        1.93
20829        107    Guyana        8.89        8.89        2.54
20830        107    Guyana        5.04        5.04        0.77
20831        107    Guyana        5.90        5.90        0.78
20832        107    Guyana        8.53        8.53        2.72
20833        107    Guyana        1.88        1.88        0.09
20834        107    Guyana        2.50        2.50        0.21
20835        107    Guyana        1.75        1.75        0.09

                                                geometry
20810  POLYGON ((-59.66476 7.13791, -59.65399 7.13693...
20811  MULTIPOLYGON (((-58.24384 6.54327, -58.24383 6...
20812  POLYGON ((-57.26185 6.20623, -57.26185 6.20572...
20813  POLYGON ((-57.49223 6.31748, -57.50396 6.30563...
20814  MULTIPOLYGON (((-57.46512 6.32022, -57.45695 6...
20815  POLYGON ((-57.29287 5.60300, -57.29403 5.59975...
20816  POLYGON ((-57.14139 5.92819, -57.14106 5.92538...
20817  POLYGON ((-57.19317 5.55596, -57.20525 5.53718...
20818  POLYGON ((-57.84332 4.61934, -57.85591 4.59462...
20819  POLYGON ((-58.33165 6.89474, -58.33163 6.88350...
20820  POLYGON ((-58.57352 6.50377, -58.59829 6.51792...
20821  MULTIPOLYGON (((-58.18375 6.67445, -58.18817 6...
20822  MULTIPOLYGON (((-58.58847 7.47909, -58.58949 7...
20823  MULTIPOLYGON (((-58.47045 7.15966, -58.46958 7...
20824  POLYGON ((-59.57584 5.40562, -59.56432 5.39457...
20825  POLYGON ((-58.84291 5.42356, -58.84729 5.41450...
20826  POLYGON ((-58.37317 6.15237, -58.36632 6.14674...
20827  POLYGON ((-57.68368 5.88155, -57.68325 5.87293...
20828  POLYGON ((-58.90786 3.99365, -58.90652 3.98224...
20829  POLYGON ((-58.42824 4.26844, -58.42150 4.26022...
20830  POLYGON ((-59.99327 8.53304, -59.99289 8.53272...
20831  POLYGON ((-59.79910 8.40342, -59.79289 8.40269...
20832  POLYGON ((-58.61591 6.42160, -58.61565 6.42120...
20833  POLYGON ((-58.01732 6.79518, -58.01539 6.79373...
20834  MULTIPOLYGON (((-57.84528 6.64902, -57.84554 6...
20835  MULTIPOLYGON (((-57.51898 6.25438, -57.51873 6...
84 HTI Haiti
      OBJECTID  ADM2_CODE               ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
6843  6,844.00      17166              Dessalines       1000       3000
6844  6,845.00      17167              Gros Morne       1000       3000
6845  6,846.00      17168                Gonaives       1000       3000
6846  6,847.00      17169               Marmelade       1000       3000
6847  6,848.00      17170              Saint-Marc       1000       3000
6848  6,849.00      17171          Ceca La Source       1000       3000
6849  6,850.00      17172                  Hinche       1000       3000
6850  6,851.00      17173              Lascahobas       1000       3000
6851  6,852.00      17174              Mirebalais       1000       3000
6852  6,853.00      17187                  Borgne       1000       3000
6853  6,854.00      17188  Grande Riviere Du Nord       1000       3000
6854  6,855.00      17189            Acul Du Nord       1000       3000
6855  6,856.00      17190             Cap Haitien       1000       3000

       OBJECTID  ADM2_CODE     ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
32845 32,846.00      36824    Al-Shikhan       1000       3000       1578
32846 32,847.00      36827       Tilkaif       1000       3000       1578
32847 32,848.00      36821  Al-Hamdaniya       1000       3000       1578
32848 32,849.00      36823         Mosul       1000       3000       1578
32849 32,850.00      36826       Telafar       1000       3000       1578
...         ...        ...           ...        ...        ...        ...
32949 32,950.00     123568        Kirkuk       2007       3000       1570
32950 32,951.00     123569         Dabes       2007       3000       1570
32951 32,952.00     123570     Al-Azezia       2007       3000       1581
32952 32,953.00     123571    Al-Suwaira       2007       3000       1581
32953 32,954.00     123572       Samarra       2007       3000       1579

          ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
32845        Ninewa  Member State        NO        118      Iraq        1.89
32846        Ninewa  Member State        NO        118      Iraq        1.72
32847        Ninewa  Member State        NO        118      Iraq        2.22
32848        Ninewa  Member State        NO        118      Iraq        4.19
32849        Ninewa  Member State        NO        118      Iraq        4.18
...             ...           ...       ...        ...       ...         ...
32949        Kirkuk  Member State        NO        118      Iraq        3.93
32950        Kirkuk  Member State        NO        118      Iraq        2.09
32951        Wassit  Member State        NO        118      Iraq        2.95
32952        Wassit  Member State        NO        118      Iraq        3.70
32953  Salah al-Din  Member State        NO        118      Iraq        2.54

       Shape_Le_1  Shape_Area  \
32845        1.89        0.13
32846        1.72        0.13
32847        2.22        0.18
32848        4.19        0.43
32849        4.18        0.45
...           ...         ...
32949        3.93        0.28
32950        2.09        0.11
32951        2.95        0.23
32952        3.70        0.18
32953        2.54        0.20

                                                geometry
32845  POLYGON ((43.65633 36.81939, 43.65569 36.81933...
32846  POLYGON ((43.16659 36.78659, 43.23003 36.74729...
32847  POLYGON ((43.51523 36.51300, 43.51490 36.51241...
32848  POLYGON ((42.74878 36.53787, 42.75125 36.53391...
32849  POLYGON ((42.37953 37.04396, 42.38207 37.04237...
...                                                  ...
32949  POLYGON ((44.62765 35.88357, 44.62559 35.87656...
32950  POLYGON ((44.48764 35.87218, 44.48485 35.85826...
32951  POLYGON ((45.41192 33.08138, 45.43152 33.02291...
32952  POLYGON ((44.73437 33.03053, 44.73892 33.02761...
32953  POLYGON ((43.88755 34.13015, 43.86214 34.13790...

[109 rows x 15 columns]
93 IRL Ireland
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
35459 35,460.00      18283  Administrative unit not available       1000
35460 35,461.00      18284  Administrative unit not available       1000
35461 35,462.00      18285  Administrative unit not available       1000
35462 35,463.00      18286  Administrative unit not available       1000
35463 35,464.00      18287  Administrative unit not available       1000
35464 35,465.00      18288  Administrative unit not available       1000
35465 35,466.00      18289  Administrative unit not available       1000
35466 35,467.00      18290  Administrative unit not available       1000
35467 35,468.00      18291  Administrative unit not available       1000
35468 35,469.00      18292  Administrative unit not available       1000
35469 35,470.00      18293  Administrative unit not available       1000
35470 35,471.00      18294  Administrative unit not available       1000
35471 35,472.00      18295  Administrative unit not available       1000
35472 35,473.00      18296  Administrative unit not available       1000
35473 35,474.00      18297  Administrative unit not available       1000
35474 35,475.00      18298  Administrative unit not available       1000
35475 35,476.00      18299  Administrative unit not available       1000
35476 35,477.00      18300  Administrative unit not available       1000
35477 35,478.00      18301  Administrative unit not available       1000
35478 35,479.00      18302  Administrative unit not available       1000
35479 35,480.00      18303  Administrative unit not available       1000
35480 35,481.00      18304  Administrative unit not available       1000
35481 35,482.00      18305  Administrative unit not available       1000
35482 35,483.00      18306  Administrative unit not available       1000
35483 35,484.00      18307  Administrative unit not available       1000
35484 35,485.00      18308  Administrative unit not available       1000
35485 35,486.00      18309  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE  ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
35459       3000       1582     Carlow  Member State        NO        119
35460       3000       1583      Cavan  Member State        NO        119
35461       3000       1584      Clare  Member State        NO        119
35462       3000       1585       Cork  Member State        NO        119
35463       3000       1586    Donegal  Member State        NO        119
35464       3000       1587     Dublin  Member State        NO        119
35465       3000       1588     Galway  Member State        NO        119
35466       3000       1589      Kerry  Member State        NO        119
35467       3000       1590    Kildare  Member State        NO        119
35468       3000       1591   Kilkenny  Member State        NO        119
35469       3000       1592      Laois  Member State        NO        119
35470       3000       1593    Leitrim  Member State        NO        119
35471       3000       1594   Limerick  Member State        NO        119
35472       3000       1595   Longford  Member State        NO        119
35473       3000       1596      Louth  Member State        NO        119
35474       3000       1597       Mayo  Member State        NO        119
35475       3000       1598      Meath  Member State        NO        119
35476       3000       1599   Monaghan  Member State        NO        119
35477       3000       1600    Munster  Member State        NO        119
35478       3000       1601     Offaly  Member State        NO        119
35479       3000       1602  Roscommon  Member State        NO        119
35480       3000       1603      Sligo  Member State        NO        119
35481       3000       1604  Tipperary  Member State        NO        119
35482       3000       1605  Waterford  Member State        NO        119
35483       3000       1606  Westmeath  Member State        NO        119
35484       3000       1607    Wexford  Member State        NO        119
35485       3000       1608    Wicklow  Member State        NO        119

      ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
35459   Ireland        2.23        2.23        0.12
35460   Ireland        3.68        3.68        0.26
35461   Ireland        6.44        6.44        0.43
35462   Ireland       15.08       15.08        0.97
35463   Ireland       13.63       13.63        0.68
35464   Ireland        3.03        3.03        0.13
35465   Ireland       13.44       13.44        0.82
35466   Ireland       10.86       10.86        0.63
35467   Ireland        2.91        2.91        0.23
35468   Ireland        2.73        2.73        0.28
35469   Ireland        2.75        2.75        0.23
35470   Ireland        3.08        3.08        0.22
35471   Ireland        4.62        4.62        0.36
35472   Ireland        2.07        2.07        0.15
35473   Ireland        2.55        2.55        0.11
35474   Ireland       12.90       12.90        0.77
35475   Ireland        3.90        3.90        0.32
35476   Ireland        2.78        2.78        0.18
35477   Ireland        0.02        0.02        0.00
35478   Ireland        4.03        4.03        0.27
35479   Ireland        4.22        4.22        0.35
35480   Ireland        4.84        4.84        0.26
35481   Ireland        5.03        5.03        0.57
35482   Ireland        3.98        3.98        0.24
35483   Ireland        2.85        2.85        0.25
35484   Ireland        4.22        4.22        0.31
35485   Ireland        2.93        2.93        0.27

                                                geometry
35459  POLYGON ((-6.62010 52.71110, -6.63800 52.70570...
35460  POLYGON ((-7.32880 54.12032, -7.32880 54.12032...
35461  MULTIPOLYGON (((-9.51966 52.60899, -9.52297 52...
35462  MULTIPOLYGON (((-9.46571 51.45240, -9.46665 51...
35463  MULTIPOLYGON (((-8.43729 54.95947, -8.44412 54...
35464  MULTIPOLYGON (((-6.16967 53.36258, -6.17281 53...
35465  MULTIPOLYGON (((-9.52815 53.07019, -9.51829 53...
35466  MULTIPOLYGON (((-10.24398 51.73379, -10.25049 ...
35467  POLYGON ((-6.46720 53.38860, -6.48190 53.36260...
35468  POLYGON ((-7.06210 52.79340, -7.09570 52.77720...
35469  POLYGON ((-7.11170 53.16970, -7.08140 53.16860...
35470  POLYGON ((-8.29998 54.48101, -8.27421 54.46827...
35471  MULTIPOLYGON (((-9.10327 52.61941, -9.10851 52...
35472  POLYGON ((-7.61040 53.93720, -7.58020 53.89890...
35473  POLYGON ((-6.26610 54.09651, -6.26609 54.09651...
35474  MULTIPOLYGON (((-10.08228 53.71212, -10.08953 ...
35475  POLYGON ((-6.69960 53.90290, -6.61000 53.86470...
35476  POLYGON ((-6.87302 54.32674, -6.87296 54.32483...
35477  POLYGON ((-9.90594 51.80635, -9.91065 51.80565...
35478  POLYGON ((-7.09650 53.37860, -7.09470 53.36510...
35479  POLYGON ((-7.92140 53.82150, -7.90790 53.78860...
35480  MULTIPOLYGON (((-8.58648 54.29455, -8.59155 54...
35481  POLYGON ((-7.73260 52.95690, -7.72990 52.94760...
35482  POLYGON ((-7.37730 52.34230, -7.31270 52.32240...
35483  POLYGON ((-7.19350 53.42560, -7.21800 53.41810...
35484  MULTIPOLYGON (((-6.61398 52.11380, -6.61991 52...
35485  POLYGON ((-6.10625 53.21425, -6.10543 53.21196...
94 IMN Isle of Man
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
95 ISR Israel
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
33120 33,121.00      18311  Administrative unit not available       1000
33121 33,122.00      18312  Administrative unit not available       1000
33122 33,123.00      18313  Administrative unit not available       1000
33123 33,124.00      18314  Administrative unit not available       1000
33124 33,125.00      18315  Administrative unit not available       1000
33125 33,126.00      18316  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE          ADM1_NAME        STATUS DISP_AREA  \
33120       3000       1610   Central District  Member State        NO
33121       3000       1611              Haifa  Member State        NO
33122       3000       1612          Jerusalem  Member State        NO
33123       3000       1613           Northern  Member State        NO
33124       3000       1614  Southern District  Member State        NO
33125       3000       1615           Tel Aviv  Member State        NO

       ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
33120        121    Israel        2.33        2.33        0.12
33121        121    Israel        1.80        1.80        0.08
33122        121    Israel        1.21        1.21        0.05
33123        121    Israel        3.57        3.57        0.33
33124        121    Israel        6.80        6.80        1.36
33125        121    Israel        0.62        0.62        0.02

                                                geometry
33120  POLYGON ((35.04153 32.38284, 35.04089 32.38164...
33121  POLYGON ((35.21088 32.54306, 35.20640 32.54140...
33122  POLYGON ((34.97042 31.86139, 34.96729 31.86108...
33123  POLYGON ((35.62467 33.24239, 35.62473 33.24240...
33124  POLYGON ((34.82510 31.79277, 34.82666 31.79277...
33125  POLYGON ((34.73325 32.00677, 34.73419 32.01996...
96 ITA Italy
       OBJECTID  ADM2_CODE ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
36707 36,708.00      18317    Chieti       1000       3000       1616
36708 36,709.00      18318  L'Aquila       1000       3000       1616
36709 36,710.00      18319   Pescara       1000       3000       1616
36710 36,711.00      18320    Teramo       1000       3000       1616
36711 36,712.00      18321    Matera       1000       3000       1617
...         ...        ...       ...        ...        ...        ...
36805 36,806.00      18416    Rovigo       1000       3000       1635
36806 36,807.00      18417   Treviso       1000       3000       1635
36807 36,808.00      18418   Venezia       1000       3000       1635
36808 36,809.00      18419    Verona       1000       3000       1635
36809 36,810.00      18420   Vicenza       1000       3000       1635

        ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
36707     Abruzzi  Member State        NO        122     Italy        2.68
36708     Abruzzi  Member State        NO        122     Italy        4.91
36709     Abruzzi  Member State        NO        122     Italy        2.07
36710     Abruzzi  Member State        NO        122     Italy        2.34
36711  Basilicata  Member State        NO        122     Italy        3.70
...           ...           ...       ...        ...       ...         ...
36805      Veneto  Member State        NO        122     Italy        4.46
36806      Veneto  Member State        NO        122     Italy        3.14
36807      Veneto  Member State        NO        122     Italy        8.64
36808      Veneto  Member State        NO        122     Italy        3.52
36809      Veneto  Member State        NO        122     Italy        3.39

       Shape_Le_1  Shape_Area  \
36707        2.68        0.28
36708        4.91        0.55
36709        2.07        0.13
36710        2.34        0.21
36711        3.70        0.36
...           ...         ...
36805        4.46        0.20
36806        3.14        0.29
36807        8.64        0.24
36808        3.52        0.36
36809        3.39        0.31

                                                geometry
36707  POLYGON ((14.27752 42.43423, 14.31819 42.40964...
36708  POLYGON ((13.40441 42.57731, 13.40542 42.57468...
36709  POLYGON ((14.07271 42.54334, 14.07483 42.54282...
36710  POLYGON ((13.91523 42.89441, 13.92206 42.85505...
36711  MULTIPOLYGON (((15.98378 40.64736, 15.98261 40...
...                                                  ...
36805  POLYGON ((12.33083 45.14705, 12.32790 45.13174...
36806  POLYGON ((12.35548 46.07705, 12.36288 46.07249...
36807  MULTIPOLYGON (((12.23922 45.24469, 12.23396 45...
36808  MULTIPOLYGON (((10.63781 45.44469, 10.62827 45...
36809  POLYGON ((11.55342 46.01267, 11.56113 46.00956...

[103 rows x 15 columns]
97 JAM Jamaica
      OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
6626  6,627.00      18421  Administrative unit not available       1000
6627  6,628.00      18422  Administrative unit not available       1000
6628  6,629.00      18423  Administrative unit not available       1000
6629  6,630.00      18424  Administrative unit not available       1000
6630  6,631.00      18426  Administrative unit not available       1000
6631  6,632.00      18427  Administrative unit not available       1000
6632  6,633.00      18428  Administrative unit not available       1000
6633  6,634.00      18429  Administrative unit not available       1000
6634  6,635.00      18430  Administrative unit not available       1000
6635  6,636.00      18431  Administrative unit not available       1000
6636  6,637.00      18432  Administrative unit not available       1000
6637  6,638.00      18433  Administrative unit not available       1000
6638  6,639.00      18425  Administrative unit not available       1000

      EXP2_YEAR  ADM1_CODE                  ADM1_NAME        STATUS DISP_AREA  \
6626       3000       1636                  Clarendon  Member State        NO
6627       3000       1637                    Hanover  Member State        NO
6628       3000       1638                 Manchester  Member State        NO
6629       3000       1639                   Portland  Member State        NO
6630       3000       1641                  Saint Ann  Member State        NO
6631       3000       1642            Saint Catherine  Member State        NO
6632       3000       1643            Saint Elizabeth  Member State        NO
6633       3000       1644                Saint James  Member State        NO
6634       3000       1645                 Saint Mary  Member State        NO
6635       3000       1646               Saint Thomas  Member State        NO
6636       3000       1647                   Trelawny  Member State        NO
6637       3000       1648               Westmoreland  Member State        NO
6638       3000       1640  Saint Andrew And Kingston  Member State        NO

      ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
6626        123   Jamaica        1.95        1.95        0.10
6627        123   Jamaica        1.37        1.37        0.04
6628        123   Jamaica        1.14        1.14        0.07
6629        123   Jamaica        1.60        1.60        0.07
6630        123   Jamaica        1.59        1.59        0.11
6631        123   Jamaica        1.77        1.77        0.10
6632        123   Jamaica        1.40        1.40        0.10
6633        123   Jamaica        1.17        1.17        0.05
6634        123   Jamaica        1.27        1.27        0.05
6635        123   Jamaica        1.48        1.48        0.06
6636        123   Jamaica        1.28        1.28        0.08
6637        123   Jamaica        1.44        1.44        0.07
6638        123   Jamaica        1.48        1.48        0.04

                                               geometry
6626  MULTIPOLYGON (((-77.18319 17.77274, -77.18311 ...
6627  POLYGON ((-78.14049 18.46111, -78.14032 18.460...
6628  POLYGON ((-77.48475 18.20226, -77.48643 18.193...
6629  MULTIPOLYGON (((-76.45192 18.18932, -76.45141 ...
6630  MULTIPOLYGON (((-77.21182 18.44904, -77.20530 ...
6631  MULTIPOLYGON (((-77.06219 17.88927, -77.06191 ...
6632  POLYGON ((-77.63280 18.22946, -77.63384 18.224...
6633  MULTIPOLYGON (((-77.93222 18.44849, -77.93306 ...
6634  MULTIPOLYGON (((-76.88372 18.37381, -76.88442 ...
6635  POLYGON ((-76.63359 18.07768, -76.63126 18.077...
6636  POLYGON ((-77.46075 18.47753, -77.46118 18.472...
6637  POLYGON ((-77.91327 18.30887, -77.91001 18.297...
6638  MULTIPOLYGON (((-76.77415 17.94586, -76.77422 ...
98 JPN Japan
       OBJECTID  ADM2_CODE       ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
23189 23,190.00      33365        Aguityoo       1000       3000       1651
23190 23,191.00      33366     Akabanetyoo       1000       3000       1651
23191 23,192.00      33367        Anzyoosi       1000       3000       1651
23192 23,193.00      33368       Asahityoo       1000       3000       1651
23193 23,194.00      33369       Asuketyoo       1000       3000       1651
...         ...        ...             ...        ...        ...        ...
26532 26,533.00      36708    Wakakusatyoo       1000       3000       1697
26533 26,534.00      36709  Yamanakakomura       1000       3000       1697
26534 26,535.00      36710      Yamanasisi       1000       3000       1697
26535 26,536.00      36711      Yamatomura       1000       3000       1697
26536 26,537.00      36712    Yatusirotyoo       1000       3000       1697

      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
23189      Aiti  Member State        NO        126     Japan        0.22
23190      Aiti  Member State        NO        126     Japan        0.28

       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
36683 36,684.00      76108  Administrative unit not available       1000
36684 36,685.00      76109  Administrative unit not available       1000
36685 36,686.00      76110  Administrative unit not available       1000
36690 36,691.00      76111  Administrative unit not available       1000
36694 36,695.00      76112  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE             ADM1_NAME        STATUS DISP_AREA  \
36683       3000      75108              Kosovski  Member State        NO
36684       3000      75109  Kosovsko-mitrovatski  Member State        NO
36685       3000      75110   Kosovsko-pomoravski  Member State        NO
36690       3000      75111                 Pecki  Member State        NO
36694       3000      75112            Prizremski  Member State        NO

       ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
36683      75008    Kosovo        4.34        4.34        0.34
36684      75008    Kosovo        2.57        2.57        0.23
36685      75008    Kosovo        2.31        2.31        0.15
36690      75008    Kosovo        3.02        3.02        0.27
36694      75008    Kosovo        2.59        2.59        0.20

                                                geometry
36683  POLYGON ((21.43101 42.85966, 21.43181 42.85886...
36684  POLYGON ((20.81775 43.26757, 20.82252 43.26779...
36685  POLYGON ((21.75611 42.69311, 21.75846 42.69252...
36690  POLYGON ((20.63748 42.84566, 20.63976 42.84353...
36694  POLYGON ((20.80777 42.51754, 20.81301 42.51455...
106 KWT Kuwait
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
31345 31,346.00      18587  Administrative unit not available       1000
31346 31,347.00      18588  Administrative unit not available       1000
31347 31,348.00      18589  Administrative unit not available       1000
31348 31,349.00      18590  Administrative unit not available       1000
31349 31,350.00      18591  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
31345       3000       1741  Al Farwaniyah  Member State        NO        137
31346       3000       1742      Al Ahmadi  Member State        NO        137
31347       3000       1743      Al Jahrah  Member State        NO        137
31348       3000       1744      Al Kuwayt  Member State        NO        137
31349       3000       1745        Hawalli  Member State        NO        137

      ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
31345    Kuwait        0.62        0.62        0.02
31346    Kuwait        3.01        3.01        0.43
31347    Kuwait        7.97        7.97        1.14
31348    Kuwait        0.43        0.43        0.00
31349    Kuwait        0.86        0.86        0.02

                                                geometry
31345  POLYGON ((48.04330 29.20810, 47.87530 29.18627...
31346  POLYGON ((48.04330 29.20810, 48.07339 29.21201...
31347  MULTIPOLYGON (((48.03966 29.82892, 48.04902 29...
31348  MULTIPOLYGON (((47.91846 29.35839, 47.91084 29...
31349  MULTIPOLYGON (((48.04498 29.34554, 48.05596 29...
107 KGZ Kyrgyz Republic
       OBJECTID  ADM2_CODE     ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
22438 22,439.00      18612      At-Bashy       1000       3000       1749
22439 22,440.00      18628     Jeti-Oguz       1000       3000       1752
22440 22,441.00      18627        Ak-Suu       1000       3000       1752
22441 22,442.00      18610      Toktogul       1000       3000       1748
22442 22,443.00      18629          Tong       1000       3000       1752
22443 22,444.00      18615         Naryn       1000       3000       1749
22444 22,445.00      18606       Chatkal       1000       3000       1748
22445 22,446.00      18614       Kochkor       1000       3000       1749
22446 22,447.00      18616          Alay       1000       3000       1750
22447 22,448.00      18592        Batken       1000       3000       1746
22448 22,449.00      18600      Panfilov       1000       3000     147294
22449 22,450.00      18598         Kemin       1000       3000     147294
22450 22,451.00      18631      Ysyk-Kol       1000       3000       1752
22451 22,452.00      18626         Talas       1000       3000       1751
22452 22,453.00      18619    Kara-Kulja       1000       3000       1750
22453 22,454.00      18611      Ak-Talaa       1000       3000       1749
22454 22,455.00      18613        Jumgal       1000       3000       1749
22455 22,456.00      18618    Chong-Alay       1000       3000       1750
22456 22,457.00      18609    Toguz-Toro       1000       3000       1748
22457 22,458.00      18603          Aksy       1000       3000       1748
22458 22,459.00      18630           Tup       1000       3000       1752
22459 22,460.00      18621        Nookat       1000       3000       1750
22460 22,461.00      18622         Ozgon       1000       3000       1750
22461 22,462.00      18608         Suzak       1000       3000       1748
22462 22,463.00      18594        Leylek       1000       3000       1746
22463 22,464.00      18620      Kara-Suu       1000       3000       1750
22464 22,465.00      18605  Bazar-Korgon       1000       3000       1748
22465 22,466.00      18604      Ala-Buka       1000       3000       1748
22466 22,467.00      18624    Kara-Buura       1000       3000       1751
22467 22,468.00      18623     Bakay-Ata       1000       3000       1751
22468 22,469.00      18607        Nooken       1000       3000       1748
22469 22,470.00      18597         Jayyl       1000       3000     147294
22470 22,471.00      18601       Sokuluk       1000       3000     147294
22471 22,472.00      18599        Moskva       1000       3000     147294
22472 22,473.00      18595      Alamudun       1000       3000     147294
22473 22,474.00      18596          Chuy       1000       3000     147294
22474 22,475.00      18625         Manas       1000       3000       1751
22475 22,476.00      18602      Ysyk-Ata       1000       3000     147294
22476 22,477.00      18617        Aravan       1000       3000       1750
22477 22,478.00      18593      Kadamjay       1000       3000       1746

        ADM1_NAME        STATUS DISP_AREA  ADM0_CODE        ADM0_NAME  \
22438       Naryn  Member State        NO        138  Kyrgyz Republic
22439    Ysyk-Kol  Member State        NO        138  Kyrgyz Republic
22440    Ysyk-Kol  Member State        NO        138  Kyrgyz Republic
22441  Jalal-Abad  Member State        NO        138  Kyrgyz Republic
22442    Ysyk-Kol  Member State        NO        138  Kyrgyz Republic
22443       Naryn  Member State        NO        138  Kyrgyz Republic
22444  Jalal-Abad  Member State        NO        138  Kyrgyz Republic
22445       Naryn  Member State        NO        138  Kyrgyz Republic
22446         Osh  Member State        NO        138  Kyrgyz Republic
22447      Batken  Member State        NO        138  Kyrgyz Republic
22448        Chuy  Member State        NO        138  Kyrgyz Republic
22449        Chuy  Member State        NO        138  Kyrgyz Republic
22450    Ysyk-Kol  Member State        NO        138  Kyrgyz Republic
22451       Talas  Member State        NO        138  Kyrgyz Republic
22452         Osh  Member State        NO        138  Kyrgyz Republic
22453       Naryn  Member State        NO        138  Kyrgyz Republic
22454       Naryn  Member State        NO        138  Kyrgyz Republic
22455         Osh  Member State        NO        138  Kyrgyz Republic
22456  Jalal-Abad  Member State        NO        138  Kyrgyz Republic
22457  Jalal-Abad  Member State        NO        138  Kyrgyz Republic
22458    Ysyk-Kol  Member State        NO        138  Kyrgyz Republic
22459         Osh  Member State        NO        138  Kyrgyz Republic
22460         Osh  Member State        NO        138  Kyrgyz Republic
22461  Jalal-Abad  Member State        NO        138  Kyrgyz Republic
22462      Batken  Member State        NO        138  Kyrgyz Republic
22463         Osh  Member State        NO        138  Kyrgyz Republic
22464  Jalal-Abad  Member State        NO        138  Kyrgyz Republic
22465  Jalal-Abad  Member State        NO        138  Kyrgyz Republic
22466       Talas  Member State        NO        138  Kyrgyz Republic
22467       Talas  Member State        NO        138  Kyrgyz Republic
22468  Jalal-Abad  Member State        NO        138  Kyrgyz Republic
22469        Chuy  Member State        NO        138  Kyrgyz Republic
22470        Chuy  Member State        NO        138  Kyrgyz Republic
22471        Chuy  Member State        NO        138  Kyrgyz Republic
22472        Chuy  Member State        NO        138  Kyrgyz Republic
22473        Chuy  Member State        NO        138  Kyrgyz Republic
22474       Talas  Member State        NO        138  Kyrgyz Republic
22475        Chuy  Member State        NO        138  Kyrgyz Republic
22476         Osh  Member State        NO        138  Kyrgyz Republic
22477      Batken  Member State        NO        138  Kyrgyz Republic

       Shape_Leng  Shape_Le_1  Shape_Area  \
22438       11.08       11.08        2.03
22439        8.03        8.03        1.65
22440        6.35        6.35        1.08
22441        7.07        7.07        0.94
22442        6.95        6.95        0.98
22443        6.46        6.46        0.85
22444        6.19        6.19        0.66
22445        6.22        6.22        0.71
22446        5.11        5.11        0.80
22447        6.52        6.52        0.63
22448        7.95        7.95        0.54
22449        4.89        4.89        0.37
22450        4.57        4.57        0.72
22451        4.55        4.55        0.56
22452        4.53        4.53        0.61
22453        4.84        4.84        0.70
22454        5.40        5.40        0.59
22455        4.37        4.37        0.52
22456        4.34        4.34        0.42
22457        4.16        4.16        0.49
22458        3.93        3.93        0.25
22459        4.26        4.26        0.43
22460        4.50        4.50        0.37
22461        4.26        4.26        0.30
22462        3.92        3.92        0.48
22463        4.01        4.01        0.31
22464        3.23        3.23        0.22
22465        4.72        4.72        0.33
22466        2.80        2.80        0.33
22467        2.71        2.71        0.26
22468        2.86        2.86        0.26
22469        5.67        5.67        0.33
22470        3.55        3.55        0.22
22471        2.97        2.97        0.17
22472        3.31        3.31        0.18
22473        2.57        2.57        0.18
22474        1.99        1.99        0.11
22475        2.26        2.26        0.21
22476        2.33        2.33        0.07
22477        5.48        5.48        0.63

                                                geometry
22438  POLYGON ((77.35465 41.38773, 77.35638 41.38694...
22439  POLYGON ((78.23189 42.57804, 78.24151 42.55569...
22440  POLYGON ((79.40549 42.50603, 79.41982 42.52778...
22441  POLYGON ((72.33887 42.20928, 72.34244 42.20955...
22442  POLYGON ((76.13494 42.61332, 76.13632 42.61240...
22443  POLYGON ((76.46646 41.81672, 76.47059 41.81148...
22444  POLYGON ((71.98118 42.09916, 71.97863 42.09541...
22445  POLYGON ((75.63625 42.44865, 75.63763 42.44860...
22446  POLYGON ((73.49970 40.44031, 73.50403 40.44013...
22447  MULTIPOLYGON (((71.23037 39.92412, 71.22886 39...
22448  MULTIPOLYGON (((74.22466 42.46091, 74.22948 42...
22449  MULTIPOLYGON (((77.26848 42.91311, 77.26846 42...
22450  POLYGON ((77.96926 42.85008, 77.96863 42.84800...
22451  POLYGON ((73.51182 42.41756, 73.51200 42.41732...
22452  POLYGON ((74.03882 40.08877, 74.03945 40.09883...
22453  POLYGON ((75.26935 41.80332, 75.25214 41.78404...
22454  POLYGON ((75.08659 41.84722, 75.08001 41.77031...
22455  POLYGON ((72.88266 39.35451, 72.88148 39.35405...
22456  POLYGON ((74.72843 41.63971, 74.73039 41.63621...
22457  POLYGON ((72.16307 41.16296, 72.16310 41.15685...
22458  POLYGON ((78.50259 42.89965, 78.51420 42.89530...
22459  POLYGON ((72.73339 40.40206, 72.73651 40.40129...
22460  POLYGON ((73.65251 41.13916, 73.65359 41.13502...
22461  POLYGON ((73.48572 41.35552, 73.48659 41.35057...
22462  POLYGON ((70.11766 39.58991, 70.11531 39.58533...
22463  POLYGON ((73.09452 40.77001, 73.10193 40.76352...
22464  POLYGON ((73.37349 41.46031, 73.37534 41.45797...
22465  POLYGON ((71.64187 41.48654, 71.64646 41.48621...
22466  POLYGON ((71.32099 42.77964, 71.33245 42.75683...
22467  POLYGON ((72.08566 42.58136, 72.08906 42.57961...
22468  POLYGON ((72.39272 41.49701, 72.39815 41.49362...
22469  MULTIPOLYGON (((74.15082 42.30351, 74.15145 42...
22470  POLYGON ((74.34115 43.20626, 74.34061 43.20414...
22471  POLYGON ((74.18677 42.45565, 74.18435 42.45210...
22472  POLYGON ((74.73890 42.99533, 74.73866 42.99529...
22473  POLYGON ((75.45066 42.81967, 75.45078 42.81939...
22474  POLYGON ((72.13696 42.73913, 72.13873 42.73838...
22475  POLYGON ((75.16072 42.84949, 75.16129 42.84256...
22476  MULTIPOLYGON (((72.05868 40.38064, 72.04600 40...
22477  POLYGON ((71.97072 40.25374, 71.97440 40.25305...
108 LAO Lao PDR
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
109 LVA Latvia
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
35412 35,413.00      18765  Administrative unit not available       1000
35413 35,414.00      18766  Administrative unit not available       1000
35414 35,415.00      18767  Administrative unit not available       1000
35415 35,416.00      18768  Administrative unit not available       1000
35416 35,417.00      18769  Administrative unit not available       1000
35417 35,418.00      18770  Administrative unit not available       1000
35418 35,419.00      18771  Administrative unit not available       1000
35419 35,420.00      18772  Administrative unit not available       1000
35420 35,421.00      18773  Administrative unit not available       1000
35421 35,422.00      18774  Administrative unit not available       1000
35422 35,423.00      18775  Administrative unit not available       1000
35423 35,424.00      18776  Administrative unit not available       1000
35424 35,425.00      18777  Administrative unit not available       1000
35425 35,426.00      18778  Administrative unit not available       1000
35426 35,427.00      18779  Administrative unit not available       1000
35427 35,428.00      18780  Administrative unit not available       1000
35428 35,429.00      18781  Administrative unit not available       1000
35429 35,430.00      18782  Administrative unit not available       1000
35430 35,431.00      18783  Administrative unit not available       1000
35431 35,432.00      18784  Administrative unit not available       1000
35432 35,433.00      18785  Administrative unit not available       1000
35433 35,434.00      18786  Administrative unit not available       1000
35434 35,435.00      18787  Administrative unit not available       1000
35435 35,436.00      18788  Administrative unit not available       1000
35436 35,437.00      18789  Administrative unit not available       1000
35437 35,438.00      18790  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE    ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
35412       3000       1771  Aizkraukles  Member State        NO        140
35413       3000       1772     Aluksnes  Member State        NO        140
35414       3000       1773        Balvu  Member State        NO        140
35415       3000       1774      Bauskas  Member State        NO        140
35416       3000       1775         Cesu  Member State        NO        140
35417       3000       1776   Daugavpils  Member State        NO        140
35418       3000       1777      Dobeles  Member State        NO        140
35419       3000       1778     Gulbenes  Member State        NO        140
35420       3000       1779    Jekabpils  Member State        NO        140
35421       3000       1780     Jelgavas  Member State        NO        140
35422       3000       1781    Kraslavas  Member State        NO        140
35423       3000       1782     Kuldigas  Member State        NO        140
35424       3000       1783     Liepajas  Member State        NO        140
35425       3000       1784      Limbazu  Member State        NO        140
35426       3000       1785       Ludzas  Member State        NO        140
35427       3000       1786      Madonas  Member State        NO        140
35428       3000       1787        Ogres  Member State        NO        140
35429       3000       1788       Preilu  Member State        NO        140
35430       3000       1789     Rezeknes  Member State        NO        140
35431       3000       1790        Rigas  Member State        NO        140
35432       3000       1791       Saldus  Member State        NO        140
35433       3000       1792        Talsu  Member State        NO        140
35434       3000       1793       Tukuma  Member State        NO        140
35435       3000       1794       Valkas  Member State        NO        140
35436       3000       1795    Valmieras  Member State        NO        140
35437       3000       1796    Ventspils  Member State        NO        140

      ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
35412    Latvia        4.66        4.66        0.38
35413    Latvia        4.09        4.09        0.34
35414    Latvia        3.29        3.29        0.35
35415    Latvia        3.24        3.24        0.27
35416    Latvia        4.30        4.30        0.45
35417    Latvia        3.54        3.54        0.37
35418    Latvia        3.42        3.42        0.24
35419    Latvia        3.24        3.24        0.28
35420    Latvia        4.82        4.82        0.43
35421    Latvia        3.19        3.19        0.24
35422    Latvia        3.33        3.33        0.33
35423    Latvia        4.08        4.08        0.37
35424    Latvia        3.65        3.65        0.53
35425    Latvia        3.70        3.70        0.39
35426    Latvia        3.99        3.99        0.38
35427    Latvia        4.59        4.59        0.49
35428    Latvia        3.76        3.76        0.27
35429    Latvia        3.29        3.29        0.30
35430    Latvia        3.66        3.66        0.39
35431    Latvia        4.87        4.87        0.51
35432    Latvia        4.20        4.20        0.31
35433    Latvia        3.60        3.60        0.42
35434    Latvia        3.50        3.50        0.36
35435    Latvia        3.46        3.46        0.37
35436    Latvia        4.35        4.35        0.36
35437    Latvia        3.44        3.44        0.37

                                                geometry
35412  POLYGON ((25.93350 56.64080, 25.83880 56.61490...
35413  POLYGON ((26.91820 57.63705, 26.92039 57.63600...
35414  POLYGON ((27.66686 56.83716, 27.66686 56.83716...
35415  POLYGON ((24.66930 56.54640, 24.63940 56.53760...
35416  POLYGON ((25.64870 57.46370, 25.65790 57.43920...
35417  POLYGON ((26.95880 56.06370, 26.94520 56.05510...
35418  POLYGON ((23.42230 56.36882, 23.38058 56.37799...
35419  POLYGON ((27.13440 57.22100, 27.13940 57.20480...
35420  POLYGON ((26.62090 56.54620, 26.57870 56.51100...
35421  POLYGON ((24.03320 56.68150, 24.03300 56.66950...
35422  POLYGON ((27.66400 56.24710, 27.72510 56.19950...
35423  POLYGON ((22.52220 57.01420, 22.49080 56.98440...
35424  POLYGON ((21.40380 56.92530, 21.42850 56.91530...
35425  POLYGON ((24.83143 57.98203, 24.84640 57.90850...
35426  POLYGON ((27.66686 56.83716, 27.68620 56.83758...
35427  POLYGON ((26.11130 57.07810, 26.19390 57.07920...
35428  POLYGON ((25.49620 56.99120, 25.51460 56.97550...
35429  POLYGON ((27.09660 56.16950, 27.11160 56.16520...

       OBJECTID  ADM2_CODE        ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
35357 35,358.00      19117     Alytaus Raj.       1000       3000       1866
35358 35,359.00      19118           Alytus       1000       3000       1866
35359 35,360.00      19119     Druskininkai       1000       3000       1866
35360 35,361.00      19120     Lazdiju Raj.       1000       3000       1866
35361 35,362.00      19121     Varenos Raj.       1000       3000       1866
...         ...        ...              ...        ...        ...        ...
35407 35,408.00      19167  Svencioniu Raj.       1000       3000       1875
35408 35,409.00      19168       Traku Raj.       1000       3000       1875
35409 35,410.00      19169    Ukmerges Raj.       1000       3000       1875
35410 35,411.00      19170    Vilniaus Raj.       1000       3000       1875
35411 35,412.00      19171          Vilnius       1000       3000       1875

      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  ADM0_NAME  Shape_Leng  \
35357   Alytaus  Member State        NO        147  Lithuania        3.36
35358   Alytaus  Member State        NO        147  Lithuania        0.41
35359   Alytaus  Member State        NO        147  Lithuania        0.23
35360   Alytaus  Member State        NO        147  Lithuania        2.50
35361   Alytaus  Member State        NO        147  Lithuania        3.84
...         ...           ...       ...        ...        ...         ...
35407  Vilniaus  Member State        NO        147  Lithuania        3.89
35408  Vilniaus  Member State        NO        147  Lithuania        2.89
35409  Vilniaus  Member State        NO        147  Lithuania        2.63
35410  Vilniaus  Member State        NO        147  Lithuania        4.77
35411  Vilniaus  Member State        NO        147  Lithuania        1.52

       Shape_Le_1  Shape_Area  \
35357        3.36        0.19
35358        0.41        0.01
35359        0.23        0.00
35360        2.50        0.22
35361        3.84        0.33
...           ...         ...
35407        3.89        0.24
35408        2.89        0.23
35409        2.63        0.20
35410        4.77        0.30
35411        1.52        0.04

                                                geometry
35357  POLYGON ((24.42000 54.53110, 24.41220 54.51510...
35358  POLYGON ((24.06530 54.43480, 24.05120 54.41870...
35359  POLYGON ((23.99960 54.01920, 24.00190 54.01790...
35360  POLYGON ((23.99330 54.16860, 24.01350 54.15390...
35361  POLYGON ((25.00560 54.43880, 25.00410 54.40660...
...                                                  ...
35407  POLYGON ((25.86520 55.29490, 25.89360 55.28330...
35408  POLYGON ((24.85890 54.87110, 24.85810 54.85030...
35409  POLYGON ((25.06450 55.31270, 25.06780 55.28990...
35410  POLYGON ((25.50610 55.03580, 25.53320 55.02790...
35411  POLYGON ((25.11020 54.63220, 25.10440 54.65080...

[55 rows x 15 columns]
116 LUX Luxembourg
       OBJECTID  ADM2_CODE         ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
37363 37,364.00      19172          Clervaux       1000       3000       1876
37364 37,365.00      19173          Diekirch       1000       3000       1876
37365 37,366.00      19174           Redange       1000       3000       1876
37366 37,367.00      19175           Vianden       1000       3000       1876
37367 37,368.00      19176             Wiltz       1000       3000       1876
37368 37,369.00      19177        Echternach       1000       3000       1877
37369 37,370.00      19178      Grevenmacher       1000       3000       1877
37370 37,371.00      19179            Remich       1000       3000       1877
37371 37,372.00      19180          Capellen       1000       3000       1878
37372 37,373.00      19181  Esch-sur-alzette       1000       3000       1878
37373 37,374.00      19182        Luxembourg       1000       3000       1878
37374 37,375.00      19183            Mersch       1000       3000       1878

          ADM1_NAME        STATUS DISP_AREA  ADM0_CODE   ADM0_NAME  \
37363      Diekirch  Member State        NO        148  Luxembourg
37364      Diekirch  Member State        NO        148  Luxembourg
37365      Diekirch  Member State        NO        148  Luxembourg
37366      Diekirch  Member State        NO        148  Luxembourg
37367      Diekirch  Member State        NO        148  Luxembourg
37368  Grevenmacher  Member State        NO        148  Luxembourg
37369  Grevenmacher  Member State        NO        148  Luxembourg
37370  Grevenmacher  Member State        NO        148  Luxembourg
37371    Luxembourg  Member State        NO        148  Luxembourg
37372    Luxembourg  Member State        NO        148  Luxembourg
37373    Luxembourg  Member State        NO        148  Luxembourg
37374    Luxembourg  Member State        NO        148  Luxembourg

       Shape_Leng  Shape_Le_1  Shape_Area  \
37363        1.13        1.13        0.04
37364        1.04        1.04        0.03
37365        0.96        0.96        0.03
37366        0.46        0.46        0.01
37367        1.02        1.02        0.04
37368        0.83        0.83        0.02
37369        0.92        0.92        0.03
37370        0.64        0.64        0.02
37371        0.85        0.85        0.03
37372        1.13        1.13        0.03
37373        0.92        0.92        0.03
37374        0.78        0.78        0.03

                                                geometry
37363  POLYGON ((6.02559 50.18495, 6.02712 50.18423, ...
37364  POLYGON ((6.24269 49.89852, 6.24269 49.89852, ...
37365  POLYGON ((5.98722 49.85331, 5.98692 49.85110, ...
37366  POLYGON ((6.16735 49.97512, 6.16842 49.97312, ...
37367  MULTIPOLYGON (((5.93830 50.01663, 5.93947 50.0...
37368  POLYGON ((6.32418 49.84750, 6.32246 49.84338, ...
37369  POLYGON ((6.50306 49.74165, 6.50430 49.73893, ...
37370  POLYGON ((6.37910 49.58718, 6.38619 49.57899, ...
37371  POLYGON ((6.09583 49.68778, 6.09444 49.68639, ...
37372  POLYGON ((6.23503 49.54000, 6.24302 49.52446, ...
37373  POLYGON ((6.31225 49.62720, 6.30250 49.62053, ...
37374  POLYGON ((6.24640 49.79053, 6.24669 49.78782, ...
117 MAC Macao SAR, China
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
118 MDG Madagascar
     OBJECTID  ADM2_CODE        ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
360    361.00     154509   Ambatondrazaka       2007       3000      41750
361    362.00     154510   Amparafaravola       2007       3000      41750
362    363.00     154511       Andilamena       2007       3000      41750
363    364.00     154512   Anosibe-An'ala       2007       3000      41750
364    365.00     154513        Moramanga       2007       3000      41750
..        ...        ...              ...        ...        ...        ...
474    475.00     154612           Ikongo       2007       3000      41771
475    476.00     154613  Manakara Atsimo       2007       3000      41771
476    477.00     154614        Mananjary       2007       3000      41771
477    478.00     154615      Nosy-Varika       2007       3000      41771
478    479.00     154616         Vohipeno       2007       3000      41771

               ADM1_NAME        STATUS DISP_AREA  ADM0_CODE   ADM0_NAME  \
360      Alaotra Mangoro  Member State        NO        150  Madagascar
361      Alaotra Mangoro  Member State        NO        150  Madagascar
362      Alaotra Mangoro  Member State        NO        150  Madagascar
363      Alaotra Mangoro  Member State        NO        150  Madagascar
364      Alaotra Mangoro  Member State        NO        150  Madagascar
..                   ...           ...       ...        ...         ...
474  Vatovavy Fitovinany  Member State        NO        150  Madagascar
475  Vatovavy Fitovinany  Member State        NO        150  Madagascar
476  Vatovavy Fitovinany  Member State        NO        150  Madagascar
477  Vatovavy Fitovinany  Member State        NO        150  Madagascar
478  Vatovavy Fitovinany  Member State        NO        150  Madagascar

     Shape_Leng  Shape_Le_1  Shape_Area  \
360        5.52        5.52        0.47
361        4.52        4.52        0.39
362        4.83        4.83        0.65
363        2.64        2.64        0.25
364        4.70        4.70        0.61
..          ...         ...         ...
474        3.56        3.56        0.28
475        3.06        3.06        0.28
476        3.75        3.75        0.47
477        4.02        4.02        0.33
478        1.96        1.96        0.10

                                              geometry
360  POLYGON ((48.79204 -17.37574, 48.79112 -17.376...
361  POLYGON ((48.28408 -17.00712, 48.28501 -17.007...
362  POLYGON ((48.23939 -16.24389, 48.24146 -16.244...
363  POLYGON ((48.26645 -19.19433, 48.26967 -19.195...
364  POLYGON ((48.30711 -18.11018, 48.30739 -18.110...
..                                                 ...
474  POLYGON ((47.48838 -21.42067, 47.48956 -21.421...
475  POLYGON ((47.81580 -21.59368, 47.81626 -21.594...
476  POLYGON ((47.97888 -20.74652, 47.98194 -20.747...
477  POLYGON ((48.19947 -20.21288, 48.20073 -20.213...
478  POLYGON ((47.66285 -22.19331, 47.66271 -22.194...

[119 rows x 15 columns]
119 MWI Malawi

     OBJECTID  ADM2_CODE                           ADM2_NAME  STR2_YEAR  \
634    635.00      19307                               Dedza       1000
635    636.00      19308                                Dowa       1000
636    637.00      19309                             Kasungu       1000
637    638.00      19310                            Lilongwe       1000
638    639.00      19311                             Mchinji       1000
639    640.00      19312                          Nkhotakota       1000
640    641.00      19313                              Ntcheu       1000
641    642.00      19314                             Ntchisi       1000
642    643.00      19315                              Salima       1000
643    644.00      19316                             Chitipa       1000
644    645.00      19317                             Karonga       1000
645    646.00      19318                              Mzimba       1000
646    647.00      19320                              Rumphi       1000
647    648.00      42172                              Likoma       1000
648    649.00      42173                          Nkhata Bay       1000
649    650.00      19321                            Blantyre       1000
650    651.00      19322                            Chikwawa       1000
651    652.00      19323                          Chiradzulu       1000
652    653.00      19325                            Mangochi       1000
653    654.00      19328                              Nsanje       1000
654    655.00      19329                              Thyolo       1000
655    656.00      19330                               Zomba       1000
656    657.00      42174                              Balaka       1000
657    658.00      42175                            Machinga       1000
658    659.00      42176                             Mulanje       1000
659    660.00      42177                            Phalombe       1000
660    661.00      65269  Area under National Administration       1000
661    662.00      65270                                Neno       2002
662    663.00      65271                              Mwanza       2002

     EXP2_YEAR  ADM1_CODE                           ADM1_NAME        STATUS  \
634       3000       1888                      Central Region  Member State
635       3000       1888                      Central Region  Member State
636       3000       1888                      Central Region  Member State
637       3000       1888                      Central Region  Member State
638       3000       1888                      Central Region  Member State
639       3000       1888                      Central Region  Member State
640       3000       1888                      Central Region  Member State
641       3000       1888                      Central Region  Member State
642       3000       1888                      Central Region  Member State
643       3000       1889                     Northern Region  Member State
644       3000       1889                     Northern Region  Member State
645       3000       1889                     Northern Region  Member State
646       3000       1889                     Northern Region  Member State
647       3000       1889                     Northern Region  Member State
648       3000       1889                     Northern Region  Member State
649       3000       1890                     Southern Region  Member State
650       3000       1890                     Southern Region  Member State
651       3000       1890                     Southern Region  Member State
652       3000       1890                     Southern Region  Member State
653       3000       1890                     Southern Region  Member State
654       3000       1890                     Southern Region  Member State
655       3000       1890                     Southern Region  Member State
656       3000       1890                     Southern Region  Member State
657       3000       1890                     Southern Region  Member State
658       3000       1890                     Southern Region  Member State
659       3000       1890                     Southern Region  Member State
660       3000      65268  Area under National Administration  Member State
661       3000       1890                     Southern Region  Member State
662       3000       1890                     Southern Region  Member State

    DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
634        NO        152    Malawi        3.69        3.69        0.31
635        NO        152    Malawi        3.61        3.61        0.26
636        NO        152    Malawi        5.00        5.00        0.67
637        NO        152    Malawi        4.74        4.74        0.52
638        NO        152    Malawi        3.28        3.28        0.26
639        NO        152    Malawi        5.04        5.04        0.36
640        NO        152    Malawi        3.13        3.13        0.27
641        NO        152    Malawi        2.26        2.26        0.14
642        NO        152    Malawi        2.54        2.54        0.18
643        NO        152    Malawi        4.68        4.68        0.35
644        NO        152    Malawi        3.48        3.48        0.28
645        NO        152    Malawi        7.54        7.54        0.88
646        NO        152    Malawi        3.52        3.52        0.38
647        NO        152    Malawi        0.70        0.70        0.02
648        NO        152    Malawi        4.13        4.13        0.35
649        NO        152    Malawi        2.27        2.27        0.17
650        NO        152    Malawi        3.40        3.40        0.42
651        NO        152    Malawi        1.57        1.57        0.06
652        NO        152    Malawi        6.07        6.07        0.58
653        NO        152    Malawi        2.94        2.94        0.17
654        NO        152    Malawi        1.98        1.98        0.14
655        NO        152    Malawi        2.90        2.90        0.27
656        NO        152    Malawi        1.98        1.98        0.18
657        NO        152    Malawi        3.03        3.03        0.34
658        NO        152    Malawi        2.65        2.65        0.17
659        NO        152    Malawi        1.83        1.83        0.13
660        NO        152    Malawi       14.56       14.56        1.86
661        NO        152    Malawi        2.28        2.28        0.13
662        NO        152    Malawi        1.47        1.47        0.06

                                              geometry
634  POLYGON ((34.55097 -14.10511, 34.55112 -14.105...
635  POLYGON ((34.11428 -13.51146, 34.11433 -13.511...
636  POLYGON ((33.83543 -12.71008, 33.83513 -12.710...
637  POLYGON ((34.23469 -13.79907, 34.23487 -13.799...
638  POLYGON ((33.32302 -13.61615, 33.32316 -13.616...
639  POLYGON ((34.02180 -12.23521, 34.02189 -12.235...
640  POLYGON ((34.74347 -14.43690, 34.74311 -14.437...
641  POLYGON ((33.91862 -13.01736, 33.91902 -13.018...
642  POLYGON ((34.55097 -14.10511, 34.55013 -14.105...
643  POLYGON ((33.12338 -9.47999, 33.12674 -9.48216...
644  POLYGON ((33.93912 -9.71145, 33.93913 -9.71145...
645  POLYGON ((34.05679 -11.09752, 34.05643 -11.098...
646  POLYGON ((34.17788 -10.58138, 34.17764 -10.582...
647  MULTIPOLYGON (((34.76880 -12.09417, 34.72768 -...
648  POLYGON ((34.21864 -10.99802, 34.21811 -10.998...
649  POLYGON ((34.98998 -15.35162, 34.99060 -15.352...
650  POLYGON ((34.35413 -15.74093, 34.35423 -15.740...
651  POLYGON ((35.32699 -15.68119, 35.32679 -15.681...
652  POLYGON ((34.87076 -13.48135, 34.88036 -13.481...
653  POLYGON ((35.26423 -16.41062, 35.26285 -16.415...
654  POLYGON ((35.30779 -15.99527, 35.30823 -15.995...
655  POLYGON ((35.81141 -15.19836, 35.85579 -15.368...
656  POLYGON ((35.28113 -14.77873, 35.28114 -14.779...
657  POLYGON ((35.87416 -14.66025, 35.88554 -14.673...
658  POLYGON ((35.82683 -15.93358, 35.81128 -15.944...
659  POLYGON ((35.82683 -15.93358, 35.81052 -15.931...
660  POLYGON ((34.07776 -9.52866, 34.08186 -9.53283...
661  POLYGON ((34.59694 -15.20780, 34.59711 -15.208...
662  POLYGON ((34.73045 -15.81679, 34.72963 -15.816...
120 MYS Malaysia
       OBJECTID  ADM2_CODE         ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
27966 27,967.00      37337        Batu Pahit       1000       3000       1891
27967 27,968.00      37338       Johor Bahru       1000       3000       1891
27968 27,969.00      37339            Kluang       1000       3000       1891
27969 27,970.00      37340       Kota Tinggi       1000       3000       1891
27970 27,971.00      37341           Mersing       1000       3000       1891
...         ...        ...               ...        ...        ...        ...
28094 28,095.00      37466           Kemaman       1000       3000       1904
28095 28,096.00      37467  Kuala Terengganu       1000       3000       1904
28096 28,097.00      37468            Marang       1000       3000       1904
28097 28,098.00      37469             Setiu       1000       3000       1904
28098 28,099.00      37367            Labuan       1000       3000      37336

        ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
27966       Johor  Member State        NO        153  Malaysia        1.82
27967       Johor  Member State        NO        153  Malaysia        2.48
27968       Johor  Member State        NO        153  Malaysia        2.38
27969       Johor  Member State        NO        153  Malaysia        2.92
27970       Johor  Member State        NO        153  Malaysia        3.90
...           ...           ...       ...        ...       ...         ...
28094  Terengganu  Member State        NO        153  Malaysia        2.80
28095  Terengganu  Member State        NO        153  Malaysia        1.58
28096  Terengganu  Member State        NO        153  Malaysia        1.46
28097  Terengganu  Member State        NO        153  Malaysia        1.98
28098      Labuan  Member State        NO        153  Malaysia        0.61

       Shape_Le_1  Shape_Area  \
27966        1.82        0.16
27967        2.48        0.15
27968        2.38        0.23
27969        2.92        0.29
27970        3.90        0.23
...           ...         ...
28094        2.80        0.21
28095        1.58        0.05
28096        1.46        0.06
28097        1.98        0.11
28098        0.61        0.01

                                                geometry
27966  POLYGON ((103.10220 2.16696, 103.16735 2.15079...
27967  MULTIPOLYGON (((104.01806 1.52115, 104.01118 1...
27968  POLYGON ((103.56063 2.05186, 103.56721 1.94632...
27969  POLYGON ((104.06379 2.05202, 104.06441 2.05005...
27970  MULTIPOLYGON (((104.08634 2.21178, 104.09494 2...
...                                                  ...
28094  POLYGON ((103.45862 4.59553, 103.46101 4.58745...
28095  MULTIPOLYGON (((103.05982 5.44247, 103.06666 5...
28096  MULTIPOLYGON (((103.27483 5.20620, 103.27161 5...
28097  POLYGON ((102.70108 5.69801, 102.70519 5.69340...
28098  MULTIPOLYGON (((115.12571 5.22984, 115.12955 5...

[133 rows x 15 columns]
121 MDV Maldives
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
29511 29,512.00      19345  Administrative unit not available       1000
29512 29,513.00      19348  Administrative unit not available       1000
29513 29,514.00      19351  Administrative unit not available       1000
29514 29,515.00      19353  Administrative unit not available       1000
29515 29,516.00      19354  Administrative unit not available       1000
29516 29,517.00      19356  Administrative unit not available       1000
29517 29,518.00      19357  Administrative unit not available       1000
29518 29,519.00      19359  Administrative unit not available       1000
29519 29,520.00      19360  Administrative unit not available       1000
29520 29,521.00      19362  Administrative unit not available       1000
29521 29,522.00      19363  Administrative unit not available       1000
29522 29,523.00      19364  Administrative unit not available       1000
29523 29,524.00      19350  Administrative unit not available       1000
29524 29,525.00      19349  Administrative unit not available       1000
29525 29,526.00      19365  Administrative unit not available       1000
29526 29,527.00      19346  Administrative unit not available       1000
29527 29,528.00      19355  Administrative unit not available       1000
29528 29,529.00      19358  Administrative unit not available       1000
29529 29,530.00      19347  Administrative unit not available       1000
29530 29,531.00      19361  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE     ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
29511       3000       1905   Alifu Alifu  Member State        NO        154
29512       3000       1908        Dhaalu  Member State        NO        154
29513       3000       1911  Gaafu Dhaalu  Member State        NO        154
29514       3000       1913     Haa Alifu  Member State        NO        154
29515       3000       1914    Haa Dhaalu  Member State        NO        154
29516       3000       1916         Laamu  Member State        NO        154
29517       3000       1917     Lhaviyani  Member State        NO        154
29518       3000       1919         Meemu  Member State        NO        154
29519       3000       1920         Noonu  Member State        NO        154
29520       3000       1922         Seenu  Member State        NO        154
29521       3000       1923     Shaviyani  Member State        NO        154
29522       3000       1924          Thaa  Member State        NO        154
29523       3000       1910   Gaafu Alifu  Member State        NO        154
29524       3000       1909         Faafu  Member State        NO        154
29525       3000       1925         Vaavu  Member State        NO        154
29526       3000       1906  Alifu Dhaalu  Member State        NO        154
29527       3000       1915         Kaafu  Member State        NO        154
29528       3000       1918         Male'  Member State        NO        154
29529       3000       1907           Baa  Member State        NO        154
29530       3000       1921           Raa  Member State        NO        154

      ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
29511  Maldives        0.33        0.33        0.00
29512  Maldives        0.60        0.60        0.00
29513  Maldives        1.99        1.99        0.00
29514  Maldives        1.15        1.15        0.00
29515  Maldives        1.22        1.22        0.00
29516  Maldives        1.39        1.39        0.00
29517  Maldives        0.93        0.93        0.00
29518  Maldives        0.59        0.59        0.00
29519  Maldives        1.27        1.27        0.00
29520  Maldives        0.76        0.76        0.00
29521  Maldives        1.14        1.14        0.00
29522  Maldives        1.08        1.08        0.00
29523  Maldives        1.24        1.24        0.00
29524  Maldives        0.21        0.21        0.00
29525  Maldives        0.25        0.25        0.00
29526  Maldives        0.81        0.81        0.00
29527  Maldives        1.54        1.54        0.00
29528  Maldives        0.08        0.08        0.00
29529  Maldives        0.96        0.96        0.00
29530  Maldives        1.20        1.20        0.00

                                                geometry
29511  MULTIPOLYGON (((72.88086 3.94299, 72.88067 3.9...
29512  MULTIPOLYGON (((72.90279 2.66601, 72.90253 2.6...
29513  MULTIPOLYGON (((73.19906 0.19213, 73.19963 0.1...
29514  MULTIPOLYGON (((73.21797 6.82254, 73.21824 6.8...
29515  MULTIPOLYGON (((72.63922 6.31567, 72.63897 6.3...
29516  MULTIPOLYGON (((73.35259 1.78057, 73.35300 1.7...
29517  MULTIPOLYGON (((73.51402 5.24414, 73.51351 5.2...
29518  MULTIPOLYGON (((73.42108 2.76357, 73.41980 2.7...
29519  MULTIPOLYGON (((73.32935 5.64455, 73.32832 5.6...
29520  MULTIPOLYGON (((73.18325 -0.69243, 73.18303 -0...
29521  MULTIPOLYGON (((73.13248 5.95123, 73.13187 5.9...
29522  MULTIPOLYGON (((73.03342 2.16399, 73.03342 2.1...
29523  MULTIPOLYGON (((73.54257 0.35327, 73.54219 0.3...
29524  MULTIPOLYGON (((72.89182 3.05919, 72.89310 3.0...
29525  MULTIPOLYGON (((73.47029 3.31342, 73.47004 3.3...
29526  MULTIPOLYGON (((72.82533 3.47440, 72.82326 3.4...
29527  MULTIPOLYGON (((73.41803 3.81209, 73.41795 3.8...
29528  MULTIPOLYGON (((73.50165 4.17055, 73.50084 4.1...
29529  MULTIPOLYGON (((72.87770 4.87683, 72.87715 4.8...
29530  MULTIPOLYGON (((72.91851 5.36225, 72.92031 5.3...
122 MLI Mali
      OBJECTID  ADM2_CODE       ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
5924  5,925.00      19372         Ansongo       1000       3000       1927
5925  5,926.00      19373          Bourem       1000       3000       1927
5926  5,927.00      19374             Gao       1000       3000       1927
5927  5,928.00      19375          Menaka       1000       3000       1927
5928  5,929.00      19376       Bafoulabe       1000       3000       1928
5929  5,930.00      19377           Diema       1000       3000       1928
5930  5,931.00      19378           Kayes       1000       3000       1928
5931  5,932.00      19379         Kenieba       1000       3000       1928
5932  5,933.00      19380            Kita       1000       3000       1928
5933  5,934.00      19381           Nioro       1000       3000       1928
5934  5,935.00      19382        Yelimane       1000       3000       1928
5935  5,936.00      19383        Abeibara       1000       3000       1929
5936  5,937.00      19384           Kidal       1000       3000       1929
5937  5,938.00      19385        Tessalit       1000       3000       1929
5938  5,939.00      19386      Tin-Essako       1000       3000       1929
5939  5,940.00      19387         Banamba       1000       3000       1930
5940  5,941.00      19388          Dioila       1000       3000       1930
5941  5,942.00      19389         Kangaba       1000       3000       1930
5942  5,943.00      19391        Kolokani       1000       3000       1930
5943  5,944.00      19392       Koulikoro       1000       3000       1930
5944  5,945.00      19393            Nara       1000       3000       1930
5945  5,946.00      19394      Bandiagara       1000       3000       1931
5946  5,947.00      19395         Bankass       1000       3000       1931
5947  5,948.00      19396          Djenne       1000       3000       1931
5948  5,949.00      19397        Douentza       1000       3000       1931
5949  5,950.00      19398            Koro       1000       3000       1931
5950  5,951.00      19399           Mopti       1000       3000       1931
5951  5,952.00      19400        Tenenkou       1000       3000       1931
5952  5,953.00      19401        Youwarou       1000       3000       1931
5953  5,954.00      19402        Baroueli       1000       3000       1932
5954  5,955.00      19403             Bla       1000       3000       1932
5955  5,956.00      19404          Macina       1000       3000       1932
5956  5,957.00      19405           Niono       1000       3000       1932
5957  5,958.00      19406             San       1000       3000       1932
5958  5,959.00      19407           Segou       1000       3000       1932
5959  5,960.00      19408        Tominian       1000       3000       1932
5960  5,961.00      19409        Bougouni       1000       3000       1933
5961  5,962.00      19410         Kadiolo       1000       3000       1933
5962  5,963.00      19411      Kolondieba       1000       3000       1933
5963  5,964.00      19412        Koutiala       1000       3000       1933
5964  5,965.00      19413         Sikasso       1000       3000       1933
5965  5,966.00      19414       Yanfolila       1000       3000       1933
5966  5,967.00      19415         Yorosso       1000       3000       1933

      OBJECTID  ADM2_CODE              ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
7883  7,884.00      19546         Aguascalientes       1000       3000
7884  7,885.00      19547               Asientos       1000       3000
7885  7,886.00      19548               Calvillo       1000       3000
7886  7,887.00      19549                  Cosio       1000       3000
7887  7,888.00      19550            Jesus Maria       1000       3000
...        ...        ...                    ...        ...        ...
9769  9,770.00      21433           Villa Garcia       1000       3000
9770  9,771.00      21434  Villa Gonzalez Ortega       1000       3000
9771  9,772.00      21435          Villa Hidalgo       1000       3000
9772  9,773.00      21436             Villanueva       1000       3000
9773  9,774.00      21437              Zacatecas       1000       3000

      ADM1_CODE       ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
7883       2028  Aguascalientes  Member State        NO        162    Mexico
7884       2028  Aguascalientes  Member State        NO        162    Mexico
7885       2028  Aguascalientes  Member State        NO        162    Mexico
7886       2028  Aguascalientes  Member State        NO        162    Mexico
7887       2028  Aguascalientes  Member State        NO        162    Mexico
...         ...             ...           ...       ...        ...       ...
9769       2059       Zacatecas  Member State        NO        162    Mexico
9770       2059       Zacatecas  Member State        NO        162    Mexico
9771       2059       Zacatecas  Member State        NO        162    Mexico
9772       2059       Zacatecas  Member State        NO        162    Mexico
9773       2059       Zacatecas  Member State        NO        162    Mexico

      Shape_Leng  Shape_Le_1  Shape_Area  \
7883        1.94        1.94        0.15
7884        1.03        1.03        0.04
7885        1.13        1.13        0.07
7886        0.56        0.56        0.02
7887        1.03        1.03        0.05
...          ...         ...         ...
9769        0.72        0.72        0.03
9770        0.79        0.79        0.03
9771        0.75        0.75        0.03
9772        2.17        2.17        0.21
9773        0.94        0.94        0.04

                                               geometry
7883  POLYGON ((-101.97523 21.97482, -101.97407 21.9...
7884  POLYGON ((-102.03757 22.20212, -102.03603 22.1...
7885  POLYGON ((-102.59671 21.93790, -102.59940 21.9...
7886  POLYGON ((-102.25325 22.34533, -102.25325 22.3...
7887  POLYGON ((-102.31575 22.00657, -102.30292 22.0...
...                                                 ...
9769  POLYGON ((-101.82023 22.15013, -101.82001 22.1...
9770  POLYGON ((-101.89475 22.62381, -101.88847 22.6...
9771  POLYGON ((-101.81467 22.28739, -101.81788 22.2...
9772  POLYGON ((-102.72421 22.56988, -102.72145 22.5...
9773  POLYGON ((-102.76154 22.80843, -102.75473 22.8...

[1891 rows x 15 columns]
128 FSM Micronesia, Fed. Sts.
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
129 MDA Moldova
       OBJECTID  ADM2_CODE          ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
33746 33,747.00      41166              Balti       1000       3000
33747 33,748.00      41167            Falesti       1000       3000
33748 33,749.00      41168            Glodeni       1000       3000
33749 33,750.00      41169            Riscani       1000       3000
33750 33,751.00      41170           Singerei       1000       3000
33751 33,752.00      41171              Cahul       1000       3000
33752 33,753.00      41172           Cantemir       1000       3000
33753 33,754.00      41173           Taraclia       1000       3000
33754 33,755.00      41174         Vulcanesti       1000       3000
33755 33,756.00      41175         Anenii Noi       1000       3000
33756 33,757.00      41176           Criuleni       1000       3000
33757 33,758.00      41177           Ialoveni       1000       3000
33758 33,759.00      41178           Straseni       1000       3000
33759 33,760.00      41179           Chisinau       1000       3000
33760 33,761.00      41180            Camenca       1000       3000
33761 33,762.00      41181           Dubasari       1000       3000
33762 33,763.00      41182        Grigoriopol       1000       3000
33763 33,764.00      41183             Rbnita       1000       3000
33764 33,765.00      41184           Slobozia       1000       3000
33765 33,766.00      41185  Tighina (Bendery)       1000       3000
33766 33,767.00      41186           Tiraspol       1000       3000
33767 33,768.00      41187            Briceni       1000       3000
33768 33,769.00      41188          Donduseni       1000       3000
33769 33,770.00      41189             Edinet       1000       3000
33770 33,771.00      41190             Ocnita       1000       3000
33771 33,772.00      41191       Ciadir-Lunga       1000       3000
33772 33,773.00      41192             Comrat       1000       3000
33773 33,774.00      41193       Basarabeasca       1000       3000
33774 33,775.00      41194           Cimislia       1000       3000
33775 33,776.00      41195           Hincesti       1000       3000
33776 33,777.00      41196              Leova       1000       3000
33777 33,778.00      41197              Orhei       1000       3000
33778 33,779.00      41198             Rezina       1000       3000
33779 33,780.00      41199          Telenesti       1000       3000
33780 33,781.00      41200            Drochia       1000       3000
33781 33,782.00      41201           Floresti       1000       3000
33782 33,783.00      41202         Soldanesti       1000       3000
33783 33,784.00      41203             Soroca       1000       3000
33784 33,785.00      41204            Cainari       1000       3000
33785 33,786.00      41205            Causeni       1000       3000
33786 33,787.00      41206        Stefan Voda       1000       3000
33787 33,788.00      41207            Calaras       1000       3000
33788 33,789.00      41208          Nisporeni       1000       3000
33789 33,790.00      41209            Ungheni       1000       3000

       ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
33746       2062     Balti  Member State        NO        165   Moldova
33747       2062     Balti  Member State        NO        165   Moldova
33748       2062     Balti  Member State        NO        165   Moldova
33749       2062     Balti  Member State        NO        165   Moldova
33750       2062     Balti  Member State        NO        165   Moldova
33751       2063     Cahul  Member State        NO        165   Moldova
33752       2063     Cahul  Member State        NO        165   Moldova
33753       2063     Cahul  Member State        NO        165   Moldova
33754       2063     Cahul  Member State        NO        165   Moldova
33755       2064  Chisinau  Member State        NO        165   Moldova
33756       2064  Chisinau  Member State        NO        165   Moldova
33757       2064  Chisinau  Member State        NO        165   Moldova
33758       2064  Chisinau  Member State        NO        165   Moldova
33759       2064  Chisinau  Member State        NO        165   Moldova
33760       2066  Dubasari  Member State        NO        165   Moldova
33761       2066  Dubasari  Member State        NO        165   Moldova
33762       2066  Dubasari  Member State        NO        165   Moldova
33763       2066  Dubasari  Member State        NO        165   Moldova
33764       2066  Dubasari  Member State        NO        165   Moldova
33765       2066  Dubasari  Member State        NO        165   Moldova
33766       2066  Dubasari  Member State        NO        165   Moldova
33767       2067    Edinet  Member State        NO        165   Moldova
33768       2067    Edinet  Member State        NO        165   Moldova
33769       2067    Edinet  Member State        NO        165   Moldova
33770       2067    Edinet  Member State        NO        165   Moldova
33771       2068  Gagauzia  Member State        NO        165   Moldova
33772       2068  Gagauzia  Member State        NO        165   Moldova
33773       2069   Lapusna  Member State        NO        165   Moldova
33774       2069   Lapusna  Member State        NO        165   Moldova
33775       2069   Lapusna  Member State        NO        165   Moldova
33776       2069   Lapusna  Member State        NO        165   Moldova
33777       2070     Orhei  Member State        NO        165   Moldova
33778       2070     Orhei  Member State        NO        165   Moldova
33779       2070     Orhei  Member State        NO        165   Moldova
33780       2071    Soroca  Member State        NO        165   Moldova
33781       2071    Soroca  Member State        NO        165   Moldova
33782       2071    Soroca  Member State        NO        165   Moldova
33783       2071    Soroca  Member State        NO        165   Moldova
33784       2072   Tighina  Member State        NO        165   Moldova
33785       2072   Tighina  Member State        NO        165   Moldova
33786       2072   Tighina  Member State        NO        165   Moldova
33787       2073   Ungheni  Member State        NO        165   Moldova
33788       2073   Ungheni  Member State        NO        165   Moldova
33789       2073   Ungheni  Member State        NO        165   Moldova

       Shape_Leng  Shape_Le_1  Shape_Area  \
33746        0.66        0.66        0.01
33747        2.02        2.02        0.12
33748        1.62        1.62        0.09
33749        2.32        2.32        0.11
33750        2.27        2.27        0.12
33751        1.33        1.33        0.08
33752        1.69        1.69        0.09
33753        1.50        1.50        0.08
33754        1.75        1.75        0.11
33755        2.34        2.34        0.10
33756        2.01        2.01        0.10
33757        1.90        1.90        0.08
33758        1.92        1.92        0.09
33759        1.04        1.04        0.02
33760        1.84        1.84        0.11
33761        2.14        2.14        0.10
33762        2.14        2.14        0.12
33763        2.04        2.04        0.14
33764        2.36        2.36        0.13
33765        0.33        0.33        0.01
33766        0.39        0.39        0.01
33767        2.43        2.43        0.10
33768        1.87        1.87        0.11
33769        1.67        1.67        0.10
33770        1.77        1.77        0.09
33771        1.78        1.78        0.09
33772        1.94        1.94        0.10
33773        1.66        1.66        0.07
33774        1.64        1.64        0.09
33775        2.39        2.39        0.13
33776        1.58        1.58        0.08
33777        2.01        2.01        0.13
33778        1.88        1.88        0.08
33779        1.77        1.77        0.10
33780        1.85        1.85        0.09
33781        1.69        1.69        0.09
33782        1.71        1.71        0.07
33783        2.41        2.41        0.13
33784        1.83        1.83        0.09
33785        2.00        2.00        0.08
33786        2.52        2.52        0.12
33787        1.62        1.62        0.09
33788        1.86        1.86        0.09
33789        2.14        2.14        0.10

                                                geometry
33746  POLYGON ((27.90752 47.78876, 27.91097 47.77365...
33747  POLYGON ((27.82810 47.72322, 27.80126 47.70985...
33748  POLYGON ((27.82586 47.75341, 27.81769 47.75107...
33749  POLYGON ((27.55403 48.04542, 27.55867 48.03825...
33750  POLYGON ((28.34297 47.66832, 28.35688 47.64442...
33751  POLYGON ((28.40834 46.07038, 28.42465 46.07030...
33752  POLYGON ((28.40814 46.40952, 28.42209 46.39913...
33753  POLYGON ((28.55735 46.02439, 28.54799 46.01093...
33754  POLYGON ((28.53548 45.72766, 28.52933 45.72248...
33755  POLYGON ((29.25314 47.10318, 29.27057 47.08801...
33756  POLYGON ((29.25671 47.13176, 29.25314 47.10318...
33757  POLYGON ((28.72796 47.01677, 28.74306 46.99842...
33758  POLYGON ((28.74240 47.17633, 28.72359 47.11845...
33759  POLYGON ((28.78986 47.06491, 28.80849 47.06085...
33760  POLYGON ((28.58147 48.16730, 28.58207 48.16177...
33761  POLYGON ((29.39403 47.31722, 29.34570 47.28144...
33762  POLYGON ((29.64420 46.94721, 29.64419 46.94721...
33763  POLYGON ((29.16100 47.51287, 29.16100 47.51287...
33764  POLYGON ((29.90989 46.52491, 29.90988 46.52492...
33765  POLYGON ((29.49105 46.76607, 29.47469 46.75185...
33766  POLYGON ((29.52496 46.86715, 29.56161 46.86629...
33767  POLYGON ((27.23113 48.37433, 27.22400 48.35836...
33768  POLYGON ((27.99854 48.32611, 27.95669 48.28016...
33769  POLYGON ((27.25977 48.23508, 27.29941 48.24203...
33770  POLYGON ((27.65392 48.44619, 27.68260 48.44354...
33771  POLYGON ((29.05500 46.20681, 29.05595 46.20625...
33772  POLYGON ((28.72155 46.39848, 28.73081 46.37937...
33773  POLYGON ((28.93282 46.53049, 29.01905 46.52928...
33774  POLYGON ((28.93282 46.53049, 28.90020 46.53144...
33775  POLYGON ((28.32358 46.99569, 28.33515 46.96783...
33776  POLYGON ((28.55328 46.63955, 28.53575 46.62216...
33777  POLYGON ((28.96238 47.49932, 28.98213 47.47937...
33778  POLYGON ((28.96238 47.49932, 28.94375 47.50577...
33779  POLYGON ((28.56791 47.68867, 28.55389 47.67682...
33780  POLYGON ((27.90047 48.17797, 27.95630 48.14276...
33781  POLYGON ((28.41488 47.96025, 28.43236 47.96255...
33782  POLYGON ((28.87021 47.86830, 28.89230 47.84992...
33783  POLYGON ((28.10338 48.23443, 28.10763 48.23411...
33784  POLYGON ((29.07220 46.78398, 29.08148 46.76805...
33785  POLYGON ((29.41070 46.78631, 29.41653 46.78469...
33786  POLYGON ((29.90989 46.52491, 29.91180 46.52269...
33787  POLYGON ((28.45640 47.40170, 28.45638 47.39455...
33788  POLYGON ((28.28785 47.13564, 28.29599 47.12687...
33789  POLYGON ((27.90304 47.44090, 27.91351 47.43450...
130 MCO Monaco
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
37184 37,185.00      21452  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE                          ADM1_NAME        STATUS  \
37184       3000       2074  Administrative unit not available  Member State

      DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
37184        NO        166    Monaco        0.14        0.14        0.00

                                                geometry
37184  POLYGON ((7.45229 43.76189, 7.44674 43.75750, ...
131 MNG Mongolia
       OBJECTID  ADM2_CODE     ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
22654 22,655.00     123574      Bayangol       2011       3000       2095
22655 22,656.00     123575    Bayanzu'rx       2011       3000       2095
22656 22,657.00     123576        Nalaix       2011       3000       2095
22657 22,658.00     123577   Bayantu'men       2011       3000       2081
22658 22,659.00     123578   Cagaan-Ovoo       2011       3000       2081
...         ...        ...           ...        ...        ...        ...
22985 22,986.00      21622       U'yench       1000       3000       2087
22986 22,987.00      21755   Zu'unxangai       1000       3000       2096
22987 22,988.00      21742    Naranbulag       1000       3000       2096
22988 22,989.00      21743        O'lgii       1000       3000       2096
22989 22,990.00      21745  O'ndorxangai       1000       3000       2096

         ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
22654  Ulaanbaatar  Member State        NO        167  Mongolia        0.35
22655  Ulaanbaatar  Member State        NO        167  Mongolia        1.79
22656  Ulaanbaatar  Member State        NO        167  Mongolia        1.41
22657       Dornod  Member State        NO        167  Mongolia        6.67
22658       Dornod  Member State        NO        167  Mongolia        4.08
...            ...           ...       ...        ...       ...         ...
22985         Xovd  Member State        NO        167  Mongolia        5.57
22986          Uvs  Member State        NO        167  Mongolia        2.96
22987          Uvs  Member State        NO        167  Mongolia        3.71
22988          Uvs  Member State        NO        167  Mongolia        2.83
22989          Uvs  Member State        NO        167  Mongolia        3.14

       Shape_Le_1  Shape_Area  \
22654        0.35        0.00
22655        1.79        0.15
22656        1.41        0.08
22657        6.67        1.05
22658        4.08        0.79
...           ...         ...
22985        5.57        0.85
22986        2.96        0.33
22987        3.71        0.64
22988        2.83        0.29
22989        3.14        0.57

                                                geometry
22654  POLYGON ((106.89451 47.91539, 106.89470 47.912...
22655  POLYGON ((107.08255 48.20855, 107.09061 48.200...
22656  POLYGON ((107.47566 47.65186, 107.47564 47.651...
22657  POLYGON ((115.78810 48.51937, 115.78369 48.514...
22658  POLYGON ((113.65824 48.78986, 113.62150 48.728...
...                                                  ...
22985  POLYGON ((92.33354 46.43714, 92.30920 46.40980...
22986  POLYGON ((95.66940 49.37844, 95.68892 49.35669...
22987  POLYGON ((92.85582 50.02919, 92.85896 50.02769...
22988  POLYGON ((92.54021 48.89139, 92.53918 48.85319...
22989  POLYGON ((95.02260 49.57073, 95.06997 49.54171...

[336 rows x 15 columns]
132 MNE Montenegro
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
35927 35,928.00      47603  Administrative unit not available       1000
35928 35,929.00      47604  Administrative unit not available       1000
35929 35,930.00      47605  Administrative unit not available       1000
35930 35,931.00      47606  Administrative unit not available       1000
35931 35,932.00      47607  Administrative unit not available       1000
35932 35,933.00      47608  Administrative unit not available       1000
35933 35,934.00      47609  Administrative unit not available       1000
35934 35,935.00      47610  Administrative unit not available       1000
35935 35,936.00      47611  Administrative unit not available       1000
35936 35,937.00      47612  Administrative unit not available       1000
35937 35,938.00      47613  Administrative unit not available       1000
35938 35,939.00      47614  Administrative unit not available       1000
35939 35,940.00      47615  Administrative unit not available       1000
35940 35,941.00      47616  Administrative unit not available       1000
35941 35,942.00      47617  Administrative unit not available       1000
35942 35,943.00      47618  Administrative unit not available       1000
35943 35,944.00      47619  Administrative unit not available       1000
35944 35,945.00      47620  Administrative unit not available       1000
35945 35,946.00      47621  Administrative unit not available       1000
35946 35,947.00      47622  Administrative unit not available       1000
35947 35,948.00      47623  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE     ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
35927       3000      25350   Andrijevica  Member State        NO       2647
35928       3000      25351           Bar  Member State        NO       2647
35929       3000      25352        Berane  Member State        NO       2647
35930       3000      25353  Bijelo Polje  Member State        NO       2647
35931       3000      25354         Budva  Member State        NO       2647
35932       3000      25355       Cetinje  Member State        NO       2647
35933       3000      25356   Danilovgrad  Member State        NO       2647
35934       3000      25357   Herceg Novi  Member State        NO       2647
35935       3000      25358       Kolasin  Member State        NO       2647
35936       3000      25359         Kotor  Member State        NO       2647

       OBJECTID  ADM2_CODE    ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
29800 29,801.00      22351      Bagmati       1000       3000       2152
29801 29,802.00      22352     Janakpur       1000       3000       2152
29802 29,803.00      22353     Narayani       1000       3000       2152
29803 29,804.00      22354        Koshi       1000       3000       2153
29804 29,805.00      22355        Mechi       1000       3000       2153
29805 29,806.00      22356   Sagarmatha       1000       3000       2153
29806 29,807.00      22357     Mahakali       1000       3000       2154
29807 29,808.00      22358         Seti       1000       3000       2154
29808 29,809.00      22359      Karnali       1000       3000       2155
29809 29,810.00      22360        Rapti       1000       3000       2155
29810 29,811.00      22361        Bheri       1000       3000       2155
29811 29,812.00      22362  Dhawalagiri       1000       3000       2156
29812 29,813.00      22363      Gandaki       1000       3000       2156
29813 29,814.00      22364      Lumbini       1000       3000       2156

         ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
29800      Central  Member State        NO        175     Nepal        4.63
29801      Central  Member State        NO        175     Nepal        5.91
29802      Central  Member State        NO        175     Nepal        5.41
29803      Eastern  Member State        NO        175     Nepal        5.95
29804      Eastern  Member State        NO        175     Nepal        5.09
29805      Eastern  Member State        NO        175     Nepal        5.62
29806  Far Western  Member State        NO        175     Nepal        5.52
29807  Far Western  Member State        NO        175     Nepal        7.18
29808  Mid Western  Member State        NO        175     Nepal        8.92
29809  Mid Western  Member State        NO        175     Nepal        5.59
29810  Mid Western  Member State        NO        175     Nepal        7.16
29811      Western  Member State        NO        175     Nepal        5.18
29812      Western  Member State        NO        175     Nepal        5.76
29813      Western  Member State        NO        175     Nepal        5.82

       Shape_Le_1  Shape_Area  \
29800        4.63        0.87
29801        5.91        0.87
29802        5.41        0.77
29803        5.95        0.88
29804        5.09        0.73
29805        5.62        0.97
29806        5.52        0.63
29807        7.18        1.20
29808        8.92        2.00
29809        5.59        1.01
29810        7.16        0.94
29811        5.18        0.76
29812        5.76        1.14
29813        5.82        0.80

                                                geometry
29800  POLYGON ((85.74162 28.25937, 85.74381 28.24986...
29801  POLYGON ((86.20996 28.09387, 86.19829 28.08569...
29802  POLYGON ((84.67713 27.82859, 84.66774 27.81904...
29803  POLYGON ((87.68966 27.81014, 87.68213 27.76719...
29804  POLYGON ((87.87269 27.91286, 87.87624 27.91237...
29805  POLYGON ((86.61545 28.07094, 86.61545 28.07094...
29806  POLYGON ((80.94473 30.18200, 80.95922 30.18140...
29807  POLYGON ((81.17227 30.01268, 81.17227 30.01268...
29808  POLYGON ((81.70794 30.41698, 81.72098 30.41079...
29809  POLYGON ((82.76042 28.83045, 82.79868 28.81675...
29810  POLYGON ((81.58369 29.05377, 81.60454 29.03679...
29811  POLYGON ((84.00000 29.31804, 84.00210 29.31571...
29812  POLYGON ((84.23558 28.89241, 84.24048 28.89201...
29813  POLYGON ((83.60558 28.01338, 83.59274 27.99117...
139 NLD Netherlands
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
37211 37,212.00      22366  Administrative unit not available       1000
37212 37,213.00      22367  Administrative unit not available       1000
37213 37,214.00      22368  Administrative unit not available       1000
37214 37,215.00      22369  Administrative unit not available       1000
37215 37,216.00      22370  Administrative unit not available       1000
37216 37,217.00      22371  Administrative unit not available       1000
37217 37,218.00      22372  Administrative unit not available       1000
37218 37,219.00      22373  Administrative unit not available       1000
37219 37,220.00      22374  Administrative unit not available       1000
37220 37,221.00      22375  Administrative unit not available       1000
37221 37,222.00      22376  Administrative unit not available       1000
37222 37,223.00      22377  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
37211       3000       2158        Drenthe  Member State        NO        177
37212       3000       2159      Flevoland  Member State        NO        177
37213       3000       2160      Friesland  Member State        NO        177
37214       3000       2161     Gelderland  Member State        NO        177
37215       3000       2162      Groningen  Member State        NO        177
37216       3000       2163        Limburg  Member State        NO        177
37217       3000       2164  Noord-brabant  Member State        NO        177
37218       3000       2165  Noord-holland  Member State        NO        177
37219       3000       2166     Overijssel  Member State        NO        177
37220       3000       2167        Utrecht  Member State        NO        177
37221       3000       2168        Zeeland  Member State        NO        177
37222       3000       2169   Zuid-holland  Member State        NO        177

         ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
37211  Netherlands        3.13        3.13        0.35
37212  Netherlands        2.54        2.54        0.21
37213  Netherlands        6.32        6.32        0.47
37214  Netherlands        6.15        6.15        0.67
37215  Netherlands        3.69        3.69        0.33
37216  Netherlands        4.89        4.89        0.28
37217  Netherlands        7.53        7.53        0.69
37218  Netherlands        5.72        5.72        0.38
37219  Netherlands        4.59        4.59        0.46
37220  Netherlands        3.12        3.12        0.18
37221  Netherlands        6.57        6.57        0.23
37222  Netherlands        4.30        4.30        0.37

                                                geometry
37211  POLYGON ((7.09248 52.83720, 7.07605 52.81536, ...
37212  POLYGON ((5.78380 52.80436, 5.80056 52.79333, ...
37213  MULTIPOLYGON (((5.38616 53.06479, 5.38326 53.0...
37214  POLYGON ((6.76056 52.11453, 6.75716 52.10227, ...
37215  MULTIPOLYGON (((6.77657 53.46664, 6.79760 53.4...
37216  POLYGON ((5.95777 51.74870, 5.95971 51.74400, ...
37217  MULTIPOLYGON (((4.01927 51.73022, 4.01724 51.7...
37218  MULTIPOLYGON (((4.85788 52.41783, 4.85742 52.4...
37219  POLYGON ((6.12953 52.85328, 6.13278 52.85166, ...
37220  POLYGON ((5.34712 52.28251, 5.36874 52.27700, ...
37221  MULTIPOLYGON (((4.14430 51.36079, 4.12908 51.3...
37222  MULTIPOLYGON (((4.36095 51.71828, 4.36067 51.7...
140 NCL New Caledonia
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
141 NZL New Zealand
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
37487 37,488.00      22379  Administrative unit not available       1000
37488 37,489.00      22380  Administrative unit not available       1000
37489 37,490.00      22381  Administrative unit not available       1000
37490 37,491.00      22382  Administrative unit not available       1000
37491 37,492.00      22383  Administrative unit not available       1000
37492 37,493.00      22384  Administrative unit not available       1000
37493 37,494.00      22385  Administrative unit not available       1000
37494 37,495.00      22386  Administrative unit not available       1000
37495 37,496.00      22387  Administrative unit not available       1000
37496 37,497.00      22388  Administrative unit not available       1000
37497 37,498.00      22389  Administrative unit not available       1000
37498 37,499.00      22390  Administrative unit not available       1000
37499 37,500.00      22391  Administrative unit not available       1000
37500 37,501.00      22392  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE           ADM1_NAME        STATUS DISP_AREA  \
37487       3000       2171            Auckland  Member State        NO
37488       3000       2172       Bay Of Plenty  Member State        NO
37489       3000       2173          Canterbury  Member State        NO
37490       3000       2174           East Cape  Member State        NO
37491       3000       2175         Hawke's Bay  Member State        NO
37492       3000       2176  Nelson-marlborough  Member State        NO
37493       3000       2177           Northland  Member State        NO
37494       3000       2178               Otago  Member State        NO
37495       3000       2179           Southland  Member State        NO
37496       3000       2180            Taranaki  Member State        NO
37497       3000       2181             Waikato  Member State        NO
37498       3000       2182   Wanganui-manawatu  Member State        NO
37499       3000       2183          Wellington  Member State        NO
37500       3000       2184            Westland  Member State        NO

       ADM0_CODE    ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
37487        179  New Zealand       14.12       14.12        0.55
37488        179  New Zealand        8.30        8.30        1.24
37489        179  New Zealand       14.58       14.58        4.74
37490        179  New Zealand        5.37        5.37        0.85
37491        179  New Zealand        7.63        7.63        1.52
37492        179  New Zealand       22.40       22.40        2.17
37493        179  New Zealand       15.47       15.47        1.28
37494        179  New Zealand       13.09       13.09        3.78
37495        179  New Zealand       36.22       36.22        3.79
37496        179  New Zealand        4.08        4.08        0.80
37497        179  New Zealand       12.88       12.88        2.41
37498        179  New Zealand        8.53        8.53        2.37
37499        179  New Zealand       10.96       10.96        1.04
37500        179  New Zealand       14.29       14.29        2.79

                                                geometry
37487  MULTIPOLYGON (((175.15233 -36.91847, 175.14919...
37488  MULTIPOLYGON (((176.97606 -37.85712, 176.96999...
37489  MULTIPOLYGON (((172.69901 -43.63227, 172.68985...
37490  POLYGON ((177.90125 -38.93450, 177.88750 -38.9...
37491  MULTIPOLYGON (((177.86328 -39.30803, 177.86063...
37492  MULTIPOLYGON (((173.17848 -41.29896, 173.17635...
37493  MULTIPOLYGON (((174.70038 -35.95535, 174.70996...
37494  POLYGON ((171.17180 -44.77302, 171.16885 -44.8...
37495  MULTIPOLYGON (((169.19885 -52.46692, 169.20561...
37496  POLYGON ((174.79570 -38.70984, 174.78970 -38.7...
37497  MULTIPOLYGON (((175.94353 -37.05614, 175.94041...
37498  POLYGON ((176.09410 -39.04130, 176.10020 -39.0...
37499  MULTIPOLYGON (((178.74329 -49.67636, 178.74113...
37500  MULTIPOLYGON (((171.45671 -41.83142, 171.45323...
142 NIC Nicaragua
      OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
9774  9,775.00      22393                            Bonanza       1000
9775  9,776.00      22394                        Prinzapolka       1000
9776  9,777.00      22395                     Puerto Cabezas       1000
9777  9,778.00      22396                             Rosita       1000
9778  9,779.00      22397                              Siuna       1000
...        ...        ...                                ...        ...
9927  9,928.00      22548                              Rivas       1000
9928  9,929.00      22549                          San Jorge       1000
9929  9,930.00      22550                               Tola       1000
9930  9,931.00      22413  Administrative unit not available       1000
9931  9,932.00      22431                               Isla       1000

      EXP2_YEAR  ADM1_CODE        ADM1_NAME        STATUS DISP_AREA  \
9774       3000       2185  Atlantico Norte  Member State        NO
9775       3000       2185  Atlantico Norte  Member State        NO
9776       3000       2185  Atlantico Norte  Member State        NO
9777       3000       2185  Atlantico Norte  Member State        NO
9778       3000       2185  Atlantico Norte  Member State        NO
...         ...        ...              ...           ...       ...
9927       3000       2201            Rivas  Member State        NO
9928       3000       2201            Rivas  Member State        NO
9929       3000       2201            Rivas  Member State        NO
9930       3000       2187            Boaco  Member State        NO
9931       3000       2189       Chinandega  Member State        NO

      ADM0_CODE  ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
9774        180  Nicaragua        1.79        1.79        0.15
9775        180  Nicaragua        4.16        4.16        0.54
9776        180  Nicaragua        3.61        3.61        0.45
9777        180  Nicaragua        3.32        3.32        0.39
9778        180  Nicaragua        3.08        3.08        0.39
...         ...        ...         ...         ...         ...
9927        180  Nicaragua        0.51        0.51        0.01
9928        180  Nicaragua        0.23        0.23        0.00
9929        180  Nicaragua        3.18        3.18        0.09
9930        180  Nicaragua        0.85        0.85        0.02
9931        180  Nicaragua        1.34        1.34        0.07

                                               geometry
9774  POLYGON ((-84.33352 14.24900, -84.39937 14.026...
9775  POLYGON ((-83.90936 13.90321, -83.90465 13.901...
9776  POLYGON ((-83.52577 13.56487, -83.52927 13.567...
9777  POLYGON ((-83.81542 14.40233, -83.81487 14.390...
9778  POLYGON ((-84.50761 13.85798, -84.50010 13.851...
...                                                 ...
9927  POLYGON ((-85.81892 11.44839, -85.81239 11.441...
9928  POLYGON ((-85.79176 11.45254, -85.78599 11.435...
9929  MULTIPOLYGON (((-85.77350 11.10809, -85.77384 ...
9930  POLYGON ((-85.77187 12.09338, -85.76441 12.082...
9931  POLYGON ((-86.67999 12.48180, -86.67637 12.472...

[158 rows x 15 columns]
143 NER Niger
      OBJECTID  ADM2_CODE         ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
5828  5,829.00      22551             Arlit       1000       3000       2202
5829  5,830.00      22552             Bilma       1000       3000       2202
5830  5,831.00      22553     Tchighozerine       1000       3000       2202
5831  5,832.00      22554             Diffa       1000       3000       2203
5832  5,833.00      22555       Maine-soroa       1000       3000       2203
5833  5,834.00      22556          N'guigmi       1000       3000       2203
5834  5,835.00      22557    Birni N'gaoure       1000       3000       2204
5835  5,836.00      22558      Dogondoutchi       1000       3000       2204
5836  5,837.00      22559             Dosso       1000       3000       2204
5837  5,838.00      22560              Gaya       1000       3000       2204
5838  5,839.00      22561              Loga       1000       3000       2204
5839  5,840.00      22562             Aguie       1000       3000       2205
5840  5,841.00      22563            Dakoro       1000       3000       2205
5841  5,842.00      22564     Guidan Roumji       1000       3000       2205
5842  5,843.00      22565        Madarounfa       1000       3000       2205
5843  5,844.00      22566            Mayahi       1000       3000       2205
5844  5,845.00      22567          Tessaoua       1000       3000       2205
5845  5,846.00      22568         Commune 1       1000       3000       2206
5846  5,847.00      22569         Commune 2       1000       3000       2206
5847  5,848.00      22570         Commune 3       1000       3000       2206
5848  5,849.00      22571     Birni N'konni       1000       3000       2207
5849  5,850.00      22572             Bouza       1000       3000       2207
5850  5,851.00      22573            Illela       1000       3000       2207
5851  5,852.00      22574             Keita       1000       3000       2207
5852  5,853.00      22575           Madaoua       1000       3000       2207
5853  5,854.00      22576            Tahoua       1000       3000       2207
5854  5,855.00      22577  Tchin Tabaradene       1000       3000       2207
5855  5,856.00      22578          Filingue       1000       3000       2208
5856  5,857.00      22579             Kollo       1000       3000       2208
5857  5,858.00      22580           Ouallam       1000       3000       2208
5858  5,859.00      22581               Say       1000       3000       2208
5859  5,860.00      22582              Tera       1000       3000       2208
5860  5,861.00      22583         Tillaberi       1000       3000       2208
5861  5,862.00      22584             Goure       1000       3000       2209
5862  5,863.00      22585           Magaria       1000       3000       2209
5863  5,864.00      22586           Matamey       1000       3000       2209
5864  5,865.00      22587             Miria       1000       3000       2209
5865  5,866.00      22588            Tanout       1000       3000       2209

      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
5828     Agadez  Member State        NO        181     Niger       17.76
5829     Agadez  Member State        NO        181     Niger       20.61
5830     Agadez  Member State        NO        181     Niger       19.45
5831      Diffa  Member State        NO        181     Niger        5.27
5832      Diffa  Member State        NO        181     Niger        5.79
5833      Diffa  Member State        NO        181     Niger       14.01
5834      Dosso  Member State        NO        181     Niger        4.02
5835      Dosso  Member State        NO        181     Niger        5.41
5836      Dosso  Member State        NO        181     Niger        4.40
5837      Dosso  Member State        NO        181     Niger        3.38
5838      Dosso  Member State        NO        181     Niger        3.42
5839     Maradi  Member State        NO        181     Niger        2.43
5840     Maradi  Member State        NO        181     Niger        6.31
5841     Maradi  Member State        NO        181     Niger        3.45
5842     Maradi  Member State        NO        181     Niger        2.59
5843     Maradi  Member State        NO        181     Niger        3.45
5844     Maradi  Member State        NO        181     Niger        4.00
5845     Niamey  Member State        NO        181     Niger        0.35
5846     Niamey  Member State        NO        181     Niger        0.40
5847     Niamey  Member State        NO        181     Niger        0.28
5848     Tahoua  Member State        NO        181     Niger        3.50
5849     Tahoua  Member State        NO        181     Niger        2.86
5850     Tahoua  Member State        NO        181     Niger        3.95
5851     Tahoua  Member State        NO        181     Niger        3.41
5852     Tahoua  Member State        NO        181     Niger        2.69
5853     Tahoua  Member State        NO        181     Niger        4.01
5854     Tahoua  Member State        NO        181     Niger       11.88
5855  Tillaberi  Member State        NO        181     Niger        6.91
5856  Tillaberi  Member State        NO        181     Niger        6.37
5857  Tillaberi  Member State        NO        181     Niger        5.78
5858  Tillaberi  Member State        NO        181     Niger        8.10
5859  Tillaberi  Member State        NO        181     Niger        5.63
5860  Tillaberi  Member State        NO        181     Niger        4.52

       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
38199 38,200.00      23694  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE                          ADM1_NAME        STATUS  \
38199       3000       2278  Administrative unit not available  Member State

      DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
38199        NO        189     Palau        8.28        8.28        0.04

                                                geometry
38199  MULTIPOLYGON (((131.12467 2.99931, 131.12417 2...
151 PAN Panama
       OBJECTID  ADM2_CODE   ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
9932   9,933.00      23712   Aguadulce       1000       3000       2282
9933   9,934.00      23713       Antón       1000       3000       2282
9934   9,935.00      23714  La Pintada       1000       3000       2282
9935   9,936.00      23715        Natá       1000       3000       2282
9936   9,937.00      23716         Olá       1000       3000       2282
...         ...        ...         ...        ...        ...        ...
10004 10,005.00      23761    Santa Fe       1000       3000      93673
10005 10,006.00      23762    Santiago       1000       3000      93673
10006 10,007.00      23763        Soná       1000       3000      93673
10007 10,008.00      93694     Cañazas       2012       3000      93673
10008 10,009.00      93695  Las Palmas       2012       3000      93673

      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
9932      Coclé  Member State        NO        191    Panama        1.12
9933      Coclé  Member State        NO        191    Panama        1.42
9934      Coclé  Member State        NO        191    Panama        1.53
9935      Coclé  Member State        NO        191    Panama        1.96
9936      Coclé  Member State        NO        191    Panama        0.82
...         ...           ...       ...        ...       ...         ...
10004  Veraguas  Member State        NO        191    Panama        2.29
10005  Veraguas  Member State        NO        191    Panama        2.98
10006  Veraguas  Member State        NO        191    Panama        4.26
10007  Veraguas  Member State        NO        191    Panama        2.24
10008  Veraguas  Member State        NO        191    Panama        2.86

       Shape_Le_1  Shape_Area  \
9932         1.12        0.04
9933         1.42        0.06
9934         1.53        0.09
9935         1.96        0.05
9936         0.82        0.03
...           ...         ...
10004        2.29        0.16
10005        2.98        0.08
10006        4.26        0.13
10007        2.24        0.07
10008        2.86        0.09

                                                geometry
9932   POLYGON ((-80.61365 8.29593, -80.61293 8.29576...
9933   MULTIPOLYGON (((-80.11020 8.35360, -80.11072 8...
9934   POLYGON ((-80.52306 8.93482, -80.51938 8.93479...
9935   POLYGON ((-80.60329 8.58638, -80.60273 8.58637...
9936   POLYGON ((-80.73180 8.63726, -80.73015 8.63712...
...                                                  ...
10004  POLYGON ((-80.87475 8.86802, -80.87435 8.86172...
10005  MULTIPOLYGON (((-81.02790 7.74168, -81.02663 7...
10006  MULTIPOLYGON (((-81.22669 7.60718, -81.22722 7...
10007  POLYGON ((-81.33408 8.50206, -81.33966 8.49639...
10008  MULTIPOLYGON (((-81.74533 7.80329, -81.74559 7...

[77 rows x 15 columns]
152 PNG Papua New Guinea
       OBJECTID  ADM2_CODE      ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
38077 38,078.00      37470           Abau       1000       3000       2290
38078 38,079.00      37471        Goilala       1000       3000       2290
38079 38,080.00      37472           Hiri       1000       3000       2290
38080 38,081.00      37473        Kairuku       1000       3000       2290
38081 38,082.00      37474           Rigo       1000       3000       2290
...         ...        ...            ...        ...        ...        ...
38177 38,178.00      37563  Hagen Central       1000       3000       2309
38178 38,179.00      37564    Hagen North       1000       3000       2309
38179 38,180.00      37565           Jimi       1000       3000       2309
38180 38,181.00      37566         Tambul       1000       3000       2309
38181 38,182.00      37567          Wahgi       1000       3000       2309

               ADM1_NAME        STATUS DISP_AREA  ADM0_CODE         ADM0_NAME  \
38077            Central  Member State        NO        192  Papua New Guinea
38078            Central  Member State        NO        192  Papua New Guinea
38079            Central  Member State        NO        192  Papua New Guinea
38080            Central  Member State        NO        192  Papua New Guinea
38081            Central  Member State        NO        192  Papua New Guinea
...                  ...           ...       ...        ...               ...
38177  Western Highlands  Member State        NO        192  Papua New Guinea
38178  Western Highlands  Member State        NO        192  Papua New Guinea
38179  Western Highlands  Member State        NO        192  Papua New Guinea
38180  Western Highlands  Member State        NO        192  Papua New Guinea
38181  Western Highlands  Member State        NO        192  Papua New Guinea

       Shape_Leng  Shape_Le_1  Shape_Area  \
38077        5.59        5.59        0.49
38078        3.78        3.78        0.58
38079        4.00        4.00        0.48
38080        3.08        3.08        0.30
38081        2.67        2.67        0.38
...           ...         ...         ...
38177        1.77        1.77        0.15
38178        1.73        1.73        0.17
38179        1.74        1.74        0.13
38180        1.06        1.06        0.07
38181        2.08        2.08        0.18

                                                geometry
38077  MULTIPOLYGON (((149.36218 -10.38333, 149.36159...
38078  POLYGON ((146.92032 -7.96733, 147.28532 -8.361...
38079  POLYGON ((147.40721 -8.81887, 147.43245 -8.822...
38080  MULTIPOLYGON (((146.54613 -8.84396, 146.54288 ...
38081  POLYGON ((148.20633 -9.73559, 148.01971 -9.912...
...                                                  ...
38177  POLYGON ((144.40630 -6.41193, 144.28345 -6.331...
38178  POLYGON ((144.34506 -5.68381, 144.35442 -5.728...
38179  POLYGON ((144.83450 -5.54647, 144.87856 -5.594...
38180  POLYGON ((144.06352 -5.96337, 144.05716 -5.976...
38181  POLYGON ((144.70781 -5.72655, 144.73924 -5.778...

[105 rows x 15 columns]
153 PRY Paraguay
       OBJECTID  ADM2_CODE               ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
21172 21,173.00      23785           Fuerte Olimpo       1000       3000
21173 21,174.00      23786             La Victoria       1000       3000
21174 21,175.00      23787  Mayor Pablo La Gerenza       1000       3000
21175 21,176.00      23788        Ciudad  Del Este       1000       3000
21176 21,177.00      23789             D. M. Irala       1000       3000
...         ...        ...                     ...        ...        ...
21386 21,387.00      24000               San Pablo       1000       3000
21387 21,388.00      24001                 Tacuati       1000       3000
21388 21,389.00      24002                   Union       1000       3000
21389 21,390.00      24003       Villa Del Rosario       1000       3000
21390 21,391.00      24004       Yataity Del Norte       1000       3000

       ADM1_CODE      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
21172       2311  Alto Paraguay  Member State        NO        194  Paraguay
21173       2311  Alto Paraguay  Member State        NO        194  Paraguay
21174       2311  Alto Paraguay  Member State        NO        194  Paraguay
21175       2312    Alto Parana  Member State        NO        194  Paraguay
21176       2312    Alto Parana  Member State        NO        194  Paraguay
...          ...            ...           ...       ...        ...       ...
21386       2327      San Pedro  Member State        NO        194  Paraguay
21387       2327      San Pedro  Member State        NO        194  Paraguay
21388       2327      San Pedro  Member State        NO        194  Paraguay
21389       2327      San Pedro  Member State        NO        194  Paraguay
21390       2327      San Pedro  Member State        NO        194  Paraguay

       Shape_Leng  Shape_Le_1  Shape_Area  \
21172        7.10        7.10        1.77
21173        7.03        7.03        2.03
21174        7.85        7.85        2.99
21175        0.50        0.50        0.01
21176        0.96        0.96        0.04
...           ...         ...         ...
21386        0.88        0.88        0.03
21387        2.59        2.59        0.20
21388        1.04        1.04        0.05
21389        3.57        3.57        0.19
21390        0.76        0.76        0.03

                                                geometry
21172  POLYGON ((-58.14727 -20.09543, -58.14385 -20.0...
21173  POLYGON ((-57.86509 -21.07294, -57.86509 -21.0...
21174  POLYGON ((-59.06597 -19.28769, -59.06075 -19.2...
21175  POLYGON ((-54.60273 -25.51117, -54.60188 -25.5...
21176  POLYGON ((-54.62728 -25.77459, -54.61504 -25.7...
...                                                  ...
21386  POLYGON ((-56.76683 -24.06952, -56.82399 -24.1...
21387  POLYGON ((-56.17513 -23.30861, -56.17794 -23.3...
21388  POLYGON ((-56.42007 -24.73126, -56.41238 -24.7...
21389  POLYGON ((-56.82399 -24.19654, -56.82242 -24.1...
21390  POLYGON ((-56.28079 -24.75394, -56.28089 -24.7...

[219 rows x 15 columns]
154 PER Peru
       OBJECTID  ADM2_CODE          ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
21453 21,454.00      24005              Bagua       1000       3000
21454 21,455.00      24006            Bongará       1000       3000
21455 21,456.00      24007        Chachapoyas       1000       3000
21456 21,457.00      24008       Condorcanqui       1000       3000
21457 21,458.00      24009               Luya       1000       3000
...         ...        ...                ...        ...        ...
21643 21,644.00      24196            Atalaya       1000       3000
21644 21,645.00      24197   Coronel Portillo       1000       3000
21645 21,646.00      24198         Padre Abad       1000       3000
21646 21,647.00      24199              Purús       1000       3000
21647 21,648.00      91842  Datem del Maranon       2005       3000

       ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
21453       2328  Amazonas  Member State        NO        195      Peru
21454       2328  Amazonas  Member State        NO        195      Peru
21455       2328  Amazonas  Member State        NO        195      Peru
21456       2328  Amazonas  Member State        NO        195      Peru
21457       2328  Amazonas  Member State        NO        195      Peru
...          ...       ...           ...       ...        ...       ...
21643       2352   Ucayali  Member State        NO        195      Peru
21644       2352   Ucayali  Member State        NO        195      Peru
21645       2352   Ucayali  Member State        NO        195      Peru
21646       2352   Ucayali  Member State        NO        195      Peru
21647       2343    Loreto  Member State        NO        195      Peru

       Shape_Leng  Shape_Le_1  Shape_Area  \
21453        4.10        4.10        0.48
21454        2.96        2.96        0.23
21455        3.76        3.76        0.25
21456        6.93        6.93        1.43
21457        2.92        2.92        0.27
...           ...         ...         ...
21643       13.10       13.10        3.18
21644       11.33       11.33        3.21
21645        4.44        4.44        0.76
21646        6.87        6.87        1.49
21647       10.23       10.23        3.82

                                                geometry
21453  POLYGON ((-78.55276 -4.50258, -78.55524 -4.509...
21454  POLYGON ((-77.69465 -5.39535, -77.69454 -5.403...
21455  POLYGON ((-77.71910 -5.94292, -77.71761 -5.943...
21456  POLYGON ((-77.78199 -3.22367, -77.78146 -3.232...
21457  POLYGON ((-78.11668 -5.91716, -78.11536 -5.917...
...                                                  ...
21643  POLYGON ((-73.19727 -9.41585, -73.19613 -9.418...
21644  POLYGON ((-74.48479 -7.29775, -74.47931 -7.298...
21645  POLYGON ((-75.43487 -8.22964, -75.43452 -8.229...
21646  POLYGON ((-70.59975 -9.80080, -70.60008 -9.800...
21647  POLYGON ((-76.26255 -3.67085, -76.26321 -3.670...

[195 rows x 15 columns]
155 PHL Philippines
       OBJECTID  ADM2_CODE          ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
28912 28,913.00      24204               Abra       1000       3000
28913 28,914.00      24205             Apayao       1000       3000
28914 28,915.00      24206            Benguet       1000       3000
28915 28,916.00      24207             Ifugao       1000       3000
28916 28,917.00      24208            Kalinga       1000       3000
...         ...        ...                ...        ...        ...
28989 28,990.00      67164  Zamboanga Del Sur       2001       3000
28990 28,991.00      67168            Dinagat       2006       3000
28991 28,992.00      67169  Surigao Del Norte       2006       3000
28992 28,993.00      67174        Maguindanao       2006       3000
28993 28,994.00      67175  Shariff Kabunsuan       2006       3000

       ADM1_CODE                                    ADM1_NAME        STATUS  \
28912       2354       Cordillera Administrative region (CAR)  Member State
28913       2354       Cordillera Administrative region (CAR)  Member State
28914       2354       Cordillera Administrative region (CAR)  Member State
28915       2354       Cordillera Administrative region (CAR)  Member State
28916       2354       Cordillera Administrative region (CAR)  Member State
...          ...                                          ...           ...
28989      67159              Region IX (Zamboanga Peninsula)  Member State
28990       2368                         Region XIII (Caraga)  Member State
28991       2368                         Region XIII (Caraga)  Member State
28992      67156  Autonomous region in Muslim Mindanao (ARMM)  Member State
28993      67156  Autonomous region in Muslim Mindanao (ARMM)  Member State

      DISP_AREA  ADM0_CODE    ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
28912        NO        196  Philippines        2.64        2.64        0.33
28913        NO        196  Philippines        2.78        2.78        0.33
28914        NO        196  Philippines        1.95        1.95        0.22
28915        NO        196  Philippines        2.29        2.29        0.23
28916        NO        196  Philippines        2.25        2.25        0.25
...         ...        ...          ...         ...         ...         ...
28989        NO        196  Philippines        6.83        6.83        0.42
28990        NO        196  Philippines        4.80        4.80        0.09
28991        NO        196  Philippines        5.81        5.81        0.15
28992        NO        196  Philippines        3.19        3.19        0.17
28993        NO        196  Philippines        3.47        3.47        0.23

                                                geometry
28912  POLYGON ((120.98479 17.93169, 120.98884 17.929...
28913  POLYGON ((121.08712 18.52818, 121.09071 18.485...
28914  POLYGON ((120.84728 16.83812, 120.84793 16.838...
28915  POLYGON ((121.53838 17.10060, 121.54394 17.099...
28916  POLYGON ((121.65846 17.50885, 121.65982 17.507...
...                                                  ...
28989  MULTIPOLYGON (((122.06236 6.85580, 122.05799 6...
28990  MULTIPOLYGON (((125.56489 9.77019, 125.56416 9...
28991  MULTIPOLYGON (((125.76553 9.57870, 125.75811 9...
28992  POLYGON ((124.72954 7.17604, 124.73847 7.16494...
28993  MULTIPOLYGON (((124.02613 7.29655, 124.02300 7...

[82 rows x 15 columns]
156 POL Poland
       OBJECTID  ADM2_CODE    ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
33369 33,370.00      24280  Boleslawiec       1000       3000       2370
33370 33,371.00      24281  Dzierzoniow       1000       3000       2370
33371 33,372.00      24282       Glogow       1000       3000       2370
33372 33,373.00      24283         Gora       1000       3000       2370
33373 33,374.00      24284        Jawor       1000       3000       2370
...         ...        ...          ...        ...        ...        ...
33741 33,742.00      24652      Swidwin       1000       3000       2385
33742 33,743.00      24653  Swinoujscie       1000       3000       2385
33743 33,744.00      24654     Szczecin       1000       3000       2385
33744 33,745.00      24655   Szczecinek       1000       3000       2385
33745 33,746.00      24656        Walcz       1000       3000       2385

                 ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
33369         Dolnoslaskie  Member State        NO        198    Poland
33370         Dolnoslaskie  Member State        NO        198    Poland
33371         Dolnoslaskie  Member State        NO        198    Poland
33372         Dolnoslaskie  Member State        NO        198    Poland
33373         Dolnoslaskie  Member State        NO        198    Poland
...                    ...           ...       ...        ...       ...
33741  Zachodnio-Pomorskie  Member State        NO        198    Poland
33742  Zachodnio-Pomorskie  Member State        NO        198    Poland
33743  Zachodnio-Pomorskie  Member State        NO        198    Poland
33744  Zachodnio-Pomorskie  Member State        NO        198    Poland
33745  Zachodnio-Pomorskie  Member State        NO        198    Poland

       Shape_Leng  Shape_Le_1  Shape_Area  \
33369        2.39        2.39        0.17
33370        1.35        1.35        0.06
33371        1.86        1.86        0.05
33372        1.73        1.73        0.10
33373        1.90        1.90        0.08
...           ...         ...         ...
33741        2.16        2.16        0.15
33742        1.10        1.10        0.01
33743        1.35        1.35        0.04
33744        2.94        2.94        0.24
33745        2.68        2.68        0.19

                                                geometry
33369  POLYGON ((15.71280 51.52230, 15.72120 51.52340...
33370  POLYGON ((16.90080 50.79180, 16.89640 50.78960...
33371  POLYGON ((16.27290 51.66100, 16.27360 51.66090...
33372  POLYGON ((16.66220 51.70850, 16.66300 51.70560...
33373  POLYGON ((16.44290 51.13250, 16.44300 51.13230...
...                                                  ...
33741  POLYGON ((16.20000 53.81670, 16.20380 53.81510...
33742  MULTIPOLYGON (((14.41107 53.84246, 14.38640 53...
33743  POLYGON ((14.77350 53.40510, 14.77850 53.40240...
33744  POLYGON ((16.96760 53.90410, 16.97340 53.90240...
33745  POLYGON ((16.70840 53.31170, 16.70600 53.30880...

[377 rows x 15 columns]
157 PRT Portugal
       OBJECTID  ADM2_CODE           ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
36120 36,121.00      24657              Agueda       1000       3000
36121 36,122.00      24658  Albergaria-a-velha       1000       3000
36122 36,123.00      24659              Anadia       1000       3000
36123 36,124.00      24660              Arouca       1000       3000
36124 36,125.00      24661              Aveiro       1000       3000
...         ...        ...                 ...        ...        ...
36393 36,394.00      24950             Tarouca       1000       3000
36394 36,395.00      24951             Tondela       1000       3000
36395 36,396.00      24952  Vila Nova De Paiva       1000       3000
36396 36,397.00      24953               Viseu       1000       3000
36397 36,398.00      24954             Vouzela       1000       3000

       ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
36120       2386    Aveiro  Member State        NO        199  Portugal
36121       2386    Aveiro  Member State        NO        199  Portugal
36122       2386    Aveiro  Member State        NO        199  Portugal

       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
33158 33,159.00      25028  Administrative unit not available       1000
33159 33,160.00      25029  Administrative unit not available       1000
33160 33,161.00      25030  Administrative unit not available       1000
33161 33,162.00      25031  Administrative unit not available       1000
33162 33,163.00      25032  Administrative unit not available       1000
...         ...        ...                                ...        ...
33244 33,245.00      25114  Administrative unit not available       1000
33245 33,246.00      25115  Administrative unit not available       1000
33246 33,247.00      25116  Administrative unit not available       1000
33247 33,248.00      25117  Administrative unit not available       1000
33248 33,249.00      25118  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE                     ADM1_NAME        STATUS  \
33158       3000       2487                  Adygeya Rep.  Member State
33159       3000       2488  Aginskiy Buryatskiy A. Okrug  Member State
33160       3000       2489                    Altay Rep.  Member State
33161       3000       2490                Altayskiy Kray  Member State
33162       3000       2491              Amurskaya Oblast  Member State
...          ...        ...                           ...           ...
33244       3000       2573           Vologodskaya Oblast  Member State
33245       3000       2574          Voronezhskaya Oblast  Member State
33246       3000       2575        Yamalo-nenetskiy Okrug  Member State
33247       3000       2576          Yaroslavskaya Oblast  Member State
33248       3000       2577         Yevreyskaya A. Oblast  Member State

      DISP_AREA  ADM0_CODE           ADM0_NAME  Shape_Leng  Shape_Le_1  \
33158        NO        204  Russian Federation        9.60        9.60
33159        NO        204  Russian Federation       11.08       11.08
33160        NO        204  Russian Federation       23.18       23.18
33161        NO        204  Russian Federation       30.88       30.88
33162        NO        204  Russian Federation       62.34       62.34
...         ...        ...                 ...         ...         ...
33244        NO        204  Russian Federation       40.17       40.17
33245        NO        204  Russian Federation       16.78       16.78
33246        NO        204  Russian Federation      214.21      214.21
33247        NO        204  Russian Federation       14.59       14.59
33248        NO        204  Russian Federation       12.59       12.59

       Shape_Area                                           geometry
33158        0.90  POLYGON ((39.67526 45.18547, 39.67445 45.18083...
33159        2.52  POLYGON ((115.20750 51.65139, 115.21194 51.647...
33160       11.76  POLYGON ((87.17333 52.61167, 87.16833 52.60750...
33161       22.54  POLYGON ((87.17333 52.61167, 87.17000 52.61444...
33162       48.81  POLYGON ((130.92305 55.67861, 130.92306 55.677...
...           ...                                                ...
33244       23.44  POLYGON ((37.77305 61.52222, 37.77556 61.52056...
33245        6.67  POLYGON ((40.50389 51.95361, 40.51028 51.95361...
33246      141.46  MULTIPOLYGON (((72.23456 66.26907, 72.23843 66...
33247        5.44  POLYGON ((40.92611 58.57917, 40.93417 58.57528...
33248        4.34  POLYGON ((134.71108 48.39368, 134.71003 48.394...

[91 rows x 15 columns]
162 RWA Rwanda
     OBJECTID  ADM2_CODE   ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
666    667.00      21974    Bugesera       2006       3000      21969
667    668.00      21978     Gatsibo       2006       3000      21969
668    669.00      21984     Kayonza       2006       3000      21969
669    670.00      21986      Kirehe       2006       3000      21969
670    671.00      21989       Ngoma       2006       3000      21969
671    672.00      21992   Nyagatare       2006       3000      21969
672    673.00      22003   Rwamagana       2006       3000      21969
673    674.00      21977      Gasabo       2006       3000      21970
674    675.00      21985    Kicukiro       2006       3000      21970
675    676.00      21996  Nyarugenge       2006       3000      21970
676    677.00      21975      Burera       2006       3000      21971
677    678.00      21976     Gakenke       2006       3000      21971
678    679.00      21979     Gicumbi       2006       3000      21971
679    680.00      21988     Musanze       2006       3000      21971
680    681.00      22000     Rulindo       2006       3000      21971
681    682.00      21980    Gisagara       2006       3000      21972
682    683.00      21981        Huye       2006       3000      21972
683    684.00      21982     Kamonyi       2006       3000      21972
684    685.00      21987     Muhanga       2006       3000      21972
685    686.00      21993   Nyamagabe       2006       3000      21972
686    687.00      21995      Nyanza       2006       3000      21972
687    688.00      21997   Nyaruguru       2006       3000      21972
688    689.00      21999     Ruhango       2006       3000      21972
689    690.00      21983     Karongi       2006       3000      21973
690    691.00      21990   Ngororero       2006       3000      21973
691    692.00      21991     Nyabihu       2006       3000      21973
692    693.00      21994  Nyamasheke       2006       3000      21973
693    694.00      21998      Rubavu       2006       3000      21973
694    695.00      22001      Rusizi       2006       3000      21973
695    696.00      22002     Rutsiro       2006       3000      21973

                        ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
666            East/Iburasirazuba  Member State        NO        205
667            East/Iburasirazuba  Member State        NO        205
668            East/Iburasirazuba  Member State        NO        205
669            East/Iburasirazuba  Member State        NO        205
670            East/Iburasirazuba  Member State        NO        205
671            East/Iburasirazuba  Member State        NO        205
672            East/Iburasirazuba  Member State        NO        205
673  Kigali City/Umujyi wa Kigali  Member State        NO        205
674  Kigali City/Umujyi wa Kigali  Member State        NO        205
675  Kigali City/Umujyi wa Kigali  Member State        NO        205
676            North/Amajyaruguru  Member State        NO        205
677            North/Amajyaruguru  Member State        NO        205
678            North/Amajyaruguru  Member State        NO        205
679            North/Amajyaruguru  Member State        NO        205
680            North/Amajyaruguru  Member State        NO        205
681               South/Amajyepfo  Member State        NO        205
682               South/Amajyepfo  Member State        NO        205
683               South/Amajyepfo  Member State        NO        205
684               South/Amajyepfo  Member State        NO        205
685               South/Amajyepfo  Member State        NO        205
686               South/Amajyepfo  Member State        NO        205
687               South/Amajyepfo  Member State        NO        205
688               South/Amajyepfo  Member State        NO        205
689           West/Iburengerazuba  Member State        NO        205
690           West/Iburengerazuba  Member State        NO        205
691           West/Iburengerazuba  Member State        NO        205
692           West/Iburengerazuba  Member State        NO        205
693           West/Iburengerazuba  Member State        NO        205
694           West/Iburengerazuba  Member State        NO        205
695           West/Iburengerazuba  Member State        NO        205

    ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
666    Rwanda        1.89        1.89        0.10
667    Rwanda        2.26        2.26        0.13
668    Rwanda        1.87        1.87        0.16
669    Rwanda        1.71        1.71        0.10
670    Rwanda        1.51        1.51        0.07
671    Rwanda        2.37        2.37        0.16
672    Rwanda        1.23        1.23        0.06
673    Rwanda        1.01        1.01        0.03
674    Rwanda        0.77        0.77        0.01
675    Rwanda        0.92        0.92        0.01
676    Rwanda        1.45        1.45        0.05
677    Rwanda        1.31        1.31        0.06
678    Rwanda        1.86        1.86        0.07
679    Rwanda        1.04        1.04        0.04
680    Rwanda        1.43        1.43        0.05
681    Rwanda        1.29        1.29        0.05
682    Rwanda        1.20        1.20        0.05
683    Rwanda        1.45        1.45        0.05
684    Rwanda        1.61        1.61        0.05
685    Rwanda        1.87        1.87        0.09
686    Rwanda        1.60        1.60        0.05
687    Rwanda        1.67        1.67        0.08
688    Rwanda        1.51        1.51        0.05
689    Rwanda        1.80        1.80        0.08
690    Rwanda        1.62        1.62        0.05
691    Rwanda        1.19        1.19        0.04
692    Rwanda        1.73        1.73        0.10
693    Rwanda        1.02        1.02        0.03
694    Rwanda        2.19        2.19        0.08
695    Rwanda        1.87        1.87        0.10

                                              geometry
666  POLYGON ((30.17503 -2.03129, 30.17518 -2.03189...
667  POLYGON ((30.74061 -1.45863, 30.74396 -1.49511...
668  POLYGON ((30.84403 -1.66078, 30.82523 -1.69114...
669  POLYGON ((30.82868 -1.97182, 30.85698 -2.01699...
670  POLYGON ((30.51618 -2.05865, 30.51627 -2.05873...
671  POLYGON ((30.46679 -1.06294, 30.46446 -1.06678...
672  MULTIPOLYGON (((30.21878 -2.07193, 30.21904 -2...
673  MULTIPOLYGON (((30.23662 -1.98242, 30.23651 -1...
674  POLYGON ((30.14356 -1.95412, 30.14402 -1.95429...
675  POLYGON ((29.98964 -1.86756, 29.98957 -1.86789...
676  POLYGON ((29.86356 -1.35957, 29.86373 -1.35982...
677  POLYGON ((29.77391 -1.55936, 29.77411 -1.55974...
678  POLYGON ((30.07031 -1.39100, 30.07051 -1.39196...
679  POLYGON ((29.66003 -1.38536, 29.66033 -1.39047...
680  POLYGON ((29.90165 -1.58997, 29.90172 -1.59004...
681  POLYGON ((29.96762 -2.44579, 29.96654 -2.44826...
682  POLYGON ((29.79235 -2.37070, 29.79255 -2.37085...
683  POLYGON ((29.81745 -1.85291, 29.81769 -1.85307...
684  POLYGON ((29.66811 -1.73118, 29.66834 -1.73122...
685  POLYGON ((29.55792 -2.20014, 29.55806 -2.20021...
686  POLYGON ((29.95084 -2.23321, 29.95146 -2.23339...
687  POLYGON ((29.54045 -2.53293, 29.54041 -2.53316...
688  POLYGON ((29.88596 -2.10086, 29.88607 -2.10100...
689  POLYGON ((29.29900 -2.02056, 29.31813 -2.02408...
690  POLYGON ((29.63900 -1.72248, 29.63945 -1.72333...
691  POLYGON ((29.47684 -1.54069, 29.48389 -1.54924...
692  POLYGON ((29.28195 -2.18743, 29.28201 -2.18913...
693  MULTIPOLYGON (((29.42319 -1.72590, 29.42324 -1...
694  POLYGON ((28.95778 -2.36222, 28.96789 -2.37687...
695  MULTIPOLYGON (((29.30815 -2.02657, 29.30803 -2...
163 WSM Samoa
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
38206 38,207.00      25301  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE                          ADM1_NAME        STATUS  \
38206       3000       2618  Administrative unit not available  Member State

      DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
38206        NO        212     Samoa        4.92        4.92        0.24

                                                geometry
38206  MULTIPOLYGON (((-171.40587 -14.07086, -171.406...
164 SMR San Marino
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
36055 36,056.00      25302  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE                          ADM1_NAME        STATUS  \
36055       3000       2619  Administrative unit not available  Member State

      DISP_AREA  ADM0_CODE   ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
36055        NO        213  San Marino        0.36        0.36        0.01

                                                geometry
36055  POLYGON ((12.49151 43.91780, 12.48995 43.91556...
165 STP Sao Tome and Principe
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
166 SAU Saudi Arabia
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
31826 31,827.00      25305  Administrative unit not available       1000
31827 31,828.00      25306  Administrative unit not available       1000
31828 31,829.00      25307  Administrative unit not available       1000
31829 31,830.00      25308  Administrative unit not available       1000
31830 31,831.00      25309  Administrative unit not available       1000
31831 31,832.00      25310  Administrative unit not available       1000
31832 31,833.00      25311  Administrative unit not available       1000
31833 31,834.00      25312  Administrative unit not available       1000
31834 31,835.00      25313  Administrative unit not available       1000
31835 31,836.00      25314  Administrative unit not available       1000
31836 31,837.00      25315  Administrative unit not available       1000
31837 31,838.00      25316  Administrative unit not available       1000
31838 31,839.00      25317  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE          ADM1_NAME        STATUS DISP_AREA  \
31826       3000       2622               Asir  Member State        NO
31827       3000       2623               Baha  Member State        NO
31828       3000       2624   Eastern Province  Member State        NO
31829       3000       2625               Hail  Member State        NO
31830       3000       2626               Jawf  Member State        NO
31831       3000       2627              Jizan  Member State        NO
31832       3000       2628            Madinah  Member State        NO
31833       3000       2629             Makkah  Member State        NO
31834       3000       2630             Najran  Member State        NO
31835       3000       2631  Northern Frontier  Member State        NO
31836       3000       2632            Quassim  Member State        NO
31837       3000       2633              Riyad  Member State        NO
31838       3000       2634              Tabuk  Member State        NO

       ADM0_CODE     ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
31826        215  Saudi Arabia       12.87       12.87        6.64
31827        215  Saudi Arabia        4.59        4.59        0.89
31828        215  Saudi Arabia       48.61       48.61       49.01
31829        215  Saudi Arabia       17.02       17.02       11.06
31830        215  Saudi Arabia       20.51       20.51       10.91
31831        215  Saudi Arabia       14.15       14.15        1.33
31832        215  Saudi Arabia       22.56       22.56       12.89
31833        215  Saudi Arabia       33.50       33.50       12.05
31834        215  Saudi Arabia       12.54       12.54        7.55
31835        215  Saudi Arabia       23.25       23.25       11.74
31836        215  Saudi Arabia       11.24       11.24        4.91
31837        215  Saudi Arabia       26.32       26.32       33.30
31838        215  Saudi Arabia       32.71       32.71        9.07

                                                geometry
31826  POLYGON ((44.51666 19.51250, 44.51805 19.49194...
31827  POLYGON ((42.03194 20.62472, 42.02111 20.59111...
31828  MULTIPOLYGON (((51.51208 24.38251, 51.51208 24...
31829  POLYGON ((44.79999 27.52083, 44.77666 27.51694...
31830  POLYGON ((40.54350 28.81601, 40.52444 28.82444...
31831  MULTIPOLYGON (((41.90640 16.42500, 41.89641 16...
31832  MULTIPOLYGON (((38.55624 23.42760, 38.55396 23...
31833  MULTIPOLYGON (((41.57442 18.11675, 41.57178 18...
31834  POLYGON ((47.43714 17.09930, 47.18333 16.95000...
31835  POLYGON ((42.77198 30.62572, 43.40964 30.16681...
31836  POLYGON ((44.62749 27.22222, 44.65083 27.21777...
31837  POLYGON ((47.74347 19.53071, 47.60694 19.49333...
31838  MULTIPOLYGON (((37.14971 24.89536, 37.13837 24...
167 SEN Senegal

      OBJECTID  ADM2_CODE          ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
5785  5,786.00       1395         Guinguineo       2008       3000       1373
5786  5,787.00      25329            Kaolack       1000       3000       1373
5787  5,788.00      25330       Nioro du rip       1000       3000       1373
5788  5,789.00       1397           Kedougou       2008       3000       1374
5789  5,790.00       1510           Salemata       2008       3000       1374
5790  5,791.00       1538             Saraya       2008       3000       1374
5791  5,792.00       1408              Kolda       2008       3000       1375
5792  5,793.00       1499  Medina yoro foula       2008       3000       1375
5793  5,794.00      25333          Velingara       1000       3000       1375
5794  5,795.00       1381         Bounkiling       2008       3000       1376
5795  5,796.00       1394            Goudomp       2008       3000       1376
5796  5,797.00       1609            Sedhiou       2008       3000       1376
5797  5,798.00       1379              Bakel       2008       3000       1377
5798  5,799.00       1384            Goudiry       2008       3000       1377
5799  5,800.00       1488         Koupentoum       2008       3000       1377
5800  5,801.00       1649        Tambacounda       2008       3000       1377
5801  5,802.00       1380          Birkilane       2008       3000       1378
5802  5,803.00       1396           Kaffrine       2008       3000       1378
5803  5,804.00       1486          Koungueul       2006       3000       1378
5804  5,805.00       1497       Maleme hodar       2008       3000       1378
5805  5,806.00       1382              Dakar       2008       3000       2636
5806  5,807.00      25321           Rufisque       1000       3000       2636
5807  5,808.00      25343              Mbour       1000       3000       2644
5808  5,809.00      25344              Thies       1000       3000       2644
5809  5,810.00      25345           Tivaoune       1000       3000       2644
5810  5,811.00      25346            Bignona       1000       3000       2645
5811  5,812.00      25347           Oussouye       1000       3000       2645
5812  5,813.00      25348         Ziguinchor       1000       3000       2645
5813  5,814.00      25322             Bambey       1000       3000      47585
5814  5,815.00      25323           Diourbel       1000       3000      47585
5815  5,816.00      47596             Mbacke       2002       3000      47585
5816  5,817.00       1383             Gossas       2008       3000      47586
5817  5,818.00      25325             Fatick       1000       3000      47586
5818  5,819.00      25326        Foundiougne       1000       3000      47586
5819  5,820.00      25334            Kebemer       1000       3000      47587
5820  5,821.00      25336              Louga       1000       3000      47587
5821  5,822.00      47594           Linguere       2002       3000      47587
5822  5,823.00      47593              Kanel       2002       3000      47588
5823  5,824.00      47595              Matam       2002       3000      47588
5824  5,825.00      47599            Ranerou       2002       3000      47588
5825  5,826.00      47590             Dagana       2002       3000      47589
5826  5,827.00      47598              Podor       2002       3000      47589
5827  5,828.00      47600        Saint louis       2002       3000      47589

        ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
5785      Kaolack  Member State        NO        217   Senegal        1.06
5786      Kaolack  Member State        NO        217   Senegal        3.89
5787      Kaolack  Member State        NO        217   Senegal        2.26
5788     Kedougou  Member State        NO        217   Senegal        5.23
5789     Kedougou  Member State        NO        217   Senegal        2.68
5790     Kedougou  Member State        NO        217   Senegal        5.40
5791        Kolda  Member State        NO        217   Senegal        3.48
5792        Kolda  Member State        NO        217   Senegal        3.20
5793        Kolda  Member State        NO        217   Senegal        5.03
5794      Sedhiou  Member State        NO        217   Senegal        2.50
5795      Sedhiou  Member State        NO        217   Senegal        2.48
5796      Sedhiou  Member State        NO        217   Senegal        2.84
5797  Tambacounda  Member State        NO        217   Senegal        5.13
5798  Tambacounda  Member State        NO        217   Senegal        6.46
5799  Tambacounda  Member State        NO        217   Senegal        3.32
5800  Tambacounda  Member State        NO        217   Senegal       10.81
5801     Kaffrine  Member State        NO        217   Senegal        1.87
5802     Kaffrine  Member State        NO        217   Senegal        1.68
5803     Kaffrine  Member State        NO        217   Senegal        2.61
5804     Kaffrine  Member State        NO        217   Senegal        2.48
5805        Dakar  Member State        NO        217   Senegal        1.05
5806        Dakar  Member State        NO        217   Senegal        0.81
5807        Thies  Member State        NO        217   Senegal        3.41
5808        Thies  Member State        NO        217   Senegal        1.94
5809        Thies  Member State        NO        217   Senegal        3.13
5810   Ziguinchor  Member State        NO        217   Senegal        3.11
5811   Ziguinchor  Member State        NO        217   Senegal        1.20
5812   Ziguinchor  Member State        NO        217   Senegal        1.89
5813     Diourbel  Member State        NO        217   Senegal        1.46
5814     Diourbel  Member State        NO        217   Senegal        1.63
5815     Diourbel  Member State        NO        217   Senegal        2.51
5816       Fatick  Member State        NO        217   Senegal        2.34
5817       Fatick  Member State        NO        217   Senegal       11.99
5818       Fatick  Member State        NO        217   Senegal       11.75
5819        Louga  Member State        NO        217   Senegal        3.39
5820        Louga  Member State        NO        217   Senegal        3.12
5821        Louga  Member State        NO        217   Senegal        5.66
5822        Matam  Member State        NO        217   Senegal        4.16
5823        Matam  Member State        NO        217   Senegal        3.39
5824        Matam  Member State        NO        217   Senegal        6.02
5825  Saint louis  Member State        NO        217   Senegal        4.21
5826  Saint louis  Member State        NO        217   Senegal        5.95
5827  Saint louis  Member State        NO        217   Senegal        3.76

      Shape_Le_1  Shape_Area  \
5785        1.06        0.06
5786        3.89        0.15
5787        2.26        0.19
5788        5.23        0.59
5789        2.68        0.17
5790        5.40        0.65
5791        3.48        0.30
5792        3.20        0.40
5793        5.03        0.46
5794        2.50        0.24
5795        2.48        0.15
5796        2.84        0.23
5797        5.13        0.55
5798        6.46        1.32
5799        3.32        0.51
5800       10.81        1.18
5801        1.87        0.12
5802        1.68        0.10
5803        2.61        0.38
5804        2.48        0.35
5805        1.05        0.01
5806        0.81        0.03
5807        3.41        0.16
5808        1.94        0.13
5809        3.13        0.27
5810        3.11        0.44
5811        1.20        0.07
5812        1.89        0.10
5813        1.46        0.11
5814        1.63        0.11
5815        2.51        0.19
5816        2.34        0.13
5817       11.99        0.19
5818       11.75        0.22
5819        3.39        0.33
5820        3.12        0.48
5821        5.66        1.30
5822        4.16        0.73
5823        3.39        0.49
5824        6.02        1.25
5825        4.21        0.47
5826        5.95        1.08
5827        3.76        0.06

                                               geometry
5785  POLYGON ((-15.92418 14.39322, -15.92230 14.391...
5786  MULTIPOLYGON (((-16.27312 14.14488, -16.27312 ...
5787  POLYGON ((-15.80155 13.91016, -15.80023 13.910...
5788  POLYGON ((-12.58163 13.19901, -12.58098 13.198...
5789  POLYGON ((-12.99080 12.79813, -12.98882 12.796...
5790  POLYGON ((-12.23999 13.46066, -12.23863 13.459...
5791  POLYGON ((-15.00379 13.06072, -15.00097 13.059...
5792  POLYGON ((-14.34802 13.23437, -14.34860 13.229...
5793  POLYGON ((-13.80403 13.54182, -13.80140 13.541...
5794  POLYGON ((-15.33787 13.34593, -15.33788 13.344...
5795  POLYGON ((-15.27062 12.85704, -15.26760 12.853...
5796  POLYGON ((-15.20666 13.03916, -15.20318 13.037...
5797  POLYGON ((-12.51577 15.02238, -12.50526 15.017...
5798  POLYGON ((-12.49083 14.66567, -12.48397 14.403...
5799  POLYGON ((-13.78338 14.41087, -13.78810 14.405...
5800  POLYGON ((-13.65439 14.12534, -13.65486 14.124...
5801  POLYGON ((-15.68929 14.47642, -15.69022 14.472...
5802  POLYGON ((-15.12654 13.99207, -15.13002 13.982...
5803  POLYGON ((-14.74618 14.58291, -14.73787 14.582...
5804  POLYGON ((-15.02291 14.60970, -15.02962 14.584...
5805  MULTIPOLYGON (((-17.46743 14.64920, -17.46745 ...
5806  POLYGON ((-17.12646 14.71837, -17.13074 14.716...
5807  MULTIPOLYGON (((-16.76865 14.05777, -16.76889 ...
5808  POLYGON ((-17.06903 14.90370, -17.06080 14.895...
5809  POLYGON ((-16.73663 15.29669, -16.73327 15.294...
5810  MULTIPOLYGON (((-16.78778 12.66776, -16.78882 ...
5811  POLYGON ((-16.52024 12.54958, -16.51722 12.549...
5812  POLYGON ((-15.95932 12.58714, -15.96083 12.585...
5813  POLYGON ((-16.40225 15.02218, -16.39885 15.021...
5814  POLYGON ((-16.28411 14.99131, -16.28095 14.990...
5815  POLYGON ((-15.80275 14.98011, -15.80231 14.968...
5816  POLYGON ((-15.68443 14.69042, -15.68340 14.690...
5817  MULTIPOLYGON (((-16.63527 13.98832, -16.63716 ...
5818  MULTIPOLYGON (((-16.52237 13.60277, -16.52188 ...
5819  POLYGON ((-16.50242 15.64564, -16.48548 15.642...
5820  POLYGON ((-15.58016 15.83710, -15.58015 15.809...
5821  POLYGON ((-15.18240 16.00315, -15.16735 16.000...
5822  POLYGON ((-13.05598 15.47982, -13.04329 15.479...
5823  POLYGON ((-13.47419 16.13288, -13.47923 16.126...
5824  POLYGON ((-14.49990 15.77793, -14.49072 15.762...
5825  MULTIPOLYGON (((-16.49825 16.06190, -16.49815 ...
5826  POLYGON ((-14.94544 16.63554, -14.93763 16.631...
5827  MULTIPOLYGON (((-16.51989 15.83324, -16.52028 ...
168 SRB Serbia
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
36676 36,677.00      47624  Administrative unit not available       1000
36677 36,678.00      47625  Administrative unit not available       1000
36678 36,679.00      47626  Administrative unit not available       1000
36679 36,680.00      47627  Administrative unit not available       1000
36680 36,681.00      47628  Administrative unit not available       1000
36681 36,682.00      47629  Administrative unit not available       1000
36682 36,683.00      47630  Administrative unit not available       1000
36686 36,687.00      47634  Administrative unit not available       1000
36687 36,688.00      47635  Administrative unit not available       1000
36688 36,689.00      47636  Administrative unit not available       1000
36689 36,690.00      47637  Administrative unit not available       1000
36691 36,692.00      47639  Administrative unit not available       1000
36692 36,693.00      47640  Administrative unit not available       1000
36693 36,694.00      47641  Administrative unit not available       1000
36695 36,696.00      47643  Administrative unit not available       1000
36696 36,697.00      47644  Administrative unit not available       1000
36697 36,698.00      47645  Administrative unit not available       1000
36698 36,699.00      47646  Administrative unit not available       1000
36699 36,700.00      47647  Administrative unit not available       1000
36700 36,701.00      47648  Administrative unit not available       1000
36701 36,702.00      47649  Administrative unit not available       1000
36702 36,703.00      47650  Administrative unit not available       1000
36703 36,704.00      47651  Administrative unit not available       1000
36704 36,705.00      47652  Administrative unit not available       1000
36705 36,706.00      47653  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE         ADM1_NAME        STATUS DISP_AREA  \
36676       3000      25371            Borski  Member State        NO
36677       3000      25372       Branicevski  Member State        NO
36678       3000      25373      Grad Beograd  Member State        NO
36679       3000      25374        Jablanicki  Member State        NO
36680       3000      25375       Juzno-backi  Member State        NO
36681       3000      25376    Juzno-banatski  Member State        NO
36682       3000      25377        Kolubarski  Member State        NO
36686       3000      25381         Macvanski  Member State        NO
36687       3000      25382         Moravicki  Member State        NO
36688       3000      25383          Nisavski  Member State        NO
36689       3000      25384          Pcinjski  Member State        NO
36691       3000      25386          Pirotski  Member State        NO
36692       3000      25387        Podunavski  Member State        NO
36693       3000      25388        Pomoravski  Member State        NO
36695       3000      25390          Rasinski  Member State        NO
36696       3000      25391             Raski  Member State        NO
36697       3000      25392     Severno-backi  Member State        NO
36698       3000      25393  Severno-banatski  Member State        NO
36699       3000      25394  Srednje-banatski  Member State        NO
36700       3000      25395           Sremski  Member State        NO
36701       3000      25396        Sumadijski  Member State        NO
36702       3000      25397          Toplicki  Member State        NO
36703       3000      25398        Zajecarski  Member State        NO
36704       3000      25399     Zapadno-backi  Member State        NO
36705       3000      25400       Zlatiborski  Member State        NO

       ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
36676       2648    Serbia        4.29        4.29        0.39
36677       2648    Serbia        3.64        3.64        0.44
36678       2648    Serbia        3.57        3.57        0.36
36679       2648    Serbia        3.10        3.10        0.30
36680       2648    Serbia        4.12        4.12        0.47
36681       2648    Serbia        3.69        3.69        0.47
36682       2648    Serbia        3.24        3.24        0.29
36686       2648    Serbia        4.14        4.14        0.37
36687       2648    Serbia        3.77        3.77        0.35
36688       2648    Serbia        3.81        3.81        0.30
36689       2648    Serbia        3.43        3.43        0.38
36691       2648    Serbia        2.88        2.88        0.30
36692       2648    Serbia        2.14        2.14        0.14
36693       2648    Serbia        3.19        3.19        0.30
36695       2648    Serbia        3.19        3.19        0.30
36696       2648    Serbia        4.32        4.32        0.43
36697       2648    Serbia        2.31        2.31        0.21
36698       2648    Serbia        3.07        3.07        0.27
36699       2648    Serbia        4.22        4.22        0.37
36700       2648    Serbia        4.44        4.44        0.39
36701       2648    Serbia        2.83        2.83        0.27
36702       2648    Serbia        2.61        2.61        0.25
36703       2648    Serbia        4.20        4.20        0.41
36704       2648    Serbia        3.51        3.51        0.28
36705       2648    Serbia        6.01        6.01        0.70

                                                geometry
36676  POLYGON ((22.67614 44.21545, 22.67522 44.21521...
36677  POLYGON ((21.35642 44.82368, 21.35731 44.82288...
36678  POLYGON ((20.42414 45.09414, 20.42531 45.09055...
36679  POLYGON ((22.23348 43.06941, 22.24118 43.06794...
36680  POLYGON ((20.09778 45.71891, 20.09558 45.71525...
36681  POLYGON ((21.48235 45.19176, 21.48266 45.19163...
36682  POLYGON ((19.99643 44.59075, 19.99657 44.58855...
36686  POLYGON ((19.97941 44.63725, 19.97905 44.63614...
36687  POLYGON ((20.65127 43.87900, 20.65090 43.87870...
36688  POLYGON ((22.34238 43.37186, 22.34246 43.36988...
36689  POLYGON ((22.43949 42.81706, 22.43956 42.81671...
36691  POLYGON ((22.74901 43.38526, 22.74905 43.38523...
36692  POLYGON ((21.03498 44.72085, 21.03556 44.71997...
36693  POLYGON ((21.81457 44.07664, 21.81075 44.07144...
36695  POLYGON ((21.49158 43.76554, 21.49782 43.75924...
36696  POLYGON ((20.74067 43.80786, 20.74522 43.80742...
36697  POLYGON ((19.66911 46.18398, 19.66937 46.18387...
36698  POLYGON ((20.26730 46.11710, 20.26778 46.11698...
36699  POLYGON ((21.06388 45.33167, 21.04539 45.31922...
36700  POLYGON ((19.43248 45.16891, 19.43645 45.16388...
36701  POLYGON ((20.78144 44.33612, 20.78555 44.33458...
36702  POLYGON ((21.48183 43.37538, 21.48535 43.37457...
36703  POLYGON ((22.53131 44.04812, 22.53156 44.04792...
36704  POLYGON ((19.29898 45.98944, 19.29898 45.98944...
36705  POLYGON ((19.69413 44.13663, 19.69831 44.13319...
169 SYC Seychelles
     OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
816    817.00      61211  Administrative unit not available       1000
817    818.00      61212  Administrative unit not available       1000
818    819.00      61213  Administrative unit not available       1000
819    820.00      61214  Administrative unit not available       1000
820    821.00      61215  Administrative unit not available       1000
..        ...        ...                                ...        ...
871    872.00      61279  Administrative unit not available       1000
872    873.00      61280  Administrative unit not available       1000
873    874.00      61281  Administrative unit not available       1000
874    875.00      61282  Administrative unit not available       1000
875    876.00      61283  Administrative unit not available       1000

     EXP2_YEAR  ADM1_CODE      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
816       3000      61135        Aldabra  Member State        NO        220
817       3000      61136       Alphonse  Member State        NO        220
818       3000      61137  Anse Aux Pins  Member State        NO        220
819       3000      61138   Anse Boileau  Member State        NO        220
820       3000      61139    Anse Etoile  Member State        NO        220
..         ...        ...            ...           ...       ...        ...
871       3000      61203     St. Pierre  Member State        NO        220
872       3000      61204       Ste Anne  Member State        NO        220
873       3000      61205       Takamaka  Member State        NO        220
874       3000      61206        Therese  Member State        NO        220
875       3000      61207        Coetivy  Member State        NO        220

      ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
816  Seychelles        1.78        1.78        0.01
817  Seychelles        0.05        0.05        0.00
818  Seychelles        0.08        0.08        0.00
819  Seychelles        0.17        0.17        0.00
820  Seychelles        0.20        0.20        0.00
..          ...         ...         ...         ...
871  Seychelles        0.04        0.04        0.00
872  Seychelles        0.06        0.06        0.00
873  Seychelles        0.21        0.21        0.00
874  Seychelles        0.04        0.04        0.00
875  Seychelles        0.18        0.18        0.00

                                              geometry
816  MULTIPOLYGON (((46.24179 -9.44121, 46.23814 -9...
817  POLYGON ((52.73624 -7.00739, 52.73506 -7.00772...
818  MULTIPOLYGON (((55.52893 -4.69034, 55.52790 -4...

     OBJECTID  ADM2_CODE   ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
696    697.00      25653        Baki       1000       3000       2688
697    698.00      25654      Borama       1000       3000       2688
698    699.00      25655     Lughaye       1000       3000       2688
699    700.00      25656      Zeylac       1000       3000       2688
700    701.00      25657  Ceel Barde       1000       3000       2689
..        ...        ...         ...        ...        ...        ...
765    766.00      25722    Owdweyne       1000       3000       2704
766    767.00      25723      Sheikh       1000       3000       2704
767    768.00      25724     Berbera       1000       3000       2705
768    769.00      25725     Gebiley       1000       3000       2705
769    770.00      25726    Hargeysa       1000       3000       2705

           ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
696            Awdal  Member State        NO        226   Somalia        2.92
697            Awdal  Member State        NO        226   Somalia        2.40
698            Awdal  Member State        NO        226   Somalia        2.42
699            Awdal  Member State        NO        226   Somalia        4.76
700           Bakool  Member State        NO        226   Somalia        3.65
..               ...           ...       ...        ...       ...         ...
765         Togdheer  Member State        NO        226   Somalia        3.53
766         Togdheer  Member State        NO        226   Somalia        2.45
767  Woqooyi Galbeed  Member State        NO        226   Somalia        5.39
768  Woqooyi Galbeed  Member State        NO        226   Somalia        2.53
769  Woqooyi Galbeed  Member State        NO        226   Somalia        4.58

     Shape_Le_1  Shape_Area                                           geometry
696        2.92        0.28  POLYGON ((44.23618 10.47239, 44.15096 10.32091...
697        2.40        0.25  POLYGON ((43.39094 10.41091, 43.35094 10.05094...
698        2.42        0.27  POLYGON ((44.07433 10.59854, 44.07241 10.59786...
699        4.76        0.50  MULTIPOLYGON (((43.53442 11.18007, 43.53456 11...
700        3.65        0.62  POLYGON ((44.59208 4.93477, 44.59208 4.93477, ...
..          ...         ...                                                ...
765        3.53        0.69  POLYGON ((45.28098 9.87095, 45.28098 9.41099, ...
766        2.45        0.24  POLYGON ((45.90746 10.09975, 45.89424 10.08785...
767        5.39        0.84  MULTIPOLYGON (((45.85816 10.83195, 45.85828 10...
768        2.53        0.35  POLYGON ((44.04095 10.17093, 44.10096 10.13093...
769        4.58        1.13  POLYGON ((44.89768 9.94114, 44.87097 9.91095, ...

[74 rows x 15 columns]
177 ZAF South Africa
      OBJECTID  ADM2_CODE                                        ADM2_NAME  \
4665  4,666.00      77316           Buffalo City Metropolitan Municipality
4666  4,667.00      77319                     Cacadu District Municipality
4667  4,668.00      77320                   Amathole District Municipality
4668  4,669.00      77322                  Joe Gqabi District Municipality
4669  4,670.00      77323                  O.R.Tambo District Municipality
...        ...        ...                                              ...
4712  4,713.00      77338                   Overberg District Municipality
4713  4,714.00      77349                       Eden District Municipality
4714  4,715.00      77357              Central Karoo District Municipality
4715  4,716.00      77348  Dr Ruth Segomotsi Mompati District Municipality
4716  4,717.00      77321                 Chris Hani District Municipality

      STR2_YEAR  EXP2_YEAR  ADM1_CODE     ADM1_NAME        STATUS DISP_AREA  \
4665       2005       3000      77310  Eastern Cape  Member State        NO
4666       2005       3000      77310  Eastern Cape  Member State        NO
4667       2005       3000      77310  Eastern Cape  Member State        NO
4668       2005       3000      77310  Eastern Cape  Member State        NO
4669       2005       3000      77310  Eastern Cape  Member State        NO
...         ...        ...        ...           ...           ...       ...
4712       2005       3000       2714  Western Cape  Member State        NO
4713       2005       3000       2714  Western Cape  Member State        NO
4714       2005       3000       2714  Western Cape  Member State        NO
4715       2005       3000      77314    North West  Member State        NO
4716       2005       3000      77310  Eastern Cape  Member State        NO

      ADM0_CODE     ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
4665        227  South Africa        4.46        4.46        0.24
4666        227  South Africa       17.94       17.94        5.62
4667        227  South Africa       16.05       16.05        2.07
4668        227  South Africa       13.80       13.80        2.43
4669        227  South Africa        9.70        9.70        1.15
...         ...           ...         ...         ...         ...
4712        227  South Africa        9.85        9.85        1.20
4713        227  South Africa       11.44       11.44        2.27
4714        227  South Africa       13.88       13.88        3.73
4715        227  South Africa       15.98       15.98        3.96
4716        227  South Africa       14.25       14.25        3.44

                                               geometry
4665  POLYGON ((27.35458 -32.67444, 27.37057 -32.675...
4666  MULTIPOLYGON (((26.28598 -33.83858, 26.28643 -...
4667  POLYGON ((28.26665 -31.80154, 28.26809 -31.802...
4668  POLYGON ((27.48308 -30.32026, 27.48044 -30.332...
4669  MULTIPOLYGON (((29.10986 -32.04117, 29.10966 -...
...                                                 ...
4712  MULTIPOLYGON (((19.41807 -34.68674, 19.41807 -...
4713  MULTIPOLYGON (((22.12048 -34.15130, 22.12005 -...
4714  POLYGON ((22.62701 -31.82335, 22.63067 -31.823...
4715  POLYGON ((23.28391 -25.27190, 23.28803 -25.280...
4716  POLYGON ((26.37107 -31.18372, 26.37934 -31.188...

[52 rows x 15 columns]
178 SSD South Sudan
     OBJECTID  ADM2_CODE      ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
770    771.00      37022          Aliab       1000       3000       2746
771    772.00      37023         Rumbek       1000       3000       2746
772    773.00      37024         Shobet       1000       3000       2746
773    774.00      37025          Yerol       1000       3000       2746
774    775.00      37115       Al Leiri       1000       3000       2747
775    776.00      37116       Al Mayom       1000       3000       2747
776    777.00      37117         Faring       1000       3000       2747
777    778.00      37118        Rabkona       1000       3000       2747
778    779.00      37033  Bahr Al Jabal       1000       3000       2748
779    780.00      37034      Kajo Kaji       1000       3000       2748
780    781.00      37035       Nahr Yei       1000       3000       2748
781    782.00      37036        Terkaka       1000       3000       2748
782    783.00      37042       Amatonge       1000       3000       2750
783    784.00      37043        Kapoeta       1000       3000       2750
784    785.00      37044          Magwi       1000       3000       2750
785    786.00      37045       Shokodom       1000       3000       2750
786    787.00      37051          Akobo       1000       3000       2751
787    788.00      37052           Ayod       1000       3000       2751
788    789.00      37053            Bor       1000       3000       2751
789    790.00      37054   Fam Al Zaraf       1000       3000       2751
790    791.00      37055     Nahr Atiem       1000       3000       2751
791    792.00      37056          Pibor       1000       3000       2751
792    793.00      37057            Wat       1000       3000       2751
793    794.00      37076          Aryat       1000       3000       2754
794    795.00      37077          Aweil       1000       3000       2754
795    796.00      37078          Malek       1000       3000       2754
796    797.00      37079         Wanjuk       1000       3000       2754
797    798.00      37127        Gogrial       1000       3000       2765
798    799.00      37128       Nahr Lol       1000       3000       2765
799    800.00      37129           Tonj       1000       3000       2765
800    801.00      37130          Warab       1000       3000       2765
801    802.00      37131       Nahr Jur       1000       3000       2766
802    803.00      37132           Raja       1000       3000       2766
803    804.00      37133            Wau       1000       3000       2766
804    805.00      37141         Meridi       1000       3000       2768
805    806.00      37142         Mundri       1000       3000       2768
806    807.00      37143        Tombura       1000       3000       2768
807    808.00      37144         Yambio       1000       3000       2768
808    809.00      37119      Al Mabien       1000       3000      37021
809    810.00      37120        Al Renk       1000       3000      37021
810    811.00      37121         Baleit       1000       3000      37021
811    812.00      37122       Fashooda       1000       3000      37021
812    813.00      37123          Malut       1000       3000      37021
813    814.00      37124          Mayot       1000       3000      37021
814    815.00      37125          Sobat       1000       3000      37021
815    816.00      37126          Tonga       1000       3000      37021

                   ADM1_NAME        STATUS DISP_AREA  ADM0_CODE    ADM0_NAME  \
770              El Buheyrat  Member State        NO         74  South Sudan
771              El Buheyrat  Member State        NO         74  South Sudan
772              El Buheyrat  Member State        NO         74  South Sudan
773              El Buheyrat  Member State        NO         74  South Sudan
774                    Unity  Member State        NO         74  South Sudan
775                    Unity  Member State        NO         74  South Sudan
776                    Unity  Member State        NO         74  South Sudan
777                    Unity  Member State        NO         74  South Sudan
778        Central Equatoria  Member State        NO         74  South Sudan
779        Central Equatoria  Member State        NO         74  South Sudan
780        Central Equatoria  Member State        NO         74  South Sudan
781        Central Equatoria  Member State        NO         74  South Sudan
782        Eastern Equatoria  Member State        NO         74  South Sudan
783        Eastern Equatoria  Member State        NO         74  South Sudan
784        Eastern Equatoria  Member State        NO         74  South Sudan
785        Eastern Equatoria  Member State        NO         74  South Sudan
786                  Jonglei  Member State        NO         74  South Sudan
787                  Jonglei  Member State        NO         74  South Sudan
788                  Jonglei  Member State        NO         74  South Sudan
789                  Jonglei  Member State        NO         74  South Sudan
790                  Jonglei  Member State        NO         74  South Sudan
791                  Jonglei  Member State        NO         74  South Sudan
792                  Jonglei  Member State        NO         74  South Sudan
793  Northern Bahr El Ghazal  Member State        NO         74  South Sudan
794  Northern Bahr El Ghazal  Member State        NO         74  South Sudan
795  Northern Bahr El Ghazal  Member State        NO         74  South Sudan
796  Northern Bahr El Ghazal  Member State        NO         74  South Sudan
797                    Warab  Member State        NO         74  South Sudan
798                    Warab  Member State        NO         74  South Sudan
799                    Warab  Member State        NO         74  South Sudan
800                    Warab  Member State        NO         74  South Sudan
801   Western Bahr El Ghazal  Member State        NO         74  South Sudan
802   Western Bahr El Ghazal  Member State        NO         74  South Sudan
803   Western Bahr El Ghazal  Member State        NO         74  South Sudan
804        Western Equatoria  Member State        NO         74  South Sudan
805        Western Equatoria  Member State        NO         74  South Sudan
806        Western Equatoria  Member State        NO         74  South Sudan
807        Western Equatoria  Member State        NO         74  South Sudan
808               Upper Nile  Member State        NO         74  South Sudan
809               Upper Nile  Member State        NO         74  South Sudan
810               Upper Nile  Member State        NO         74  South Sudan
811               Upper Nile  Member State        NO         74  South Sudan
812               Upper Nile  Member State        NO         74  South Sudan
813               Upper Nile  Member State        NO         74  South Sudan
814               Upper Nile  Member State        NO         74  South Sudan
815               Upper Nile  Member State        NO         74  South Sudan

     Shape_Leng  Shape_Le_1  Shape_Area  \
770        2.69        2.69        0.36
771        7.49        7.49        1.74
772        3.41        3.41        0.50
773        4.53        4.53        0.90
774        5.95        5.95        1.04
775        3.69        3.69        0.47
776        2.81        2.81        0.32
777        5.71        5.71        1.18
778        5.86        5.86        1.39
779        1.96        1.96        0.20
780        5.33        5.33        1.07
781        5.66        5.66        0.94
782        6.89        6.89        1.80
783        9.74        9.17        3.12
784        3.56        3.56        0.44
785        3.75        3.75        0.67
786        6.73        6.73        1.09
787        6.51        6.51        1.51
788        3.76        3.76        0.55
789        4.03        4.03        0.61
790        6.57        6.57        1.56
791        9.06        9.06        3.55
792        5.70        5.70        1.04
793        1.86        1.86        0.12
794        6.71        6.71        1.76
795        2.03        2.03        0.15
796        2.77        2.77        0.46
797        5.51        5.51        0.79
798        3.17        3.17        0.34
799        5.56        5.56        0.98
800        5.37        5.37        0.99
801        3.34        3.34        0.45
802       10.91       10.91        4.68
803        6.58        6.58        2.23
804        7.32        7.32        1.60
805        5.16        5.16        1.25
806        8.88        8.88        2.27
807        7.16        7.16        1.28
808        3.52        3.52        0.70
809        5.31        5.31        0.88
810        5.25        5.25        0.94
811        6.54        6.54        0.79
812        5.06        5.06        1.04
813        3.62        3.62        0.70
814        4.91        4.91        0.87
815        3.67        3.67        0.52

                                              geometry
770  POLYGON ((31.69169 5.86563, 31.69323 5.86433, ...
771  POLYGON ((29.71243 7.82936, 29.72880 7.82471, ...
772  POLYGON ((29.61778 7.84461, 29.61707 7.83640, ...
773  POLYGON ((30.70669 7.21087, 30.70802 7.20955, ...
774  POLYGON ((30.22976 8.96489, 30.22879 8.96321, ...
775  POLYGON ((29.10740 9.75014, 29.11121 9.74918, ...
776  POLYGON ((30.79288 9.74854, 30.79076 9.74855, ...
777  POLYGON ((30.47794 9.49333, 30.47636 9.49245, ...
778  POLYGON ((32.08837 5.20889, 32.08922 5.20621, ...
779  POLYGON ((31.79497 3.82559, 31.79647 3.82289, ...
780  POLYGON ((31.31441 4.33826, 31.30071 4.31969, ...
781  POLYGON ((30.80980 6.07798, 30.81391 6.07454, ...
782  POLYGON ((32.91741 5.86459, 32.91755 5.84837, ...
783  POLYGON ((35.03948 5.83573, 35.10661 5.72866, ...
784  POLYGON ((32.68630 3.76330, 32.66822 3.76229, ...
785  POLYGON ((34.00230 4.22168, 33.99915 4.21876, ...
786  POLYGON ((32.58186 8.61657, 32.58335 8.61011, ...
787  POLYGON ((31.77261 8.98297, 31.77327 8.98237, ...
788  POLYGON ((32.26280 6.25944, 32.25925 5.87495, ...
789  POLYGON ((30.74804 9.46598, 30.75139 9.46796, ...
790  POLYGON ((32.27239 7.29889, 32.27224 7.28337, ...
791  POLYGON ((33.95809 7.44606, 33.95809 7.44606, ...
792  POLYGON ((32.48074 8.91111, 32.48482 8.91043, ...
793  POLYGON ((27.45822 9.62111, 27.45692 9.61936, ...
794  POLYGON ((27.09228 9.61489, 27.09283 9.61196, ...
795  POLYGON ((27.65999 8.30484, 27.65848 8.30718, ...
796  POLYGON ((27.46723 9.62094, 27.47341 9.61999, ...
797  POLYGON ((27.95176 7.98708, 27.95104 7.99011, ...
798  POLYGON ((28.71832 9.04250, 28.71062 9.03930, ...
799  POLYGON ((29.71243 7.82936, 29.71052 7.83076, ...
800  POLYGON ((29.30056 8.65131, 29.30185 8.65044, ...
801  POLYGON ((28.48849 7.62498, 28.50880 7.61701, ...
802  POLYGON ((25.81703 10.43416, 25.81988 10.43083...
803  POLYGON ((27.62626 8.28199, 27.62694 8.28055, ...
804  POLYGON ((29.67496 5.98962, 29.67793 5.98636, ...
805  POLYGON ((30.08720 6.37343, 30.09233 6.35400, ...
806  POLYGON ((28.02355 6.76085, 28.02572 6.75981, ...
807  POLYGON ((28.50070 6.50069, 28.49587 6.50041, ...
808  POLYGON ((33.65611 10.45515, 33.65809 10.45282...
809  POLYGON ((33.02315 12.22673, 33.25586 12.21435...
810  POLYGON ((33.38424 9.48193, 33.38006 9.47930, ...
811  POLYGON ((32.64179 10.98557, 32.64036 10.98409...
812  POLYGON ((33.25213 10.50559, 33.25022 10.50265...
813  POLYGON ((33.96096 9.49911, 34.01616 9.49864, ...
814  POLYGON ((33.52815 8.46692, 33.52407 8.46616, ...
815  POLYGON ((32.00807 9.78854, 32.00780 9.78809, ...
179 ESP Spain

       OBJECTID  ADM2_CODE    ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
36624 36,625.00      25776      Almería       1000       3000       2716
36625 36,626.00      25777        Cádiz       1000       3000       2716
36626 36,627.00      25778      Córdoba       1000       3000       2716
36627 36,628.00      25779      Granada       1000       3000       2716
36628 36,629.00      25780       Huelva       1000       3000       2716
...         ...        ...          ...        ...        ...        ...
36671 36,672.00      25824  Araba/Álava       1000       3000       2733
36672 36,673.00      25826      Bizkaia       1000       3000       2733
36673 36,674.00      25825     Gipuzkoa       1000       3000       2733
36674 36,675.00      25787     Asturias       1000       3000       2718
36675 36,676.00      25822       Murcia       1000       3000       2731

                    ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
36624               Andalucía  Member State        NO        229     Spain
36625               Andalucía  Member State        NO        229     Spain
36626               Andalucía  Member State        NO        229     Spain
36627               Andalucía  Member State        NO        229     Spain
36628               Andalucía  Member State        NO        229     Spain
...                       ...           ...       ...        ...       ...
36671      País Vasco/Euskadi  Member State        NO        229     Spain
36672      País Vasco/Euskadi  Member State        NO        229     Spain
36673      País Vasco/Euskadi  Member State        NO        229     Spain
36674  Principado de Asturias  Member State        NO        229     Spain
36675        Región de Murcia  Member State        NO        229     Spain

       Shape_Leng  Shape_Le_1  Shape_Area  \
36624        5.76        5.76        0.89
36625        6.35        6.35        0.74
36626        8.32        8.32        1.41
36627        7.15        7.15        1.28
36628        7.58        7.58        1.02
...           ...         ...         ...
36671        6.86        6.86        0.33
36672        4.18        4.18        0.24
36673        3.02        3.02        0.22
36674        8.57        8.57        1.18
36675        6.50        6.50        1.16

                                                geometry
36624  MULTIPOLYGON (((-3.03670 35.93785, -3.03719 35...
36625  MULTIPOLYGON (((-5.60342 36.00071, -5.60904 36...
36626  MULTIPOLYGON (((-5.08114 37.64655, -5.08000 37...
36627  POLYGON ((-2.54975 38.08289, -2.54910 38.08167...
36628  MULTIPOLYGON (((-6.87885 37.13892, -6.88114 37...
...                                                  ...
36671  POLYGON ((-3.02689 43.21657, -3.02630 43.21590...
36672  MULTIPOLYGON (((-3.04896 43.04609, -3.04781 43...
36673  POLYGON ((-1.79500 43.36966, -1.79109 43.36635...
36674  MULTIPOLYGON (((-7.04336 43.51821, -7.04758 43...
36675  MULTIPOLYGON (((-0.77023 37.69026, -0.77366 37...

[52 rows x 15 columns]
180 LKA Sri Lanka
       OBJECTID  ADM2_CODE     ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
30871 30,872.00      25830        Matale       1000       3000       2736
30872 30,873.00      41748         Kandy       1000       3000       2736
30873 30,874.00      41749  Nuwara Eliya       1000       3000       2736
30874 30,875.00      25832        Ampara       1000       3000       2737
30875 30,876.00      25833    Batticaloa       1000       3000       2737
30876 30,877.00      25834   Trincomalee       1000       3000       2737
30877 30,878.00      25835  Anuradhapura       1000       3000       2738
30878 30,879.00      25836   Polonnaruwa       1000       3000       2738
30879 30,880.00      25837    Kurunegala       1000       3000       2739
30880 30,881.00      25838      Puttalam       1000       3000       2739
30881 30,882.00      25839        Jaffna       1000       3000       2740
30882 30,883.00      25840   Kilinochchi       1000       3000       2740
30883 30,884.00      25841        Mannar       1000       3000       2740
30884 30,885.00      25842    Mullattivu       1000       3000       2740
30885 30,886.00      25843      Vavuniya       1000       3000       2740
30886 30,887.00      25844       Kegalle       1000       3000       2741
30887 30,888.00      25845     Ratnapura       1000       3000       2741
30888 30,889.00      25846         Galle       1000       3000       2742
30889 30,890.00      25847    Hambantota       1000       3000       2742
30890 30,891.00      25848        Matara       1000       3000       2742
30891 30,892.00      25849       Badulla       1000       3000       2743
30892 30,893.00      25850    Moneragala       1000       3000       2743
30893 30,894.00      25851       Colombo       1000       3000       2744
30894 30,895.00      25852       Gampaha       1000       3000       2744
30895 30,896.00      25853      Kalutara       1000       3000       2744

           ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  ADM0_NAME  \
30871        Central  Member State        NO        231  Sri Lanka
30872        Central  Member State        NO        231  Sri Lanka
30873        Central  Member State        NO        231  Sri Lanka
30874        Eastern  Member State        NO        231  Sri Lanka
30875        Eastern  Member State        NO        231  Sri Lanka
30876        Eastern  Member State        NO        231  Sri Lanka
30877  North Central  Member State        NO        231  Sri Lanka
30878  North Central  Member State        NO        231  Sri Lanka
30879  North Western  Member State        NO        231  Sri Lanka
30880  North Western  Member State        NO        231  Sri Lanka
30881       Northern  Member State        NO        231  Sri Lanka
30882       Northern  Member State        NO        231  Sri Lanka
30883       Northern  Member State        NO        231  Sri Lanka
30884       Northern  Member State        NO        231  Sri Lanka
30885       Northern  Member State        NO        231  Sri Lanka
30886   Sabaragamuwa  Member State        NO        231  Sri Lanka
30887   Sabaragamuwa  Member State        NO        231  Sri Lanka
30888       Southern  Member State        NO        231  Sri Lanka
30889       Southern  Member State        NO        231  Sri Lanka
30890       Southern  Member State        NO        231  Sri Lanka
30891            Uva  Member State        NO        231  Sri Lanka
30892            Uva  Member State        NO        231  Sri Lanka
30893        Western  Member State        NO        231  Sri Lanka
30894        Western  Member State        NO        231  Sri Lanka
30895        Western  Member State        NO        231  Sri Lanka

       Shape_Leng  Shape_Le_1  Shape_Area  \
30871        2.63        2.63        0.17
30872        3.00        3.00        0.16
30873        2.51        2.51        0.14
30874        4.95        4.95        0.37
30875        2.94        2.94        0.22
30876        3.80        3.80        0.22
30877        4.36        4.36        0.59
30878        3.07        3.07        0.28
30879        3.64        3.64        0.40
30880        5.56        5.56        0.26
30881        5.30        5.30        0.09
30882        3.97        3.97        0.11
30883        4.34        4.34        0.16
30884        2.92        2.92        0.21
30885        2.46        2.46        0.16
30886        2.24        2.24        0.14
30887        3.29        3.29        0.27
30888        2.48        2.48        0.13
30889        3.55        3.55        0.21
30890        2.33        2.33        0.11
30891        3.83        3.83        0.24
30892        4.66        4.66        0.47
30893        1.67        1.67        0.06
30894        1.86        1.86        0.12
30895        1.97        1.97        0.13

                                                geometry
30871  POLYGON ((80.98834 7.72038, 80.98835 7.72023, ...
30872  POLYGON ((80.97396 7.48873, 80.97397 7.48852, ...
30873  POLYGON ((80.83276 7.19456, 80.83329 7.19453, ...
30874  POLYGON ((81.82023 7.45174, 81.82037 7.45132, ...
30875  MULTIPOLYGON (((81.55843 7.98667, 81.55849 7.9...
30876  MULTIPOLYGON (((81.40353 8.27093, 81.40382 8.2...
30877  POLYGON ((80.94138 8.34192, 80.94133 8.34189, ...
30878  POLYGON ((80.94138 8.34192, 80.94152 8.34159, ...
30879  POLYGON ((80.13549 8.17868, 80.13566 8.17854, ...
30880  MULTIPOLYGON (((79.78233 8.26825, 79.78273 8.2...
30881  MULTIPOLYGON (((79.66185 9.55391, 79.66190 9.5...
30882  MULTIPOLYGON (((79.98485 9.30666, 79.98495 9.3...
30883  MULTIPOLYGON (((79.92533 8.80841, 79.92445 8.8...
30884  MULTIPOLYGON (((80.81643 9.27367, 80.81633 9.2...
30885  POLYGON ((80.76195 8.93697, 80.76167 8.93674, ...
30886  POLYGON ((80.42106 7.35424, 80.42100 7.35408, ...
30887  POLYGON ((80.25372 6.89366, 80.25384 6.89344, ...
30888  MULTIPOLYGON (((80.38100 5.96232, 80.38089 5.9...
30889  MULTIPOLYGON (((80.94338 6.06836, 80.94329 6.0...
30890  MULTIPOLYGON (((80.53216 5.93699, 80.53197 5.9...
30891  POLYGON ((81.27100 7.27815, 81.27064 7.27802, ...
30892  POLYGON ((81.47551 7.44757, 81.47528 7.44722, ...
30893  MULTIPOLYGON (((79.85155 6.96060, 79.85175 6.9...
30894  POLYGON ((80.19576 7.25818, 80.19563 7.25795, ...
30895  POLYGON ((80.17774 6.81575, 80.17774 6.81562, ...
181 KNA St. Kitts and Nevis
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
182 LCA St. Lucia
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
183 MAF St. Martin (French part)
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
184 VCT St. Vincent and the Grenadines
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
185 SDN Sudan
      OBJECTID  ADM2_CODE         ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
2248  2,249.00      37026      Al Hasaheisa       1000       3000       2745
2249  2,250.00      37027         Al Kamlin       1000       3000       2745
2250  2,251.00      37028        Al Managil       1000       3000       2745
2251  2,252.00      37029   East Al Jazeera       1000       3000       2745
2252  2,253.00      37030  North Al Jazeera       1000       3000       2745
...        ...        ...               ...        ...        ...        ...
2330  2,331.00      37048        Al Gadaref       1000       3000      68805
2331  2,332.00      37049        Al Galabat       1000       3000      68805
2332  2,333.00      37050           Al Rahd       1000       3000      68805
2333  2,334.00      68803            Seteet       2006       3000      68783
2334  2,335.00      68804         Al Fushqa       2006       3000      68805

       ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
2248  Al Jazeera  Member State        NO          6     Sudan        3.10
2249  Al Jazeera  Member State        NO          6     Sudan        1.84
2250  Al Jazeera  Member State        NO          6     Sudan        3.90
2251  Al Jazeera  Member State        NO          6     Sudan        3.41
2252  Al Jazeera  Member State        NO          6     Sudan        3.40
...          ...           ...       ...        ...       ...         ...
2330     Gadaref  Member State        NO          6     Sudan        2.78
2331     Gadaref  Member State        NO          6     Sudan        5.43
2332     Gadaref  Member State        NO          6     Sudan        6.42
2333     Kassala  Member State        NO          6     Sudan        4.06
2334     Gadaref  Member State        NO          6     Sudan        2.97

      Shape_Le_1  Shape_Area  \
2248        3.10        0.23
2249        1.84        0.13
2250        3.90        0.30
2251        3.41        0.26
2252        3.40        0.55
...          ...         ...
2330        2.78        0.29
2331        5.43        1.18
2332        6.42        1.09
2333        4.06        0.64
2334        2.97        0.32

                                               geometry
2248  POLYGON ((33.22952 14.90264, 33.23044 14.90110...
2249  POLYGON ((33.22952 14.90264, 33.22847 14.90198...
2250  POLYGON ((32.89140 14.76615, 32.89509 14.73541...
2251  POLYGON ((33.47188 14.52966, 33.47240 14.52846...
2252  POLYGON ((33.56919 15.45539, 33.57037 15.45500...
...                                                 ...
2330  POLYGON ((35.52537 14.10020, 35.52150 14.08512...
2331  POLYGON ((36.45376 13.76637, 36.45370 13.76627...
2332  POLYGON ((34.80079 14.12564, 34.83283 14.08810...
2333  POLYGON ((36.55864 14.25532, 36.55822 14.25510...
2334  POLYGON ((36.55864 14.25532, 36.55831 14.25485...

[87 rows x 15 columns]
186 SUR Suriname

       OBJECTID  ADM2_CODE         ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
21391 21,392.00      25880         Brownsweg       1000       3000       2771
21392 21,393.00      25881           Centrum       1000       3000       2771
21393 21,394.00      25882        Klaaskreek       1000       3000       2771
21394 21,395.00      25883        Kwakoegron       1000       3000       2771
21395 21,396.00      25884      Marchalkreek       1000       3000       2771
...         ...        ...               ...        ...        ...        ...
21448 21,449.00      25938        Koewarasan       1000       3000       2780
21449 21,450.00      25939            Kwatta       1000       3000       2780
21450 21,451.00      25940          Lelydorp       1000       3000       2780
21451 21,452.00      25941  Saramacca Polder       1000       3000       2780
21452 21,453.00      25887             Bakki       1000       3000       2772

        ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
21391  Brokopondo  Member State        NO        233  Suriname        1.42
21392  Brokopondo  Member State        NO        233  Suriname        0.71
21393  Brokopondo  Member State        NO        233  Suriname        0.91
21394  Brokopondo  Member State        NO        233  Suriname        1.70
21395  Brokopondo  Member State        NO        233  Suriname        0.76
...           ...           ...       ...        ...       ...         ...
21448      Wanica  Member State        NO        233  Suriname        0.35
21449      Wanica  Member State        NO        233  Suriname        0.35
21450      Wanica  Member State        NO        233  Suriname        0.56
21451      Wanica  Member State        NO        233  Suriname        0.24
21452  Commewijne  Member State        NO        233  Suriname        1.01

       Shape_Le_1  Shape_Area  \
21391        1.42        0.06
21392        0.71        0.02
21393        0.91        0.03
21394        1.70        0.08
21395        0.76        0.03
...           ...         ...
21448        0.35        0.01
21449        0.35        0.00
21450        0.56        0.01
21451        0.24        0.00
21452        1.01        0.03

                                                geometry
21391  POLYGON ((-55.07798 5.13464, -55.07640 5.13281...
21392  POLYGON ((-54.89658 5.15499, -54.89434 5.15307...
21393  POLYGON ((-54.89658 5.15499, -54.89722 5.15476...
21394  POLYGON ((-55.24852 5.22840, -55.27554 5.13515...
21395  POLYGON ((-55.01748 5.34411, -54.96865 5.31335...
...                                                  ...
21448  POLYGON ((-55.23497 5.80791, -55.23466 5.80817...
21449  POLYGON ((-55.29755 5.93868, -55.29499 5.93606...
21450  POLYGON ((-55.33534 5.75369, -55.32575 5.74787...
21451  POLYGON ((-55.23838 5.83095, -55.23818 5.83043...
21452  POLYGON ((-54.84923 5.99530, -54.84551 5.99516...

[62 rows x 15 columns]
187 SWE Sweden
       OBJECTID  ADM2_CODE    ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
34744 34,745.00      25996    Karlshamn       1000       3000       2786
34745 34,746.00      25997   Karlskrona       1000       3000       2786
34746 34,747.00      25998   Olofstroem       1000       3000       2786
34747 34,748.00      25999      Ronneby       1000       3000       2786
34748 34,749.00      26000  Soelvesborg       1000       3000       2786
...         ...        ...          ...        ...        ...        ...
35028 35,029.00      26280    Uddevalla       1000       3000       2806
35029 35,030.00      26281   Ulricehamn       1000       3000       2806
35030 35,031.00      26282   Vaargaarda       1000       3000       2806
35031 35,032.00      26283  Vaenersborg       1000       3000       2806
35032 35,033.00      26284         Vara       1000       3000       2806

                     ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
34744            Blekinge Laen  Member State        NO        236    Sweden
34745            Blekinge Laen  Member State        NO        236    Sweden
34746            Blekinge Laen  Member State        NO        236    Sweden
34747            Blekinge Laen  Member State        NO        236    Sweden
34748            Blekinge Laen  Member State        NO        236    Sweden
...                        ...           ...       ...        ...       ...
35028  Vaestra Goetalands Laen  Member State        NO        236    Sweden
35029  Vaestra Goetalands Laen  Member State        NO        236    Sweden
35030  Vaestra Goetalands Laen  Member State        NO        236    Sweden
35031  Vaestra Goetalands Laen  Member State        NO        236    Sweden
35032  Vaestra Goetalands Laen  Member State        NO        236    Sweden

       Shape_Leng  Shape_Le_1  Shape_Area  \
34744        1.61        1.61        0.07
34745        3.84        3.84        0.15
34746        1.00        1.00        0.06
34747        2.76        2.76        0.12
34748        0.95        0.95        0.03
...           ...         ...         ...
35028        2.44        2.44        0.09
35029        1.98        1.98        0.17
35030        1.30        1.30        0.07
35031        2.04        2.04        0.14
35032        1.74        1.74        0.11

                                                geometry
34744  MULTIPOLYGON (((14.98682 56.10875, 14.98207 56...
34745  MULTIPOLYGON (((15.79648 56.01304, 15.79070 56...
34746  POLYGON ((14.58333 56.43333, 14.61072 56.42902...
34747  MULTIPOLYGON (((15.43294 56.12405, 15.42059 56...
34748  MULTIPOLYGON (((14.85333 56.00000, 14.83662 56...
...                                                  ...
35028  MULTIPOLYGON (((11.62762 58.25180, 11.61146 58...
35029  POLYGON ((13.72500 57.92500, 13.76974 57.92073...
35030  POLYGON ((12.90833 58.10000, 12.89532 58.08184...
35031  POLYGON ((12.73333 58.55833, 12.73818 58.54544...
35032  POLYGON ((13.20000 58.34167, 13.23744 58.33179...

[289 rows x 15 columns]
188 CHE Switzerland
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
37185 37,186.00      26285  Administrative unit not available       1000
37186 37,187.00      26286  Administrative unit not available       1000
37187 37,188.00      26287  Administrative unit not available       1000
37188 37,189.00      26288  Administrative unit not available       1000
37189 37,190.00      26289  Administrative unit not available       1000
37190 37,191.00      26290  Administrative unit not available       1000
37191 37,192.00      26291  Administrative unit not available       1000
37192 37,193.00      26292  Administrative unit not available       1000
37193 37,194.00      26293  Administrative unit not available       1000
37194 37,195.00      26294  Administrative unit not available       1000
37195 37,196.00      26295  Administrative unit not available       1000
37196 37,197.00      26296  Administrative unit not available       1000
37197 37,198.00      26297  Administrative unit not available       1000
37198 37,199.00      26298  Administrative unit not available       1000
37199 37,200.00      26299  Administrative unit not available       1000
37200 37,201.00      26300  Administrative unit not available       1000
37201 37,202.00      26301  Administrative unit not available       1000
37202 37,203.00      26302  Administrative unit not available       1000
37203 37,204.00      26303  Administrative unit not available       1000
37204 37,205.00      26304  Administrative unit not available       1000
37205 37,206.00      26305  Administrative unit not available       1000
37206 37,207.00      26306  Administrative unit not available       1000
37207 37,208.00      26307  Administrative unit not available       1000
37208 37,209.00      26308  Administrative unit not available       1000
37209 37,210.00      26309  Administrative unit not available       1000
37210 37,211.00      26310  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE                ADM1_NAME        STATUS DISP_AREA  \
37185       3000       2807                   Aargau  Member State        NO
37186       3000       2808  Appenzell Ausser-rhoden  Member State        NO
37187       3000       2809   Appenzell Inner-rhoden  Member State        NO
37188       3000       2810         Basel-landschaft  Member State        NO
37189       3000       2811              Basel-stadt  Member State        NO
37190       3000       2812                     Bern  Member State        NO
37191       3000       2813                 Fribourg  Member State        NO
37192       3000       2814                   Geneve  Member State        NO
37193       3000       2815                   Glarus  Member State        NO
37194       3000       2816               Graubunden  Member State        NO
37195       3000       2817                     Jura  Member State        NO
37196       3000       2818                   Luzern  Member State        NO
37197       3000       2819                Neuchatel  Member State        NO
37198       3000       2820                Nidwalden  Member State        NO
37199       3000       2821                 Obwalden  Member State        NO
37200       3000       2822             Sankt Gallen  Member State        NO
37201       3000       2823             Schaffhausen  Member State        NO
37202       3000       2824                   Schwyz  Member State        NO
37203       3000       2825                Solothurn  Member State        NO
37204       3000       2826                  Thurgau  Member State        NO
37205       3000       2827                   Ticino  Member State        NO
37206       3000       2828                      Uri  Member State        NO
37207       3000       2829                   Valais  Member State        NO
37208       3000       2830                     Vaud  Member State        NO
37209       3000       2831                      Zug  Member State        NO
37210       3000       2832                   Zurich  Member State        NO

       ADM0_CODE    ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
37185        237  Switzerland        3.02        3.02        0.17
37186        237  Switzerland        1.39        1.39        0.03
37187        237  Switzerland        0.87        0.87        0.02
37188        237  Switzerland        1.42        1.42        0.05
37189        237  Switzerland        0.39        0.39        0.00
37190        237  Switzerland        7.36        7.36        0.70
37191        237  Switzerland        3.61        3.61        0.20
37192        237  Switzerland        1.12        1.12        0.03
37193        237  Switzerland        1.50        1.50        0.08
37194        237  Switzerland        6.81        6.81        0.84
37195        237  Switzerland        2.23        2.23        0.11
37196        237  Switzerland        2.69        2.69        0.18
37197        237  Switzerland        1.79        1.79        0.10
37198        237  Switzerland        1.32        1.32        0.03
37199        237  Switzerland        1.47        1.47        0.06
37200        237  Switzerland        4.46        4.46        0.25
37201        237  Switzerland        1.49        1.49        0.03
37202        237  Switzerland        1.94        1.94        0.11
37203        237  Switzerland        3.42        3.42        0.10
37204        237  Switzerland        2.51        2.51        0.12
37205        237  Switzerland        3.16        3.16        0.32
37206        237  Switzerland        1.88        1.88        0.13
37207        237  Switzerland        5.11        5.11        0.59
37208        237  Switzerland        5.74        5.74        0.38
37209        237  Switzerland        0.78        0.78        0.03
37210        237  Switzerland        2.60        2.60        0.20

                                                geometry
37185  POLYGON ((8.43553 47.57328, 8.41517 47.55146, ...
37186  POLYGON ((9.59626 47.42990, 9.57420 47.43447, ...
37187  MULTIPOLYGON (((9.38916 47.24195, 9.36765 47.2...
37188  POLYGON ((7.63847 47.56113, 7.63724 47.55902, ...
37189  POLYGON ((7.63847 47.56113, 7.63846 47.56113, ...
37190  MULTIPOLYGON (((7.14239 46.92191, 7.12994 46.9...
37191  MULTIPOLYGON (((6.76387 46.71478, 6.76003 46.7...
37192  MULTIPOLYGON (((6.24240 46.27649, 6.23579 46.2...
37193  POLYGON ((9.25071 46.90941, 9.22781 46.91190, ...
37194  POLYGON ((9.14729 46.16299, 9.14444 46.16805, ...
37195  POLYGON ((7.35577 47.43879, 7.35577 47.43879, ...
37196  MULTIPOLYGON (((8.50449 47.02236, 8.50570 47.0...
37197  POLYGON ((7.02823 47.00468, 7.01314 46.99549, ...
37198  POLYGON ((8.38316 47.01943, 8.37743 47.00340, ...
37199  MULTIPOLYGON (((8.38161 46.85545, 8.38603 46.8...
37200  POLYGON ((9.47996 47.05979, 9.47996 47.05978, ...
37201  MULTIPOLYGON (((8.56444 47.57666, 8.55639 47.5...
37202  POLYGON ((9.01235 47.17786, 8.97398 47.15340, ...
37203  MULTIPOLYGON (((7.69406 47.15746, 7.67722 47.1...
37204  MULTIPOLYGON (((9.47444 47.49638, 9.46336 47.4...
37205  POLYGON ((9.14729 46.16299, 9.13972 46.16091, ...
37206  POLYGON ((8.91751 46.91155, 8.94243 46.90065, ...
37207  POLYGON ((8.45390 46.52448, 8.43021 46.50344, ...
37208  MULTIPOLYGON (((6.74638 46.86166, 6.76833 46.8...
37209  POLYGON ((8.67826 47.15384, 8.68083 47.13914, ...
37210  POLYGON ((8.67106 47.69424, 8.66815 47.68951, ...
189 SYR Syrian Arab Republic
       OBJECTID  ADM2_CODE      ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
33012 33,013.00      26311         Al_Fiq       1000       3000       2833
33013 33,014.00      26312  Al_Qunaytirah       1000       3000       2833
33014 33,015.00      26313          A'zaz       1000       3000       2834
33015 33,016.00      26314          Afrin       1000       3000       2834
33016 33,017.00      26315    Ain_Al_Arab       1000       3000       2834
...         ...        ...            ...        ...        ...        ...
33075 33,076.00      26374         Banyas       1000       3000       2846
33076 33,077.00      26375      Dreikisch       1000       3000       2846
33077 33,078.00      26376         Safita       1000       3000       2846
33078 33,079.00      26377    Sheikh Badr       1000       3000       2846
33079 33,080.00      26378        Tartous       1000       3000       2846

           ADM1_NAME        STATUS DISP_AREA  ADM0_CODE             ADM0_NAME  \
33012  Al_Qunaytirah  Member State        NO        238  Syrian Arab Republic
33013  Al_Qunaytirah  Member State        NO        238  Syrian Arab Republic
33014         Aleppo  Member State        NO        238  Syrian Arab Republic
33015         Aleppo  Member State        NO        238  Syrian Arab Republic
33016         Aleppo  Member State        NO        238  Syrian Arab Republic
...              ...           ...       ...        ...                   ...
33075        Tartous  Member State        NO        238  Syrian Arab Republic
33076        Tartous  Member State        NO        238  Syrian Arab Republic
33077        Tartous  Member State        NO        238  Syrian Arab Republic
33078        Tartous  Member State        NO        238  Syrian Arab Republic
33079        Tartous  Member State        NO        238  Syrian Arab Republic

       Shape_Leng  Shape_Le_1  Shape_Area  \
33012        1.08        1.17        0.04
33013        1.82        1.87        0.12
33014        2.15        2.15        0.12
33015        2.23        2.23        0.19
33016        2.62        2.62        0.29
...           ...         ...         ...
33075        1.26        1.26        0.06
33076        0.80        0.80        0.02
33077        1.16        1.16        0.05
33078        0.39        0.39        0.01
33079        1.42        1.42        0.05

                                                geometry
33012  POLYGON ((35.64451 32.95578, 35.64705 32.95525...
33013  POLYGON ((35.62450 33.24236, 35.62444 33.24235...
33014  POLYGON ((37.29982 36.66193, 37.30313 36.66163...
33015  POLYGON ((36.74387 36.82228, 36.74592 36.82147...
33016  POLYGON ((38.30299 36.90640, 38.31160 36.90575...
...                                                  ...
33075  POLYGON ((36.14201 35.22121, 36.17131 35.22103...
33076  POLYGON ((36.27872 34.94165, 36.27383 34.94162...
33077  POLYGON ((36.27872 34.94165, 36.28024 34.93962...
33078  POLYGON ((36.13076 35.01463, 36.13686 35.00249...
33079  POLYGON ((36.05655 35.04220, 36.04477 35.00683...

[68 rows x 15 columns]
190 TJK Tajikistan
       OBJECTID  ADM2_CODE       ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
22382 22,383.00      37575   Ishkashimskiy       1000       3000       2847
22383 22,384.00      37576  Kalay-Humbskiy       1000       3000       2847
22384 22,385.00      37577      Murgabskiy       1000       3000       2847
22385 22,386.00      37578       Roshtkala       1000       3000       2847
22386 22,387.00      37579      Rushanskiy       1000       3000       2847
...         ...        ...             ...        ...        ...        ...
22433 22,434.00      37626       Shahrinav       1000       3000       2850
22434 22,435.00      37627       Tavildara       1000       3000       2850
22435 22,436.00      37628       Tojikobod       1000       3000       2850
22436 22,437.00      37629      Tursunzade       1000       3000       2850
22437 22,438.00      37630          Varzob       1000       3000       2850

                      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
22382          Badakhshoni Kuni  Member State        NO        239
22383          Badakhshoni Kuni  Member State        NO        239
22384          Badakhshoni Kuni  Member State        NO        239
22385          Badakhshoni Kuni  Member State        NO        239
22386          Badakhshoni Kuni  Member State        NO        239
...                         ...           ...       ...        ...
22433  Tadzhikistan Territories  Member State        NO        239
22434  Tadzhikistan Territories  Member State        NO        239
22435  Tadzhikistan Territories  Member State        NO        239
22436  Tadzhikistan Territories  Member State        NO        239
22437  Tadzhikistan Territories  Member State        NO        239

        ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
22382  Tajikistan        4.35        4.35        0.18
22383  Tajikistan        3.87        3.87        0.25
22384  Tajikistan       13.01       13.01        3.98
22385  Tajikistan        4.36        4.36        0.47
22386  Tajikistan        5.46        5.46        0.60
...           ...         ...         ...         ...
22433  Tajikistan        1.52        1.52        0.08
22434  Tajikistan        5.90        5.90        0.67
22435  Tajikistan        2.75        2.75        0.22
22436  Tajikistan        1.89        1.89        0.11
22437  Tajikistan        1.90        1.90        0.17

                                                geometry
22382  POLYGON ((72.80580 37.25250, 72.82508 37.23421...
22383  POLYGON ((71.27450 38.40390, 71.25990 38.40310...
22384  POLYGON ((73.54390 39.45706, 73.56325 39.45206...
22385  POLYGON ((72.80580 37.25250, 72.77920 37.25320...
22386  POLYGON ((72.73030 37.87250, 72.72280 37.87610...
...                                                  ...
22433  POLYGON ((68.44760 38.90170, 68.46490 38.89030...
22434  POLYGON ((72.01660 38.88100, 72.01710 38.87360...
22435  POLYGON ((71.02389 39.40360, 71.02389 39.40360...
22436  POLYGON ((68.30031 38.51044, 68.30031 38.47901...
22437  POLYGON ((69.00600 38.97580, 69.00000 38.95650...

[56 rows x 15 columns]
191 TZA Tanzania
      OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
877     878.00     115082                             Arusha       1000
878     879.00      48384                       Arusha Urban       1000
879     880.00     115068                             Karatu       1995
880     881.00     115121                            Longido       1000
881     882.00     115047                               Meru       1000

      OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
6666  6,667.00      27408  Administrative unit not available       1000
6667  6,668.00      27409  Administrative unit not available       1000
6668  6,669.00      27410  Administrative unit not available       1000
6669  6,670.00      27411  Administrative unit not available       1000
6670  6,671.00      27412  Administrative unit not available       1000
6671  6,672.00      27414  Administrative unit not available       1000
6672  6,673.00      27415  Administrative unit not available       1000
6673  6,674.00      27416  Administrative unit not available       1000
6674  6,675.00      27417  Administrative unit not available       1000
6675  6,676.00      27418  Administrative unit not available       1000
6676  6,677.00      27419  Administrative unit not available       1000
6677  6,678.00      27420  Administrative unit not available       1000
6678  6,679.00      27421  Administrative unit not available       1000
6679  6,680.00      27422  Administrative unit not available       1000
6680  6,681.00      27413  Administrative unit not available       1000

      EXP2_YEAR  ADM1_CODE                ADM1_NAME        STATUS DISP_AREA  \
6666       3000       2977                    Arima  Member State        NO
6667       3000       2978                Chaguanas  Member State        NO
6668       3000       2979  Couva/Tabaquite/Talparo  Member State        NO
6669       3000       2980             Diego Martin  Member State        NO
6670       3000       2981               Penal/Debe  Member State        NO
6671       3000       2983            Port Of Spain  Member State        NO
6672       3000       2984             Princes Town  Member State        NO
6673       3000       2985         Rio Claro/Mayaro  Member State        NO
6674       3000       2986             San Fernando  Member State        NO
6675       3000       2987      San Juan/Laventille  Member State        NO
6676       3000       2988            Sangre Grande  Member State        NO
6677       3000       2989                  Siparia  Member State        NO
6678       3000       2990                   Tobago  Member State        NO
6679       3000       2991          Tunapuna/Piarco  Member State        NO
6680       3000       2982             Point Fortin  Member State        NO

      ADM0_CODE            ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
6666        246  Trinidad and Tobago        0.20        0.20        0.00
6667        246  Trinidad and Tobago        0.35        0.35        0.01
6668        246  Trinidad and Tobago        1.39        1.39        0.06
6669        246  Trinidad and Tobago        1.32        1.32        0.01
6670        246  Trinidad and Tobago        0.67        0.67        0.02
6671        246  Trinidad and Tobago        0.22        0.22        0.00
6672        246  Trinidad and Tobago        1.06        1.06        0.05
6673        246  Trinidad and Tobago        1.29        1.29        0.06
6674        246  Trinidad and Tobago        0.29        0.29        0.00
6675        246  Trinidad and Tobago        1.07        1.07        0.02
6676        246  Trinidad and Tobago        1.63        1.63        0.07
6677        246  Trinidad and Tobago        1.28        1.28        0.04
6678        246  Trinidad and Tobago        1.62        1.62        0.03
6679        246  Trinidad and Tobago        1.36        1.36        0.05
6680        246  Trinidad and Tobago        0.31        0.31        0.00

                                               geometry
6666  POLYGON ((-61.29833 10.65406, -61.28976 10.651...
6667  POLYGON ((-61.42113 10.56569, -61.41866 10.565...
6668  POLYGON ((-61.19626 10.45793, -61.19651 10.453...
6669  MULTIPOLYGON (((-61.60111 10.65860, -61.60097 ...
6670  POLYGON ((-61.37595 10.07244, -61.37621 10.072...
6671  POLYGON ((-61.52413 10.67849, -61.51276 10.677...
6672  POLYGON ((-61.22583 10.30867, -61.22367 10.294...
6673  POLYGON ((-61.17109 10.07510, -61.16251 10.157...
6674  POLYGON ((-61.41687 10.31199, -61.42136 10.274...
6675  MULTIPOLYGON (((-61.49011 10.75963, -61.49026 ...
6676  MULTIPOLYGON (((-61.01345 10.70203, -61.01372 ...
6677  POLYGON ((-61.61492 10.24886, -61.61361 10.248...
6678  MULTIPOLYGON (((-60.64998 11.18371, -60.64998 ...
6679  MULTIPOLYGON (((-61.25074 10.79647, -61.25231 ...
6680  POLYGON ((-61.62780 10.20609, -61.62662 10.190...
197 TUN Tunisia
      OBJECTID  ADM2_CODE           ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
2335  2,336.00      39236        Ariana Ville       1000       3000
2336  2,337.00      39237           El Mnihla       1000       3000
2337  2,338.00      39238          Ettadhamen       1000       3000
2338  2,339.00      39239  Kalaat El Andalous       1000       3000
2339  2,340.00      39240              Raoued       1000       3000
...        ...        ...                 ...        ...        ...
2591  2,592.00      39493             Nadhour       1000       3000
2592  2,593.00      39494              Saouaf       1000       3000
2593  2,594.00      39495            Zaghouan       1000       3000
2594  2,595.00      39496               Zriba       1000       3000
2595  2,596.00      39374       Sidi Makhlouf       1000       3000

      ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
2335       2993    Ariana  Member State        NO        248   Tunisia
2336       2993    Ariana  Member State        NO        248   Tunisia
2337       2993    Ariana  Member State        NO        248   Tunisia
2338       2993    Ariana  Member State        NO        248   Tunisia
2339       2993    Ariana  Member State        NO        248   Tunisia
...         ...       ...           ...       ...        ...       ...
2591       3016  Zaghouan  Member State        NO        248   Tunisia
2592       3016  Zaghouan  Member State        NO        248   Tunisia
2593       3016  Zaghouan  Member State        NO        248   Tunisia
2594       3016  Zaghouan  Member State        NO        248   Tunisia
2595       3007  Medenine  Member State        NO        248   Tunisia

      Shape_Leng  Shape_Le_1  Shape_Area  \
2335        0.19        0.19        0.00
2336        0.26        0.26        0.00
2337        0.08        0.08        0.00
2338        1.08        1.08        0.02
2339        0.44        0.44        0.01
...          ...         ...         ...
2591        1.04        1.04        0.03
2592        0.83        0.83        0.03
2593        1.33        1.33        0.04
2594        1.06        1.06        0.03
2595        1.47        1.47        0.06

                                               geometry
2335  POLYGON ((10.17889 36.87326, 10.18127 36.87177...
2336  POLYGON ((10.14604 36.87529, 10.14545 36.87390...
2337  POLYGON ((10.11491 36.83593, 10.11574 36.83253...
2338  MULTIPOLYGON (((10.19761 37.08453, 10.19698 37...
2339  POLYGON ((10.24814 36.94548, 10.24669 36.94432...
...                                                 ...
2591  POLYGON ((10.03679 36.20583, 10.03716 36.20453...
2592  POLYGON ((10.25424 36.22358, 10.25371 36.22287...
2593  POLYGON ((10.34092 36.48882, 10.34278 36.48845...
2594  POLYGON ((10.37656 36.32539, 10.37569 36.32465...
2595  MULTIPOLYGON (((10.44963 33.63029, 10.44962 33...

[261 rows x 15 columns]
198 TUR Turkey
       OBJECTID  ADM2_CODE  ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
31839 31,840.00      27448     Aladag       1000       3000       3017
31840 31,841.00      27449     Ceyhan       1000       3000       3017
31841 31,842.00      27450       Feke       1000       3000       3017
31842 31,843.00      27451   Imamoglu       1000       3000       3017
31843 31,844.00      27452  Karaisali       1000       3000       3017
...         ...        ...        ...        ...        ...        ...
32760 32,761.00      28369    Caycuma       1000       3000       3096
32761 32,762.00      28370     Devrek       1000       3000       3096
32762 32,763.00      28371     Eregli       1000       3000       3096
32763 32,764.00      28372   Gokcebey       1000       3000       3096
32764 32,765.00      28373     Merkez       1000       3000       3096

       ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  \
31839      Adana  Member State        NO        249    Turkey        1.68
31840      Adana  Member State        NO        249    Turkey        1.70
31841      Adana  Member State        NO        249    Turkey        1.46
31842      Adana  Member State        NO        249    Turkey        0.93
31843      Adana  Member State        NO        249    Turkey        1.84
...          ...           ...       ...        ...       ...         ...
32760  Zonguldak  Member State        NO        249    Turkey        1.04
32761  Zonguldak  Member State        NO        249    Turkey        1.34
32762  Zonguldak  Member State        NO        249    Turkey        1.35
32763  Zonguldak  Member State        NO        249    Turkey        0.70
32764  Zonguldak  Member State        NO        249    Turkey        1.33

       Shape_Le_1  Shape_Area  \
31839        1.68        0.14
31840        1.70        0.14
31841        1.46        0.11
31842        0.93        0.03
31843        1.84        0.15
...           ...         ...
32760        1.04        0.05
32761        1.34        0.10
32762        1.35        0.08
32763        0.70        0.02
32764        1.33        0.07

                                                geometry
31839  POLYGON ((35.53303 37.74437, 35.52644 37.73018...
31840  POLYGON ((35.91312 37.26293, 35.91335 37.25740...
31841  POLYGON ((35.75481 38.04082, 35.76991 38.02627...
31842  POLYGON ((35.76595 37.27394, 35.76402 37.26457...
31843  POLYGON ((35.40597 37.33755, 35.40366 37.32406...
...                                                  ...
32760  POLYGON ((32.07488 41.57269, 32.08020 41.57048...
32761  POLYGON ((32.06896 41.28401, 32.08015 41.28394...
32762  POLYGON ((31.84796 41.26753, 31.83818 41.26229...
32763  POLYGON ((32.33111 41.31604, 32.32544 41.31411...
32764  POLYGON ((32.08832 41.33050, 32.08838 41.32634...

[926 rows x 15 columns]
199 TKM Turkmenistan
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
22376 22,377.00      28374  Administrative unit not available       1000
22377 22,378.00      28375  Administrative unit not available       1000
22378 22,379.00      28376  Administrative unit not available       1000
22379 22,380.00      28377  Administrative unit not available       1000
22380 22,381.00     147324  Administrative unit not available       1000
22381 22,382.00     147325  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE                          ADM1_NAME        STATUS  \
22376       3000       3097                          Chardzhou  Member State
22377       3000       3098  Administrative unit not available  Member State
22378       3000       3099                               Mary  Member State
22379       3000       3100                            Tashauz  Member State
22380       3000     147322                             Balkan  Member State
22381       3000     147323                               Ahal  Member State

      DISP_AREA  ADM0_CODE     ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
22376        NO        250  Turkmenistan       19.37       19.37       10.08
22377        NO        250  Turkmenistan       27.76       27.76        8.72
22378        NO        250  Turkmenistan       16.99       16.99        8.76
22379        NO        250  Turkmenistan       17.04       17.04        7.88
22380        NO        250  Turkmenistan       33.36       33.36       12.26
22381        NO        250  Turkmenistan       20.15       20.15       10.20

                                                geometry
22376  POLYGON ((62.13881 40.56176, 62.14430 40.55648...
22377  POLYGON ((53.89781 37.34081, 53.89781 37.34081...
22378  POLYGON ((64.75912 36.86848, 64.74888 36.85428...
22379  POLYGON ((58.64533 42.77992, 58.65706 42.76905...
22380  MULTIPOLYGON (((53.10210 39.10645, 53.09997 39...
22381  POLYGON ((57.07291 38.18982, 57.00481 38.25921...
200 TCA Turks and Caicos Islands
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
201 TUV Tuvalu
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
38208 38,209.00      28380  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE                          ADM1_NAME        STATUS  \
38208       3000       3103  Administrative unit not available  Member State

      DISP_AREA  ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
38208        NO        252    Tuvalu        2.21        2.21        0.00

                                                geometry
38208  MULTIPOLYGON (((179.85759 -9.43032, 179.85819 ...
202 UGA Uganda
      OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
1059  1,060.00      28381                           Adjumani       1000
1060  1,061.00      28382                               Kole       1000
1061  1,062.00      28383                             Kwania       1000
1062  1,063.00      28384                             Maruzi       1000
1063  1,064.00      28385                               Oyam       1000
...        ...        ...                                ...        ...
1224  1,225.00      28542                Tororo Municipality       1000
1225  1,226.00     149623  Administrative unit not available       1000
1226  1,227.00      42212                           Kyadondo       1000
1227  1,228.00      28394                            Bukooli       1000
1228  1,229.00     149624  Administrative unit not available       1000

      EXP2_YEAR  ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
1059       3000       3104  Adjumani  Member State        NO        253
1060       3000        764      Kole  Member State        NO        253
1061       3000        746      Apac  Member State        NO        253
1062       3000        746      Apac  Member State        NO        253
1063       3000        782      Oyam  Member State        NO        253
...         ...        ...       ...           ...       ...        ...
1224       3000      47090    Tororo  Member State        NO        253
1225       3000      42182   Kampala  Member State        NO        253
1226       3000      42200    Wakiso  Member State        NO        253
1227       3000        748    Bugiri  Member State        NO        253
1228       3000       1366    Lwengo  Member State        NO        253

     ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
1059    Uganda        2.55        2.55        0.25
1060    Uganda        1.83        1.83        0.09
1061    Uganda        1.88        1.88        0.12
1062    Uganda        2.35        2.35        0.15
1063    Uganda        2.16        2.16        0.18
...        ...         ...         ...         ...
1224    Uganda        0.19        0.19        0.00
1225    Uganda        0.30        0.30        0.00
1226    Uganda        1.67        1.67        0.05
1227    Uganda        1.59        1.59        0.09
1228    Uganda        1.66        1.66        0.08

                                               geometry
1059  POLYGON ((32.05753 3.58097, 32.05882 3.57984, ...
1060  POLYGON ((32.87227 2.08749, 32.87198 2.08755, ...
1061  POLYGON ((32.87227 2.08749, 32.87300 2.08713, ...
1062  POLYGON ((32.57604 2.22152, 32.57606 2.22147, ...
1063  POLYGON ((32.77645 2.58766, 32.77724 2.58675, ...
...                                                 ...
1224  POLYGON ((34.19972 0.71278, 34.19971 0.71228, ...
1225  POLYGON ((32.60429 0.31740, 32.60500 0.31700, ...
1226  MULTIPOLYGON (((32.54187 0.27444, 32.54250 0.2...
1227  POLYGON ((33.90083 0.48651, 33.90010 0.48669, ...
1228  POLYGON ((31.70502 -0.34729, 31.70398 -0.34932...

[170 rows x 15 columns]
203 UKR Ukraine
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
33133 33,134.00      28543  Administrative unit not available       1000
33134 33,135.00      28544  Administrative unit not available       1000
33135 33,136.00      28545  Administrative unit not available       1000
33136 33,137.00      28546  Administrative unit not available       1000
33137 33,138.00      28547  Administrative unit not available       1000
33138 33,139.00      28548  Administrative unit not available       1000
33139 33,140.00      28549  Administrative unit not available       1000
33140 33,141.00      28550  Administrative unit not available       1000
33141 33,142.00      28551  Administrative unit not available       1000
33142 33,143.00      28552  Administrative unit not available       1000
33143 33,144.00      28553  Administrative unit not available       1000
33144 33,145.00      28554  Administrative unit not available       1000
33145 33,146.00      28555  Administrative unit not available       1000
33146 33,147.00      28556  Administrative unit not available       1000
33147 33,148.00      28557  Administrative unit not available       1000
33148 33,149.00      28558  Administrative unit not available       1000
33149 33,150.00      28559  Administrative unit not available       1000
33150 33,151.00      28560  Administrative unit not available       1000
33151 33,152.00      28561  Administrative unit not available       1000
33152 33,153.00      28562  Administrative unit not available       1000
33153 33,154.00      28563  Administrative unit not available       1000
33154 33,155.00      28564  Administrative unit not available       1000
33155 33,156.00      28565  Administrative unit not available       1000
33156 33,157.00      28566  Administrative unit not available       1000
33157 33,158.00      28567  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE          ADM1_NAME        STATUS DISP_AREA  \
33133       3000       3148         Cherkas'ka  Member State        NO
33134       3000       3149      Chernihivs'ka  Member State        NO
33135       3000       3150      Chernivets'ka  Member State        NO
33136       3000       3151   Dnipropetrovs'ka  Member State        NO
33137       3000       3152          Donets'ka  Member State        NO
33138       3000       3153  Ivano-frankivs'ka  Member State        NO
33139       3000       3154        Kharkivs'ka  Member State        NO
33140       3000       3155        Khersons'ka  Member State        NO
33141       3000       3156      Khmel'nyts'ka  Member State        NO
33142       3000       3157     Kirovohrads'ka  Member State        NO
33143       3000       3158               Krym  Member State        NO
33144       3000       3159          Kyyivs'ka  Member State        NO
33145       3000       3160          L'vivs'ka  Member State        NO
33146       3000       3161          Luhans'ka  Member State        NO
33147       3000       3162      Mykolayivs'ka  Member State        NO
33148       3000       3163            Odes'ka  Member State        NO
33149       3000       3164         Poltavs'ka  Member State        NO
33150       3000       3165         Rivnens'ka  Member State        NO
33151       3000       3166            Sums'ka  Member State        NO
33152       3000       3167      Ternopil's'ka  Member State        NO
33153       3000       3168         Vinnyts'ka  Member State        NO
33154       3000       3169          Volyns'ka  Member State        NO
33155       3000       3170       Zakarpats'ka  Member State        NO
33156       3000       3171         Zaporiz'ka  Member State        NO
33157       3000       3172       Zhytomyrs'ka  Member State        NO

       ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
33133        254   Ukraine       11.08       11.08        2.63

       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
20836 20,837.00      31819  Administrative unit not available       1000
20837 20,838.00      31820  Administrative unit not available       1000
20838 20,839.00      31821  Administrative unit not available       1000
20839 20,840.00      31822  Administrative unit not available       1000
20840 20,841.00      31823  Administrative unit not available       1000
20841 20,842.00      31824  Administrative unit not available       1000
20842 20,843.00      31825  Administrative unit not available       1000
20843 20,844.00      31826  Administrative unit not available       1000
20844 20,845.00      31827  Administrative unit not available       1000
20845 20,846.00      31828  Administrative unit not available       1000
20846 20,847.00      31829  Administrative unit not available       1000
20847 20,848.00      31830  Administrative unit not available       1000
20848 20,849.00      31831  Administrative unit not available       1000
20849 20,850.00      31832  Administrative unit not available       1000
20850 20,851.00      31833  Administrative unit not available       1000
20851 20,852.00      31834  Administrative unit not available       1000
20852 20,853.00      31835  Administrative unit not available       1000
20853 20,854.00      31836  Administrative unit not available       1000
20854 20,855.00      31837  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE       ADM1_NAME        STATUS DISP_AREA  \
20836       3000       3265         Artigas  Member State        NO
20837       3000       3266       Canelones  Member State        NO
20838       3000       3267     Cerro Largo  Member State        NO
20839       3000       3268         Colonia  Member State        NO
20840       3000       3269         Durazno  Member State        NO
20841       3000       3270          Flores  Member State        NO
20842       3000       3271         Florida  Member State        NO
20843       3000       3272       Lavalleja  Member State        NO
20844       3000       3273       Maldonado  Member State        NO
20845       3000       3274      Montevideo  Member State        NO
20846       3000       3275        Paysandu  Member State        NO
20847       3000       3276       Rio Negro  Member State        NO
20848       3000       3277          Rivera  Member State        NO
20849       3000       3278           Rocha  Member State        NO
20850       3000       3279           Salto  Member State        NO
20851       3000       3280        San Jose  Member State        NO
20852       3000       3281         Soriano  Member State        NO
20853       3000       3282      Tacuarembo  Member State        NO
20854       3000       3283  Treinta Y Tres  Member State        NO

       ADM0_CODE ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
20836        260   Uruguay        5.87        5.87        1.10
20837        260   Uruguay        3.74        3.74        0.46
20838        260   Uruguay        7.21        7.21        1.31
20839        260   Uruguay        4.09        4.09        0.63
20840        260   Uruguay        7.32        7.32        1.18
20841        260   Uruguay        3.42        3.42        0.50
20842        260   Uruguay        5.70        5.70        1.01
20843        260   Uruguay        5.20        5.20        0.98
20844        260   Uruguay        4.05        4.05        0.49
20845        260   Uruguay        1.54        1.54        0.06
20846        260   Uruguay        6.45        6.45        1.35
20847        260   Uruguay        7.53        7.53        0.92
20848        260   Uruguay        5.33        5.33        0.83
20849        260   Uruguay        5.36        5.36        1.08
20850        260   Uruguay        6.14        6.14        1.34
20851        260   Uruguay        3.71        3.71        0.51
20852        260   Uruguay        5.14        5.14        0.88
20853        260   Uruguay        7.40        7.40        1.53
20854        260   Uruguay        5.71        5.71        0.95

                                                geometry
20836  POLYGON ((-56.01102 -31.05446, -56.01102 -31.0...
20837  MULTIPOLYGON (((-55.91916 -34.95359, -55.92486...
20838  POLYGON ((-53.15833 -32.80070, -53.15833 -32.8...
20839  MULTIPOLYGON (((-57.55751 -34.48292, -57.55153...
20840  POLYGON ((-55.30310 -32.46312, -55.30346 -32.4...
20841  POLYGON ((-56.53186 -33.47362, -56.52706 -33.4...
20842  POLYGON ((-55.13707 -33.40995, -55.13688 -33.4...
20843  POLYGON ((-54.12597 -33.44222, -54.12865 -33.4...
20844  MULTIPOLYGON (((-54.87031 -35.02885, -54.87060...
20845  MULTIPOLYGON (((-56.38281 -34.80336, -56.39229...
20846  POLYGON ((-56.30071 -31.71540, -56.29887 -31.7...
20847  MULTIPOLYGON (((-58.18064 -33.09267, -58.17948...
20848  POLYGON ((-54.46043 -31.66246, -54.46043 -31.6...
20849  MULTIPOLYGON (((-54.14857 -34.66296, -54.14876...
20850  POLYGON ((-56.01102 -31.05446, -56.01062 -31.0...
20851  POLYGON ((-56.45250 -33.88312, -56.45100 -33.8...
20852  POLYGON ((-57.14580 -33.05794, -57.13462 -33.0...
20853  POLYGON ((-54.66856 -32.08889, -54.66954 -32.0...
20854  POLYGON ((-53.15833 -32.80070, -53.16241 -32.8...
208 UZB Uzbekistan
       OBJECTID  ADM2_CODE                ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
22177 22,178.00      39699        Altinkul district       1000       3000
22178 22,179.00      39700             Andijan city       1000       3000
22179 22,180.00      39701         Andijan district       1000       3000
22180 22,181.00      39702               Asaka city       1000       3000
22181 22,182.00      39703           Asaka district       1000       3000
...         ...        ...                      ...        ...        ...
22371 22,372.00      39872  Sabir Rakhimov district       1000       3000
22372 22,373.00      39873         Sergeli district       1000       3000
22373 22,374.00      39874  Shaykhantokhur district       1000       3000
22374 22,375.00      39875      Yakkasaray district       1000       3000
22375 22,376.00      39876       Yunusabad district       1000       3000

       ADM1_CODE      ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
22177       3284        Andijan  Member State        NO        261
22178       3284        Andijan  Member State        NO        261
22179       3284        Andijan  Member State        NO        261
22180       3284        Andijan  Member State        NO        261
22181       3284        Andijan  Member State        NO        261
...          ...            ...           ...       ...        ...
22371      39698  Tashkent city  Member State        NO        261
22372      39698  Tashkent city  Member State        NO        261
22373      39698  Tashkent city  Member State        NO        261
22374      39698  Tashkent city  Member State        NO        261
22375      39698  Tashkent city  Member State        NO        261

        ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
22177  Uzbekistan        1.00        1.00        0.02
22178  Uzbekistan        0.25        0.25        0.00
22179  Uzbekistan        1.26        1.26        0.04
22180  Uzbekistan        0.04        0.04        0.00
22181  Uzbekistan        1.31        1.31        0.03
...           ...         ...         ...         ...
22371  Uzbekistan        0.28        0.28        0.00
22372  Uzbekistan        0.72        0.72        0.01
22373  Uzbekistan        0.34        0.34        0.00
22374  Uzbekistan        0.20        0.20        0.00
22375  Uzbekistan        0.38        0.38        0.00

                                                geometry
22177  POLYGON ((72.18884 40.85503, 72.22875 40.86523...
22178  POLYGON ((72.29615 40.76744, 72.28493 40.79653...
22179  POLYGON ((72.53808 40.90875, 72.53419 40.88966...
22180  POLYGON ((72.23366 40.67178, 72.23875 40.67007...
22181  POLYGON ((72.29394 40.75766, 72.31343 40.73686...
...                                                  ...
22371  POLYGON ((69.23329 41.31100, 69.22911 41.30523...
22372  POLYGON ((69.27430 41.20757, 69.19090 41.20766...
22373  POLYGON ((69.23329 41.31100, 69.24554 41.30376...
22374  POLYGON ((69.24166 41.27772, 69.23820 41.26923...
22375  POLYGON ((69.28899 41.35018, 69.29569 41.33563...

[199 rows x 15 columns]
209 VUT Vanuatu
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
38070 38,071.00      31850  Administrative unit not available       1000
38071 38,072.00      31851  Administrative unit not available       1000
38072 38,073.00      31852  Administrative unit not available       1000
38073 38,074.00      31853  Administrative unit not available       1000
38074 38,075.00      31854  Administrative unit not available       1000
38075 38,076.00      31855  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE  \
38070       3000       3296   Malampa  Member State        NO        262
38071       3000       3297    Penama  Member State        NO        262
38072       3000       3298     Sanma  Member State        NO        262
38073       3000       3299     Shefa  Member State        NO        262
38074       3000       3300     Tafea  Member State        NO        262
38075       3000       3301     Torba  Member State        NO        262

      ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
38070   Vanuatu        6.09        6.09        0.24
38071   Vanuatu        4.03        4.03        0.10
38072   Vanuatu        6.56        6.56        0.36
38073   Vanuatu        5.63        5.63        0.13
38074   Vanuatu        3.91        3.91        0.14
38075   Vanuatu        4.11        4.11        0.07

                                                geometry
38070  MULTIPOLYGON (((167.47238 -16.58165, 167.47266...
38071  MULTIPOLYGON (((168.28263 -15.92403, 168.28289...
38072  MULTIPOLYGON (((167.24784 -15.73091, 167.24784...
38073  MULTIPOLYGON (((168.46732 -17.81558, 168.46611...
38074  MULTIPOLYGON (((169.77396 -20.24790, 169.77527...
38075  MULTIPOLYGON (((168.03797 -14.43860, 168.03796...
210 VEN Venezuela, RB
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
211 VNM Vietnam
       OBJECTID  ADM2_CODE          ADM2_NAME  STR2_YEAR  EXP2_YEAR  \
27132 27,133.00      32174  Chau Doc Township       1000       3000
27133 27,134.00      32175           Chau Phu       1000       3000
27134 27,135.00      32176         Chau Thanh       1000       3000
27135 27,136.00      32177            Cho Moi       1000       3000
27136 27,137.00      32178    Long Xuyen City       1000       3000
...         ...        ...                ...        ...        ...
27784 27,785.00      74141           Muong Te       2004       3000
27785 27,786.00      74143             Sin Ho       2004       3000
27786 27,787.00      74140  Lai Chau township       2005       3000
27787 27,788.00      74144          Tam Duong       2005       3000
27788 27,789.00      74152       Lao Cai City       2005       3000

       ADM1_CODE ADM1_NAME        STATUS DISP_AREA  ADM0_CODE ADM0_NAME  \
27132       3326  An Giang  Member State        NO        264   Vietnam
27133       3326  An Giang  Member State        NO        264   Vietnam
27134       3326  An Giang  Member State        NO        264   Vietnam
27135       3326  An Giang  Member State        NO        264   Vietnam
27136       3326  An Giang  Member State        NO        264   Vietnam
...          ...       ...           ...       ...        ...       ...
27784      73938  Lai Chau  Member State        NO        264   Vietnam
27785      73938  Lai Chau  Member State        NO        264   Vietnam
27786      73938  Lai Chau  Member State        NO        264   Vietnam
27787      73938  Lai Chau  Member State        NO        264   Vietnam
27788      73939   Lao Cai  Member State        NO        264   Vietnam

       Shape_Leng  Shape_Le_1  Shape_Area  \
27132        0.45        0.45        0.01
27133        0.90        0.90        0.04
27134        0.78        0.78        0.03
27135        0.83        0.83        0.03
27136        0.44        0.44        0.01
...           ...         ...         ...
27784        3.27        3.27        0.32
27785        2.57        2.57        0.18
27786        0.60        0.60        0.01
27787        1.86        1.86        0.07
27788        0.79        0.79        0.02

                                                geometry
27132  POLYGON ((105.12366 10.70997, 105.12514 10.708...
27133  POLYGON ((105.32713 10.53989, 105.32703 10.538...
27134  POLYGON ((105.34784 10.48973, 105.35025 10.486...
27135  POLYGON ((105.55340 10.51581, 105.55386 10.514...
27136  POLYGON ((105.48775 10.33416, 105.48903 10.332...
...                                                  ...
27784  POLYGON ((102.50159 22.78024, 102.52867 22.765...
27785  POLYGON ((103.24448 22.60601, 103.24681 22.603...
27786  POLYGON ((103.41690 22.36232, 103.41542 22.364...
27787  POLYGON ((103.39797 22.50355, 103.40022 22.500...
27788  POLYGON ((103.96120 22.50686, 103.96546 22.505...

[657 rows x 15 columns]
212 VIR Virgin Islands (U.S.)
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
213 PSE West Bank and Gaza
       OBJECTID  ADM2_CODE                          ADM2_NAME  STR2_YEAR  \
31350 31,351.00      32679  Administrative unit not available       1000
31351 31,352.00      32680  Administrative unit not available       1000
31352 31,353.00      32681  Administrative unit not available       1000
31353 31,354.00      32682  Administrative unit not available       1000
31354 31,355.00      32683  Administrative unit not available       1000
31355 31,356.00      32684  Administrative unit not available       1000
31356 31,357.00      32685  Administrative unit not available       1000
31357 31,358.00      32686  Administrative unit not available       1000
31358 31,359.00      32687  Administrative unit not available       1000
31359 31,360.00      32688  Administrative unit not available       1000
31360 31,361.00      32689  Administrative unit not available       1000
31361 31,362.00      68768  Administrative unit not available       1000
32840 32,841.00      16442  Administrative unit not available       1000
32841 32,842.00      16443  Administrative unit not available       1000
32842 32,843.00      16444  Administrative unit not available       1000
32843 32,844.00      16445  Administrative unit not available       1000
32844 32,845.00      16446  Administrative unit not available       1000

       EXP2_YEAR  ADM1_CODE                          ADM1_NAME  \
31350       3000       3394                 Al Khalil (Hebron)
31351       3000       3395                Al Quds (Jerusalem)
31352       3000       3396                    Ariha (Jericho)
31353       3000       3397                          Bethlehem
31354       3000       3398                              Jenin
31355       3000       3399                             Nablus
31356       3000       3400                          Qalqiliya
31357       3000       3401                           Ramallah
31358       3000       3402                             Salfit
31359       3000       3403                              Tubas
31360       3000       3404                            Tulkarm
31361       3000      68766  Administrative unit not available
32840       3000       1291                      Deir al Balah
32841       3000       1292                               Gaza
32842       3000       1293                            Jabalya
32843       3000       1294                         Khan Yunis
32844       3000       1295                              Rafah

                               STATUS DISP_AREA  ADM0_CODE  \
31350  Occupied Palestinian Territory        NO         91
31351  Occupied Palestinian Territory        NO         91
31352  Occupied Palestinian Territory        NO         91
31353  Occupied Palestinian Territory        NO         91
31354  Occupied Palestinian Territory        NO         91
31355  Occupied Palestinian Territory        NO         91
31356  Occupied Palestinian Territory        NO         91
31357  Occupied Palestinian Territory        NO         91
31358  Occupied Palestinian Territory        NO         91
31359  Occupied Palestinian Territory        NO         91
31360  Occupied Palestinian Territory        NO         91
31361  Occupied Palestinian Territory        NO         91
32840   Occupied Palestinan Territory        NO         91
32841   Occupied Palestinan Territory        NO         91
32842   Occupied Palestinan Territory        NO         91
32843   Occupied Palestinan Territory        NO         91
32844   Occupied Palestinan Territory        NO         91

                ADM0_NAME  Shape_Leng  Shape_Le_1  Shape_Area  \
31350  West Bank and Gaza        1.51        1.51        0.10
31351  West Bank and Gaza        1.33        1.33        0.03
31352  West Bank and Gaza        1.72        1.72        0.06
31353  West Bank and Gaza        1.45        1.45        0.07
31354  West Bank and Gaza        1.27        1.27        0.06
31355  West Bank and Gaza        1.49        1.49        0.06
31356  West Bank and Gaza        0.74        0.74        0.02
31357  West Bank and Gaza        1.80        1.80        0.08
31358  West Bank and Gaza        0.76        0.76        0.02
31359  West Bank and Gaza        1.00        1.00        0.04
31360  West Bank and Gaza        0.98        0.98        0.02
31361  West Bank and Gaza        0.08        0.08        0.00
32840  West Bank and Gaza        0.34        0.34        0.01
32841  West Bank and Gaza        0.43        0.43        0.01
32842  West Bank and Gaza        0.33        0.33        0.01
32843  West Bank and Gaza        0.45        0.45        0.01
32844  West Bank and Gaza        0.34        0.34        0.01

                                                geometry
31350  POLYGON ((35.36565 31.46821, 35.35750 31.46170...
31351  POLYGON ((35.21673 31.88294, 35.22001 31.88191...
31352  POLYGON ((35.56677 32.19755, 35.56680 32.19751...
31353  POLYGON ((35.22623 31.73464, 35.22940 31.73170...
31354  POLYGON ((35.43026 32.40925, 35.43101 32.40586...
31355  POLYGON ((35.16970 32.32518, 35.16955 32.32450...
31356  POLYGON ((35.16135 32.16451, 35.15991 32.16511...
31357  POLYGON ((35.17268 32.07248, 35.17374 32.07186...
31358  POLYGON ((35.16135 32.16451, 35.16141 32.16395...
31359  MULTIPOLYGON (((35.57027 32.19728, 35.57027 32...
31360  POLYGON ((35.16970 32.32518, 35.16901 32.32428...
31361  MULTIPOLYGON (((35.23623 31.74493, 35.23550 31...
32840  POLYGON ((34.42896 31.42989, 34.42673 31.42718...
32841  POLYGON ((34.51692 31.49988, 34.51031 31.49768...
32842  POLYGON ((34.51692 31.49988, 34.51484 31.50125...
32843  POLYGON ((34.37300 31.37697, 34.37000 31.37320...
32844  POLYGON ((34.32824 31.25948, 34.32770 31.25891...
214 YEM Yemen, Rep.
Empty GeoDataFrame
Columns: [OBJECTID, ADM2_CODE, ADM2_NAME, STR2_YEAR, EXP2_YEAR, ADM1_CODE, ADM1_NAME, STATUS, DISP_AREA, ADM0_CODE, ADM0_NAME, Shape_Leng, Shape_Le_1, Shape_Area, geometry]
Index: []
215 ZMB Zambia
      OBJECTID  ADM2_CODE      ADM2_NAME  STR2_YEAR  EXP2_YEAR  ADM1_CODE  \
1229  1,230.00      65174       Chibombo       1000       3000       3426
1230  1,231.00      65175          Kabwe       1000       3000       3426
1231  1,232.00      65176  Kapiri-Mposhi       1000       3000       3426
1232  1,233.00      65177         Mkushi       1000       3000       3426
1233  1,234.00      65178         Mumbwa       1000       3000       3426
...        ...        ...            ...        ...        ...        ...

In [24]:
GAUL_borders_2[GAUL_borders_2["ADM0_NAME"] == 'Zimbabwe']

,OBJECTID,ADM2_CODE,ADM2_NAME,STR2_YEAR,EXP2_YEAR,ADM1_CODE,ADM1_NAME,STATUS,DISP_AREA,ADM0_CODE,ADM0_NAME,Shape_Leng,Shape_Le_1,Shape_Area,geometry
1301,"1,302.00",33051,Bulawayo,1000,3000,3435,Bulawayo,Member State,NO,271,Zimbabwe,1.17,1.17,0.04,"POLYGON ((28.60867 -20.23069, 28.60512 -20.226..."
1302,"1,303.00",33053,Buhera,1000,3000,3437,Manicaland,Member State,NO,271,Zimbabwe,4.06,4.06,0.46,"POLYGON ((31.59200 -19.01383, 31.59200 -19.014..."
1303,"1,304.00",33054,Chimanimani,1000,3000,3437,Manicaland,Member State,NO,271,Zimbabwe,3.04,3.04,0.29,"POLYGON ((32.78558 -19.38889, 32.78536 -19.394..."
1304,"1,305.00",33055,Chipinge,1000,3000,3437,Manicaland,Member State,NO,271,Zimbabwe,4.21,4.21,0.45,"POLYGON ((32.87057 -20.11030, 32.86818 -20.111..."
1305,"1,306.00",33056,Makoni,1000,3000,3437,Manicaland,Member State,NO,271,Zimbabwe,5.13,5.13,0.67,"POLYGON ((32.56430 -17.60184, 32.56434 -17.601..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,"1,359.00",68809,Harare,2006,3000,3436,Harare,Member State,NO,271,Zimbabwe,1.70,1.70,0.08,"POLYGON ((31.10567 -17.98799, 31.10533 -17.987..."
1359,"1,360.00",68806,Bulilima,2006,3000,3443,Matabeleland South,Member State,NO,271,Zimbabwe,4.67,4.67,0.57,"POLYGON ((27.31032 -19.79525, 27.31053 -19.795..."
1360,"1,361.00",68810,Mangwe,2006,3000,3443,Matabeleland South,Member State,NO,271,Zimbabwe,4.25,4.25,0.52,"POLYGON ((28.29908 -20.42886, 28.29627 -20.449..."
1361,"1,362.00",68808,Guruve,2008,3000,3438,Mashonaland Central,Member State,NO,271,Zimbabwe,2.78,2.78,0.25,"POLYGON ((30.43364 -16.35285, 30.43410 -16.352..."
1362,"1,363.00",68811,Mbire,2008,3000,3438,Mashonaland Central,Member State,NO,271,Zimbabwe,4.48,4.48,0.40,"POLYGON ((30.42234 -15.62240, 30.42515 -15.628..."

In [6]:
Map = geemap.Map(center = (40, -100), zoom = 3)
Map

Map(center=[40, -100], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=HBox(children=(T…

In [7]:
ee_class_table = """
Value	Color	Description
1	05450a	Evergreen Needleleaf Forests: dominated by evergreen conifer trees (canopy >2m). Tree cover >60%.
2	086a10	Evergreen Broadleaf Forests: dominated by evergreen broadleaf and palmate trees (canopy >2m). Tree cover >60%.
3	54a708	Deciduous Needleleaf Forests: dominated by deciduous needleleaf (larch) trees (canopy >2m). Tree cover >60%.
4	78d203	Deciduous Broadleaf Forests: dominated by deciduous broadleaf trees (canopy >2m). Tree cover >60%.
5	009900	Mixed Forests: dominated by neither deciduous nor evergreen (40-60% of each) tree type (canopy >2m). Tree cover >60%.
6	c6b044	Closed Shrublands: dominated by woody perennials (1-2m height) >60% cover.
7	dcd159	Open Shrublands: dominated by woody perennials (1-2m height) 10-60% cover.
8	dade48	Woody Savannas: tree cover 30-60% (canopy >2m).
9	fbff13	Savannas: tree cover 10-30% (canopy >2m).
10	b6ff05	Grasslands: dominated by herbaceous annuals (<2m).
11	27ff87	Permanent Wetlands: permanently inundated lands with 30-60% water cover and >10% vegetated cover.
12	c24f44	Croplands: at least 60% of area is cultivated cropland.
13	a5a5a5	Urban and Built-up Lands: at least 30% impervious surface area including building materials, asphalt and vehicles.
14	ff6d4c	Cropland/Natural Vegetation Mosaics: mosaics of small-scale cultivation 40-60% with natural tree, shrub, or herbaceous vegetation.
15	69fff8	Permanent Snow and Ice: at least 60% of area is covered by snow and ice for at least 10 months of the year.
16	f9ffa4	Barren: at least 60% of area is non-vegetated barren (sand, rock, soil) areas with less than 10% vegetation.
17	1c0dff	Water Bodies: at least 60% of area is covered by permanent water bodies.

"""
legend_dict = geemap.legend_from_ee(ee_class_table)
Map.add_legend(legend_title="MODIS Global Land Cover", legend_dict=legend_dict)

In [10]:
roi = gaul2.filter(ee.Filter.eq('ADM0_NAME', 'Japan'))
Map.addLayer(roi, {'color': '00909F', 'fillColor': 'b5ffb4', 'width': .1}, 'Second Level Administrative Units')
Map.centerObject(roi)

In [11]:
# Get the MODIS Yearly 500m Landcover Collection
modisLandCover = ee.Image("MODIS/006/MCD12Q1/2018_01_01")
igbpLandCover = modisLandCover.select('LC_Type1')
igbpLandCoverVis = {
  'min': 1.0,
  'max': 17.0,
  'palette': [
    '05450a', '086a10', '54a708', '78d203', '009900', 'c6b044', 'dcd159',
    'dade48', 'fbff13', 'b6ff05', '27ff87', 'c24f44', 'a5a5a5', 'ff6d4c',
    '69fff8', 'f9ffa4', '1c0dff'
  ],
}
Map.addLayer(igbpLandCover.clip(roi), igbpLandCoverVis, 'IGBP Land Cover')

In [12]:
urban = igbpLandCover.eq(13)
Map.addLayer(urban.selfMask().clip(roi), {'min': 0, 'max':1, 'palette': ['grey','black']}, 'Urban')

In [13]:
merit = ee.Image("MERIT/DEM/v1_0_3").select('dem')
lowAreas = merit.lte(5)
Map.addLayer(lowAreas.selfMask().clip(roi), {'min': 0, 'max':1, 'palette': ['grey','blue']}, "Low Areas")

In [46]:
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
nlcd_stats = os.path.join(out_dir, 'kerala.csv')  
geemap.zonal_statistics_by_group(igbpLandCover.clip(roi), 
                                 roi, 
                                 nlcd_stats, 
                                 statistics_type='SUM', 
                                 denominator=1000000, 
                                 decimal_places=2,
                                 scale = 500)

Computing ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/tables/667051605513c89cf82f403c5bf3eae3-c7632cbd5149fd48d18cc45c675dec04:getFeatures
Please wait ...
Data downloaded to /Users/javierparada/Downloads/kerala.csv

In [47]:
df = wb.data.DataFrame(['AG.LND.EL5M.ZS', 'EN.POP.EL5M.ZS'], wb.region.members('WLD'), time=2010, labels=True)
df = df.sort_values(by=['Country'], ascending=True).reset_index()
df["economy"]= df["economy"].replace("XKX", "KSV") # replace code for Kosovo
df = df[df["economy"]!="CHI"] # remove Channel Islands
countries = list(df["economy"])
print('{} countries in WDI'.format(len(countries)))
df

216 countries in WDI

    economy                Country  AG.LND.EL5M.ZS  EN.POP.EL5M.ZS
0       AFG            Afghanistan             NaN             NaN
1       ALB                Albania            4.86            7.07
2       DZA                Algeria            0.03            0.76
3       ASM         American Samoa            3.56            3.27
4       AND                Andorra             NaN             NaN
..      ...                    ...             ...             ...
212     VIR  Virgin Islands (U.S.)            6.64            5.44
213     PSE     West Bank and Gaza            0.09            0.55
214     YEM            Yemen, Rep.            0.41            1.58
215     ZMB                 Zambia             NaN             NaN
216     ZWE               Zimbabwe             NaN             NaN

[216 rows x 4 columns]

In [ ]:
df[